JDimproved/JDim

- src/jdlib/misctrip.cpp
（オリジナルのJDもですが）Fedora 28でビルドが通らないのでその修正です。
glibc 2.27 deprecated libcrypt and Fedora 28 now uses
libxcrypt instead. So to use crypt() function, it must always
include crypt.h (glibc 2.26 had the function in unistd.h).
> Always include crypt.h header for crypt function

- src/jdlib/miscutil.cpp
Fedora rawhideでgcc8でビルドすると、（オリジナルもそうですが）std::stringのアクセスが厳しくなっていて、そのままだと
```
$ ./src/jd
(process:27119): GLib-WARNING **: 23:24:45.256: gmem.c:489: custom memory allocation vtable not supported
/usr/include/c++/8/bits/basic_string.h:1029: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator[](std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) const [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::const_reference = const char&; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type = long unsigned int]: Assertion '__pos <= size()' failed.
中止 (コアダンプ)
```
みたいになって動きません
gcc8 now checks array member access …
> Check array member access more strictly

- src/jdlib/miscutil.cpp
すみません...これで直ると思います。
http://mao.5ch.net/test/read.cgi/linux/1516535816/69 の
「ダブルクォート」と「スペースで改行」と「左のタブが閉じる」件の修正
> std:stringアクセスのチェックの修正

- src/main.cpp
http://mao.5ch.net/test/read.cgi/linux/1516535816/354
あたりから議論になっていますが、GLib内部のprofiler機能
https://developer.gnome.org/glib/stable/glib-Memory-Allocation.html#g-mem-set-vtable
https://developer.gnome.org/glib/stable/glib-Memory-Allocation.html#g-mem-profile
は、2.46でdeprecatedになっていて、それ以降のGLibでは、起動時に警告が出るだけで
何もしないので、2.46以降では使用しないようにするためのpatchです。
まだ、CentOS 6 (GLib 2.28)や、Ubuntu LTS 14.04 (GLIb 2.40)では、2.46になってないので、
一応残しました。
> Deprecate usage of GLib memory profiler on 2.46 and above

- src/article/articleviewbase.cpp
- src/article/drawareabase.cpp
- src/article/embeddedimage.cpp
- src/article/preference.cpp
- src/bbslist/bbslistviewbase.cpp
- src/bbslist/selectdialog.cpp
- src/bbslist/toolbar.cpp
- src/board/boardviewbase.cpp
- src/browserpref.h
- src/config/aboutconfig.cpp
- src/control/mousekeypref.cpp
- src/fontcolorpref.cpp
- src/image/imageareabase.cpp
- src/image/imageareaicon.cpp
- src/jdlib/imgloader.cpp
- src/linkfilterpref.cpp
- src/message/messageviewbase.cpp
- src/setupwizard.cpp
- src/skeleton/compentry.cpp
- src/skeleton/edittreeview.cpp
- src/skeleton/edittreeview.h
- src/skeleton/label_entry.cpp
- src/skeleton/toolbar.cpp
- src/skeleton/treeviewbase.cpp
- src/skeleton/window.cpp
- src/usrcmdpref.cpp
現在alphaバージョンであるgtk3版からいくつかのコミットを抽出してリクエストします。gtk3版のブランチは変更量が多すぎるので安定している変更を分けたいと思います。
廃止予定の機能を同等の機能に置き換える。([deprecated list](https://developer.gnome.org/gtkmm/2.24/deprecated.html)を参照した) gtkmmのドキュメントには特にバージョンが記載されてないので無条件でリプレースする。
非常に古いディストリビューション(例えばRHEL 5)のglibmmはGlib::RefPtr::reset()がないのでコンパイルエラーになる。サポートするには条件コンパイルが必要。
> Replace deprecated features

- src/article/drawareabase.cpp
- src/bbslist/bbslistviewbase.cpp
- src/board/boardviewbase.cpp
- src/control/mousekeypref.cpp
- src/fontcolorpref.cpp
- src/image/imageadmin.cpp
- src/image/imageview.cpp
- src/image/imageviewicon.cpp
- src/linkfilterpref.cpp
- src/skeleton/dragtreeview.cpp
- src/skeleton/edittreeview.cpp
- src/skeleton/selectitempref.cpp
- src/skeleton/tablabel.cpp
- src/skeleton/tabnote.cpp
- src/skeleton/toolbar.cpp
- src/skeleton/treeviewbase.cpp
- src/winmain.cpp
現在alphaバージョンであるgtk3版からいくつかのコミットを抽出してリクエストします。gtk3版のブランチは変更量が多すぎるので安定している変更を分けたいと思います。
互換性の問題からコンパイルエラーやクラッシュの原因となる機能を修正する。`Gtk::BUTTONBOX_EDGE`の修正はgtk2版の事実上のデフォルトであるとgtkのソースコードから推定した（[コミットメッセージ](https://github.com/yama-natuki/JD/commit/2f5a8319ad78652b4e4540eb8d61f4c833b1e969)を参照）。
修正はgtk2版の問題ではないためgtk3版でビルドするときのみ有効（＝条件コンパイル）にする。
> Replace incompatible features

- Makefile.am
- configure.ac
- src/environment.cpp
gitのレポジトリを使ってビルドした時に、revision等の情報を動作環境に追加するように変更するための変更です。
* gitのレポジトリでない時の挙動は従来通りです。
* gitのレポジトリの時は、例えば [バージョン] 2.8.9-20181010(git:ec7127a8:M) みたいな感じになります。:Mはcommitされてない変更があるときに追加します。
> Add git revision information to env info

- INSTALL
- configure.ac
- src/article/embeddedimage.cpp
- src/dispatchmanager.cpp
- src/image/imageareabase.cpp
- src/jdlib/imgloader.cpp
- src/jdlib/imgloader.h
- src/jdlib/jdmutex.h
- src/jdlib/jdthread.cpp
- src/jdlib/jdthread.h
- src/jdlib/loader.cpp
- src/jdlib/timeout.cpp
- src/jdlib/timeout.h
- src/winmain.cpp
現在alphaバージョンであるgtk3版からいくつかのコミットを抽出してリクエストします。gtk3版のブランチは変更量が多すぎるので安定している変更を分けたいと思います。
gthreadはglibmmの新しいバージョンで[廃止予定の機能](https://developer.gnome.org/glibmm/2.48/deprecated.html#_deprecated000020)となったため代わりにstd::threadを使うためのオプションを追加する。
* pthreadやgthreadの代わりにstd::threadを使うためのconfigureフラグ`--with-stdthread`を追加（デフォルトではno）。
修正できるが重要ではないもの
* gthreadを使うコードは`Glib::Threads`名前空間 (glibmm 2.47からdeprecated) を参照するように修正する。
* C++11が必須となったので無条件でstd::threadを使うようにする。
> Add support for std::thread

- Makefile.am
- src/environment.cpp
ビルドメタデータに表示するコミットハッシュを固定長(10文字)にします。
古いバージョンのgit(< 2.11)では省略表記のデフォルト長が7に固定されているためハッシュを表示できません。
2.11以前のバージョンでもハッシュを表示できるように長さを指定して取得するように変更します。
* コミットハッシュの長さチェックを省略すれば表示できるが表記ゆれが発生する。
* 余裕を見て10文字取得していますが8文字でも大丈夫かもしれないです。
> Fix hash length for git revision information

- src/cache.cpp
- src/cache.h
- src/control/controlutil.cpp
- src/core.cpp
- src/core.h
- src/image/imageadmin.cpp
- src/image/imageviewicon.cpp
- src/jdlib/miscutil.cpp
- src/jdlib/miscutil.h
- src/message/messageviewbase.cpp
- src/skeleton/aamenu.cpp
子ウィジェットを扱うコンテナ型を変更しgtk2/3で共通のコードになるように修正します。
gtk2サポートの最小バージョンを引き上げたりgtkmm2/3の違いを避けてC APIを使うなど共通化できるコードは一応ありますがアグレッシブ＆重箱の隅をつつく変更になるので予定してません。
> Replace container type

- configure.ac
- src/bbslist/bbslistview.h
- src/bbslist/bbslistviewbase.h
- src/bbslist/editlistwin.h
- src/bbslist/selectdialog.h
- src/bbslist/selectlistview.h
- src/board/boardview.h
- src/board/boardviewbase.h
- src/board/boardviewlog.h
- src/board/boardviewnext.h
- src/board/boardviewsidebar.h
- src/dbtree/interface.h
- src/dbtree/nodetreebase.cpp
- src/environment.cpp
- src/history/historymanager.h
- src/image/imageadmin.h
- src/jdlib/jdiconv.cpp
- src/jdlib/jdthread.cpp
- src/jdlib/loader.h
- src/jdlib/misctrip.cpp
- src/jdlib/misctrip.h
- src/jdlib/miscutil.cpp
- src/jdversion.h
- src/openurldiag.h
- src/session.h
- src/skeleton/msgdiag.cpp
gcc以外のコンパイラにも対応しやすくするためにオプション`-pedantic-errors`を追加してコンパイラの拡張機能を禁止します。修正の詳細は b46e404 を見てください。
その他
* gitのリポジトリでビルドしているときはマクロを使わずgitのリビジョンから日付を取得することを`jdversion.h`に説明コメントを追加する。またマクロの名前を`JDDATE`から`JDDATE_FALLBACK`に変更する。 ( 405da09 )
* std::threadのデバッグ用コードが壊れていたのを修正する。 ( 69da80e  )
> Use flag pedantic errors

- configure.ac
ライブラリヘッダーのエラーを避けるためコンパイラの拡張機能は警告にする
https://github.com/yama-natuki/JD/pull/20#issuecomment-449643098
> Use compiler option "-pedantic" instead of "-pedantic-errors"

- src/dbtree/nodetreebase.cpp
JD(im) には，名前欄に数字が含まれる場合に，その数字をアンカー扱いにする機能がありますが，名前欄がデフォルト名無し(板の SETTING.TXT の BBS_NONAME_NAME で設定されている名前)に一致している場合はその機能は無効になります。
しかしながら，その判定は県名表示なども含む完全一致で行われているため，デフォルト名無しに加えて県名表示やワッチョイなどが有効になっている板(やスレッド)では，機能が有効のままになってしまいます(例: [地下アイドル(AKB48)](http://rosie.5ch.net/akb/)板など)。
そこでこの変更では，名前欄の解析を行う際にも，デフォルト名無しに一致しているかチェックすることにより，機能を無効に出来るようにしました。
確認環境:
```
[バージョン] 0.1.0-20190123(git:f6390b7f97)
[ディストリ ] Debian GNU/Linux buster/sid (x86_64)
[パッケージ] バイナリ/ソース( <配布元> )
[ DE／WM ] 
[　gtkmm 　] 2.24.5
[　glibmm 　] 2.58.0
[ そ の 他 ] LANG = en_US.utf8
```
> Fix enabling digitlink in NodeTreeBase::parse_name

- src/environment.cpp
- src/environment.h
- src/linkfilterpref.cpp
- src/main.cpp
- src/usrcmdpref.cpp
* 動作環境をクリップボードへコピーするときバージョン情報にプログラム名(JDim)を追加します。
Example(抜粋):
`[バージョン] JDim 0.1.0-20190122(git:95e5f2d5c8)`
* gitリビジョンの変化によって再コンパイルが発生するファイルを減らします。
> Add progname info

- src/jdlib/hash_set.cpp
`JDLIB::hash_set_thread::get_key` が不正な値を返さないように修正します。
`JDLIB::hash_set_thread::get_key`はハッシュ値としてスレッドの番号(datの番号)を利用していますが
その際に呼び出している`atoi` はintの範囲を超えると未定義動作を起こします。
(すでにスレッドが落ちてしまっていますが[http://leia.5ch.net/test/read.cgi/poverty/2321433869/](http://leia.5ch.net/test/read.cgi/poverty/2321433869/)などを開くとクラッシュしました)
C++11には無例外動作が保証されている`std::hash`というハッシュ関数が標準で用意されているのでそちらを使うようにしました。
バグの確認環境:
```
[バージョン] 2.8.9-20190109(git:df8e0c1d20:M)
[ディストリ ] Ubuntu 18.10 (x86_64)
[パッケージ] バイナリ/ソース( <配布元> )
[ DE／WM ] GNOME
[　gtkmm 　] 2.24.5
[　glibmm 　] 2.56.0
[オプション ] 
[ そ の 他 ] 
```
> Fix undefined behavior in JDLIB::hash_set_thread::get_key

- src/dbtree/root.cpp
JBBS型(したらば掲示板)の板を一覧に追加するときに`http://jbbs.shitaraba.net`ではなく板URLの解析結果を使うように修正する。以前の方法ではhttpsではじまるURLを正常に設定できない問題があった。
JBBS型の板のうち`https?://jbbs.shitaraba.net`からはじまらないものは修正によって登録URLが換わる。そのため修正前から登録してある板を削除すると再登録したときにURLが換わり板情報が引き継がれないことがある。
> Fix JBBS board URL for setting board info

- README.md
jdパッケージの削除とjdimパッケージの導入に伴ってbuild-depの指定が変更。
その前の準備についても整理した
> Debianでの開発環境について更新

- src/jdlib/ssl.cpp
- src/jdversion.h
GnuTLSを使うとchunked transfer encoding方式の受信がエラーになる不具合を修正します。この不具合の影響でスレタイ検索の結果が0件になる問題がありました。
このエラーはチャンク長を処理せず受信するデータがゼロになるまで通信していることが原因ですがこのコミットでは受信の方法自体は修正していません。
* データを受信するとき特定のエラーを受信データ無し(=通信終了)に変換する。
* 新しいバージョンで導入された機能を使って初期化するように修正する。([gnutls公式のサンプルコード][1])
* データの送受信をリトライするように修正する。
[1]: https://gnutls.org/manual/html_node/Client-example-with-X_002e509-certificate-support.html
> Fix gnutls reception

- src/skeleton/window.cpp
ステータスバーのテキストが長いときはウインドウの幅に収まるように末尾を省略する。GTK3版は省略設定がないとテキストの長さに合わせてウインドウの幅が広がる問題があった。
修正にあたり不具合報告や動作検証をしていただきありがとうございました。
https://mao.5ch.net/test/read.cgi/linux/1540656394/627-639
> Set ellipsize to window status label since GTK+ 2.6

- src/article/drawareabase.cpp
- src/article/drawareabase.h
- src/jdversion.h
GTK3版のスレビューをタッチスクリーン操作に対応させます。
Thanks @tack1953 for testing.
* スレビューをタッチして上下にスワイプするとスクロールし 指を離すと減速して止まる。(慣性スクロール)
* URLやレス番号などのリンクをタップするとマウスの左ボタンクリックと同じように処理する。
* 2本指タップするとマウスの右ボタンクリックと同じように処理する。
* テキストの上でダブルタップをすると単語を範囲選択する。
環境変数`GTK_TEST_TOUCHSCREEN`を設定してJDを起動するとマウスの左クリック＋上下ドラッグでスレビューをスクロールできます。
```sh
GTK_TEST_TOUCHSCREEN=1 ./src/jdim
```
> Add touchscreen support (a.k.a. Add gtk3 support [2/2])

- src/control/controlutil.cpp
```
warning: result of comparison of constant 18446744073709551615 with expression of type 'unsigned int' is always true [-Wtautological-constant-out-of-range-compare]
```
上記のコンパイル時警告を修正します。`std::string::find()`の戻り値を`unsigned int`の変数に代入している箇所があり、`std::string::npos`が返ったときにオーバーフローが発生する可能性があります。
標準では`std::string::size_type`型ですがこのPRでは`auto`を使っています。
> Fix variable type for assigning from std::string::find()

- src/environment.cpp
- src/environment.h
- src/jdversion.h
- src/skeleton/window.cpp
GTK+ベースのデスクトップ環境(MATE, Cinnamon)を動作環境の表示に追加します。
どちらもGNOMEの挙動に準じるように設定します。
**注意:** Cinnamonは画像ビューをウインドウ表示したときの挙動(ウインドウ切り替え)に疑わしさが残ります。ウインドウ切り替え時に画像ビューウインドウが出ていると開く挙動は修正前後で変わっていません。しかし、これはGNOMEやMATEと異なります(画像ビューウインドウは閉じたまま)。
>  Add MATE and Cinnamon to ENVIRONMENT::get_wm() 

- src/jdlib/jdregex.cpp
https://github.com/JDimproved/JDim/issues/46 に対処するパッチです
容量の大きなレスを含むスレッドではキーワード抽出を行うと
検索処理中にバッファが足りずにオーバーフローを起こしてしまうので
バッファの容量を増やして回避します。
> Avoid crash on extraction

- src/jdlib/jdregex.cpp
- src/jdlib/loader.cpp
現在一部のmalloc()で
foo *bar = ( foo * ) malloc( buzz ) ;
という形で"buffバイト"のヒープを確保したあとそのポインタに対して
bar[ buzz ] ;
のように"buff個目の要素"としてアクセスしているため、fooが1バイト場合を除き要素の後ろの部分でオーバーフローが発生しています。
例)
buzz=5、fooが1要素当たり4バイトの場合、確保されたメモリは5バイトなのに対して bar[5] は 4*5=20 バイト目となる
foo *bar = ( foo * ) malloc( sizeof( foo ) * buzz ) ;
として正しいバイトを確保するように修正します。
また、charは1バイトが保証されているため変更せず
Bytefは現状1バイトのようですがその保証が有るのか確認できなかったためsizeof(Bytef)に
末尾の +64 は番兵のようなので変更せず
としました。
> #46 の(とりあえずの)修正

- src/article/font.cpp
現在font.cpp内ではmalloc()によって確保したポインタをdeleteで削除しています。
これは未定義動作になるので、代わりにnewを使うように変更し、同時にmemsetによるゼロフィルをリスト初期化に置き換えます。
また現在g++による警告(type qualifiers ignored on cast result type)が出ているため不要なconstを取り除きます。
> font.cpp内のmallocをnewに置き換える

- configure.ac
正規表現ライブラリ鬼車(oniguruma)を利用するときに./configureスクリプトによるライブラリ検出が失敗する問題を修正します。
この問題は検出に使用していた`onig-config`スクリプトがUbuntu 18.10では提供されていないことが原因でした。修正後は`pkg-config`を使ってonigurumaを探します。
> Fix oniguruma detection for configure script

- src/article/drawareabase.cpp
- src/jdversion.h
スレビューの描画領域の座標が割り当てられていないときに再描画を実行するとGTKの実行時警告が出るので修正します。
GTK+ 3.20以上?
スレ一覧からスレッドを選択してスレビューで開く
```
Gtk-WARNING **: HH:MM:SS.sss: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node tab owner gtkmm__GtkNotebook)
```
起動時に隠れているタブのスレビューを開くとこの警告が出る
> Fix runtime warning for opening a thread since GTK+ 3.20

- INSTALL
- configure.ac
- src/jdversion.h
#40 の修正です。
glibmm 2.47からGlib::Threadは非推奨になりました。JDimでもgthreadのサポートを終了するためにconfigureオプションを非推奨にします。
いつ削除されるか言及していませんが少なくとも次のリリースまでは`--with-gthread`オプションは維持されると思います。
> Fix #40: Make --with-gthread deprecated

- src/jdlib/miscutil.cpp
サロゲートペアなど数値文字参照としてはエラーになる値をチェックしてかわりに規定の値を返すよう修正します。
issueを立ててないので不具合の説明をここに記載します。
JDim 0.1.0-20190309(git:e649cc2f0c)
不正な数値文字参照が文字化け(いわゆる豆腐)になります。
例えばサロゲートペアは数値文字参照としては不正です。(:x: `&#55356;&#57141;`, :ok:  `&#127797;` -> &#127797;)
不正となる数値文字参照は以下のリンクを参考にしました。
Numeric character reference end state (HTML 5.3)
https://www.w3.org/TR/html53/syntax.html#numeric-character-reference-end-state
未修正のJDimで以下のスレッドにアクセスします。
* 本文が文字化け  
https://swallow.5ch.net/test/read.cgi/livejupiter/1529864683/605  
https://swallow.5ch.net/test/read.cgi/livejupiter/1539076573/186
* スレタイが文字化け  
**スレッド履歴が正常に読み込めなくなりますので注意してください！**
https://swallow.5ch.net/test/read.cgi/livejupiter/1534241668/1
```
(jdim:10185): Pango-WARNING **: 16:41:50.003: Invalid UTF-8 string passed to pango_layout_set_text()
``` …
> Sanitize numeric character reference

- src/jdlib/jdregex.cpp
- src/jdlib/jdregex.h
- src/jdlib/miscutil.cpp
- src/jdlib/miscutil.h
変換したデータを書き込むバッファを固定長配列のポインター渡しから可変長配列の参照渡しに変更します。
渡された配列は初期化せずデータを追加(push_back)していきます。
配列のメモリ再確保や再配置を避けるには予め領域を予約(reserve)して渡す必要があります。
関連のissue: #46
[ma8ma:minefield](https://github.com/ma8ma/JDim/commits/minefield)に変換のテストケースがあります。テストの導入についてはメンテナーの方と #45 で話をしています。
平仮名片仮名にUnicode正規化を導入して文字列の比較を強化します。採用する正規化形式はNFKD(互換等価性によって分解)を想定しています。具体的には濁点、半濁点の分解です。
**edit:** 例を更新
例
片仮名の「&#x30ac;」`U+30AC` を分解すると  → 「&#x30AB;&#x3099;」`U+30AB U+3099`
半角片仮名の「&#xff76;&#xff9e;」`U+FF76 U+FF9E` を分解すると  → 「&#x30AB;&#x3099;」`U+30AB U+3099` 
分解後の文字列を比較することにより`U+30AC`と`U+FF76 U+FF9E` は等しいと評価されます。
> Update function parameters for MISC::asc()

- src/article/drawareabase.cpp
JDim 0.1.0-20190309(git:e649cc2f0c)
GTK3版 (--with-gtkmm3)
GTK3版を使っているとき、スレビューでマウスボタンのButton4をクリックしても割り当てた動作が実行されないことがある。ボタンの反応が悪い。
`GtkGestureMultiPress`を使うとButton4以上のマウスボタン(>=Button4)でbutton-release-eventの反応が悪くなる環境があります。そのためpressedから直接releasedの処理を実行することによって問題を回避します。
修正後は>=Button4にダブルクリックの設定を割り当てても無効となります。(私が確認したマウスではButton4,5はダブルクリックに対応していませんでした。)
https://mao.5ch.net/test/read.cgi/linux/1540656394/988-989
https://mao.5ch.net/test/read.cgi/linux/1551877588/11
> Fix released-event misfire for GtkGestureMultiPress

- src/article/preference.cpp
- src/dbtree/articlebase.cpp
- src/dbtree/articlebase.h
- src/dbtree/interface.cpp
- src/dbtree/interface.h
- src/dbtree/nodetreebase.cpp
- src/dbtree/nodetreebase.h
- src/jdlib/constptr.h
#59 の修正版です。
このプルリクエストは #53 を修正するパッチの一部です。
定数`MAX_RESNUMBER`によって定められているレス数の上限を取り除くため、`std::vector<char>`で管理しているしおりなどのレス情報をレス番号(int)をキーにした`std::unordered_set<int>`で管理します。
しおり、書き込み、返信などのマークはレス数に対して十分少なくなるはずです。
したがって`std::vector`を使ってレス数と同じサイズの領域を確保する必要性は低いと考えられるのでハッシュセットにレス番号を記録する方法へ変更します。
挿入時にハッシュ計算(レス番号=int)のコストがかかります。また、最悪の場合はハッシュの再計算や挿入時にメモリの再確保が発生します。
レス情報が増加するほど`std::vector`と比べてメモリ使用量が多くなります。
レス番号の順序が必要な箇所がありますが実行される条件は限られている(プロパティのあぼ〜ん設定)ので`std::set<int>`の一時変数を使っています。
> Use std::unordered_set instead of std::vector for res information

- src/jdlib/miscutil.cpp
- src/jdlib/miscutil.h
- src/message/messageviewbase.cpp
* 文字列の走査を整理します。
* `MISC::count_chr()`は未使用になるので削除します。
文字の種類ごとにループを回していたので修正では１つのループにまとめました。
> Use range-based for instead of MISC::count_chr()

- src/control/mousekeypref.cpp
- src/linkfilterpref.cpp
- src/usrcmdpref.cpp
GTK3版の設定ダイアログで子ウィジェット(設定のリスト)が隠れてしまうレイアウト崩れを修正します。
> Tweak config dialog layout for GTK+3

- src/config/defaultconf.h
- src/jdversion.h
デフォルトのスレタイ検索サイトを壊れたままの https://dig.5ch.net からhttps://ff5ch.syoboi.jp へ変更します。
私が利用していたサイトというだけなので別の検索サイトの提案があればそちらへ変更しても大丈夫です。
> Fix #60: Change default thread title search site (ff5ch.syoboi.jp)

- src/usrcmdpref.cpp
バージョン条件の真偽値が逆になっていてダイアログに配置されないままになっているチェックボタンを修正します。
gitログを読んだところ https://github.com/JDimproved/JDim/commit/0e58affd83f57d99b921b42194177de7b382f733#diff-aa4eba76ca7df8a6a93b201665220f49 から条件が逆になったようです。
> Fix check button for usrcmdpref

- AUTHORS
- CONTRIBUTING.md
- ChangeLog
- INSTALL
- NEWS
- README.md
- src/core.cpp
- src/jdversion.h
#66 の修正としてオンラインマニュアルのリンクをJDからJDimへ変更します。
修正後は下の２つがリンクとして使われます。
- JDimのホームページは <https://github.com/JDimproved/JDim> (設定で変更可)
- オンラインマニュアルは <https://jdimproved.github.io/JDim/> (jdversion.hにハードコーディング)
> Fix manual link (a.k.a. Create online manual [2/2])

- src/board/boardviewbase.cpp
GTK3版のスレ一覧で列の幅が記憶されない不具合(次回起動時に前回の列の幅が復元されない)を修正します。
https://mao.5ch.net/test/read.cgi/linux/1551889442/43-47
> Fix to save thread list column width for GTK3

- docs/manual/2019.md
- src/bbslist/favoriteview.cpp
- src/cache.cpp
- src/cache.h
- src/config/configitems.cpp
- src/cssmanager.cpp
- src/dbtree/root.cpp
- src/usrcmdmanager.cpp
- src/usrcmdmanager.h
#79 のPRです。バージョン1.9.5未満の書式の設定ファイルをサポート終了します。
現行の設定ファイルが読み込めなかった場合に古い設定ファイルを読み込めるか試す処理を削除します。
修正後は古い設定ファイル自体は無視されるだけで削除はされません。
- `~/.jdrc`
-  `$JDIM_CACHE/list_main.xml`
- `$JDIM_CACHE/favorite.xml`
- `$JDIM_CACHE/usrcmd.txt`
- `$JDIM_CACHE/jd.css`
- `$JDIM_CACHE/Res.html`
> Fix #79: Remove support for old version config files

- INSTALL
- README.md
- configure.ac
- docs/manual/2019.md
- docs/manual/make.md
#80 のPRです。CPUに合わせた最適化を設定するconfigureオプションを廃止予定にします。
- 対象のCPUは古い世代になっており最近の世代に対応していない。
- 最適化に関心のあるユーザーならコンパイラのオプションを調べてCXXFLAGSなどを設定できるはず。
`--with-native`はどのCPUでも有効なためこの提案では廃止しません。
- `--with-core2duo`
- `--with-athlon64`
- `--with-atom`
- `--with-ppc7400`
- `--with-ppc7450`
> Fix #80: Deprecate configure option for CPU optimization

- INSTALL
- configure.ac
- docs/manual/make.md
- src/article/drawareabase.cpp
- src/main.cpp
#81 のPRです。既存のconifigureオプションのうち、衝突する（どれか一つしか設定できない）オプションをグループ化します。
さらに元のオプションを廃止予定にします。
- configureスクリプトを修正し実行時のメッセージ表示などを改めます。
- セッション管理ライブラリXSMPのチェックにpkg-configを利用します。
| 廃止予定 | 新オプション | 指定しない場合(デフォルト) |
| -- | -- | -- |
| `--with-gthread`<br>`--with-stdthread` | `--with-thread=[posix\|glib\|std]` | `posix` |
| `--with-oniguruma`<br>`--with-pcre` | `--with-regex=[posix\|oniguruma\|pcre]` | `posix` |
| `--with-openssl` | `--with-tls=[gnutls\|openssl]` | `gnutls` |
グループに入ってない値(e.g. `--with-thread=foobar`)や値なしオプション(e.g. `--with-thread`)はエラーとします。
> Fix #81: Add grouped configure option

- src/environment.cpp
- src/environment.h
- src/skeleton/window.cpp
デスクトップ環境を調べる方法を修正し、表示可能な環境を追加します。
追加するデスクトップ: unity, budgie, pantheon, environment, lxqt
> Improve ENVIRONMENT::get_wm() and ENVIRONMENT::get_wm_str()

- .clang-format
- docs/manual/2019.md
- src/skeleton/Makefile.am
- src/skeleton/dragtreeview.cpp
- src/skeleton/dragtreeview.h
- src/skeleton/editview.cpp
- src/skeleton/editview.h
- src/skeleton/jdtoolbar.cpp
- src/skeleton/jdtoolbar.h
- src/skeleton/popupwinbase.cpp
- src/skeleton/popupwinbase.h
SKELETON名前空間にあるクラスのメンバー関数の定義を移動します。
- メンバーのメソッドを呼び出すラッパーはヘッダーに移動する。
- 複数の命令文があるメンバー関数はcppファイルに移動する。
- `.clang-format`の設定をバージョン8.0に合うように更新する。
> Refactor SKELETON namespace

- docs/README.md
- docs/manual/2019.md
- src/jdversion.h
次期バージョンのリリースのため変更履歴やバージョン番号を修正します。
- マニュアル更新の例を修正
- 変更履歴にリリースを追加する
- バージョン番号を修正する
TODO
> Release 0.2.0

- .travis.yml
- README.md
- docs/manual/2019.md
CIサービスを利用したJDimのビルドとテストを設定します。
- 環境はxenial
- 対象ブランチはmaster
- gtkmm2 + gcc (migemo, alsa, PangoLayout) DEBUG
- gtkmm2 + clang (gnomeui, PCRE, OpenSSL)
- gtkmm3 + gcc (Oniguruma, std::thread)
- gtkmm3 + clang (xdg-open) DEBUG
- manual build
> Fix #98: Add travis-ci.com configuration

- Makefile.am
- configure.ac
- src/environment.cpp
- src/jdversion.h
#101 のPRです。
subversion対応機能はgitに移行してから使われておらずメンテナンスされていないため削除します。
これによりReproducible builds(ビルド再現性)を妨げるコードの一部が修正されますが、[問題の箇所][salsa]がまだ残っているためDebianパッケージのreprotestには成功しません。
[salsa]: https://salsa.debian.org/debian/jdim/commit/a3a95960f87597d55c2ffe358896d3cef78f879d#note_103083
> Fix #101 Remove subversion support

- Makefile.am
- jdim.metainfo.xml
#103 のPRです。
クロスプラットホームの[メタデータ][meta]を追加して配布元がJDimのアプリケーション情報を扱いやすくなるようにします。
[meta]: https://www.freedesktop.org/software/appstream/docs/
> Fix #103: Add jdim.metainfo.xml

- docs/manual/start.md
> Fix markdown format for the table of cache directory priority

- src/config/configitems.cpp
- src/config/configitems.h
- src/config/defaultconf.h
#109 のPRです。
旧バージョン(1.9.0未満, 2006-2007年頃)との互換のため残してある未使用のキャッシュのルートディレクトリ設定 `path_cacheroot` を削除することを提案します。
> Fix #109: Remove cache root config providing compatible with old version

- src/environment.cpp
動作環境の記入で参照されるconfigureオプションの検索条件を変更して`--without-*`や`--disable-*`ではじまるオプションを引数情報に含めるようにします。
新しく導入されたconfigureオプション`--disable-compat-cache-dir`がオプション情報に載らない問題を修正します。
> Fix configure args info to include "without" and "disable" options

- docs/manual/2019.md
- src/article/drawareabase.h
- src/image/imageadmin.cpp
- src/image/imageadmin.h
- src/image/imageviewicon.cpp
- src/image/imageviewicon.h
- src/skeleton/dragnote.h
- src/skeleton/dragtreeview.h
Fixes #110.
マウスホイール関連の追加PRです。
画像ビューのマウスホイールによるタブ切り替えを画像アイコンの境目やタブの空白領域でも操作が効くように修正します。
また、GTK 3.3.18以降ではタブ切り替え処理で `GDK_SCROOL_SMOOTH` を扱うように修正します。この修正によってGTK3版でマウスホイールによる切り替え操作が使えるようになります。
その他
- コメントの訂正: `GDK_SMOOTH_SCROLL` → `GDK_SCROOL_SMOOTH`
> Improve tab switch by mouse wheel for image view

- docs/manual/2019.md
- snap/snapcraft.yaml
#116 のPRです。
snapパッケージのビルドやランタイムの要件を定めたsnapcraft.yamlを追加します。
| 項目 | 値 |
| --- | --- |
| base | core18 |
| confinement | strict |
| grade | devel (今のところstable, candidateチャンネルには公開しません) |
| 依存plugs | [gnome-3-28-1804][gnome] and [gtk-3-themes][themes] |
| configureオプション | `--disable-compat-cache-dir` `--with-gtkmm3` `--with-xdgopen` |
| ビルドの環境変数 | [dpkg-buildflags][dpkg]を使ってHardening(セキュリティ強化)する |
- KDE環境下でアイコンがうまく表示されないため、gtk-3-themesに収録されていないbreeze-icon-themesをバンドルします。
[gnome]: https://gitlab.gnome.org/Community/Ubuntu/gnome-3-28-1804
[themes]: https://gitlab.gnome.org/Community/Ubuntu/gtk-common-themes
[dpkg]: https://wiki.debian.org/Hardening#Using_Hardening_Options
- JDのキャッシュディレクトリ `~/.jd` は使えません。
- 環境変数 `JDIM_CACHE` でキャッシュディレクトリを変更する場合、
ホームディレクトリ以下の隠しファイルでないパスを指定する必要があります。
- …
> Add snapcraft.yaml

- src/skeleton/dragtreeview.cpp
GTK3版のスレ一覧や板一覧でマウスのチルトホイール(横スクロール)を使えるようにします。
スクロール量はabout:configのツリービュー（板一覧、スレ一覧）にある「ツリービューでマウスホイールを回したときのスクロール量(行数)」で変更できます（[設定値に補正がかかる][factor]）。
GTKのシグナル処理や構成設定の都合によりチルトホイールへの動作割当ては横スクロール固定となり設定変更しても反映されません。
今後の更新次第ですが横スクロール固定を仕様にすることも考えております。
[factor]: https://github.com/ma8ma/JDim/blob/ace0517ffb141678aa0045b341d06c6d56f3b888/src/skeleton/dragtreeview.cpp#L530
> Implement tilt wheel for DragTreeView on GTK3

- docs/manual/2019.md
- src/control/mousekeypref.cpp
マウスボタン設定でマウスの拡張ボタン2(次のページへ進む)を入力したときに正しいボタン番号を割り当てるように修正します。
> Fix mouse button config to set Button5 correctly

- docs/Gemfile
- docs/Makefile
マニュアルビルドで使うjekyllの実行時エラーを回避します。[travis-ciのjob log](https://travis-ci.com/JDimproved/JDim/jobs/240017015), https://github.com/JDimproved/JDim/pull/124#issuecomment-536258187
NOTE: oktokitまたはfaradayの修正がリリースされたらこのパッチは不要になります。
> [WORKAROUND] Fix build error for manual

- src/bbslist/bbslistviewbase.cpp
- src/dbtree/boardbase.cpp
- src/dbtree/nodetreebase.cpp
- src/jdlib/miscutil.cpp
- src/xml/dom.cpp
玉葱版からのパッチです。
文字列操作の細かなリファクタリングを行います。
> Refactor string operation

- docs/Gemfile
This reverts commit 0f121542fee72c4968a7e6f40329e2035254609e.
faradayの修正が[リリースされた][rubygems]のでマニュアルビルドの依存関係を戻します。
[rubygems]: https://rubygems.org/gems/faraday/versions/0.16.2
> Revert "[WORKAROUND] Fix build error for manual"

- docs/README.md
- docs/index.md
- docs/manual/link-20190122.md
- docs/manual/link-20190720.md
前のバージョンのマニュアルを参照しやすくするためgithub.comの原稿へのリンクをオンラインマニュアルに追加します。
ただし、原稿のMarkdownファイルはHTMLに変換される前提で書かれているので一部の表示やリンクが機能しません。
- オンラインマニュアルに前バージョンの内容を追加する。
→作業の手間とブランチ内のファイル増加によるgitコマンドの速度低下が気になる。
- github wikiに前バージョンの内容orリンクを追加する。
→wikiが未作成。今後の状況で移動を検討する。
> Add github links for previous version manuals

- src/gtkmmversion.h
- src/jddebug.h
引数minorの値を比較するマクロを`GTK_MINOR_VERSION`から`GTKMM_MINOR_VERSION`に修正します。
修正にあたり報告をしていただきありがとうございました。
<https://mao.5ch.net/test/read.cgi/linux/1540656394/645>
> Fix GTKMM_CHECK_VERSION macro

- docs/manual/2019.md
- src/bbslist/bbslistviewbase.cpp
- src/board/boardviewbase.cpp
スレ一覧・板一覧のツールチップを列や一覧の幅より内容が長いときにだけ表示するように修正します。
スレ一覧はさらにマウスオーバーしたセルの内容をツールチップに表示するように変更します。
0e29f3d2 と 5774f110 からマウスオーバーしたときいつもツールチップが表示されるように変更されていました。
修正にあたり報告をしていただきありがとうございました。
<https://mao.5ch.net/test/read.cgi/linux/1551889442/319-320>
> Improve displaying tooltip for bbs list/thread list

- src/menuslots.cpp
GTK3版で「メニューバー＞設定＞フォントと色＞スレビューフォント」からダイアログを開くとクラッシュする報告があったので非推奨のウィジェット(`Gtk::FileSelectionDialog`)のかわりに`Gtk::FontChooserDialog`を使うように修正します。
<https://mao.5ch.net/test/read.cgi/linux/1551889442/322>
> Use Gtk::FontChooserDialog instead of Gtk::FileSelectionDialog on GTK3

- src/skeleton/label_entry.cpp
ダイアログ内の情報テキストが長いときはウインドウの幅に収まるように末尾を省略します。
GTK3版は省略設定がないとテキストの長さに合わせてダイアログの幅が広がり縮小できない問題がありました。
> Set ellipsize to dialog info label

- INSTALL
- configure.ac
- docs/manual/2019.md
- docs/manual/make.md
- src/jdversion.h
廃止予定になっている特定のCPUに最適化したコードを生成するためのconfigureオプションを削除します。
最近1〜2年の間に2/5chスレッドに投稿された動作環境で対象のオプションを利用しているものはありませんでした。
- `--with-core2duo`
- `--with-athlon64`
- `--with-atom`
- `--with-ppc7400`
- `--with-ppc7450`
最適化のCPUを指定する場合は `./configure CXXFLAGS="-march=ARCH"` を利用してください。
> Remove deprecated cpu optimization options

- INSTALL
- configure.ac
- docs/manual/make.md
Fixes #139.
セッション管理ライブラリ [libgnomeui][2] を利用するオプション(`--with-sessionlib=gnomeui`)を廃止予定にします。
libgnomeuiはgtk3で[廃止されており][1]、2019年にリリースされたディストロからもパッケージが削除されました。
[2]: https://developer.gnome.org/libgnomeui/
[1]: https://wiki.gnome.org/Attic/LibgnomeMustDie
> Deprecate --with-sessionlib=gnomeui option

- src/cache.cpp
JD互換機能が有効なとき環境変数 `JDIM_CACHE` で指定したキャシュディレクトリが初期化(\*)できない問題を修正します。
条件を間違えていたためディレクトリ未作成のパスを指定すると `XDG_CACHE_HOME` を使う挙動になっていました。
JDim起動時、デフォルトまたは`JDIM_CACHE`による指定のキャッシュディレクトリが存在しないときにディレクトリと設定ファイルが生成されます。
> Fix unable for initialization by JDIM_CACHE on compat mode

- Makefile.am
Fixes #145.
未使用のコンパイラー情報(`CC_INFO`, `CXX_INFO`)を`buildinfo.h`ヘッダーから取り除くためmakeルールを削除します。
コンパイラー情報のマクロは一度もソフトウェアで使われていませんでした。
> Remove make rule which generates unused compiler info

- configure.ac
- src/sound/playsound.cpp
`asoundlib.h`をincludeしたときに発生する`This header is deprecated, use <alsa/asoundlib.h> instead.` の警告に対処するため `alsa/asoundlib.h` が存在するかチェックしてヘッダーのincludeを変更する条件を追加します。
> Fix deprecated warning for including <asoundlib.h>

- .github/workflows/ccpp.yml
- .travis.yml
- README.md
- docs/manual/2019.md
Fixes #157.
GitHub Actionsを使って継続的インテグレーションを設定します。
travis-ciとジョブを振り分けてジョブの分散を行い実行時間の短縮とテストの種類を増やします。
- ubuntu 16.04 & GTK2 でオプションのライブラリや機能のビルド
- ubuntu 16.04 or 18.04 でコンパイラーを選択してビルド
- gcc-5 (16.04)
- gcc-6
- gcc-7
- gcc-8
- clang-4.0 (16.04)
- clang-5.0
- clang-6.0
- clang-7
- clang-8
- ubuntu 18.04 & GTK3 でオプションのライブラリや機能のビルド
- ubuntu 18.04 でオンラインマニュアルのビルド
> Add GitHub Actions configuration for CI

- README.md
GitHub Actionsのページはアクセス権限がないと404 Not Foundが返されるためCIバッジのリンクを解除します。
> Unset 404 link on the GitHub Actions CI badge

- docs/manual/2019.md
- src/dbtree/root.cpp
- src/dbtree/root.h
- src/message/post.cpp
- src/message/post.h
malloc/freeによるバッファ確保をstd::stringで置き換えます。
std::stringでメモリは自動的に確保されますが挙動の変化を抑えるため修正前と同じ量を予約しておきます。
修正ではstd::stringのイテレーターからデーターへのポインター(`&*str.begin()`)を取得していますがC++11の規格で保証されています。
http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2011/n3242.pdf#subsection.21.4.1
> The char-like objects in a basic_string object shall be stored contiguously. That is, for any basic_string objects, the identity &*(s.begin() + n) == &*s.begin() + n shall hold for all values of n such that 0 <= n < s.size().
> Replace char buffer with std::string part2

- README.md
- docs/index.md
- docs/manual/2019.md
- docs/manual/2020.md
- docs/manual/about.md
- docs/manual/history.md
- src/jdversion.h
copyrightの表示を2020年に更新します。
オンラインマニュアルに更新履歴(2020年)を作成し未リリースの変更を移動します。
> Update year to 2020

- src/jdlib/miscutil.cpp
引数の文字列は渡す先がchar*を要求しているためバッファのコピーが必要です。
> Replace char buffer with std::string for MISC::Iconv()

- README.md
- docs/manual/2020.md
- docs/manual/start.md
- snap/snapcraft.yaml
- test/Makefile.in
Snapパッケージのgrade設定をstableに変更し安定版として公開できるようにします。
- Snapパッケージのバージョン番号にコミットハッシュを追加
- マニュアルにSnapパッケージの説明を追加
- READMEにマニュアルへのリンクとバッジを追加
> Update snapcraft grade to stable

- src/dbtree/boardbase.cpp
- src/dbtree/boardbase.h
> Replace char buffer with std::string for DBTREE::BoardBase

- INSTALL
- README.md
- configure.ac
- docs/manual/make.md
Fixes #170.
configureスクリプトのオプション `--with-gtkmm3` のデフォルト値を **yes** に 変更してGTK3版をメインにします。
GTK2版をビルドするには `--with-gtkmm3=no` を指定して ./configure を実行してください。
> Set gtkmm3 as default for configure script

- INSTALL
- configure.ac
- docs/manual/make.md
Fixes #171.
configureスクリプトのオプション `--with-thread` のデフォルト値を **std** に変更して `std::thread` をメインにします。
POSIX Threadsを使う場合は `--with-thread=posix` を指定して ./configure を実行してください。
> Set std::thread as default for configure script

- docs/manual/2020.md
- snap/snapcraft.yaml
Snapパッケージの構成を従来の[desktop helpers][helper]からSnapcraft 3.8から導入された[Gnome extension][ext]に移行します。
- 実行ファイルのサイズを削減する (`strip -s`)
- プログラムの実行に不要なファイルをパッケージから外す
- https://snapcraft.io/docs/release-notes-snapcraft-3-8
- https://forum.snapcraft.io/t/desktop-app-support-gtk/6834
- https://forum.snapcraft.io/t/gtk3-applications/13483
- https://forum.snapcraft.io/t/the-gnome-3-28-extension/13485
- https://forum.snapcraft.io/t/snapcraft-extensions/13486
- https://forum.snapcraft.io/t/legacy-desktop-app-support-gtk3-applications-without-extensions/13506
[helper]: https://github.com/ubuntu/snapcraft-desktop-helpers
[ext]: https://forum.snapcraft.io/t/the-gnome-3-28-extension/13485
> Migrate snap package from legacy helper to gnome extension

- src/jdlib/miscutil.cpp
Fedoraでは（でrpmにパッケージする時には）defaultで ``-Wp,-D_GLIBCXX_ASSERTIONS``をつけてcompileすることになっていて、 https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_macros.html これをつけて test と master branchをcompileすると、JDimが起動しません。
```
[tasaka1@localhost JDim]$ gdb ./src/jdim 
GNU gdb (GDB) Fedora 8.3.50.20190824-27.fc31
(gdb) r
Starting program: /home/tasaka1/rpmbuild/fedora-specific/JDim/src/jdim 
Program received signal SIGABRT, Aborted.
0x00007ffff633b625 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install at-spi2-atk-2.34.1-1.fc31.x86_64 at-spi2-core-2.34.0-1.fc31.x86_64 atk-2.34.1-1.fc31.x86_64 atkmm-2.24.3-3.fc31.x86_64 bzip2-libs-1.0.8-1.fc31.x86_64 cairo-1.16.0-6.fc31.x86_64 cairo-gobject-1.16.0-6.fc31.x86_64 cairomm-1.12.0-11.fc31.x86_64 …
```
> MISC::remove_space: handle the case str consists of just spaces

- src/cssmanager.cpp
- src/dbtree/nodetreebase.cpp
- src/jdlib/heap.cpp
- src/jdlib/heap.h
一先ずpull requestを作りました。default alignmentは8で、char用にalignment 1の専用関数を作りました。ただ、本当は型を引数とするマクロを作った方がすっきりすると思います。
```
gcc10 -fsanitize=address detects alignment errors like:
=====================================================
cssmanager.cpp:614:22: runtime error: member access within misaligned address 0x6290002a3224 for type 'struct DOM', which requires 8 byte alignment
0x6290002a3224: note: pointer points here
00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
=====================================================
So adjust the return address of heap_alloc() for alignment.
Also, create heap_alloc_char() function, which sets alignment as 1.
```
Closes JDimproved/JDim#183 .
> HEAP::heap_alloc(): adjust alignment

- src/cssmanager.cpp
Fixes #182 
Compiler warns:
```
In file included from /usr/include/string.h:494,
from /usr/include/c++/9/cstring:42,
from jdlib/miscutil.h:9,
from cssmanager.cpp:8:
In function 'char* strncpy(char*, const char*, size_t)',
inlined from 'CORE::DOM* CORE::Css_Manager::create_textnode(const char*)' at cssmanager.cpp:665:12:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:34: warning: 'char* __builtin_strncpy(char*, const char*, long unsigned int)' output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
|          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cssmanager.cpp: In member function 'CORE::DOM* …
```
> Fix number of bytes for strncpy argument of Css_Manager::create_textnode()

- src/dbtree/nodetreejbbs.cpp
- src/dbtree/nodetreejbbs.h
`malloc/free`で確保しているバッファを`std::string`で置き換えます。
> Replace char buffer with std::string for DBTREE::NodeTreeJBBS

- docs/manual/2020.md
- src/jdlib/misctrip.cpp
Compiler warns:
```
misctrip.cpp: In function 'std::string create_trip_newtype(const string&)':
misctrip.cpp:147:28: warning: 'char* strncat(char*, const char*, size_t)' specified bound 2 equals source length [-Wstringop-overflow=]
147 |                     strncat( salt, "..", 2 );
|                     ~~~~~~~^~~~~~~~~~~~~~~~~
```
The salt string is short and it probably does the std::string's small string optimization.
> Fix a -Wstringop-overflow compiler warning in create_trip_newtype()

- test/gtest_jdlib_miscutil.cpp
Occurred a buffer overrun on `make test` in the case of the build using gcc-9 with configure `CXXFLAGS="-fsanitize=address -fno-omit-frame-pointer"` `LDFLAGS="-fsanitize=address"`.
error log:
```
==20309==ERROR: AddressSanitizer: global-buffer-overflow on address 0x56135a804967 at pc 0x56135a235afb bp 0x7fff9ce8b3e0 sp 0x7fff9ce8b3d0
READ of size 1 at 0x56135a804967 thread T0
#0 0x56135a235afa in MISC::is_url_scheme_impl(char const*, int*) src/jdlib/miscutil.cpp:963
#1 0x561359a69946 in MISC::is_url_scheme(char const*, int*) ../src/jdlib/miscutil.h:272
#2 0x561359a69946 in TestBody test/gtest_jdlib_miscutil.cpp:94
(snip)
0x56135a804967 is located 0 bytes to the right of global variable '*.LC85' defined in 'gtest_jdlib_miscutil.cpp' (0x56135a804960) of size 7
'*.LC85' is ascii string …
```
> Fix buffer overrun for MISC::is_url_scheme_impl() test

- src/jdlib/loader.cpp
- src/jdlib/loader.h
zlibの古いバージョン（1.2.0未満）に対応するためのコードを削除します。
zlib 1.2.0は[2003-03-09][changelog]にリリースされているため、2014年以降にリリースされたディストロにはバージョン1.2.0以上のzlibが入っているはずです。([repology.orgのリスト][repology])
[changelog]: https://github.com/madler/zlib/blob/master/ChangeLog#L985
[repology]: https://repology.org/project/zlib/versions
> Remove zlib client codes for version < 1.2.0

- docs/manual/2020.md
- src/dbtree/nodetreemachi.cpp
- src/dbtree/nodetreemachi.h
> Replace char buffer with std::string for DBTREE::NodeTreeMachi

- src/dbtree/nodetreemachi.cpp
修正で抜け落ちた出力パラメーター"byte"への代入を追加します。
> Fix not setting result to the out parameter of NodeTreeMachi::raw2dat()

- INSTALL
- docs/manual/make.md
- src/article/layouttree.cpp
- src/cssmanager.cpp
- src/dbtree/nodetreebase.cpp
- src/jdlib/heap.cpp
- src/jdlib/heap.h
Fixes #183
ヒープクラスによるメモリ確保を型に合わせてアライメント調整されるように修正します。
この修正でメモリ使用量が若干減ります。
パッチで使用する[`std::align()`][align]はgcc 5以上が必要になります。
[align]: https://cpprefjp.github.io/reference/memory/align.html
> Improve JDLIB::HEAP to return pointer aligned by specified type

- src/dbtree/articlebase.cpp
- src/dbtree/articlebase.h
- src/dbtree/nodetreebase.cpp
- src/dbtree/nodetreebase.h
bc4eb7e5ccf1a1540ad104eef15997883f8508b9 で実装されてから一度も使われていない`get_raw_res_str()`を削除します。
> Remove unused NodeTreeBase::get_raw_res_str()

- docs/manual/2020.md
- src/control/keysyms.h
- src/skeleton/aamenu.cpp
- src/skeleton/editview.cpp
- src/skeleton/entry.cpp
- src/skeleton/msgdiag.cpp
- src/skeleton/selectitempref.cpp
- src/skeleton/tabnote.cpp
- src/skeleton/view.cpp
- src/skeleton/window.cpp
Fixes #137
GTK2版のバージョン要件の変更(2.24以上)により使われなくなったコードを削除します。
- GTK3で廃止されたマクロを新しく導入されたマクロへ移行する
- GTK3からウィジェットのフィールドに直接アクセスできなくなるためメンバー関数を使う
- GTK3で廃止されたメンバー関数を削除してコードを統一する
> Remove legacy gtk2 codes for less than version 2.24

- src/article/drawareabase.cpp
- src/article/drawareabase.h
- src/config/configitems.cpp
- src/config/defaultconf.h
- src/core.cpp
- src/core.h
- src/dbtree/nodetreebase.cpp
- src/dbtree/nodetreebase.h
- src/fontcolorpref.cpp
- src/fontid.h
- src/menuslots.cpp
- src/setupwizard.cpp
- src/setupwizard.h
http://mao.2ch.net/test/read.cgi/linux/1551889442/194 で話題になってた、メール欄で別のフォントを設定する、というのを実装してみたものです。実装したものは、 http://mao.2ch.net/test/read.cgi/linux/1551889442/899 のようなものになってます。
色々チェックが必要だと思うので、確認お願いします。
> Separate mail font

- src/dbtree/root.cpp
https://github.com/JDimproved/JDim/pull/195#issuecomment-592562856 より
> 話がちょっとそれますが
> 
> > ```
> > 2. `next2ch.net`はサイトの`http://next2ch.net/bbsmenu.html`を読み込むとクラッシュするため別サイトを使った
> > 3. `2ch.sc`はサイトの`https://menu.2ch.sc/bbsmenu.html`を読み込むとクラッシュするため外部板として登録した
> > ```
> 
中略
> 
> https://github.com/JDimproved/JDim/blob/df78f8145a4ef4cfa539f10334bc7ffdeb371982/src/dbtree/root.cpp#L414
> この辺で死んでます。クラッシュするサイトのソースを見ると、他のにはある`<font size=2>` というのがこれらのサイトに無い為、`html.getElementsByTagName( "font" )[0]`というのがnullptrになって死んでいるようです。
2ch.scとnext2ch.netのbbsmenu.htmlではfontタグが使われていないためfontタグが見つからない場合は別のタグ（small, body）を取得して解析するようにします。
それでも見つからないときはエラーメッセージを出して解析処理を中止します。
> Root: Fix parsing bbsmenu for 2ch.sc and next2ch.net

- src/jdlib/miscutil.cpp
詳細は後で書きます。
まちBBSでタイトルを検索するを落ちる現象が発生するので、修正する。
入力文字列について、null終端を超えてアクセスしないよう、修正。
> MISC::asc: Fix crash when searching title on Machi BBS

- docs/manual/2020.md
- src/jdlib/miscutil.cpp
- test/gtest_jdlib_miscutil.cpp
Fixes #198
全角英数字を半角英数字、半角片仮名を全角片仮名に置き換える関数(`MISC::asc()`)の置き換えた文字列の位置を保存しておくテーブルに文字列の終端（ヌル文字）の位置を追加します。
終端位置の追加は以前の修正で抜け落ちていたため呼び出し元の検索処理で文字列の末尾にマッチングした場合テーブルの範囲を超えてアクセスして未定義の動作が起こる状態でした。
さらに`MISC::asc()`の単体テストを追加します。
> Fix out-of-range for JDLIB::Regex::exec()

- INSTALL
- docs/manual/make.md
ビルド要件に載っていなかったautoconf-archiveを追記します。
> Add autoconf-archive to build requirement

- src/article/drawareabase.cpp
Fixes #200
GTK3版スレビューのポップアップウインドウでポップアップ内容をスクロールしたとき表示内容が一番上に戻ってしまう問題を修正します。
> Fix thread view popup window scrolling for GTK3

- src/article/articleviewbase.cpp
- src/bbslist/bbslistviewbase.cpp
- src/board/boardviewbase.cpp
- src/control/control.cpp
- src/image/imageviewbase.cpp
マウスジェスチャー（右クリック）中にマウスホイール操作をするとタブやページの切り替えを行う機能をGTK3版に実装します。
この機能は元々GTK2版にありましたがGTK3版を実装したときに抜け落ちていました。
https://mao.5ch.net/test/read.cgi/linux/1551889442/950
> Implement mouse gesture wheel for GTK3

- src/article/font.cpp
フォント幅をキャッシュするUnicode符号範囲を縮小しメモリ使用量を減らします。
Unicode第三漢字面(TIP, U+30000 - U+3FFFF)は2020年3月時点では文字が割り当てられていませんが追加予定の漢字があるためキャッシュの範囲にします。
キャッシュする文字を0x10FFFF個から0x40000個に変更するためフォント設定毎に17,408 KiBから4,096 KiBになります。(x86\_64は1文字辺り16バイト消費する、0x10FFFF \* 16, 0x40000 \* 16)
ただしOSや実行環境のメモリ管理があるので実際にどれくらい減少するか不明です。
> Reduce memory usage for font width caches

- src/article/drawareabase.cpp
よく見てみて分かったのですが、メールのフォントを極端に大きくした時に、下のスクリーンショットのように、スレビューで、本文の1行目と2行目との間に余計な隙間が出来てしまうので、これを修正します。 
https://mtasaka.fedorapeople.org/Bugfix/jdim/jd-screenshot-89c12d7816.png
現状だと、1行目と2行目は、（メールのフォントの高さ）と（スレビューのフォントの高さ）のおおきい方分隙間が空いてしまうので、本文を書いた時には常に改行高さを更新するようにします。
----------------------------------------------------------------------------------------------------------------------
テキストノードで一文字でも文字を書いた後は、改行の高さを、現在の行のフォントの高さに更新する。
> layout_one_text_node: reset br_size after writing characters

- src/article/articleviewbase.cpp
- src/jdlib/jdregex.cpp
詳細は後で書きます。
スレビューで検索をする時、幾つかのクラスのbool memberが未初期化と怒られるので、
明示的に初期化する。
> Initialize some bool members for search mode

- src/article/drawareabase.cpp
- src/article/drawareabase.h
- src/article/scrollinfo.h
メンバ変数の初期化を変更して[cppcheckの警告][warn] `(warning) Member variable 'DrawAreaBase::XXX' is not initialized in the constructor.` を修正します。
未初期化メンバーの警告を修正するためのモデルpull requestです。
アイデアなどコメントいただければ幸いです。
[warn]: https://github.com/JDimproved/JDim/pull/207#issuecomment-596205162
> DrawAreaBase: Fix member initialization

- src/jdlib/misctime.cpp
- test/gtest_jdlib_misctime.cpp
`MISC::timettostr()` の中にある `snprintf()` の呼び出しでバッファの長さより書き込む内容が長くなる可能性をコンパイラに警告されたため修正します。
NOTE: 修正で使用している `std::put_time()` のgcc対応はバージョン5から
gcc 9 warns:
```
misctime.cpp: In function 'std::string MISC::timettostr(time_t, int)':
misctime.cpp:154:60: warning: '%02d' directive output may be truncated writing between 2 and 11 bytes into a region of size between 0 and 51 [-Wformat-truncation=]
154 |             snprintf( str_ret, lng, "%d/%02d/%02d(%s) %02d:%02d:%02d",
|                                                            ^~~~
In file included from /usr/include/stdio.h:867,
from /usr/include/c++/9/cstdio:42,
from /usr/include/c++/9/ext/string_conversions.h:43,
from /usr/include/c++/9/bits/basic_string.h:6493,
from /usr/include/c++/9/string:55,
from misctime.h:8,
from misctime.cpp:10: …
```
> Fix compiler warning -Wformat-truncation= for MISC::timettostr()

- docs/manual/2020.md
- src/dbtree/nodetreebase.cpp
- src/dbtree/nodetreebase.h
> Replace char buffer with std::string for DBTREE::NodeTreeBase [1/2]

- src/jdlib/jdiconv.cpp
emoji subdivision flags sequenceのUTF-8文字列が現れたとき、
最初の U+1F3F4 が現れた時にはCP932への変換に失敗するので、その後
数値文字参照形式に変換されるが、
その後の Tag Latin Small Letter と  Cancel Tag は、libcの
iconv()関数が無視してしまうので、
iconv()関数に渡す前に処理してしまう
Fixes #214
> Iconv::convert: handle emoji subdivision flags sequence

- snap/snapcraft.yaml
dbusの利用にはSnap Storeのレビューが必要ですが今のところ使用していないためslotから外して自動レビューに戻します。
> snap: Remove dbus slot from snapcraft.yaml

- src/article/drawareabase.cpp
ecbc982d03ba5be6d4ef735f0bd3c45dd841b71f のマージ後GTK2版スレビューでフォント変更が反映されなくなった環境があったためGTK2の部分を元に戻します。
https://mao.5ch.net/test/read.cgi/linux/1551889442/986-996
> Fix thread view font configuration for GTK2

- src/article/articleview.cpp
- src/article/articleview.h
メンバ変数の初期化を変更してcppcheckの警告 `(warning) Member variable 'ArticleViewMain::XXX' is not initialized in the constructor.` を修正します。
> ArticleViewMain: Fix member initialization

- src/dbtree/nodetreebase.cpp
- src/dbtree/nodetreebase.h
malloc/freeで確保しているバッファを`std::string`で置き換えます。
> Replace char buffer with std::string for DBTREE::NodeTreeBase [2/2]

- docs/manual/2020.md
- src/xml/dom.cpp
- src/xml/dom.h
- test/gtest_xml_dom.cpp
[`XML::Dom`](https://github.com/JDimproved/JDim/blob/7a0f87c29256db2bf772cb8c2a1c0441e9e55115/src/xml/dom.h) のコードを整理してテストケースを追加します。
- メンバ関数にconstやnoexceptを指定する
- 未使用のメンバ関数やクラス外で使用していないgetter/setter関数を削除する
- 単純なgetter/setterはヘッダーに実装を移動してインライン展開を図る
関連のpull request: #210
> Refactor XML::Dom

- src/article/articleviewbase.cpp
- src/article/articleviewbase.h
メンバ変数の初期化を変更してcppcheckの警告 `(warning) Member variable 'ArticleViewBase::XXX' is not initialized in the constructor.` を修正します。
関連のpull request: #208, #219
> ArticleViewBase: Fix member initialization

- src/cache.cpp
> Replace char buffer with std::string for CACHE::jdcopy()

- docs/manual/2020.md
- src/xml/dom.cpp
- src/xml/dom.h
[`XML::Dom`][dom]のコード整理(#221)の続きです。
- イテレーターのループを範囲ベースforに修正する。
- ソースコードのスタイルを修正する。
関連のpull request: #210
[dom]: https://github.com/JDimproved/JDim/blob/a8cff72/src/xml/dom.h
> Refactor XML::Dom part2

- src/xml/dom.cpp
- test/gtest_xml_dom.cpp
[MDNのリファレンス][mdn]を参考に `Dom::insertBefore()` の挙動を変更します。
変更後もJavaScriptの挙動と異なるので注意してください。
https://github.com/JDimproved/JDim/blob/9c2098d69ada53fea4b4670fd95575eb12c015eb/src/xml/dom.h#L124
- 引数 `insNode` が `nullptr` の場合はノードを子の末尾に挿入する。
- 引数 `insNode` が子の中に無い場合はノードを挿入せず `nullptr` を返す。
関連のissue: #209
[mdn]: https://developer.mozilla.org/ja/docs/Web/API/Node/insertBefore
> XML::Dom: Change behavior for insertBefore()

- src/skeleton/textloader.cpp
- src/skeleton/textloader.h
> Replace char buffer with std::string for SKELETON::TextLoader

- docs/manual/2020.md
- src/image/imageview.cpp
- src/image/imageview.h
メンバ変数の初期化を変更してcppcheckの警告
`(warning) Member variable 'ImageViewMain::XXX' is not initialized in the constructor.` を修正します。
```
[src/image/imageview.cpp:46]: (warning) Member variable 'ImageViewMain::m_pre_width' is not initialized in the constructor.
[src/image/imageview.cpp:46]: (warning) Member variable 'ImageViewMain::m_pre_height' is not initialized in the constructor.
[src/image/imageview.cpp:46]: (warning) Member variable 'ImageViewMain::m_redraw_count' is not initialized in the constructor.
```
> ImageViewMain: Fix member initialization

- src/control/controllabel.h
[以前の変更][prev]で「ブックマーク」から「しおり」に改名がありましたがマウスボタン設定の項目がブックマークのままになっていたため修正します。
ソースコードのコメントで使われている「ブックマーク」は変更していません。
[変更履歴(2008年)][2008]から
> お気に入りと混同すると指摘があったのでスレやレスの「ブックマーク」を「しおり」に改名
[prev]: https://github.com/JDimproved/JDim/commit/c996b54fa438acbc31cb696d268015bf34eb60d1
[2008]: https://jdimproved.github.io/JDim/2008/#2.0.0-beta080418
> Change button config name "ブックマーク" with "しおりの設定/解除"

- src/image/imageviewbase.cpp
- src/image/imageviewbase.h
メンバ変数の初期化を変更してcppcheckの警告 `(warning) Member variable ImageViewBase::m_dblclick' is not initialized in the constructor.` を修正します。
```
[src/image/imageviewbase.cpp:44]: (warning) Member variable 'ImageViewBase::m_dblclick' is not initialized in the constructor.
```
> ImageViewBase: Fix member initialization

- src/aamanager.cpp
- src/bbslist/bbslistviewbase.cpp
- src/dbtree/root.cpp
- src/history/historymanager.cpp
- src/linkfiltermanager.cpp
- src/skeleton/edittreeview.cpp
- src/skeleton/edittreeview.h
- src/usrcmdmanager.cpp
- src/usrcmdmanager.h
- src/xml/document.cpp
- src/xml/document.h
`XML::Dom*`や`XML::Document`の変数にconst修飾子を付けて保守性を高めます。
関連のissue: #209
> Add const qualifier to XML::Dom* variables

- src/jdlib/miscutil.cpp
- src/jdlib/miscutil.h
- test/gtest_jdlib_miscutil.cpp
URLスキームのチェックを修正して5chのsssp（BEアイコン・エモティコン）を表示可能にします。
https://mao.5ch.net/test/read.cgi/linux/1584619744/51
> Fix checking sssp scheme

- INSTALL
- configure.ac
- docs/manual/2020.md
- docs/manual/make.md
スレッドライブラリを`std::thread`にまとめる(#228)のステップ1です。
configureスクリプトを修正してスレッドライブラリのオプションが将来のバージョンで削除されることを通知します。(`--with-thread=std`を除く)
また、ドキュメントを更新してスレッドライブラリのオプションが将来削除されることを載せます。
> Deprecate thread configure options except for std

- src/dbtree/nodetreebase.cpp
アンカーのチェック部分でANCINFOの配列サイズ(MAX_ANCINFO)を超えてデータを追加しないようにループ処理に条件を追加します。
つまり一連のアンカーのうちMAX_ANCINFO個を超えた部分はリンクに含まれなくなります。
https://mao.5ch.net/test/read.cgi/linux/1584619744/69
> Fix buffer overrun for NodeTreeBase::parse_html()

- src/skeleton/msgdiag.h
メンバ変数の初期化を変更してcppcheckの警告 `(warning) Member variable 'MsgDiag::m_conn_timer' is not initialized in the constructor.` を修正します。
```
[src/skeleton/msgdiag.cpp:17]: (warning) Member variable 'MsgDiag::m_conn_timer' is not initialized in the constructor.
[src/skeleton/msgdiag.cpp:27]: (warning) Member variable 'MsgDiag::m_conn_timer' is not initialized in the constructor.
```
> MsgDiag: Fix member initialization

- src/skeleton/edittreeview.cpp
- src/skeleton/edittreeview.h
メンバ変数の初期化を変更してcppcheckの警告 `(warning) Member variable 'EditTreeView::XXX' is not initialized in the constructor.` を修正する。
```
[src/skeleton/edittreeview.cpp:170]: (warning) Member variable 'EditTreeView::m_row_dest_before' is not initialized in the constructor.
[src/skeleton/edittreeview.cpp:170]: (warning) Member variable 'EditTreeView::m_dropped_from_other' is not initialized in the constructor.
[src/skeleton/edittreeview.cpp:170]: (warning) Member variable 'EditTreeView::m_jump_count' is not initialized in the constructor.
[src/skeleton/edittreeview.cpp:170]: (warning) Member variable 'EditTreeView::m_max_dirid' is not initialized in the constructor.
[src/skeleton/edittreeview.cpp:180]: (warning) Member variable 'EditTreeView::m_exec_drop' is not initialized in the constructor. …
```
> EditTreeView: Fix member initialization

- src/image/imageareaicon.cpp
- src/image/imageareaicon.h
メンバ変数の初期化を変更してcppcheckの警告 `(warning) Member variable 'ImageAreaIcon::m_imagetype' is not initialized in the constructor.` を修正します。
```
[src/image/imageareaicon.cpp:22]: (warning) Member variable 'ImageAreaIcon::m_imagetype' is not initialized in the constructor.
```
> ImageAreaIcon: Fix member initialization

- src/config/aboutconfig.cpp
- src/config/configitems.cpp
- src/config/configitems.h
- src/config/defaultconf.h
- src/config/globalconf.cpp
- src/config/globalconf.h
- src/dbtree/article2ch.cpp
- src/dbtree/nodetree2ch.cpp
Fixes #242
2chの過去ログ取得時にofflaw2を使用するオプションを削除します。
offlaw2.soは[2015-03-17][]に廃止されています。
機能削除後も設定ファイルのオプション項目`use_offlaw2_2ch`は残ります。
そのため互換性を考慮しソースコード上でも`use_offlaw2_2ch`を無名のenumで予約しておきます。
[2015-03-17]: https://maguro.5ch.net/test/read.cgi/mango/1426045212/538
> Remove the option to fetch kako logs using offlaw2

- CONTRIBUTING.md
- README.md
- docs/index.md
RFCリポジトリのリンクをドキュメントに追加し開発ドキュメントを参照しやすくします。
> Add RFC repository link to documents

- src/jdlib/imgloader.cpp
- src/jdlib/imgloader.h
メンバ変数の初期化を変更してcppcheckの警告 `(warning) Member variable 'ImgLoader::m_loadlevel' is not initialized in the constructor.` を修正します。
```
[src/jdlib/imgloader.cpp:18]: (warning) Member variable 'ImgLoader::m_loadlevel' is not initialized in the constructor.
```
> ImgLoader: Fix member initialization

- src/skeleton/panecontrol.cpp
- src/skeleton/panecontrol.h
メンバ変数の初期化を変更してcppcheckの警告 `(warning) Member variable 'PaneControl::m_pos' is not initialized in the constructor.` を修正します。
```
[src/skeleton/panecontrol.cpp:15]: (warning) Member variable 'PaneControl::m_pos' is not initialized in the constructor.
```
> PaneControl: Fix member initialization

- src/jdlib/miscutil.cpp
- src/jdlib/miscutil.h
clangのコンパイル時警告を修正します。
clang 9.0.0 warns:
```
miscutil.cpp:1735:12: warning: local variable 'list_str' will be copied despite being returned by name [-Wreturn-std-move]
return list_str;
^~~~~~~~
miscutil.cpp:1735:12: note: call 'std::move' explicitly to avoid copying
return list_str;
^~~~~~~~
std::move(list_str)
```
> Fix compiler warning for MISC::recover_path()

- src/main.cpp
[RFC 0006][rfc6] と #244 で動作環境を2016年以降のディストロに更新したため
glib 2.46 から [廃止予定] になっている `g_mem_set_vtable()` を呼び出すコードを削除します。
[rfc6]: https://github.com/JDimproved/rfcs/blob/d6469b2/docs/0006-platform-support.md "プラットフォームのサポート"
[廃止予定]: https://developer.gnome.org/glib/2.46/glib-Memory-Allocation.html#g-mem-set-vtable
> Remove deprecated g_mem_set_vtable()

- src/skeleton/tablabel.cpp
- src/skeleton/tablabel.h
メンバ変数の初期化を変更してcppcheckの警告 `(warning) Member variable 'TabLabel::XXX' is not initialized in the constructor.` を修正します。
```
[src/skeleton/tablabel.cpp:22]: (warning) Member variable 'TabLabel::m_x' is not initialized in the constructor.
[src/skeleton/tablabel.cpp:22]: (warning) Member variable 'TabLabel::m_y' is not initialized in the constructor.
[src/skeleton/tablabel.cpp:22]: (warning) Member variable 'TabLabel::m_width' is not initialized in the constructor.
[src/skeleton/tablabel.cpp:22]: (warning) Member variable 'TabLabel::m_height' is not initialized in the constructor.
```
> TabLabel: Fix member initialization

- src/sound/playsound.cpp
- src/sound/playsound.h
メンバ変数の初期化を変更してcppcheckの警告 `(warning) Member variable 'Play_Sound::m_stop' is not initialized in the constructor.` を修正します。
```
[src/sound/playsound.cpp:22]: (warning) Member variable 'Play_Sound::m_stop' is not initialized in the constructor.
```
> Play_Sound: Fix member initialization

- src/skeleton/view.cpp
- src/skeleton/view.h
メンバ変数の初期化を変更してcppcheckの警告 `(warning) Member variable 'View::XXX' is not initialized in the constructor.` を修正します。
```
[src/skeleton/view.cpp:19]: (warning) Member variable 'View::m_width_client' is not initialized in the constructor.
[src/skeleton/view.cpp:19]: (warning) Member variable 'View::m_height_client' is not initialized in the constructor.
```
> SKELETON::View: Fix member initialization

- src/skeleton/window.cpp
- src/skeleton/window.h
メンバ変数の初期化を変更してcppcheckの警告 `(warning) Member variable 'JDWindow::m_counter' is not initialized in the constructor.` を修正します。
```
[src/skeleton/window.cpp:54]: (warning) Member variable 'JDWindow::m_counter' is not initialized in the constructor.
```
> JDWindow: Fix member initialization

- src/updatemanager.cpp
- src/updatemanager.h
メンバ変数の初期化を変更してcppcheckの警告`(warning) Member variable 'CheckUpdate_Manager::m_total' is not initialized in the constructor.` を修正します。
```
[src/updatemanager.cpp:38]: (warning) Member variable 'CheckUpdate_Manager::m_total' is not initialized in the constructor.
```
> CheckUpdate_Manager: Fix member initialization

- src/searchmanager.cpp
- src/searchmanager.h
メンバ変数の初期化を変更してcppcheckの警告 `(warning) Member variable 'Search_Manager::XXX' is not initialized in the constructor.` を修正します。
```
[src/searchmanager.cpp:39]: (warning) Member variable 'Search_Manager::m_searchmode' is not initialized in the constructor.
[src/searchmanager.cpp:39]: (warning) Member variable 'Search_Manager::m_mode_or' is not initialized in the constructor.
[src/searchmanager.cpp:39]: (warning) Member variable 'Search_Manager::m_bm' is not initialized in the constructor.
[src/searchmanager.cpp:39]: (warning) Member variable 'Search_Manager::m_calc_data' is not initialized in the constructor.
[src/searchmanager.cpp:39]: (warning) Member variable 'Search_Manager::m_stop' is not initialized in the constructor.
```
> Search_Manager: Fix member initialization

- INSTALL
- configure.ac
- docs/manual/make.md
#253 の第一段階目のPRです。
将来のリリースで xdg-open を初期設定のブラウザに変更するためconfigureオプション `--with-xdgopen` を廃止予定にします。
> Deprecate --with-xdgopen

- src/dbtree/articlehash.cpp
- src/dbtree/articlehash.h
メンバ変数の初期化を変更してcppcheckの警告 `(warning) Member variable 'ArticleHash::XXX' is not initialized in the constructor.` を修正します。
```
[src/dbtree/articlehash.cpp:20]: (warning) Member variable 'ArticleHash::m_it_hash' is not initialized in the constructor.
[src/dbtree/articlehash.cpp:20]: (warning) Member variable 'ArticleHash::m_it_pos' is not initialized in the constructor.
[src/dbtree/articlehash.cpp:20]: (warning) Member variable 'ArticleHash::m_it_size' is not initialized in the constructor.
```
> ArticleHash: Fix member initialization

- src/jdlib/jdiconv.cpp
- src/jdlib/jdiconv.h
メンバ変数の初期化を変更してcppcheckの警告 `(warning) Member variable
'Iconv::m_buf_in_tmp' is not initialized in the constructor.` を修正します。
```
[src/jdlib/jdiconv.cpp:36]: (warning) Member variable 'Iconv::m_buf_in_tmp' is not initialized in the constructor.
```
> Iconv: Fix member initialization

- src/article/drawareabase.cpp
冗長なnullチェックを削除してcppcheckの警告 `(warning) Either the condition 'layout_next' is redundant or there is possible null pointer dereference: layout_next.` を修正します。
```
[src/article/drawareabase.cpp:4300] -> [src/article/drawareabase.cpp:4309]: (warning) Either the condition 'layout_next' is redundant or there is possible null pointer dereference: layout_next.
```
> DrawAreaBase: Fix redundant condition

- src/dbtree/articlehash.h
ArticleHashはコンストラクタ/デストラクタでメモリの確保/解放をしているためcppcheckからコピー対応するよう警告された。(Rule of three)
実際のコードではArticleHashのコピーはしていないのでメンバ関数のdelete宣言でコピーできないように修正する。
```
[src/dbtree/articlehash.cpp:23]: (warning) Class 'ArticleHash' does not have a copy constructor which is recommended since it has dynamic memory/resource allocation(s).
[src/dbtree/articlehash.cpp:23]: (warning) Class 'ArticleHash' does not have a operator= which is recommended since it has dynamic memory/resource allocation(s).
```
> ArticleHash: Fix the class to be compliant with rule of three

- src/dbtree/articlebase.cpp
- src/dbtree/articlebase.h
メンバ関数empty()をconstメンバーに修正して副作用がないことを明らかにします。
empty()はassertマクロで呼び出されるためcppcheckが望ましい副作用がある可能性を警告しました。
```
[src/dbtree/articlebase.cpp:1010]: (warning) Assert statement calls a function which may have desired side effects: 'empty'.
```
> ArticleBase: Fix ArticleBase::empty() to const member

- src/config/defaultconf.h
- src/searchmanager.cpp
Fixes #257 
初期設定のスレタイ検索サイト https://ff5ch.syoboi.jp の検索結果が0件になる不具合を修正します。合わせて ff5ch.syoboi.jp 対応の正規表現を更新します。
- HTMLソースを行で分けて行頭行末の空白を削除したり "\&amp;" を "&" に変換する処理を止めてソースをそのまま検索するように変更する。
- 複数行に分かれているデータに対応するため正規表現パターン中の "\n" は改行文字に変換して検索する。
不具合のあるバージョンから更新した場合はabout:configの「スレタイ検索時にアドレスとスレタイを取得する正規表現」をデフォルトに戻してください。
https://mao.5ch.net/test/read.cgi/linux/1584619744/191
> Fix thread title search for the initial setting

- src/article/articleadmin.cpp
- src/article/articleadmin.h
- src/core.cpp
- src/core.h
- src/jdlib/timeout.cpp
- src/jdlib/timeout.h
- src/skeleton/msgdiag.h
- src/skeleton/prefdiag.cpp
- src/skeleton/prefdiag.h
Fixes #276 
タイマーを使うコードで寿命管理が徹底されていなかったためメモリリークが発生していました。
スマートポインターを返すように変更してリークを修正します。
gcc-9のログ
```
Direct leak of 24 byte(s) in 1 object(s) allocated from:
#0 0x7f18a17e03d1 in operator new(unsigned long) (/lib/x86_64-linux-gnu/liblsan.so.0+0x103d1)
#1 0x55ff4e8a91f5 in JDLIB::Timeout::connect(sigc::slot<bool, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil, sigc::nil>, unsigned int) src/jdlib/timeout.cpp:54
#2 0x55ff4df0f034 in ARTICLE::ArticleViewMain::show_instruct_diag() src/article/articleview.cpp:654
#3 0x55ff4df15888 in ARTICLE::ArticleViewMain::update_finish() src/article/articleview.cpp:593
#4 0x55ff4e3ed537 in SKELETON::Admin::update_finish(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) src/skeleton/admin.cpp:1645
```
> Fix memory leak for JDLIB::Timeout::connect()

- src/history/viewhistory.cpp
- src/history/viewhistory.h
メンバ関数empty()がassertマクロの中で呼ばれていますがcppcheckがconstメンバ関数でなく副作用がある可能性を警告していたため修正します。
さらにViewHistoryのメンバ関数のうちconstやnoexcept指定可能なものを修正します。
cppcheckのレポート
```
src/history/viewhistory.cpp:325:13: warning: Assert statement calls a function which may have desired side effects: 'get_current_url'. [assertWithSideEffect]
assert( get_current_url() == url );
^
```
> ViewHistory: Fix ArticleBase::get_current_url() to const member

- src/dbtree/nodetree2chcompati.cpp
- src/dbtree/nodetreebase.cpp
- src/dbtree/nodetreejbbs.cpp
- src/dbtree/nodetreemachi.cpp
NodeTreeXXXはデストラクタ内で仮想関数clear()を呼び出していますが、仮想関数はデストラクタ内で派生クラスの関数として呼び出しできないためcppcheckに警告されます。
cppcheckのレポート
```
src/dbtree/nodetree2chcompati.h:30:14: warning: Virtual function 'clear' is called from destructor '~NodeTree2chCompati()' at line 36. Dynamic binding is not used. [virtualCallInConstructor]
void clear() override;
^
src/dbtree/nodetree2chcompati.cpp:36:5: note: Calling clear
clear();
^
src/dbtree/nodetree2chcompati.h:30:14: note: clear is a virtual function
void clear() override;
^
src/dbtree/nodetreejbbs.h:34:14: warning: Virtual function 'clear' is called from destructor '~NodeTreeJBBS()' at line 45. Dynamic binding is not used. [virtualCallInConstructor]
void clear() override;
^
src/dbtree/nodetreejbbs.cpp:45:5: note: Calling clear
clear();
^ …
```
> NodeTreeBase: Fix calling virtual function from the destructor

- src/article/articleview.cpp
- src/board/boardview.cpp
ArticleViewMain、BoardViewはコンストラクタ内で仮想関数save_session()を呼び出していますが、仮想関数はコントラクタ内で派生クラスの関数として呼び出しできないためcppcheckに警告されます。
cppcheckのレポート
```
src/article/articleview.h:46:14: warning: Virtual function 'save_session' is called from destructor '~ArticleViewMain()' at line 78. Dynamic binding is not used. [virtualCallInConstructor]
void save_session() override;
^
src/article/articleview.cpp:78:5: note: Calling save_session
save_session();
^
src/article/articleview.h:46:14: note: save_session is a virtual function
void save_session() override;
^
src/board/boardview.h:21:14: warning: Virtual function 'save_session' is called from destructor '~BoardView()' at line 54. Dynamic binding is not used. [virtualCallInConstructor]
void save_session() override;
^ …
```
> View: Fix calling virtual function from the destructor

- src/article/articleviewsearch.cpp
ArticleViewSearchはデストラクタ内で仮想関数stop()を呼び出していますが、仮想関数はデストラクタ内で派生クラスの関数として呼び出しできないためcppcheckに警告されます。
cppcheckのレポート
```
src/article/articleviewsearch.h:49:14: warning: Virtual function 'stop' is called from destructor '~ArticleViewSearch()' at line 62. Dynamic binding is not used. [virtualCallInConstructor]
void stop() override;
^
src/article/articleviewsearch.cpp:62:5: note: Calling stop
stop();
^
src/article/articleviewsearch.h:49:14: note: stop is a virtual function
void stop() override;
^
```
> ArticleViewSearch: Fix calling virtual function from the destructor

- src/article/toolbar.cpp
- src/article/toolbarsearch.cpp
- src/article/toolbarsimple.cpp
- src/bbslist/toolbar.cpp
- src/board/toolbar.cpp
- src/maintoolbar.cpp
- src/message/toolbar.cpp
XXXToolBarはコンストラクタ内で仮想関数pack_buttons()を呼び出していますが、仮想関数はコントラクタ内で派生クラスの関数として呼び出しできないためcppcheckに警告されます。
<details>
<summary>cppcheckのレポート</summary>
```
src/article/toolbarsearch.h:36:14: warning: Virtual function 'pack_buttons' is called from constructor 'SearchToolBar()' at line 36. Dynamic binding is not used. [virtualCallInConstructor]
void pack_buttons() override;
^
src/article/toolbarsearch.cpp:36:5: note: Calling pack_buttons
pack_buttons();
^
src/article/toolbarsearch.h:36:14: note: pack_buttons is a virtual function
void pack_buttons() override;
^
src/article/toolbar.h:39:14: warning: Virtual function 'pack_buttons' is called from constructor 'ArticleToolBar()' at line 47. Dynamic binding is not used. [virtualCallInConstructor]
void pack_buttons() override; …
```
> ToolBar: Fix calling virtual function from the constructor

- src/article/articleview.cpp
ArticleViewMainはデストラクタ内で仮想関数live_stop()を呼び出していますが、仮想関数はデストラクタ内で派生クラスの関数として呼び出しできないためcppcheckに警告されます。
cppcheckのレポート
```
src/article/articleview.h:64:14: warning: Virtual function 'live_stop' is called from destructor '~ArticleViewMain()' at line 87. Dynamic binding is not used. [virtualCallInConstructor]
void live_stop() override;
^
src/article/articleview.cpp:87:22: note: Calling live_stop
if( get_live() ) live_stop();
^
src/article/articleview.h:64:14: note: live_stop is a virtual function
void live_stop() override;
^
```
> ArticleViewMain: Fix calling virtual function from the destructor

- src/dbtree/articlebase.cpp
ArticleBaseはデストラクタ内で仮想関数unlock_impl()を呼び出していますが、仮想関数はデストラクタ内で派生クラスの関数として呼び出しできないためcppcheckに警告されます。
cppehckのレポート
```
src/dbtree/articlebase.h:420:14: warning: Virtual function 'unlock_impl' is called from destructor '~ArticleBase()' at line 120. Dynamic binding is not used. [virtualCallInConstructor]
void unlock_impl() override;
^
src/dbtree/articlebase.cpp:120:5: note: Calling unlock_impl
unlock_impl();
^
src/dbtree/articlebase.h:420:14: note: unlock_impl is a virtual function
void unlock_impl() override;
^
```
> ArticleBase: Fix calling virtual function from the destructor

- src/dbtree/ruleloader.cpp
RuleLoaderはコンストラクタ・デストラクタ内で仮想関数get_url()を呼び出していますが、仮想関数はコンストラクタ・デストラクタ内で派生クラスの関数として呼び出しできないためcppcheckに警告されます。
cppcheckのレポート
```
src/dbtree/ruleloader.h:31:21: warning: Virtual function 'get_url' is called from constructor 'RuleLoader(const std::string&url_boardbase)' at line 25. Dynamic binding is not used. [virtualCallInConstructor]
std::string get_url() override;
^
src/dbtree/ruleloader.cpp:25:49: note: Calling get_url
std::cout << "RuleLoader::RuleLoader : " << get_url() << std::endl;
^
src/dbtree/ruleloader.h:31:21: note: get_url is a virtual function
std::string get_url() override;
^
src/dbtree/ruleloader.h:31:21: warning: Virtual function 'get_url' is called from destructor '~RuleLoader()' at line 35. Dynamic binding is not used. …
```
> RuleLoader: Fix calling virtual function from the ctor and dtor

- src/image/imageadmin.cpp
- src/skeleton/admin.cpp
Admin、ImageAdminはデストラクタ内で仮想関数close_window()を呼び出していますが、仮想関数はデストラクタ内で派生クラスの関数として呼び出しできないためcppcheckに警告されます。
cppehckのレポート
```
src/image/imageadmin.h:83:14: warning: Virtual function 'close_window' is called from destructor '~ImageAdmin()' at line 93. Dynamic binding is not used. [virtualCallInConstructor]
void close_window() override;
^
src/image/imageadmin.cpp:93:5: note: Calling close_window
close_window();
^
src/image/imageadmin.h:83:14: note: close_window is a virtual function
void close_window() override;
^
src/skeleton/admin.h:225:22: warning: Virtual function 'close_window' is called from destructor '~Admin()' at line 110. Dynamic binding is not used. [virtualCallInConstructor]
virtual void close_window(){}
^
src/skeleton/admin.cpp:110:5: note: Calling …
```
> Admin: Fix calling virtual function from the destructor

- src/image/imagewin.cpp
- src/message/messagewin.cpp
ImageWin、MessageWinはデストラクタ内で仮想関数set_shown_win()を呼び出していますが、仮想関数はデストラクタ内で派生クラスの関数として呼び出しできないためcppcheckに警告されます。
cppehckのレポート
```
src/image/imagewin.h:54:14: warning: Virtual function 'set_shown_win' is called from destructor '~ImageWin()' at line 45. Dynamic binding is not used. [virtualCallInConstructor]
void set_shown_win( const bool set ) override;
^
src/image/imagewin.cpp:45:5: note: Calling set_shown_win
set_shown_win( false );
^
src/image/imagewin.h:54:14: note: set_shown_win is a virtual function
void set_shown_win( const bool set ) override;
^
src/message/messagewin.h:46:14: warning: Virtual function 'set_shown_win' is called from destructor '~MessageWin()' at line 45. Dynamic binding is not used. [virtualCallInConstructor]
void set_shown_win( const bool …
```
> JDWindow: Fix calling virtual function from the destructor

- src/image/imagewin.cpp
- src/message/messagewin.cpp
ImageWin、MessageWinはコンストラクタ・デストラクタ内のprintデバッグで仮想関数get_xxx()を呼び出していますが、仮想関数はコンストラクタ・デストラクタ内で派生クラスの関数として呼び出しできないためcppcheckに警告されます。
<details>
<summary>cppcheckのレポート</summary>
```
src/image/imagewin.h:31:13: warning: Virtual function 'get_x_win' is called from constructor 'ImageWin()' at line 25. Dynamic binding is not used. [virtualCallInConstructor]
int get_x_win() override;
^
src/image/imagewin.cpp:25:18: note: Calling get_x_win
<< get_x_win() << " " << get_y_win()
^
src/image/imagewin.h:31:13: note: get_x_win is a virtual function
int get_x_win() override;
^
src/image/imagewin.h:32:13: warning: Virtual function 'get_y_win' is called from constructor 'ImageWin()' at line 25. Dynamic binding is not used. [virtualCallInConstructor]
int get_y_win() override;
^ …
```
> JDWindow: Fix calling virtual function from the ctor and dtor

- src/dbtree/board2chcompati.cpp
- src/dbtree/boardjbbs.cpp
- src/dbtree/boardmachi.cpp
char配列について冗長または範囲外なアクセスの可能性をcppcheckに警告されました。
配列の長さは16でSmall String Optimizationが期待できるためstd::stringに置き換えます。
cppcheckのレポート
```
src/dbtree/board2chcompati.cpp:399:16: warning: Either the condition 'i<16' is redundant or the array 'str_num[16]' is accessed at index 16, which is out of bounds. [arrayIndexOutOfBoundsCond]
str_num[ i ] = '\0';
^
src/dbtree/board2chcompati.cpp:389:48: note: Assuming that condition 'i<16' is not redundant
while( '0' <= *pos && *pos <= '9' && i < 16 ) str_num[ i++ ] = *( pos++ );
^
src/dbtree/board2chcompati.cpp:399:16: note: Array index out of bounds
str_num[ i ] = '\0';
^
src/dbtree/boardjbbs.cpp:205:16: warning: Either the condition 'i<16' is redundant or the array 'str_num[16]' is accessed at index 16, which is out of bounds. [arrayIndexOutOfBoundsCond] …
```
> Replace char buffer with std::string for DBTREE::Board classes

- src/jdlib/miscutil.cpp
return文が抜けているとcppcheckに警告された箇所があったため修正します。
cppcheckのレポート
```
src/jdlib/miscutil.cpp:1654:39: warning: Return value of function path.substr() is not used. [ignoredReturnValue]
if( i == std::string::npos ) path.substr( pos );
^
```
> Fix ignored return value for MISC::get_hostname()

- src/main.cpp
標準出力をログファイルにリダイレクトさせる処理の中で一時変数の文字列からポインターを使っている、つまりダングリングポインターになっているとcppcheckに警告されたため修正します。
cppcheckのレポート
```
src/main.cpp:505:24: error: Using pointer to temporary. [danglingTemporaryLifetime]
tmp = freopen( logfile, "ab", stdout );
^
src/main.cpp:504:31: note: Pointer to container is created here.
const char *logfile = to_locale_cstr( CACHE::path_msglog() );
^
src/main.cpp:505:24: note: Using pointer to temporary.
tmp = freopen( logfile, "ab", stdout );
^
src/main.cpp:507:24: error: Using pointer to temporary. [danglingTemporaryLifetime]
tmp = freopen( logfile, "ab", stderr );
^
src/main.cpp:504:31: note: Pointer to container is created here.
const char *logfile = to_locale_cstr( CACHE::path_msglog() );
^
src/main.cpp:507:24: note: Using pointer to temporary.
tmp = freopen( logfile, …
```
> Fix dangling pointer for logging file

- src/message/messageadmin.cpp
条件文で常にtrueになる箇所があるとcppcheckに警告されたため修正します。
cppcheckのレポート
```
src/message/messageadmin.cpp:138:14: warning: Conversion of string literal "toggle_wrap" to bool always evaluates to true. [incorrectStringBooleanError]
else if( "toggle_wrap" ){
^
```
> MessageAdmin: Fix if-statement which is always true

- src/jdlib/miscutil.cpp
括弧が一致しないとcppcheckから警告されたため修正します。
cppcheckのレポート
```
src/jdlib/miscutil.cpp:1702:24: error: Unmatched '('. Configuration: '_WIN32'. [syntaxError]
return recover_path( Glib::locale_to_utf8( std::string( env.data() ) );
^
```
> Fix unmatched paren for MISC::getenv_limited()

- src/board/boardviewbase.cpp
Fixes #295
スレ一覧の項目を3つ以下にするとマウスホイールでスクロールできない不具合を修正します。
https://mao.5ch.net/test/read.cgi/linux/1584619744/323
> Fix mouse wheel scrolling for thread list

- src/article/articleviewetc.cpp
- src/article/articleviewsearch.cpp
Fixes #296
抽出タブをロックして再起動するとタブアイコンが表示されない不具合を修正します。
> Fix displaying tab icon for extraction tab

- src/dbtree/boardlocal.h
- src/dbtree/root.cpp
Fixes #297
コマンドライン引数にローカルのDATファイルを指定して起動しても内容が表示されない問題を修正します。
> Fix loading local dat file specified by command line arguments

- src/skeleton/admin.h
SKELETON::Adminはコンストラクタ/デストラクタでメモリの確保/解放をしているためcppcheckからコピー対応するよう警告されました。(Rule of three)
実際のコードではAdminのコピーはしていないのでメンバ関数のdelete宣言でコピーできないように修正します。
cppcheckのレポート
```
src/skeleton/admin.cpp:63:5: warning: Class 'Admin' does not have a copy constructor which is recommended since it has dynamic memory/resource allocation(s). [noCopyConstructor]
m_notebook = new DragableNoteBook();
^
src/skeleton/admin.cpp:63:5: warning: Class 'Admin' does not have a operator= which is recommended since it has dynamic memory/resource allocation(s). [noOperatorEq]
m_notebook = new DragableNoteBook();
^
```
> Admin: Fix the class to be compliant with rule of three

- src/skeleton/toolmenubutton.cpp
メンバーm_buttonがassertマクロの中で関数を呼び出していますがcppcheckがconstメンバ関数でなく副作用がある可能性を警告していたため修正します。
cppcheckのレポート
```
src/skeleton/toolmenubutton.cpp:39:23: warning: Assert statement calls a function which may have desired side effects: 'get_label_widget'. [assertWithSideEffect]
assert( m_button->get_label_widget() != nullptr );
^
```
> ToolMenuButton: Fix mutable member function in assert macro

- src/xml/dom.cpp
std::stringの変数について冗長または範囲外なアクセスの可能性をcppcheckに警告されたため条件文を整理して修正します。
cppcheckのレポート
```
src/xml/dom.cpp:133:41: warning: Either the condition 'open_tag.empty()' is redundant or expression 'open_tag[0]' cause access out of bounds. [containerOutOfBounds]
bool is_alpha = ( ( open_tag[0] >= 'A' && open_tag[0] <= 'Z' ) || ( open_tag[0] >= 'a' && open_tag[0] <= 'z' ) );
^
src/xml/dom.cpp:137:31: note: Assuming that condition 'open_tag.empty()' is not redundant
if( open_tag.empty() || ! is_alpha ) continue;
^
src/xml/dom.cpp:133:41: note: Access out of bounds
bool is_alpha = ( ( open_tag[0] >= 'A' && open_tag[0] <= 'Z' ) || ( open_tag[0] >= 'a' && open_tag[0] <= 'z' ) );
^
```
> Dom: Fix accessing first character for std::string

- src/dbtree/nodetreebase.cpp
- src/dbtree/nodetreejbbs.cpp
- src/jdlib/misctrip.cpp
- src/jdlib/miscutil.cpp
配列にアクセスした後で境界のチェックをしているとcppehckに指摘された箇所があったため条件の順序を修正します。
cppcheckのレポート
```
src/dbtree/nodetreejbbs.cpp:240:29: style: Array index 'pos' is used before limits check. [arrayIndexThenCheck]
while( lines[ pos ] != '\n' && pos < byte_lines ) ++pos;
^
src/dbtree/nodetreebase.cpp:1772:15: style: Array index 'i' is used before limits check. [arrayIndexThenCheck]
while( str[ i ] != 's' && i < lng ) ++i;
^
src/jdlib/misctrip.cpp:129:33: style: Array index 'n' is used before limits check. [arrayIndexThenCheck]
for( n = 17; key[n] && n < 19; ++n )
^
src/jdlib/miscutil.cpp:139:16: style: Array index 'i' is used before limits check. [arrayIndexThenCheck]
if( str[ i ] == '\"' && (i < 1 || str[ i -1 ] != '\\') ){
^
```
> Fix array bounds checking

- src/jdlib/imgloader.cpp
イテレーターのインクリメントを前置にしたほうがよいとcppcheckに指摘された箇所を標準ライブラリのアルゴリズムを使うように修正しました。
cppcheckのレポート
```
src/jdlib/imgloader.cpp:254:34: performance: Prefer prefix ++/-- operators for non-primitive types. [postfixOperator]
it != m_cache.end(); it++ ) {
^
```
> ImgProvider: Fix iterator loop to use std::find_if()

- src/jdlib/tfidf.cpp
- src/skeleton/view.cpp
std::setの挿入操作のために事前検索は必要ないとcppcheckに指摘されたため挿入結果を使って条件分岐するように修正します。
cppcheckのレポート
```
src/skeleton/view.cpp:203:33: performance: Searching before insertion is not necessary. [stlFindInsert]
m_url_popup.insert( url );
^
src/jdlib/tfidf.cpp:38:31: performance: Searching before insertion is not necessary. [stlFindInsert]
set_words.insert( word );
^
```
> Fix std::set insertation to avoid double searching

- src/config/defaultconf.h
- src/searchmanager.cpp
#313 の修正です。
初期設定のスレタイ検索サイト https://ff5ch.syoboi.jp の検索結果が2020年6月から変更されてスレッド抽出に失敗するようになりました。
そのため正規表現パターン構築の修正とabout:config「スレタイ検索時にアドレスとスレタイを取得する正規表現」のデフォルト設定を更新します。
デフォルト設定はPOSIX Character class(`[:space:]`)を使いますが利用できない環境では他の方法(Perl互換の`\s`など)を使用してください。
2aa3488fbb の変更のうち"複数行に分かれているデータに対応するため正規表現パターン中の "\n" は改行文字に変換して検索する"を取り消します。
> Fix thread title search for intial setting (2020-06)

- src/board/preference.cpp
- src/config/configitems.cpp
- src/config/configitems.h
- src/config/defaultconf.h
- src/config/globalconf.cpp
- src/config/globalconf.h
- src/dbtree/board2ch.cpp
- src/dbtree/board2ch.h
- src/dbtree/board2chcompati.cpp
- src/dbtree/board2chcompati.h
- src/dbtree/boardbase.cpp
- src/dbtree/boardbase.h
- src/dbtree/interface.cpp
- src/dbtree/interface.h
- src/dbtree/nodetree2ch.cpp
- src/message/post.cpp
- src/proxypref.h
#317 の修正です。
プロキシ側のクッキー処理と整合性を取るため書き込み用クッキーの生成処理を読み込み用の処理から分離します。
プロキシ利用がoffのとき、またはプロキシ利用時にプロキシにクッキーを送る設定がonのときはサイトにcookieを送信します。
プロキシ設定にチェック項目「クッキーを送る」を追加します。(初期設定はoff)
チェックを入れるとプロキシ利用時にJDimからプロキシへサイトのクッキーを送信します。
プロキシのクッキー処理にあわせて設定してください。
[![thumb][]][screenshot]
[thumb]: https://i.imgur.com/qplOu2el.png
[screenshot]: https://i.imgur.com/qplOu2e.png
> Separate cookie generation for posting

- src/article/drawareabase.cpp
if文の中で論理和(`||`)であるべき箇所がビット単位和(`|`)になっているとcppcheckに指摘されたため修正します。
cppcheckのレポート
```
src/article/drawareabase.cpp:4645:21: style: Boolean result is used in bitwise operation. Clarify expression with parentheses. [clarifyCondition]
if( ! rect_from | ! rect_to ) return false;
^
```
> DrawAreaBase: Fix bitwise OR operation to logical OR for if condition

- src/main.cpp
C-styleのポインターキャストを使っているとcppcheckに指摘されたためreinterpret_castを使って修正します。
```
src/main.cpp:197:26: style: C-style pointer casting [cstyleCast]
XSMPDATA *xsmpdata = ( XSMPDATA* ) client_data;
^
```
> main: Fix C-style pointer casting

- src/dbtree/Makefile.am
- src/dbtree/board2ch.cpp
- src/dbtree/board2ch.h
- src/dbtree/boardbase.h
- src/dbtree/frontloader.cpp
- src/dbtree/frontloader.h
- src/dbtree/interface.cpp
- src/dbtree/interface.h
- src/message/messageview.cpp
- src/message/post.cpp
Fixes #317
新スレ作成時の書き込みメッセージ作成を更新します。
対応サイトでは板のフロントページを読み込む処理を追加してスレ立て用キーワードを解析します。
読み込みは以下の状況で行われます。ただし、受信したデータが空の時はキーワードの更新をしません。
- 書き込みビューを開く
- スレ立てに成功する
> Update HTTP request for new article creation

- src/jdlib/jdiconv.cpp
printデバッグの書式フラグと変数の型の符号が異なっているとcppcheckに指摘されたため修正します。
cppcheckのレポート
```
src/jdlib/jdiconv.cpp:238:17: portability: %zd in format string (no. 1) requires 'ssize_t' but the argument type is 'size_t {aka unsigned long}'. [invalidPrintfArgType_sint]
snprintf( str_tmp, 256, "iconv EILSEQ left = %zd code = %x %x %x", m_byte_left_in, code0, code1, code2 );
^
```
> Iconv: Fix printf format for print debug

- src/image/imageview.cpp
- src/image/imageviewpopup.cpp
画像サイズ表示の書式フラグと変数の型の符号が異なっているとcppcheckに指摘されたためstd::to_string()を使って修正します。
cppcheckのレポート
```
src/image/imageviewpopup.cpp:323:9: portability: %u in format string (no. 1) requires 'unsigned int' but the argument type is 'size_t {aka unsigned long}'. [invalidPrintfArgType_uint]
snprintf( tmpstr, sizeof( tmpstr ), "%u / %u KiB", m_length_prev/1024, get_img()->total_length()/1024 );
^
src/image/imageview.cpp:369:13: portability: %u in format string (no. 1) requires 'unsigned int' but the argument type is 'size_t {aka unsigned long}'. [invalidPrintfArgType_uint]
snprintf( tmpstr, sizeof( tmpstr ), "%u / %u KiB", m_length_prev/1024, get_img()->total_length()/1024 );
^
```
> image: Replace printf format for image size with std::to_string()

- src/skeleton/entry.h
privateメンバが存在するのにコンストラクタが無いとcppcheckに指摘されたためデフォルトメンバ初期化子を指定して修正します。
cppcheckのレポート
```
src/skeleton/entry.h:15:5: style: The class 'JDEntry' does not have a constructor although it has private member variables. [noConstructor]
class JDEntry : public Gtk::Entry
^
```
> JDEntry: Use member initializer

- src/jdlib/miscutil.cpp
条件文の中でヌル文字チェックが常にtrueになるとcppcheckに指摘されたため当該の部分を削除します。
cppcheckのレポート
```
src/jdlib/miscutil.cpp:64:35: style: Redundant condition: If 'EXPR == ' '', the comparison 'EXPR != '\0'' is always true. [redundantCondition]
while( data[ pos ] == ' ' && data[ pos ] != '\0' ) ++pos;
^
```
> misc: Remove redundant condition for NUL character check

- src/bbslist/bbslistviewbase.cpp
- src/dbtree/nodetreebase.cpp
ローカル変数をシャドーイングしているとcppcheckから指摘されたため内側のスコープにある変数名を変更します。
cppcheckのレポート
```
src/bbslist/bbslistviewbase.cpp:3055:29: style: Local variable 'url' shadows outer argument [shadowArgument]
const Glib::ustring url = row[ m_columns.m_url ];
^
src/dbtree/nodetreebase.cpp:582:28: style: Local variable 'query' shadows outer argument [shadowArgument]
const std::string &query = ( *it_query );
^
```
> Rename local variable names to avoid shadowing

- src/xml/dom.cpp
符号なし整数で負の数を想定した比較になっているとcppcheckに指摘されたため条件文を修正します。
cppcheckのレポート
```
src/xml/dom.cpp:208:31: style: Checking if unsigned expression 'count' is less than zero. [unsignedLessThanZero]
if( count <= 0 ) break;
^
```
> Dom: Fix comparison condition for unsigned integer

- src/article/drawareabase.cpp
特定の式で標準ライブラリの数学関数が使えるとcppcheckに指摘されたためコードを修正します。
- `( dy / fabs( dy ) ) * X` -> `std::copysign( X, dy )`
- `MIN( X, Y )` -> `std::fmin( X, Y )`
- `exp( X ) -1` -> `std::expm1( X )`
cppcheckのレポート
```
src/article/drawareabase.cpp:3510:57: style: Expression 'exp(x) - 1' can be replaced by 'expm1(x)' to avoid loss of precision. [unpreciseMathCall]
else dy =  ( dy / fabs( dy ) ) * MIN( ( exp( ( fabs( dy ) - AUTOSCR_CIRCLE/4 ) /50 ) -1 ) * 5,
^
```
> DrawAreaBase: Use standard library math functions

- src/jdlib/confloader.cpp
- src/xml/document.cpp
生のループに対してSTLアルゴリズム関数を使用することをcppcheckに指摘されたため修正します。
cppcheckのレポート
```
src/jdlib/confloader.cpp:72:18: style: Consider using std::accumulate algorithm instead of a raw loop. [useStlAlgorithm]
str_conf += conf.name + " = " + conf.value + "\n";
^
src/jdlib/confloader.cpp:92:33: style: Consider using std::find_if algorithm instead of a raw loop. [useStlAlgorithm]
if( conf.name == name ) {
^
src/xml/document.cpp:123:9: style: Consider using std::find_if algorithm instead of a raw loop. [useStlAlgorithm]
{
^
```
> Use STL Algorithm for raw loops

- src/article/preference.cpp
- src/cssmanager.cpp
- src/dbimg/img.cpp
古い値を使用する前に再度変数に代入しているとcppcheckい指摘されたため修正します。
- `src/article/preference.cpp` は二度代入していたので削除
- `src/cssmanager.cpp` は変数名の間違いを修正
- `src/dbimg/img.cpp` は条件が重ならないためelse ifに変更
cppcheckのレポート
```
src/article/preference.cpp:154:21: style: Variable 'pre_res' is reassigned a value before the old one has been used. [redundantAssignment]
pre_res = res;
^
src/article/preference.cpp:146:25: note: pre_res is assigned
pre_res = save = res;
^
src/article/preference.cpp:154:21: note: pre_res is overwritten
pre_res = res;
^
src/cssmanager.cpp:371:43: style: Variable 'css.border_right_width_em' is reassigned a value before the old one has been used. [redundantAssignment]
css.border_right_width_em = size;
^
src/cssmanager.cpp:370:43: note: css.border_right_width_em is assigned
css.border_right_width_em = size; …
```
> Fix re-assign value before the old one is used

- src/article/drawareabase.cpp
- src/dbtree/frontloader.cpp
- src/dbtree/ruleloader.cpp
- src/dbtree/settingloader.cpp
- src/skeleton/edittreeview.cpp
条件に関係なく代入の結果と同じになるとcppcheckに指摘されたため代入の条件文を削除します。
cppcheckのレポート
```
src/article/drawareabase.cpp:5442:28: style: The statement 'if (m_scrollinfo.x!=m_x_pointer) m_scrollinfo.x=m_x_pointer' is logically equivalent to 'm_scrollinfo.x=m_x_pointer'. [duplicateConditionalAssign]
if( m_scrollinfo.x != m_x_pointer ) m_scrollinfo.x = m_x_pointer;
^
src/article/drawareabase.cpp:5442:60: note: Assignment 'm_scrollinfo.x=m_x_pointer'
if( m_scrollinfo.x != m_x_pointer ) m_scrollinfo.x = m_x_pointer;
^
src/article/drawareabase.cpp:5442:28: note: Condition 'm_scrollinfo.x!=m_x_pointer' is redundant
if( m_scrollinfo.x != m_x_pointer ) m_scrollinfo.x = m_x_pointer;
^
src/article/drawareabase.cpp:5443:28: style: The statement 'if (m_scrollinfo.y!=m_y_pointer) m_scrollinfo.y=m_y_pointer' is logically …
```
> Remove unnecessary condition for assigning value

- src/article/embeddedimage.cpp
- src/bbslist/bbslistviewbase.cpp
- src/config/configitems.cpp
- src/dbimg/img.cpp
- src/globalabonethreadpref.h
未使用の変数が存在するとcppcheckに指摘されたため削除します。
cppcheckのレポート
```
src/article/embeddedimage.cpp:135:17: style: Unused variable: errmsg [unusedVariable]
std::string errmsg;
^
src/config/configitems.cpp:485:30: style: Unused variable: list_tmp [unusedVariable]
std::list< std::string > list_tmp;
^
src/config/configitems.cpp:486:40: style: Unused variable: it_tmp [unusedVariable]
std::list< std::string >::iterator it_tmp;
^
src/bbslist/bbslistviewbase.cpp:3004:32: style: Unused variable: list_path [unusedVariable]
std::list< Gtk::TreePath > list_path;
^
src/dbimg/img.cpp:780:34: style: Unused variable: list_tmp [unusedVariable]
std::list< std::string > list_tmp;
^
src/dbimg/img.cpp:781:44: style: Unused variable: it_tmp [unusedVariable]
std::list< std::string >::iterator it_tmp;
^ …
```
> Remove unused local variables

- src/article/articleviewbase.cpp
- src/dbtree/boardbase.cpp
隣り合うif文が同じ条件であるとcppcheckに指摘されたためブロックをまとめます。
cppcheckのレポート
```
src/dbtree/boardbase.cpp:2365:9: style: The if condition is the same as the previous if condition [duplicateCondition]
if( ! m_list_subject_created ) return list_url;
^
src/dbtree/boardbase.cpp:2364:9: note: First condition
if( ! m_list_subject_created ) download_subject( std::string(), true );
^
src/dbtree/boardbase.cpp:2365:9: note: Second condition
if( ! m_list_subject_created ) return list_url;
^
src/article/articleviewbase.cpp:677:9: style: The if condition is the same as the previous if condition [duplicateCondition]
if( m_drawarea ) return m_drawarea->width_client();
^
src/article/articleviewbase.cpp:674:9: note: First condition
if( m_drawarea ) std::cout << "ArticleViewBase::width_client : " << …
```
> Unite if-statement blocks for same condition

- src/bbslist/bbslistviewbase.cpp
- src/bbslist/bbslistviewbase.h
- src/bbslist/editlistwin.cpp
- src/bbslist/editlistwin.h
- src/board/boardviewbase.cpp
- src/board/boardviewbase.h
- src/skeleton/dragnote.cpp
- src/skeleton/dragnote.h
- src/skeleton/edittreeview.cpp
- src/skeleton/edittreeview.h
関数の引数にconst修飾子を付けることができるとcppcheckに指摘されたため修正します。さらにconstメンバ関数にできる場合は変更します。
cppcheckのレポート
```
src/bbslist/bbslistviewbase.cpp:1042:71: style: Parameter 'store' can be declared with const [constParameter]
void BBSListViewBase::copy_treestore( Glib::RefPtr< Gtk::TreeStore >& store )
^
src/board/boardviewbase.cpp:976:57: style: Parameter 'row_a' can be declared with const [constParameter]
int BoardViewBase::compare_drawbg( Gtk::TreeModel::Row& row_a, Gtk::TreeModel::Row& row_b )
^
src/board/boardviewbase.cpp:976:85: style: Parameter 'row_b' can be declared with const [constParameter]
int BoardViewBase::compare_drawbg( Gtk::TreeModel::Row& row_a, Gtk::TreeModel::Row& row_b )
^
src/board/boardviewbase.cpp:993:89: style: Parameter 'row_a' can be declared with const [constParameter]
int …
```
> Add const qualifier to function parameters

- src/jdlib/misccharcode.cpp
- src/jdlib/misccharcode.h
関数の引数にconst修飾子を付けることができるとcppcheckに指摘されたため整数の参照渡しを値渡しに変更します。
cppcheckのレポート
```
src/jdlib/misccharcode.cpp:43:47: style: Parameter 'read_byte' can be declared with const [constParameter]
bool MISC::is_euc( const char* input, size_t& read_byte )
^
src/jdlib/misccharcode.cpp:134:48: style: Parameter 'read_byte' can be declared with const [constParameter]
bool MISC::is_sjis( const char* input, size_t& read_byte )
^
src/jdlib/misccharcode.cpp:190:47: style: Parameter 'read_byte' can be declared with const [constParameter]
bool MISC::is_utf( const char* input, size_t& read_byte )
^
```
> Modify parameter type from reference to value

- src/dbtree/root.cpp
- src/dbtree/root.h
45e0ec4d7c の修正でメンバ関数の引数を参照渡しに変更しましたが、関数内処理の影響で引数の参照値が変化し板移転の処理に支障が生じることが分かりました。
そのため引数を値渡しに変更することで意図しない値の更新を防ぎます。
> Root: Change parameters to pass by value

- src/dbtree/boardbase.cpp
板のsubject.txtを取得するとき`301 Moved Permanently`が返ってきたときは板のフロントページを取得して移転の確認を行っています。
確認でHTMLから移転先が見つからなかったときはこれまで板一覧の更新を行っていましたが、新たに処理を追加し再び`301`が返ってきた場合はLocationレスポンスヘッダーで示されたURLへ板を移転するようにします。
関連のissue: #332
> Support processing for moving board by 301 Moved Permanently

- src/config/globalconf.cpp
- src/config/globalconf.h
- src/dbtree/root.cpp
板一覧の取得で`301 Moved Permanently`が返ってきたときこれまでエラーとして処理していましたが、移転処理を新たにサポートし移転を行うか確認のダイアログを表示するようにします。
関連のissue: #332
> Support processing for moving bbsmenu by 301 Moved Permanently

- src/config/defaultconf.h
5chの[https化][res]に備えてデフォルトの板一覧URLをhttpsに変更します。
関連のissue: #332
[res]: https://mercury.bbspink.com/test/read.cgi/erobbs/1490249679/530
> Modify default bbsmenu URL to https

- src/article/drawareabase.cpp
- src/bbslist/bbslistviewbase.cpp
- src/control/controlutil.cpp
- src/history/historymanager.cpp
- src/message/post.cpp
- src/skeleton/edittreeview.cpp
ローカル変数の名前がシャドウイングされているとcppcheckに指摘されたため重複している変数名を変更します。
> Rename local variable to avoid shadowing

- src/dbtree/boardmachi.cpp
- src/history/historysubmenu.cpp
- src/message/messageadmin.cpp
- src/skeleton/admin.cpp
ローカル変数の名前がシャドウイングされているとcppcheckに指摘されたため重複している変数を統廃合します。
> Remove local var declaration to avoid shadowing

- src/image/imageviewbase.cpp
ローカル変数の名前がシャドウイングされているとcppcheckに指摘されたため内側のスコープへ変数宣言を移動します。
cppcheckのレポート
```
src/image/imageviewbase.cpp:1200:43: style: Local variable 'tact' shadows outer variable [shadowVariable]
Glib::RefPtr< Gtk::ToggleAction > tact = Glib::RefPtr< Gtk::ToggleAction >::cast_dynamic( act );
^
src/image/imageviewbase.cpp:1192:39: note: Shadowed declaration
Glib::RefPtr< Gtk::ToggleAction > tact;
^
src/image/imageviewbase.cpp:1200:43: note: Shadow variable
Glib::RefPtr< Gtk::ToggleAction > tact = Glib::RefPtr< Gtk::ToggleAction >::cast_dynamic( act );
^
```
> ImageViewBase: Move local variables to inner scope to avoid shadowing

- src/article/drawareabase.cpp
cppcheckのレポート
```
src/article/drawareabase.cpp:933:9: style: The scope of the variable 'x' can be reduced. [variableScope]
int x, y = 0;
^
src/article/drawareabase.cpp:3250:12: style: The scope of the variable 'dy' can be reduced. [variableScope]
double dy = 0;
^
```
> DrawAreaBase: Move local variable to inner scope

- src/dbtree/root.cpp
ローカル変数の名前がシャドウイングされているとcppcheckに指摘されたため修正します。
cppcheckのレポート
```
src/dbtree/root.cpp:218:47: style: Local variable 'it' shadows outer variable [shadowVariable]
std::list< BoardBase* >::iterator it;
^
src/dbtree/root.cpp:186:39: note: Shadowed declaration
std::list< BoardBase* >::iterator it;
^
src/dbtree/root.cpp:218:47: note: Shadow variable
std::list< BoardBase* >::iterator it;
^
src/dbtree/root.cpp:245:32: style: Local variable 'board' shadows outer variable [shadowVariable]
BoardBase* board = get_board( url, count + 1 );
^
src/dbtree/root.cpp:221:28: note: Shadowed declaration
BoardBase* board = *( it );
^
src/dbtree/root.cpp:245:32: note: Shadow variable
BoardBase* board = get_board( url, count + 1 );
^
src/dbtree/root.cpp:1279:27: style: Local variable 'movetable' shadows outer …
```
> Root: Modify local variable to avoid shadowing

- src/image/imageadmin.cpp
cppcheckのレポート
```
src/image/imageadmin.cpp:1099:10: style: The scope of the variable 'use_name_in_cache' can be reduced. [variableScope]
bool use_name_in_cache = false;
^
```
> ImageAdmin: Move local variable to inner scope

- src/jdlib/imgloader.cpp
cppcheckのレポート
```
src/jdlib/imgloader.cpp:126:12: style: The scope of the variable 'readsize' can be reduced. [variableScope]
size_t readsize = 0;
^
```
> ImgLoader: Move local variable to inner scope

- src/dbtree/nodetreebase.cpp
cppcheckのレポート
```
src/dbtree/nodetreebase.cpp:309:21: style: The scope of the variable 'num_to' can be reduced. [variableScope]
int num_to = 0;
^
src/dbtree/nodetreebase.cpp:2213:13: style: The scope of the variable 'n_out' can be reduced. [variableScope]
int n_out = 0;
^
src/dbtree/nodetreebase.cpp:3224:21: style: The scope of the variable 'anc_from' can be reduced. [variableScope]
int anc_from;
^
src/dbtree/nodetreebase.cpp:3225:21: style: The scope of the variable 'anc_to' can be reduced. [variableScope]
int anc_to;
^
src/dbtree/nodetreebase.cpp:3351:25: style: The scope of the variable 'anc_from' can be reduced. [variableScope]
int anc_from;
^
src/dbtree/nodetreebase.cpp:3352:25: style: The scope of the variable 'anc_to' can be …
```
> NodeTreeBase: Move local variable to inner scope

- src/jdlib/miscutil.cpp
cppcheckのレポート
```
src/jdlib/miscutil.cpp:27:27: style: The scope of the variable 'r' can be reduced. [variableScope]
size_t i = 0, i2 = 0, r = 0;
^
src/jdlib/miscutil.cpp:54:21: style: The scope of the variable 'length' can be reduced. [variableScope]
size_t pos = 0, length = 0;
^
src/jdlib/miscutil.cpp:116:10: style: The scope of the variable 'dquote' can be reduced. [variableScope]
bool dquote;
^
src/jdlib/miscutil.cpp:120:19: style: The scope of the variable 'i2' can be reduced. [variableScope]
size_t i = 0, i2 = 0, lng = str.length();
^
```
> misc: Move local variable to inner scope

- src/skeleton/treeviewbase.cpp
cppcheckのレポート
```
src/skeleton/treeviewbase.cpp:96:15: style: The scope of the variable 'o_x' can be reduced. [variableScope]
int x, y, o_x, o_y;
^
src/skeleton/treeviewbase.cpp:96:20: style: The scope of the variable 'o_y' can be reduced. [variableScope]
int x, y, o_x, o_y;
^
```
> JDTreeViewBase: Move local variable to inner scope

- src/xml/dom.cpp
cppcheckのレポート
```
src/xml/dom.cpp:91:29: style: The scope of the variable 'tag_lt_pos' can be reduced. [variableScope]
size_t current_pos = 0, tag_lt_pos = 0, tag_gt_pos = 0;
^
```
> Dom: Move local variable to inner scope

- src/control/mousekeypref.cpp
ローカル変数の名前がシャドウイングされているとcppcheckに指摘されたためrange-based forを使ってループを整理します。
cppcheckのレポート
```
src/control/mousekeypref.cpp:485:44: style: Local variable 'it' shadows outer variable [shadowVariable]
std::vector< int >::const_iterator it = vec_ids.begin();
^
src/control/mousekeypref.cpp:478:40: note: Shadowed declaration
std::list< std::string >::iterator it = list_motions.begin();
^
src/control/mousekeypref.cpp:485:44: note: Shadow variable
std::vector< int >::const_iterator it = vec_ids.begin();
^
```
> MouseKeyDiag: Use range-based for statements to avoid shadowing

- .github/workflows/ccpp.yml
- INSTALL
- configure.ac
- docs/manual/make.md
- src/jdlib/jdregex.cpp
- src/jdlib/jdregex.h
使用する正規表現ライブラリを指定するconfigureオプションに[Glib Regex][gregex](`--with-regex=glib`)を追加します。
Glib Regex(GRegex)はGlibに含まれており現在の要件では依存関係を追加せずに使用することが可能です。
[gregex]: https://developer.gnome.org/glib/stable/glib-regex-syntax.html
関連のissue: #361
> Add configure option for Glib Regex

- INSTALL
- configure.ac
- docs/manual/make.md
ビルドオプションを増やすとテストにかかる時間が増えるため
新たに追加されたGlib Regexと同じPerl互換であるPCREを廃止予定にしてオプション数を維持します。
関連のissue: #361
> Deprecate configure option for PCRE

- src/jdlib/loader.h
Remove preprocessor for zlib version check
zlibのバージョンをチェックするプリプロセッサを削除します。
zlib 1.2.0は[2003-03-09][120]にリリースされているため現在サポートしている動作環境では使えるはずです。
[120]: https://github.com/madler/zlib/blob/master/ChangeLog#L985
> Remove preprocessor for zlib version check

- test/Makefile.in
テストコードが更新されていないときは再コンパイルしないようにします。
> Fix make rule to not recompile all test codes

- src/bbslist/bbslistviewbase.cpp
- src/config/aboutconfig.cpp
- src/control/mousekeypref.cpp
- src/fontcolorpref.cpp
- src/linkfilterpref.cpp
- src/skeleton/aboutdiag.cpp
- src/skeleton/edittreeview.cpp
- src/usrcmdpref.cpp
[]演算子で代入した値を使っていないとcppcheckに指摘されましたが参照先を書き換えているためvoidキャストで警告を抑制します。
cppcheckのレポート
```
src/config/aboutconfig.cpp:352:33: style: Variable 'row[m_columns.m_col_type]' is assigned a value that is never used. [unreadVariable]
row[ m_columns.m_col_type ] = CONFTYPE_COMMENT;
^
src/bbslist/bbslistviewbase.cpp:1546:41: style: Variable 'row[m_columns.m_name]' is assigned a value that is never used. [unreadVariable]
row[ m_columns.m_name ] = name;
^
src/control/mousekeypref.cpp:415:62: style: Variable 'row[m_columns.m_col_motion]' is assigned a value that is never used. [unreadVariable]
if( ! str_motion.empty() ) row[ m_columns.m_col_motion ] = str_motion;
^
src/control/mousekeypref.cpp:462:43: style: Variable '(*it_new)[m_columns.m_col_motion]' is assigned a value that is never used. …
```
> Add void cast for unread variables

- src/dbtree/nodetreebase.cpp
- src/image/imagearea.cpp
- src/skeleton/window.cpp
代入した値を使っていないとcppcheckに指摘されたため内側のスコープへ変数宣言を移動します。
cppcheckのレポート
```
src/image/imagearea.cpp:70:18: style: Variable 'scale' is assigned a value that is never used. [unreadVariable]
double scale = 1;
^
src/dbtree/nodetreebase.cpp:1664:20: style: Variable 'digitlink' is assigned a value that is never used. [unreadVariable]
bool digitlink = true;
^
src/skeleton/window.cpp:189:23: style: Variable 'waitcount' is assigned a value that is never used. [unreadVariable]
int waitcount = 0;
^
```
> Move local variables to inner scope to avoid unused value

- src/article/drawareabase.cpp
- src/bbslist/bbslistviewbase.cpp
- src/board/boardviewbase.cpp
- src/dbimg/delimgcachediag.cpp
- src/dbtree/board2ch.cpp
- src/dbtree/boardbase.cpp
- src/jdlib/misccharcode.cpp
- src/message/post.cpp
- src/skeleton/editview.cpp
値を代入した後使っていないとcppcheckに指摘されたため変数宣言や代入文を整理します。
cppcheckのレポート
```
src/article/drawareabase.cpp:2358:27: style: Variable 'y' is assigned a value that is never used. [unreadVariable]
y += height_refer_post;
^
src/article/drawareabase.cpp:3987:35: style: Variable '(*(--it)).select' is assigned a value that is never used. [unreadVariable]
else ( *( --it ) ).select = true;
^
src/bbslist/bbslistviewbase.cpp:1156:31: style: Variable 'subject' is assigned a value that is never used. [unreadVariable]
Glib::ustring subject = row[ m_columns.m_name ];
^
src/board/boardviewbase.cpp:841:24: style: Variable 'path' is assigned a value that is never used. [unreadVariable]
Gtk::TreePath path = GET_PATH( row );
^
src/dbimg/delimgcachediag.cpp:103:17: style: Variable 'days' is assigned a value that is never …
```
> Remove local variable to avoid unread value

- src/control/mousekeypref.cpp
std::find_if()が使えるとcppcheckに指摘されたためループ文を修正します。
さらにイテレーターを使ったループをrange-based forへ書き換えます。
cppcheckのレポート
```
src/control/mousekeypref.cpp:490:52: style: Consider using std::find_if algorithm instead of a raw loop. [useStlAlgorithm]
if( id != CONTROL::None && id != m_id ){
^
```
> mousekeypref: Modify loop statements

- src/core.cpp
- src/jdlib/loader.cpp
ローカル変数の名前がシャドウイングされているとcppcheckに指摘されたため名前を変更します。
cppcheckのレポート
```
src/core.cpp:1113:14: style: Local variable 'item' shadows outer variable [shadowVariable]
auto item = dynamic_cast< Gtk::MenuItem* >( widget );
^
src/core.cpp:1087:10: note: Shadowed declaration
auto item = dynamic_cast< Gtk::MenuItem* >( *std::next( items.begin(), 2 ) );
^
src/core.cpp:1113:14: note: Shadow variable
auto item = dynamic_cast< Gtk::MenuItem* >( widget );
^
src/jdlib/loader.cpp:938:31: style: Local variable 'ret' shadows outer variable [shadowVariable]
const int ret = receive_header( m_buf, read_size );
^
src/jdlib/loader.cpp:732:9: note: Shadowed declaration
int ret;
^
src/jdlib/loader.cpp:938:31: note: Shadow variable
const int ret = receive_header( m_buf, read_size );
^
```
> Rename local variables to avoid shadowing

- src/core.cpp
関数の引数にconst修飾子を付けることができるとcppcheckに指摘されたため
修正します。
cppcheckのレポート
```
src/core.cpp:1387:129: performance: Parameter 'url' is passed by value. It could be passed as a const reference which is usually faster and recommended in C++. [passedByValue]
static inline void toggle_sidebar_action( Glib::RefPtr< Gtk::ActionGroup >& group, const std::string& action, const std::string url )
^
```
> Core: Add const qualifier to function parameters

- src/core.cpp
- src/core.h
メンバ変数の初期化を変更してcppcheckの警告 `(warning) Member variable 'Core::xxx' is not initialized in the constructor.` を修正します。
cppcheckのレポート
```
src/core.cpp:86:7: warning: Member variable 'Core::m_sidebar' is not initialized in the constructor. [uninitMemberVar]
Core::Core( JDWinMain& win_main )
^
src/core.cpp:86:7: warning: Member variable 'Core::m_menubar' is not initialized in the constructor. [uninitMemberVar]
Core::Core( JDWinMain& win_main )
^
src/core.cpp:86:7: warning: Member variable 'Core::m_menuitem_prevview' is not initialized in the constructor. [uninitMemberVar]
Core::Core( JDWinMain& win_main )
^
src/core.cpp:86:7: warning: Member variable 'Core::m_menuitem_nextview' is not initialized in the constructor. [uninitMemberVar]
Core::Core( JDWinMain& win_main )
^
```
> Core: Fix member initialization

- src/jdlib/loader.cpp
- src/jdlib/loader.h
無意味な代入や参照渡しがあるとcppcheckに指摘されたため修正します。
cppcheckのレポート
```
src/jdlib/loader.cpp:444:13: style: Variable 'i' is reassigned a value before the old one has been used. [redundantAssignment]
if( ( i = m_data.host.find( ":" ) ) != std::string::npos ){
^
src/jdlib/loader.cpp:439:7: note: i is assigned
i = i2; m_data.path = m_data.url.substr( i2 );
^
src/jdlib/loader.cpp:444:13: note: i is overwritten
if( ( i = m_data.host.find( ":" ) ) != std::string::npos ){
^
src/jdlib/loader.cpp:1337:19: style: The scope of the variable 'i2' can be reduced. [variableScope]
size_t i = 0, i2 = 0;
^
src/jdlib/loader.cpp:1358:12: style: The scope of the variable 'i' can be reduced. [variableScope]
size_t i = 0, i2 = 0;
^
src/jdlib/loader.cpp:1532:40: style: Parameter 'read_size' can be declared with const …
```
> Loader: Fix dead assignment

- snap/snapcraft.yaml
snapcraftに新たに導入された拡張機能[gnome-3-34-1804][ext]を使ってjdimを構築、頒布するようにsnapcraft.yamlを更新します。
Snapパッケージのビルドオプション
* `--disable-compat-cache-dir`
* `--with-pangolayout`
* `--with-xdgopen`
snapcraft prime時にライブラリが欠けているとメッセージが出たので
指摘されたパッケージをバンドルします。
```
The 'jdim' part is missing libraries that are not included in the snap or base. They can be satisfied by adding the following entry for this part
stage-packages:
- libsigc++-2.0-0v5
```
関連のissue: #314
[ext]: https://snapcraft.io/blog/gnome-3-34-snapcraft-extension
> Update snapcraft.yaml to bundle the gnome-3-34 extension

- snap/snapcraft.yaml
Reverts JDimproved/JDim#378
gnome-3-34 extensionを使ったビルドに失敗したためコミットを取り消します。
- amd64: https://build.snapcraft.io/user/JDimproved/JDim/1027980
```
libtool: Version mismatch error.  This is libtool 2.4.6.44-b9b4, but the
libtool: definition of this LT_INIT comes from libtool 2.4.6.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6.44-b9b4
libtool: and run autoconf again.
Makefile:588: recipe for target 'jdim' failed
```
- i386: https://build.snapcraft.io/user/JDimproved/JDim/1027979
```
Could not install snap defined in plug 'gnome-3-34-1804'.
The missing library report may have false positives listed if those libraries are provided by the content snap.
```
- ppc64el: https://build.snapcraft.io/user/JDimproved/JDim/1027983
```
Failed to install or refresh a snap: …
```
> Revert "Update snapcraft.yaml to bundle the gnome-3-34 extension"

- src/skeleton/editview.cpp
無意味な変数初期化を行っているとcppcheckの指摘されたため修正します。
cppcheckのレポート
```
src/skeleton/editview.cpp:571:24: style: Redundant initialization for 'nlpos'. The initialized value is overwritten before it is read. [redundantInitialization]
while( ( nlpos = text.rfind( "\n", rpos ) ) != std::string::npos )
^
src/skeleton/editview.cpp:568:22: note: nlpos is initialized
size_t nlpos = std::string::npos;
^
src/skeleton/editview.cpp:571:24: note: nlpos is overwritten
while( ( nlpos = text.rfind( "\n", rpos ) ) != std::string::npos )
^
```
> EditTextView: Fix redundant initialization

- src/winmain.cpp
JDWinMainはコンストラクタ・デストラクタ内で仮想関数set_xxx(), get_xxx()を呼び出していますが仮想関数はコンストラクタ・デストラクタ内で派生クラスの関数として呼び出しできないためcppcheckに警告されます。
<details>
<summary>cppcheckのレポート</summary>
```
src/winmain.h:45:10: warning: Virtual function 'set_width_win' is called from constructor 'JDWinMain(const bool init,const bool skip_setupdiag,const int init_w,const int init_h,const int init_x,const int init_y)' at line 64. Dynamic binding is not used. [virtualCallInConstructor]
void set_width_win( const int width ) override;
^
src/winmain.cpp:64:9: note: Calling set_width_win
set_width_win( init_w );
^
src/winmain.h:45:10: note: set_width_win is a virtual function
void set_width_win( const int width ) override;
^
src/winmain.h:46:10: warning: Virtual function 'set_height_win' is called from …
```
> JDWinMain: Fix calling virtual function from the ctor and dtor

- src/winmain.cpp
隣り合うif文が同じ条件であるとcppcheckに指摘されたためブロックをまとめます。
cppcheckのレポート
```
src/winmain.cpp:281:9: style: The if condition is the same as the previous if condition [duplicateCondition]
if( m_cancel_state_event ) return Gtk::Window::on_window_state_event( event );
^
src/winmain.cpp:277:9: note: First condition
if( m_cancel_state_event ) std::cout << "cancel\n";
^
src/winmain.cpp:281:9: note: Second condition
if( m_cancel_state_event ) return Gtk::Window::on_window_state_event( event );
^
src/winmain.cpp:295:9: style: The if condition is the same as the previous if condition [duplicateCondition]
if( m_cancel_state_event ) return Gtk::Window::on_configure_event( event );
^
src/winmain.cpp:291:9: note: First condition
if( m_cancel_state_event ) std::cout << "cancel\n";
^
src/winmain.cpp:295:9: note: Second …
```
> JDWinMain: Unite if-statement blocks for same condition

- src/message/messageviewbase.cpp
ポインターがnullの可能性があるとclang analyzerに指摘されましたが冗長なnullチェックを削除して検出しないように修正します。
```
Description: Called C++ object pointer is null
File: /home/ma8ma/var/repos/worktree/jdim-echo/src/message/messageviewbase.cpp
Line: 999
```
> MessageViewBase: Remove redundant null check

- src/image/imageadmin.cpp
nullの可能性があるポインターをデリファレンスしているとclang-analyzerに指摘されたためnullチェックを追加します。
```
Description: Called C++ object pointer is null
File: /home/ma8ma/var/repos/JDim/src/image/imageadmin.cpp
Line: 554
```
> ImageAdmin: Add null check before dereferencing pointer

- src/dbtree/nodetreebase.cpp
無意味なインクリメントがあるとclang analyzerに指摘されたため削除します。
```
Description: Value stored to 'lng_out' is never read
File: /home/ma8ma/var/repos/worktree/jdim-echo/src/dbtree/nodetreebase.cpp
Line: 2686
```
> DrawAreaBase: Fix dead increment

- src/article/drawareabase.cpp
nullの可能性があるポインターをデリファレンスしているとclang-analyzerに指摘されたためnullチェックを追加します。
```
Description: Access to field 'x' results in a dereference of a null pointer (loaded from field 'rect')
File: /home/ma8ma/var/repos/worktree/jdim-echo/src/article/drawareabase.cpp
Line: 4306
```
> DrawAreaBase: Add null check before dereferencing pointer

- src/skeleton/editview.cpp
std::string::front()を呼び出す前に要素数をチェックするように修正します。
> EditTextView: Fix bounds check

- src/message/post.cpp
- src/message/post.h
仮想関数を持つクラスが非仮想のデストラクタにアクセスしているとgcc 9に指摘されたため修正します。
gcc 9のレポート
```
In file included from ../src/message/messageview.cpp:8:
../src/message/post.h:25:12: warning: ‘struct MESSAGE::PostStrategy’ has virtual functions and accessible non-virtual destructor [-Wnon-virtual-dtor]
25 |     struct PostStrategy
|            ^~~~~~~~~~~~
[171/314] Compiling C++ object 'src/message/350ae8d@@message@sta/messageviewbase.cpp.o'
In file included from ../src/message/messageviewbase.cpp:10:
../src/message/post.h:25:12: warning: ‘struct MESSAGE::PostStrategy’ has virtual functions and accessible non-virtual destructor [-Wnon-virtual-dtor]
25 |     struct PostStrategy
|            ^~~~~~~~~~~~
[174/314] Compiling C++ object 'src/message/350ae8d@@message@sta/post.cpp.o'
In file included from …
```
> post: Fix compiler waring for -Wnon-virtual-dtor

- src/environment.cpp
cppcheckのレポート
```
src/environment.cpp:212:11: style: The scope of the variable 'regVal' can be reduced. [variableScope]
char *regVal;
^
```
> environment: Move local variable to inner scope

- src/jdlib/ssl.cpp
無意味な代入があるとclang analyzerに指摘されたためassert文からエラー処理に変更します。
```
../../../src/jdlib/ssl.cpp:75:5: warning: Value stored to 'ret' is never read
ret = gnutls_certificate_allocate_credentials( &m_cred );
^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../src/jdlib/ssl.cpp:77:5: warning: Value stored to 'ret' is never read
ret = gnutls_certificate_set_x509_system_trust( m_cred );
^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../src/jdlib/ssl.cpp:80:5: warning: Value stored to 'ret' is never read
ret = gnutls_server_name_set( m_session, GNUTLS_NAME_DNS, host, strlen( host ) );
^     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../src/jdlib/ssl.cpp:83:5: warning: Value stored to 'ret' is …
```
> JDSSL: Fix dead assignment

- meson.build
mesonの設定を調整します。
- `gprof`オプションを利用するときコンパイラーが `-pg` オプションをサポートしない場合はエラーにします。
- meson.buildの導入説明でFedoraのコマンド例が間違っていたため修正します。
> Tweak meson.build

- snap/snapcraft.yaml
snapcraftに新たに導入された[GNOME 3.34 extension][gnome-3-34-1804]を使ってjdimを構築、頒布するようにsnapcraft.yamlを更新します。
また、正規表現ライブラリにGlib Regexを使うよう変更します。
Snapパッケージのビルドオプション
- `-Dcompat_cache_dir=disabled`
- `-Dpangolayout=enabled`
- `-Dregex=glib`
build時にgcc拡張を使用しているとメッセージが出るのでコンパイラーオプションで警告を抑制します。
```
/snap/gnome-3-34-1804-sdk/current/usr/include/limits.h:124:3: warning: #include_next is a GCC extension
^~~~~~~~~~~~
```
prime時にライブラリが欠けているとメッセージが出るので指摘されたパッケージをバンドルします。
```
The 'jdim' part is missing libraries that are not included in the snap or base. They can be satisfied by adding the following entry for this part
stage-packages:
- libsigc++-2.0-0v5
```
[gnome-3-34-1804]: https://snapcraft.io/blog/gnome-3-34-snapcraft-extension
関連のissue: https://github.com/JDimproved/JDim/issues/314
> Snap: Update dependencies to use GNOME 3.34 snapcraft extension

- snap/snapcraft.yaml
SnapがサポートするCPUアーキテクチャのうち i386, ppc64el, s390x ではgnome-3-34 extensionを使ったパッケージの構築ができないためパッケージのビルドと頒布を止めます。
- i386: https://build.snapcraft.io/user/JDimproved/JDim/1038357
```
Could not install snap defined in plug 'gnome-3-34-1804'.
The missing library report may have false positives listed if those libraries are provided by the content snap.
```
- ppc64el: https://build.snapcraft.io/user/JDimproved/JDim/1038309
```
Failed to install or refresh a snap: 'gnome-3-34-1804-sdk' does not exist or is not available on the desired channel 'latest/stable'.
Use `snap info gnome-3-34-1804-sdk` to get a list of channels the snap is available on.
```
- s390x: https://build.snapcraft.io/user/JDimproved/JDim/1038361
```
Failed to install or refresh a snap: 'gnome-3-34-1804-sdk' does not exist or is not …
```
> Snap: Drop architectures i386, ppc64el and s390x

- snap/snapcraft.yaml
前のコミット(fe1458eb3f6)はsnapcraft.yamlのarchitecturesにamd64, arm64, armhf 3つのアーキテクチャで実行可能なパッケージをビルドするように設定しています。
これは意図した設定と異なるため、CPUアーキテクチャ毎にパッケージをビルドするように修正します。
参考文献: https://snapcraft.io/docs/architectures
> Snap: Fix architectures settings

- snap/snapcraft.yaml
設定項目名が間違っていたため修正します。
https://build.snapcraft.io/user/JDimproved/JDim/1038575
```
Issues while validating snapcraft.yaml: The 'architectures[0]' property does not match the required schema:
additional properties are not allowed ('runs-on' was unexpected) or orderedDict([('build-on', 'amd64'), ('runs-on', 'amd64')]) is not of type 'string'
```
関連のissue: https://github.com/JDimproved/JDim/issues/314
> Snap: Fix wrong keyword "runs-on" to "run-on" for snapcraft.yaml

- src/dbtree/articlebase.cpp
gccのサニタイザーが算術オーバーフローを検出したためintの値をtime_tにキャストします。
サニタイザーのレポート
```
../src/dbtree/articlebase.cpp:158:37: runtime error: signed integer overflow: 37693 * 86400 cannot be represented in type 'int'
```
> ArticleBase: Fix integer overflow

- src/board/boardviewbase.cpp
- src/dbtree/nodetreebase.cpp
- src/jdlib/confloader.cpp
- src/jdlib/loader.cpp
- 数値の書式化を`Glib::ustring`の関数で行うように修正します。
- 数値から書式化して`std::string`に渡す変数を`snprintf()`から`std::to_string()`に変更します。
> Replace snprintf with string format function

- src/bbslist/bbslistviewbase.cpp
ローカル変数のコピーを減らすためconst参照で変数束縛や`Glib::ustring`から`std::string`へ明示的にconst参照を取得します。
> BBSListViewBase: Use const reference to make alias for local variable

- INSTALL
- configure.ac
- docs/manual/make.md
非推奨のconfigureオプション`--with-openssl`を削除します。
削除したオプションを指定すると明示的にエラーを発生させます。
> Remove deprecated configure option --with-openssl

- INSTALL
- configure.ac
- docs/manual/make.md
非推奨のconfigureオプション`--with-oniguruma`と`--with-pcre`を削除します。
削除したオプションを指定すると明示的にエラーを発生させます。
> Remove deprecated configure options --with-[oniguruma|pcre]

- .github/workflows/ccpp.yml
- .travis.yml
- INSTALL
- configure.ac
- docs/manual/make.md
- meson.build
- src/config/defaultconf.h
非推奨のconfigureオプション`--with-xdgopen`を削除します。
削除したオプションを指定しても無視されますので注意してください。
合わせてCIマトリックスの設定からxdg-openのオプションを取り除きソースコードを整理します。
Closes #253
> Remove deprecated configure option --with-xdgopen

- .github/workflows/ccpp.yml
- .travis.yml
- INSTALL
- configure.ac
- docs/manual/make.md
- src/jdlib/jdregex.cpp
- src/jdlib/jdregex.h
非推奨のconfigureオプション`--with-regex=pcre`を削除します。
削除したオプションを指定すると明示的にエラーを発生させます。
合わせてCIマトリックスの設定とソースコードを整理します。
関連のissue: #361
> Remove deprecated configure option --with-regex=pcre

- configure.ac
- meson.build
- src/jdlib/jdthread.cpp
- src/jdlib/jdthread.h
- src/winmain.cpp
`JDLIB::Thread`クラスの実装から廃止されたPOSIX threadとGlib Threadを削除します。
また、不慮の事故を避けるためThreadクラスのコピーやムーブを禁止しておきます。
> Remove JDLIB::Thread implementations for pthread and gthread

- src/jdlib/cookiemanager.cpp
- test/gtest_jdlib_cookiemanager.cpp
Fixes #412
JDサポートBBSに書き込めない不具合を修正するため空の値のCookieを送受信に含めるように変更します。
> CookieManager: Accept empty value Cookie

- src/board/preference.cpp
- src/board/preference.h
- src/core.cpp
- src/core.h
- src/message/confirmdiag.cpp
- src/message/confirmdiag.h
- src/message/messageviewbase.cpp
- src/message/messageviewbase.h
- src/setupwizard.cpp
- src/setupwizard.h
- src/skeleton/admin.cpp
- src/skeleton/admin.h
- src/skeleton/detaildiag.cpp
- src/skeleton/detaildiag.h
- src/skeleton/dragnote.cpp
- src/skeleton/dragnote.h
- src/skeleton/tabnote.h
シグナルハンドラーの引数の型を更新してGTK2対応コードを整理します。
> Replace GtkNotebookPage* with Gtk::Widget*

- src/skeleton/popupwinbase.cpp
- src/skeleton/popupwinbase.h
> PopupWinBase: Remove member functions which are no longer in use

- src/skeleton/tabswitchbutton.cpp
- src/skeleton/tabswitchbutton.h
> TabSwtichButton: Remove member function which are no longer in use

- INSTALL
- docs/manual/make.md
configureオプション`--with-pangolayout`を使うときのヒントをドキュメントに追加します。
> Add note for configure option --with-pangolayout

- src/skeleton/toolbarnote.cpp
- src/skeleton/toolbarnote.h
> ToolBarNotebook: Remove member function which is no longer in use

- src/skeleton/viewnote.cpp
- src/skeleton/viewnote.h
> ViewNotebook: Remove member functions which are no longer in use

- src/article/articleviewbase.cpp
- src/article/drawareabase.cpp
- src/article/drawareabase.h
- src/bbslist/bbslistviewbase.cpp
- src/board/boardviewbase.cpp
- src/control/control.cpp
- src/image/imageadmin.cpp
- src/image/imageadmin.h
- src/image/imageviewbase.cpp
- src/skeleton/dragnote.cpp
- src/skeleton/dragnote.h
- src/skeleton/dragtreeview.cpp
- src/skeleton/dragtreeview.h
- src/skeleton/tablabel.cpp
マウスホイール操作のGTK3対応で導入されたコンパイル条件を整理します。
関連のissue: #229
> Remove compile conditions for supporting smooth scroll

- src/cache.cpp
GTK2とGTK3で変数の型が異なりコンパイル条件で分かれている箇所を整理します。
関連のissue: #229
> cache: Remove compile conditions for local variables

- src/control/controlutil.cpp
GTK2とGTK3でループ処理が異なりコンパイル条件で分かれている箇所を整理します。
関連のissue: #229
> control: Remove compile conditions for iterating elements

- src/dbimg/delimgcachediag.cpp
- src/dbimg/delimgcachediag.h
GTK2とGTK3でメンバ関数が異なりコンパイル条件で分かれている箇所を整理します。
関連のissue: #229
> DelImgCacheDiag: Remove compile conditions for member function

- src/core.cpp
- src/skeleton/tabnote.cpp
> Remove compile conditions for value getting/setting part1

- src/control/control.cpp
- src/image/imageadmin.cpp
- src/skeleton/compentry.cpp
- src/skeleton/iconpopup.h
- src/skeleton/popupwin.cpp
> Remove compile conditions for value getting/setting part2

- src/image/imageviewicon.cpp
- src/image/imageviewpopup.cpp
- src/skeleton/aamenu.cpp
- src/skeleton/aboutdiag.cpp
- src/skeleton/compentry.h
- src/skeleton/dragtreeview.cpp
- src/skeleton/editview.h
> Remove compile conditions for value getting/setting part3

- src/fontcolorpref.cpp
- src/fontcolorpref.h
> Remove compile conditions for value getting/setting part4

- src/board/boardviewbase.cpp
- src/jdlib/miscgtk.cpp
- src/jdlib/miscgtk.h
- src/skeleton/aboutdiag.cpp
- src/skeleton/compentry.cpp
> Remove compile conditions for value getting/setting part5

- src/jdlib/miscx.cpp
GTK2とGTK3でコンパイル条件で分かれている箇所を整理します。
また、X11環境をサポートしない環境に対応するためのコンパイル条件を追加します。
関連のissue: #229
> Improve compile conditions for MISC::WarpPointer()

- src/message/messageviewbase.cpp
- src/skeleton/dragtreeview.cpp
- src/skeleton/dragtreeview.h
- src/skeleton/editview.cpp
- src/skeleton/editview.h
- src/skeleton/toolbar.cpp
- src/skeleton/toolbar.h
- src/skeleton/window.cpp
- src/skeleton/window.h
GTK2とGTK3でスタイル設定方法が異なりコンパイル条件で分かれている箇所を整理します。
関連のissue: #229
> Remove compile conditions for style setting

- src/icons/iconmanager.cpp
アイコンのレンダーに使うオブジェクトの条件コンパイルを整理します。
関連のissue: #229
> ICON_Manager: Remove compile condition for rendering icon

- src/menuslots.cpp
GTK3対応用のラッパークラスを整理して`Gtk::FontChooserDialog`を直接使うように修正します。
関連のissue: #229
> Core: Remove wrapper class which is no longer needed

- src/skeleton/editview.cpp
GTK3版で導入された新しい機能（マウスクリックによる単語/行選択）を隔離するためのコンパイル条件を整理します。
関連のissue: #229
> EditTextView: Remove compile condition for word/line selection

- src/article/drawareabase.cpp
- src/article/drawareabase.h
GTK2とGTK3で描画処理が異なりコンパイル条件で分かれている箇所を整理します。
関連のissue: #229
> DrawAreaBase: Remove compile conditions for drawing thread view

- src/article/drawareabase.cpp
- src/article/drawareabase.h
GTK3版で導入されたタッチスクリーン操作のコードを隔離するためのコンパイル条件を整理します。
関連のissue: #229
> DrawAreaBase: Remove compile condition for touchscreen

- INSTALL
- configure.ac
- docs/manual/make.md
- meson.build
- meson_options.txt
Fix #444
デフォルトの正規表現ライブラリをPOSIX regexからGlib Regex(GRegex)に変更します。
また、mesonを利用したときはglibではなくposixを指定したときにビルドオプションを表示するように変更します。
GRegexはPerl互換の正規表現なので、従来のPOSIX拡張の正規表現から設定変更が必要になる場合があります。
> Change default regex library to Glib Regex

- src/skeleton/menubutton.cpp
- src/skeleton/menubutton.h
- src/skeleton/tabswitchbutton.cpp
- src/skeleton/tabswitchbutton.h
GTK4で廃止される`Gtk::Arrow`のかわりにアイコンテーマを使います。
[GtkArrowのリファレンス][gtkarrow]より
> GtkArrow has been deprecated; you can simply use a GtkImage with a suitable icon name, such as "pan-down-symbolic".
```
```
コンパイラのレポート
```
../src/skeleton/tabswitchbutton.h:20:14: error: 'Arrow' in namespace 'Gtk' does not name a type
20 |         Gtk::Arrow m_arrow{ Gtk::ARROW_DOWN, Gtk::SHADOW_NONE };
|              ^~~~~
../src/skeleton/menubutton.h:28:14: error: 'Arrow' in namespace 'Gtk' does not name a type
28 |         Gtk::Arrow* m_arrow;
|              ^~~~~
```
関連のissue: #229 
[gtkarrow]: https://developer.gnome.org/gtk3/stable/GtkArrow.html
> Use icon theme instead of Gtk::Arrow

- src/image/imageadmin.cpp
- src/image/imageadmin.h
GTK4で廃止される`Gtk::Button`の`pressed/released`シグナルハンドラのかわりに`Gtk::GestureMultiPress`を使います。
```
-DGDK_DISABLE_DEPRECATED
-DGTK_DISABLE_DEPRECATED
-DGDKMM_DISABLE_DEPRECATED
-DGTKMM_DISABLE_DEPRECATED
-DGIOMM_DISABLE_DEPRECATED
-DGLIBMM_DISABLE_DEPRECATED
```
コンパイラのレポート
```
../src/image/imageadmin.cpp:62:12: error: 'class Gtk::Button' has no member named 'signal_pressed'; did you mean 'on_pressed'?
62 |     m_left.signal_pressed().connect( sigc::mem_fun( *this, &ImageAdmin::slot_press_left ) );
|            ^~~~~~~~~~~~~~
|            on_pressed
../src/image/imageadmin.cpp:63:13: error: 'class Gtk::Button' has no member named 'signal_pressed'; did you mean 'on_pressed'?
63 |     m_right.signal_pressed().connect( sigc::mem_fun( *this, &ImageAdmin::slot_press_right ) );
| …
```
> Use Gtk::GestureMultiPress instead of Gtk::Button::signal_pressed/released

- src/skeleton/hpaned.cpp
- src/skeleton/hpaned.h
GTK4で廃止される`Gtk::HPaned`のかわりに`Gtk::Paned`を使います。
```
-DGDK_DISABLE_DEPRECATED
-DGTK_DISABLE_DEPRECATED
-DGDKMM_DISABLE_DEPRECATED
-DGTKMM_DISABLE_DEPRECATED
-DGIOMM_DISABLE_DEPRECATED
-DGLIBMM_DISABLE_DEPRECATED
```
<details>
```
../src/skeleton/hpaned.h:16:5: error: expected class-name before '{' token
16 |     {
|     ^
../src/skeleton/hpaned.h:28:14: error: 'void SKELETON::JDHPaned::on_realize()' marked 'override', but does not override
28 |         void on_realize() override;
|              ^~~~~~~~~~
../src/skeleton/hpaned.h:29:14: error: 'bool SKELETON::JDHPaned::on_button_press_event(GdkEventButton*)' marked 'override', but does not override
29 |         bool on_button_press_event( GdkEventButton* event ) override;
| …
```
> Use Gtk::Paned instead of Gtk::HPaned

- src/skeleton/vpaned.cpp
- src/skeleton/vpaned.h
GTK4で廃止される`Gtk::VPaned`のかわりに`Gtk::Paned`を使います。
```
```
<details>
```
../src/skeleton/vpaned.h:16:5: error: expected class-name before '{' token
16 |     {
|     ^
../src/skeleton/vpaned.h:28:14: error: 'void SKELETON::JDVPaned::on_realize()' marked 'override', but does not override
28 |         void on_realize() override;
|              ^~~~~~~~~~
../src/skeleton/vpaned.h:29:14: error: 'bool SKELETON::JDVPaned::on_button_press_event(GdkEventButton*)' marked 'override', but does not override
29 |         bool on_button_press_event( GdkEventButton* event ) override;
| …
```
> Use Gtk::Paned instead of Gtk::VPaned

- README.md
Snapの[webサイト更新][snapcraft]によってビルド状況を表すバッジが廃止されたためREADME.mdからバッジを取り除きます。
[snapcraft]: https://snapcraft.io/blog/we-are-changing-the-way-you-build-snaps-from-github-repos
> Get rid of snap build badge from README.md

- src/dbtree/board2ch.cpp
スレ立て用のメッセージボディ構築でスレ立て用キーワードの関数ではなく、書き込み用キーワードの関数を呼び出していた箇所を修正します。
> Board2ch: Fix clearing keyword for new article

- src/dbtree/board2chcompati.cpp
2ch互換板スレ立てに利用するフォームデータの解析に渡すHTMLソースから使用しない部分をカットします。
スレ立てのフォームはwebページの最後にあると決め打ちしている
> Board2chCompati: Cut html source for analyzing form data

- src/skeleton/detaildiag.cpp
GTK4で廃止される`Gtk::Misc::set_padding()`のかわりに`Gtk::Widget::property_margin()`を使います。
```
```
コンパイラのレポート
```
../src/skeleton/detaildiag.cpp:24:15: error: 'class Gtk::Label' has no member named 'set_padding'
24 |     m_message.set_padding( 8, 8 );
|               ^~~~~~~~~~~
```
関連のissue: #229
> Use Gtk::Widget::property_margin() instead of Gtk::Misc::set_padding()

- src/article/preference.cpp
- src/bbslist/toolbar.cpp
- src/browserpref.h
- src/message/messageviewbase.cpp
- src/skeleton/label_entry.cpp
- src/skeleton/toolbar.cpp
- src/skeleton/window.cpp
GTK4で廃止される`Gtk::Misc::set_alignment()`のかわりに`Gtk::Label::set_xalign()`を使います。
```
```
<details>
```
../src/article/preference.cpp:124:23: error: 'class Gtk::Label' has no member named 'set_alignment'; did you mean 'set_lines'?
124 |         m_label_abone.set_alignment( Gtk::ALIGN_START, Gtk::ALIGN_CENTER );
|                       ^~~~~~~~~~~~~
|                       set_lines
../src/bbslist/toolbar.cpp:38:13: error: 'class Gtk::Label' has no member named 'set_alignment'; did you mean 'set_lines'?
38 |     m_label.set_alignment( Gtk::ALIGN_START );
|             ^~~~~~~~~~~~~
| …
```
> Use Gtk::Label::set_xalign() instead of Gtk::Misc::set_alignment()

- src/image/imageareabase.cpp
GTK4で廃止される`Gtk::Misc::set_alignment()`のかわりに`Gtk::Widget::set_[hv]align()`を使います。
```
```
コンパイラのレポート
```
../src/image/imageareabase.cpp:68:5: error: 'set_alignment' was not declared in this scope; did you mean 'set_halign'?
68 |     set_alignment( Gtk::ALIGN_CENTER, Gtk::ALIGN_CENTER );
|     ^~~~~~~~~~~~~
|     set_halign
```
関連のissue: #229
> Use Gtk::Widget::set_[hv]align() instead of Gtk::Misc::set_alignment()

- src/dbtree/article2ch.cpp
- src/dbtree/board2ch.cpp
- src/dbtree/board2ch.h
- src/dbtree/board2chcompati.cpp
- src/dbtree/board2chcompati.h
- src/dbtree/boardbase.h
- src/dbtree/interface.cpp
- src/dbtree/interface.h
- src/jdlib/loader.cpp
- src/jdlib/loaderdata.cpp
- src/jdlib/loaderdata.h
- src/jdlib/miscutil.cpp
- src/jdlib/miscutil.h
- src/message/post.cpp
- src/message/post.h
- test/gtest_jdlib_miscutil.cpp
2ch互換板への書き込みを修正します。
[2020年8月中旬くらい][res103]から特定の掲示板への書き込みでエラーが出て失敗することがありました。
詳細は上記スレッドを参照してください。
[res103]: https://mao.5ch.net/test/read.cgi/linux/1594134444/103
- 投稿確認画面が出たときはフォームのデータを使って再度投稿するように変更します。
- 投稿確認後の2回目のHTTPリクエストに使うURLは上記解析で取得したURLがあればそれを使います。
- HTTPヘッダーRefererやOriginの設定を調整します。
- その他細かい変更はコミットメッセージを見てください。
> Fix posting to 2ch

- src/article/preference.cpp
- src/bbslist/addetcdialog.cpp
- src/bbslist/selectdialog.cpp
- src/board/preference.cpp
- src/browserpref.h
- src/config/aboutconfig.cpp
- src/config/aboutconfigdiag.cpp
GTK4で廃止される`Gtk::Dialog::get_vbox()`のかわりに`Gtk::Dialog::get_content_area()`を使います。
```
```
コンパイラのレポート
```
../src/article/preference.cpp:203:5: error: 'get_vbox' was not declared in this scope
203 |     get_vbox()->pack_start( m_notebook );
|     ^~~~~~~~
../src/bbslist/addetcdialog.cpp:35:5: error: 'get_vbox' was not declared in this scope; did you mean 'm_vbox'?
35 |     get_vbox()->set_spacing( 8 );
|     ^~~~~~~~
|     m_vbox
../src/bbslist/selectdialog.cpp:88:5: error: 'get_vbox' was not declared in this scope
88 |     get_vbox()->pack_start( m_label_name, Gtk::PACK_SHRINK );
|     ^~~~~~~~ …
```
> Use Gtk::Dialog::get_content_area() instead of get_vbox() part1

- src/control/mousekeypref.cpp
- src/dbimg/delimgcachediag.cpp
- src/dbimg/delimgdiag.h
- src/fontcolorpref.cpp
- src/globalabonepref.h
- src/globalabonethreadpref.h
- src/image/preference.cpp
- src/linkfilterpref.cpp
- src/livepref.cpp
- src/main.cpp
- src/message/confirmdiag.cpp
- src/openurldiag.cpp
- src/passwdpref.h
GTK4で廃止される`Gtk::Dialog::get_vbox()`のかわりに`Gtk::Dialog::get_content_area()`を使います。
```
```
コンパイラのレポート
```
../src/control/mousekeypref.cpp:41:5: error: 'get_vbox' was not declared in this scope
41 |     get_vbox()->pack_start( m_label );
|     ^~~~~~~~
../src/control/mousekeypref.cpp:301:5: error: 'get_vbox' was not declared in this scope
301 |     get_vbox()->set_spacing( 8 );
|     ^~~~~~~~
../src/control/mousekeypref.cpp:532:5: error: 'get_vbox' was not declared in this scope
532 |     get_vbox()->set_spacing( 8 );
|     ^~~~~~~~
../src/dbimg/delimgcachediag.cpp:34:5: error: 'get_vbox' was not declared in this scope
34 | …
```
> Use Gtk::Dialog::get_content_area() instead of get_vbox() part2

- src/privacypref.h
- src/proxypref.h
- src/setupwizard.cpp
- src/skeleton/aboutdiag.cpp
- src/skeleton/detaildiag.cpp
- src/skeleton/editviewdialog.h
- src/skeleton/msgdiag.cpp
- src/skeleton/selectitempref.cpp
- src/usrcmdmanager.cpp
- src/usrcmdpref.cpp
GTK4で廃止される`Gtk::Dialog::get_vbox()`のかわりに`Gtk::Dialog::get_content_area()`を使います。
```
```
コンパイラのレポート
```
../src/privacypref.h:74:13: error: 'get_vbox' was not declared in this scope; did you mean 'm_vbox'?
74 |             get_vbox()->set_spacing( 8 );
|             ^~~~~~~~
|             m_vbox
../src/proxypref.h:139:13: error: 'get_vbox' was not declared in this scope
139 |             get_vbox()->set_spacing( 4 );
|             ^~~~~~~~
../src/setupwizard.cpp:297:5: error: 'get_vbox' was not declared in this scope
297 |     get_vbox()->pack_start( m_notebook, Gtk::PACK_EXPAND_PADDING, SPACING_SIZE );
|     ^~~~~~~~ …
```
> Use Gtk::Dialog::get_content_area() instead of get_vbox() part3

- src/jdversion.h
Windows(MinGW)版で使うマクロはもう使用しないため削除します。
関連のissue: #445
> Remove unused macros for windows support

- src/setupwizard.cpp
- src/setupwizard.h
GTK4で廃止される`Gtk::Table`のかわりに`Gtk::Grid`を使います。
```
```
コンパイラのレポート
```
../src/setupwizard.h:73:14: error: 'Table' in namespace 'Gtk' does not name a type
73 |         Gtk::Table m_table;
|              ^~~~~
```
関連のissue: #229
> setupwizard: Use Gtk::Grid instead of Gtk::Table

- src/article/drawareabase.cpp
- src/article/drawareabase.h
GTK4で廃止される`Gtk::Widget::signal_visibility_notify_event()`を整理します。
> GtkWidget::visibility-notify-event has been deprecated since version 3.12 and should not be used in newly-written code.
> Modern composited windowing systems with pervasive transparency make it impossible to track the visibility of a window reliably, so this signal can not be guaranteed to provide useful information.
```
```
```
../src/article/drawareabase.cpp:187:12: error: 'class Gtk::DrawingArea' has no member named 'signal_visibility_notify_event'; did you mean 'on_visibility_notify_event'?
187 |     m_view.signal_visibility_notify_event().connect( sigc::mem_fun(*this, …
```
> DrawAreaBase: Remove deprecated Gtk::Widget::signal_visibility_notify_event()

- configure.ac
- meson.build
- src/jdlib/jdiconv.cpp
- src/jdlib/jdiconv.h
- src/meson.build
Fix #470 
BSD系プラットフォームでは2種類のiconv関数が使われています。(標準Cライブラリ[dragonfly][1], [freebsd][2], [netbsd][3] と [GNU libiconv][4])
そのためビルド時にどちらのiconvを使うか設定しないとリンクエラーが起こる場合があります。
そこでGlibが提供する[ラッパーAPI][5]を利用して依存関係の問題を回避します。
[1]: https://man.dragonflybsd.org/?command=iconvctl&section=3
[2]: https://www.freebsd.org/cgi/man.cgi?query=iconv&sektion=3
[3]: https://man.netbsd.org/iconv.3
[4]: https://www.gnu.org/software/libiconv/
[5]: https://developer.gnome.org/glib/stable/glib-Character-Set-Conversion.html
> Use GIConv instead of the underlying iconv implementation

- README.md
- docs/manual/start.md
- src/core.cpp
- src/fontcolorpref.cpp
Fix #469 
GTK4で廃止される`Gtk::ColorSelectionDialog`のかわりに`Gtk::ColorChooserDialog`を使います。
JDimの関数や設定が対応してないためalphaチャンネルは無効にしてあります。
KDE plasma(X11?)環境では色選択ダイアログのカラーピッカーで色を抜き出すことができない。([関連の問題？][bugs])
[bugs]: https://bugs.kde.org/show_bug.cgi?id=407226
```
```
コンパイラのレポート
```
../src/core.cpp:1681:10: error: 'ColorSelectionDialog' is not a member of 'Gtk'
1681 |     Gtk::ColorSelectionDialog diag( title );
|          ^~~~~~~~~~~~~~~~~~~~
../src/core.cpp:1682:5: error: 'diag' was not declared in this scope
1682 |     diag.get_color_selection()->set_current_color( color );
|     ^~~~
../src/core.cpp:1685:14: error: 'ColorSelection' is not …
```
> Use Gtk::ColorChooserDialog instead of Gtk::ColorSelectionDialog

- src/icons/iconmanager.cpp
GTK4で廃止される`Gtk::Widget::render_icon_pixbuf()`のかわりに`Gtk::IconTheme::load_icon()`を使います。
アイコン名はfreedesktop.orgの規格とGTK3デフォルトテーマAdwaitaを参照しています。
Gtk::Stockからアイコン名に変更する参考文献:
- https://developer.gnome.org/gtk3/stable/gtk3-Stock-Items.html
- https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html
- https://gitlab.gnome.org/GNOME/adwaita-icon-theme
```
```
<details>
```
../src/icons/iconmanager.cpp:90:55: error: 'Gtk::BuiltinStockID' has not been declared
90 |         Glib::RefPtr< Gdk::Pixbuf > render_icon( Gtk::BuiltinStockID stock, Gtk::BuiltinIconSize size )
| …
```
> Use Gtk::IconTheme instead of Gtk::Widget::render_icon_pixbuf()

- src/jdlib/miscutil.cpp
- test/gtest_jdlib_miscutil.cpp
コミット 3db07d3d97e43601bd6c871ad12038c0c8ee200f より後でJDサポート掲示板への書き込みが失敗する不具合を修正します。
上記コミットから書き込み確認で再POSTするURLを解析しますがサポート掲示板はパターンが異なっていたため失敗していました。
> Fix posting to JD support BBS

- src/article/articleviewbase.cpp
- src/board/preference.cpp
- src/dbtree/boardbase.cpp
- src/dbtree/nodetree2chcompati.cpp
- src/dbtree/nodetreejbbs.cpp
- src/dbtree/nodetreemachi.cpp
- src/dbtree/root.cpp
- src/jdlib/jdiconv.cpp
- src/jdlib/jdiconv.h
- src/jdlib/misctrip.cpp
- src/jdlib/miscutil.cpp
- src/jdlib/miscutil.h
- src/message/messageviewbase.cpp
- src/message/post.cpp
- src/skeleton/textloader.cpp
[JDLIB::Iconvクラス][jdlib]はiconv APIのラッパーですがエンコーディングを指定する引数が基底のライブラリと逆順になっています。
API | 順序
--- | ---
iconv API | `iconv_open(to_code, from_code)`
JDLIB::Iconv | `JDLIB:Iconv(from_code, to_code)`
[POSIX][2008][のAPI][susv2]や[Glibの][glib][ラッパーAPI][glibmm]はすべて`(to_code, from_code)`の順序です。
jdimの実装だけ逆順なのは紛らわしいため基底のライブラリの順序に修正します。
[jdlib]: https://github.com/JDimproved/JDim/blob/5a8e66f3d0/src/jdlib/jdiconv.h#L33
[2008]: https://pubs.opengroup.org/onlinepubs/9699919799/functions/iconv_open.html "POSIX-1.2008"
[susv2]: https://pubs.opengroup.org/onlinepubs/7908799/xsh/iconv_open.html "SUSv2"
[glib]: https://developer.gnome.org/glib/stable/glib-Character-Set-Conversion.html "glib"
[glibmm]: https://developer.gnome.org/glibmm/stable/classGlib_1_1IConv.html "glibmm"
> Fix argument order for JDLIB::Iconv constructor

- snap/snapcraft.yaml
snapcraftのgnome-3-34-1804スタックが更新され[libsigc++を同梱する][1]ようになりました。
Snapパッケージの[stableチャンネル][2]にも反映されましたのでjdimに同梱していたパッケージを取り除きます。
開発用パッケージ(-dev)に変更はないためbuild-packagesの設定は維持します。
[1]: https://gitlab.gnome.org/Community/Ubuntu/gnome-sdk/-/merge_requests/21
[2]: https://snapcraft.io/gnome-3-34-1804
> snapcraft: Get rid of libsigc++-2.0 from stage-packages

- test/gtest_jdlib_jdiconv.cpp
- test/meson.build
iconv関数のラッパークラスにテストケースを追加します。
エンコーディング変換のパターンは無数にあるためラッパークラスに追加した変換失敗時の処理をテストします。
> Add JDLIB::Iconv test cases

- configure.ac
- meson.build
- src/article/articleviewbase.cpp
- src/bbslist/bbslistviewbase.cpp
- src/cache.cpp
- src/dbtree/articlebase.cpp
- src/dbtree/boardbase.cpp
- src/message/messageview.cpp
- src/skeleton/msgdiag.cpp
GTK4で廃止される`Gtk::Stock::YES`をi18n対応テキストに置き換えます。
GTK3用のgettextパッケージを利用して日本語テキストを表示します。
GTK3用gettextパッケージ名のマクロ定義をコンパイラーの引数に追加します。
現時点ではパッケージ名として文字列リテラル("gtk30")をgettext APIの引数に直接指定することは可能です。
しかし将来のGTK4対応で変更が必要になるためマクロを使います。
```
```
コンパイラのレポート
```
../src/article/articleviewbase.cpp:1127:44: error: 'Gtk::Stock' has not been declared
1127 |             mdiag.add_default_button( Gtk::Stock::YES, Gtk::RESPONSE_YES );
|                                            ^~~~~ …
```
> Use i18n text instead of Gtk::Stock::YES for button label

- src/article/articleviewbase.cpp
- src/bbslist/bbslistviewbase.cpp
- src/cache.cpp
- src/dbtree/articlebase.cpp
- src/dbtree/boardbase.cpp
- src/message/messageview.cpp
- src/skeleton/msgdiag.cpp
GTK4で廃止される`Gtk::Stock::NO`をi18n対応テキストに置き換えます。
Gtk::Stockからラベルに変更する参考文献:
```
```
コンパイラのレポート
```
../src/article/articleviewbase.cpp:1126:36: error: 'Gtk::Stock' has not been declared
1126 |             mdiag.add_button( Gtk::Stock::NO, Gtk::RESPONSE_NO );
|                                    ^~~~~
../src/bbslist/bbslistviewbase.cpp:2631:56: error: 'Gtk::Stock' has not been declared
2631 |                         mdiag.add_default_button( Gtk::Stock::NO, …
```
> Use i18n text instead of Gtk::Stock::NO for button label

- src/skeleton/editviewdialog.h
- src/skeleton/msgdiag.cpp
- src/skeleton/prefdiag.cpp
GTK4で廃止される`Gtk::Stock::OK`をi18n対応テキストに置き換えます。
Gtk::Stockからラベルに変更する参考文献:
```
```
コンパイラのレポート
```
../src/skeleton/editviewdialog.h:24:30: error: 'Gtk::Stock' has not been declared
24 |             add_button( Gtk::Stock::OK, Gtk::RESPONSE_OK );
|                              ^~~~~
../src/skeleton/msgdiag.cpp:162:53: error: 'Gtk::Stock' has not been declared
162 |         button = Gtk::manage( new Gtk::Button( Gtk::Stock::OK ) );
| …
```
> Use i18n text instead of Gtk::Stock::OK for button label

- src/dbimg/delimgcachediag.cpp
- src/message/messageadmin.cpp
- src/message/messageview.cpp
- src/skeleton/admin.cpp
- src/skeleton/filediag.h
- src/skeleton/prefdiag.cpp
GTK4で廃止される`Gtk::Stock::CANCEL`をi18n対応テキストに置き換えます。
Gtk::Stockからラベルに変更する参考文献:
```
```
コンパイラのレポート
```
../src/dbimg/delimgcachediag.cpp:28:22: error: 'Gtk::Stock' has not been declared
28 |     add_button( Gtk::Stock::CANCEL, Gtk::RESPONSE_CANCEL )
|                      ^~~~~
../src/message/messageadmin.cpp:383:28: error: 'Gtk::Stock' has not been declared
383 |     mdiag.add_button( Gtk::Stock::CANCEL, Gtk::RESPONSE_CANCEL );
|                            ^~~~~ …
```
> Use i18n text instead of Gtk::Stock::CANCEL for button label

- INSTALL
- docs/manual/make.md
- meson.build
ドキュメントに記載したmesonのコマンド例は新しいバージョン(>= 0.54.0)でないと使えないサブコマンド([compile])を使用していたため古いバージョンでも利用できる例を追加します。
https://mao.5ch.net/test/read.cgi/linux/1597722999/561
[compile]: https://mesonbuild.com/Commands.html#compile
> Fix documents for meson command example

- src/skeleton/prefdiag.cpp
- src/skeleton/prefdiag.h
GTK4で廃止される`Gtk::Stock::APPLY`をi18n対応テキストに置き換えます。
```
```
コンパイラのレポート
```
../src/skeleton/prefdiag.cpp:17:73: error: 'Gtk::Stock' has not been declared
17 |     : Gtk::Dialog(), m_url( url ), m_bt_ok( nullptr ), m_bt_apply( Gtk::Stock::APPLY )
|                                                                         ^~~~~
```
> Use i18n text instead of Gtk::Stock::APPLY for button label

- src/skeleton/aboutdiag.cpp
GTK4で廃止される`Gtk::Stock::CLOSE`をi18n対応テキストに置き換えます。
```
```
コンパイラのレポート
```
../src/skeleton/aboutdiag.cpp:31:44: error: 'Gtk::Stock' has not been declared
31 |     Gtk::Button* button = add_button( Gtk::Stock::CLOSE, Gtk::RESPONSE_CLOSE );
|                                            ^~~~~
```
> Use i18n text instead of Gtk::Stock::CLOSE for button label

- src/message/messageview.cpp
GTK4で廃止される`Gtk::Stock::REMOVE`をi18n対応テキストに置き換えます。
修正箇所はコメントアウトされていますが一連の修正に合わせて変更します。
```
```
> Use i18n text instead of Gtk::Stock::REMOVE for button label

- src/control/mousekeypref.cpp
- src/linkfilterpref.cpp
GTK4で廃止される`Gtk::Stock::(ADD|DELETE)`をi18n対応テキストに置き換えます。
https://gitlab.gnome.org/GNOME/gtk/blob/3.24.20/gtk/deprecated/gtkstock.c#L346
```
```
コンパイラのレポート
```
../src/control/mousekeypref.cpp:272:29: error: 'Gtk::Stock' has not been declared
272 |       m_button_delete( Gtk::Stock::DELETE ),
|                             ^~~~~
../src/control/mousekeypref.cpp:273:26: error: 'Gtk::Stock' has not been declared
273 |       m_button_add( …
```
> Use i18n text instead of Gtk::Stock::(ADD|DELETE) for button label

- src/skeleton/filediag.h
- src/skeleton/prefdiag.cpp
GTK4で廃止される`Gtk::Stock::OPEN`をi18n対応テキストに置き換えます。
Gtk::Stockからラベルに変更する参考文献:
https://gitlab.gnome.org/GNOME/gtk/blob/3.24.20/gtk/deprecated/gtkstock.c#L422
```
```
コンパイラのレポート
```
../src/skeleton/filediag.h:26:78: error: 'Gtk::Stock' has not been declared
26 |             if( m_action == Gtk::FILE_CHOOSER_ACTION_OPEN ) add_button( Gtk::Stock::OPEN, Gtk::RESPONSE_ACCEPT );
|                                                                              ^~~~~ …
```
> Use i18n text instead of Gtk::Stock::OPEN for button label

- src/message/messageadmin.cpp
- src/skeleton/filediag.h
GTK4で廃止される`Gtk::Stock::SAVE`をi18n対応テキストに置き換えます。
https://gitlab.gnome.org/GNOME/gtk/blob/3.24.20/gtk/deprecated/gtkstock.c#L442
```
```
コンパイラのレポート
```
../src/message/messageadmin.cpp:384:30: error: 'Gtk::Stock' has not been declared
384 |     Gtk::Button button( Gtk::Stock::SAVE );
|                              ^~~~~
../src/skeleton/filediag.h:27:35: error: 'Gtk::Stock' has not been declared
27 |             else add_button( …
```
> Use i18n text instead of Gtk::Stock::SAVE for button label

- src/skeleton/selectitempref.cpp
GTK4で廃止される`Gtk::Stock::REVERT_TO_SAVED`をi18n対応テキストに置き換えます。
https://gitlab.gnome.org/GNOME/gtk/blob/3.24.20/gtk/deprecated/gtkstock.c#L441
```
```
コンパイラのレポート
```
../src/skeleton/selectitempref.cpp:26:30: error: 'Gtk::Stock' has not been declared
26 |       m_button_default( Gtk::Stock::REVERT_TO_SAVED )
|                              ^~~~~
```
> Use i18n text instead of Gtk::Stock::REVERT_TO_SAVED for button label

- src/article/articleviewbase.cpp
GTK4で廃止される`Gtk::Stock::REFRESH`のアイコンをボタンから削除します。
```
```
コンパイラのレポート
```
../src/article/articleviewbase.cpp:1130:36: error: 'Gtk::Stock' has not been declared
1130 |             Gtk::Image image( Gtk::Stock::REFRESH, Gtk::ICON_SIZE_BUTTON );
|                                    ^~~~~
```
> Remove Gtk::Stock::REFRESH icon from button

- src/skeleton/selectitempref.cpp
- src/skeleton/selectitempref.h
GTK4で廃止される`Gtk::Stock::GO_(FORWARD|BACK)`をアイコンテーマに置き換えます。
```
```
コンパイラのレポート
```
../src/skeleton/selectitempref.cpp:24:29: error: 'Gtk::Stock' has not been declared
24 |       m_button_delete( Gtk::Stock::GO_FORWARD, std::string(), Gtk::ICON_SIZE_BUTTON ),
|                             ^~~~~
../src/skeleton/selectitempref.cpp:25:26: error: 'Gtk::Stock' has not been declared
25 |       m_button_add( Gtk::Stock::GO_BACK, std::string(), …
```
> Use named icons instead of Gtk::Stock::GO_(FORWARD|BACK) for button

- src/linkfilterpref.cpp
- src/skeleton/selectitempref.cpp
GTK4で廃止される`Gtk::Stock`をi18n対応テキストとアイコンテーマに置き換えます。
ナビゲージョンのアイコンは表示したほうが分かりやすいと判断したため残しておきます。
https://gitlab.gnome.org/GNOME/gtk/blob/3.24.20/gtk/deprecated/gtkstock.c
```
```
コンパイラのレポート
```
../src/linkfilterpref.cpp:66:26: error: 'Gtk::Stock' has not been declared
66 |       m_button_top( Gtk::Stock::GOTO_TOP ),
|                          ^~~~~
../src/linkfilterpref.cpp:67:25: error: 'Gtk::Stock' has not been declared
67 | …
```
> Use i18n text and nemed icon instead of Gtk::Stock for buttons

- src/image/imageadmin.cpp
ヌルポインタをデリファレンスする可能性があるとcppcheck 2.1に指摘されたため条件文を修正します。
cppcheckのレポート
```
src/image/imageadmin.cpp:660:13: warning: Either the condition 'if(view)' is redundant or there is possible null pointer dereference: view. [nullPointerRedundantCheck]
if( view->get_url() == url ) break;
^
src/image/imageadmin.cpp:661:11: note: Assuming that condition 'if(view)' is not redundant
if( view ) {
^
src/image/imageadmin.cpp:660:13: note: Null pointer dereference
if( view->get_url() == url ) break;
^
```
> ImageAdmin: Fix null pointer redundant check

- src/jdlib/miscutil.cpp
ダングリングポインタを関数から返しているとcppcheck 2.1に指摘されたため戻り値を修正します。
cppcheckのレポート
```
src/jdlib/miscutil.cpp:1699:20: error: Returning object that points to local variable 'env' that will be invalid when returning. [returnDanglingLifetime]
return env.data();
^
src/jdlib/miscutil.cpp:1699:12: note: Pointer to container is created here.
return env.data();
^
src/jdlib/miscutil.cpp:1696:25: note: Variable created here.
std::vector< char > env( size + 1, '\0' );
^
src/jdlib/miscutil.cpp:1699:20: note: Returning object that points to local variable 'env' that will be invalid when returning.
return env.data();
^
```
> miscutil: Fix return dangling pointer

- src/jdlib/miscutil.cpp
既に条件が判明している比較があるとcppcheck 2.1に指摘されたため条件文を修正します。
cppcheckのレポート
```
src/jdlib/miscutil.cpp:1347:51: style: Condition 'raw_point<=0xFDEF' is always true [knownConditionTrueFalse]
|| ( 0xFDD0 <= raw_point && raw_point <= 0xFDEF ) // Noncharacters
^
src/jdlib/miscutil.cpp:1334:21: note: Assuming that condition '0xFDEF<raw_point' is not redundant
else if( 0xFDEF < raw_point ) return raw_point;
^
src/jdlib/miscutil.cpp:1347:51: note: Condition 'raw_point<=0xFDEF' is always true
|| ( 0xFDD0 <= raw_point && raw_point <= 0xFDEF ) // Noncharacters
^
```
> miscutil: Fix known condition true/false

- src/dbtree/root.cpp
ヌルポインタをデリファレンスする可能性があるとcppcheck 2.1に指摘されたため変数定義を修正します。
cppcheckのレポート
```
src/dbtree/root.cpp:410:32: warning: Either the condition 'if(libiconv)' is redundant or there is possible null pointer dereference: libiconv. [nullPointerRedundantCheck]
const char* rawdata_utf8 = libiconv->convert( &*m_rawdata.begin(), m_rawdata.size(),  byte_out );
^
src/dbtree/root.cpp:422:7: note: Assuming that condition 'if(libiconv)' is not redundant
if( libiconv ) delete libiconv;
^
src/dbtree/root.cpp:410:32: note: Null pointer dereference
const char* rawdata_utf8 = libiconv->convert( &*m_rawdata.begin(), m_rawdata.size(),  byte_out );
^
```
> Root: Fix null pointer redundant check

- src/skeleton/msgdiag.cpp
- src/skeleton/msgdiag.h
GTK4で廃止される`Gtk::StockID`を使う関数オーバーロードを削除します。
```
```
コンパイラのレポート
```
../src/skeleton/msgdiag.cpp:52:66: error: no matching function for call to 'Gtk::Button::Button(const Gtk::StockID&)'
52 |     Gtk::Button* button = Gtk::manage( new Gtk::Button( stock_id ) );
|                                                                  ^
```
関連のissue: #229
> Remove unused MsgDiag::add_default_button(const Gtk::StockID&, const int)

- src/setupwizard.cpp
- src/setupwizard.h
> setupwizard: Use Gtk::Grid instead of Gtk::VBox for PageStart

- src/setupwizard.cpp
- src/setupwizard.h
> setupwizard: Use Gtk::Grid instead of Gtk::VBox for PageNet

- src/setupwizard.cpp
- src/setupwizard.h
設定ダイアログに親ウインドウを設定します。環境によっては子ダイアログボックスが親の下に隠れて表示される問題がありました。
> setupwizard: Set parent window to pref dialogs for PageNet

- src/setupwizard.cpp
- src/setupwizard.h
> setupwizard: Use Gtk::Grid instead of Gtk::VBox for PageFont

- src/setupwizard.cpp
- src/setupwizard.h
> setupwizard: Use Gtk::Grid instead of Gtk::VBox for PagePane

- src/setupwizard.cpp
- src/setupwizard.h
> setupwizard: Use Gtk::Grid instead of Gtk::VBox for PageEnd

- meson.build
- meson_options.txt
mesonの構成にテストプログラムのビルドをオプトアウトするビルドオプション`build_tests`を追加します。
これまではテストライブラリを見つけるとテストプログラムをビルドする設定だったのでテストが不要なときは余計に時間がかかっていました。
> meson: Add build_tests option

- src/skeleton/tablabel.cpp
デバッグ出力のコードにポインターのヌルチェックが抜けている箇所があったため修正します。
> TabLabel: Fix null pointer check for debug print

- meson.build
Debian Stretchは[backportsリポジトリ][bpo]でmeson __0.49.0__ が利用できます。
JDimはmesonのバージョン要件を __0.49.2__ に設定していますがstretch-backportsとはマイナーバージョンの差です。
互換性に影響がないので要件を修正してbackportsのmesonを利用したビルドができるようにします。
[bpo]: https://packages.debian.org/source/stretch-backports/meson
> meson: Fall back requirement to version 0.49.0

- src/article/articleviewbase.cpp
- src/article/articleviewsearch.cpp
- src/article/preference.cpp
- src/bbslist/bbslistviewbase.cpp
- src/board/boardadmin.cpp
- src/board/boardviewbase.cpp
- src/board/preference.cpp
- src/core.cpp
- src/dbtree/articlebase.cpp
- src/dbtree/boardbase.cpp
- src/dbtree/interface.cpp
- src/dbtree/interface.h
- src/history/historysubmenu.cpp
- src/menuslots.cpp
- src/message/messageview.cpp
- src/skeleton/toolbar.cpp
- src/updatemanager.cpp
`CORE::PrefDiagFactory()`や`CORE::core_set_command()`などに使う板の識別子をsubject.txtのURLから板のURLへ変更します。
`DBTREE::url_subject()`は呼び出すコードが無くなるため削除します。
> Use boardbase URL instead of subject.txt URL for identifier

- src/dbtree/board2chcompati.cpp
- src/dbtree/board2chcompati.h
- src/dbtree/boardbase.h
- src/dbtree/boardjbbs.cpp
- src/dbtree/boardjbbs.h
- src/dbtree/interface.cpp
- src/dbtree/interface.h
- src/dbtree/ruleloader.cpp
- src/dbtree/ruleloader.h
- src/dbtree/settingloader.cpp
- src/dbtree/settingloader.h
したらば掲示板のローカルルールとSETTING.TXTの読み込みを実装します。
読み込んだ板設定からデフォルト名無しを設定します。
したらばのAPI
http://blog.livedoor.jp/bbsnews/archives/51024405.html
> Implement loading local rule and settings for JBBS

- INSTALL
- configure.ac
- docs/manual/make.md
- meson.build
正規表現ライブラリPOSIX regexのサポートを廃止予定にします。
POSIXは幅広い環境で利用できる利点がありますが、PCRE系の正規表現と比べると機能が少なく動作確認の手間がかかります。
デフォルトオプションのGRegexはPCRE系の構文でありJDimが動作する環境なら利用できるためライブラリを整理してメンテナンスの負担を削減します。
関連のissue: #521
> Deprecate posix regex option

- src/article/drawareabase.cpp
- src/bbslist/bbslistviewbase.cpp
- src/board/boardviewbase.cpp
- src/config/configitems.cpp
- src/control/buttonconfig.cpp
- src/control/keyconfig.cpp
- src/dbtree/boardbase.cpp
- src/dbtree/boardbase.h
- src/dbtree/boardmachi.cpp
- src/dbtree/nodetreebase.cpp
- src/dbtree/nodetreebase.h
- src/dbtree/root.cpp
- src/jdlib/cookiemanager.cpp
- src/jdlib/jdregex.cpp
- src/jdlib/jdregex.h
- src/jdlib/miscutil.cpp
- src/linkfiltermanager.cpp
- src/main.cpp
- src/searchmanager.cpp
- src/urlreplacemanager.cpp
- src/urlreplacemanager.h
正規表現クラスとクライアント側のコードを更新します。
- `RegexPattern`クラスを導入してコンパイル済みの正規表現オブジェクトと検索実行してマッチ結果を保持する`Regex`クラスに分割します。
- 正規表現のコンパイルや検索に失敗したときエラー内容をテキストで取得できるようにします。
- 検索実行時に行頭行末にマッチさせないオプションを追加します。
- マッチ結果を使って文字列を置換するメンバー関数を追加します。
- マッチした部分文字列の長さを返す`Regex::length()`を導入し一時変数の生成を回避します。
> Improve regex class

- INSTALL
- docs/manual/make.md
プロジェクトで使うテスト環境ではclang-4.0を利用する[ビルドが失敗][1]するためv0.5.0リリース後のコンパイラ要件をclang-5.0にします。
gcc-6は変更ありません。
[1]: https://github.com/ma8ma/JDim/pull/52#issuecomment-731599869
> Update compiler requirement to clang-5.0 since version 0.5.0

- README.md
- docs/manual/start.md
- src/core.cpp
- src/fontcolorpref.cpp
Reverts JDimproved/JDim#476
https://github.com/JDimproved/JDim/issues/469#issuecomment-739875118
環境によっては色を抽出するスポイト機能が使えなくなるため一旦コミットを取り消します。
> Revert "Use Gtk::ColorChooserDialog instead of Gtk::ColorSelectionDialog"

- src/dbtree/nodetreebase.cpp
ループ文で配列の範囲外へアクセスする可能性のあるコードを修正します。
> NodeTreeBase: Fix out of bounds error

- src/dbtree/nodetreebase.cpp
- src/dbtree/nodetreebase.h
- src/skeleton/dragtreeview.cpp
- src/skeleton/dragtreeview.h
コンパイラの未定義動作を検出するオプション(`-fsanitize=undefined`)で未初期化変数の使用を見つけたため修正します。
エラーログ
```
../src/dbtree/nodetreebase.cpp:3160:11: runtime error: load of value 93, which is not a valid value for type 'bool'
../src/dbtree/nodetreebase.cpp:3186:37: runtime error: load of value 92, which is not a valid value for type 'bool'
../src/dbtree/nodetreebase.cpp:3187:38: runtime error: load of value 92, which is not a valid value for type 'bool'
../src/dbtree/nodetreebase.cpp:3189:38: runtime error: load of value 85, which is not a valid value for type 'bool'
../src/dbtree/nodetreebase.cpp:3190:39: runtime error: load of value 85, which is not a valid value for type 'bool'
../src/dbtree/nodetreebase.cpp:3287:10: runtime error: load of value 109, which is not a valid value for type 'bool' …
```
> NodeTreeBase, DragTreeView: Fix member initialization

- src/dbtree/board2chcompati.cpp
- src/dbtree/boardjbbs.cpp
- src/dbtree/boardmachi.cpp
- したらばとまちBBSのキャッシュのファイル名チェックを修正してシンプルにします。
- 2ch互換板のキャッシュのファイル名チェックを修正してシンプルにします。
コンパイラの未定義動作を検出するオプション(`-fsanitize=undefined`)で符号付き整数のオーバーフローを見つけたため修正します。
エラーログ
```
../src/jdlib/miscutil.cpp:551:22: runtime error: signed integer overflow: 924222222 * 10 cannot be represented in type 'int'
```
> board: Fix cache filename checking

- docs/manual/2020.md
- src/jdversion.h
> Bump version to 0.5.0-beta

- src/control/mousekeypref.cpp
- src/linkfilterpref.cpp
- src/message/messageadmin.cpp
- src/replacestrpref.cpp
- src/skeleton/filediag.h
- src/skeleton/prefdiag.cpp
- src/skeleton/selectitempref.cpp
以前の修正で廃止予定の`GtkStock`をi18n対応テキストに置き換えましたが言語パックがインストールされていない環境では正常に表示されない状態でした。
そのため利用するgettext APIを変更して修正します。
> Fix button label text without language pack

- src/replacestrpref.cpp
GTK4で廃止される`Gtk::Dialog::get_vbox()`のかわりに`Gtk::Dialog::get_content_area()`を使います。
コンパイラのレポート
```
../src/replacestrpref.cpp:68:5: error: ‘get_vbox’ was not declared in this scope
68 |     get_vbox()->set_spacing( 8 );
|     ^~~~~~~~
../src/replacestrpref.cpp:211:5: error: ‘get_vbox’ was not declared in this scope
211 |     get_vbox()->set_spacing( 8 );
|     ^~~~~~~~
```
関連のissue: #229
> Use Gtk::Dialog::get_content_area() instead of get_vbox() part4

- src/article/drawareabase.cpp
- src/skeleton/menubutton.cpp
Fixes #506
コンパイラ(gcc11)が警告したnullの可能性がある箇所を修正します。
gcc11のログ
```
menubutton.cpp:126:115: warning: 'this' pointer null [-Wnonnull]
126 |             dynamic_cast< Gtk::Label* >( item->get_child() )->set_text( MISC::cut_str( items[ i ], MENU_MAX_LNG ) );
|                                                                                                                   ^
drawareabase.cpp:5405:83: warning: 'this' pointer null [-Wnonnull]
5405 |     return dynamic_cast< DrawAreaBase* >( widget )->deceleration_tick_impl( clock );
|                                                                                   ^
```
> Fix compiler warning for null possibility

- src/dbtree/nodetreebase.cpp
コンパイラ(clang11)が警告した未使用の定数を削除します。
clang11のレポート
```
../src/dbtree/nodetreebase.cpp:47:18: warning: unused variable 'LNG_RES' [-Wunused-const-variable]
constexpr size_t LNG_RES = 16;
^
```
> Fix compiler warning for unused const variable

- src/dbtree/root.cpp
`std::find_if()`が使えるとcppcheckに指摘されたためループ文を修正します。
cppcheckのレポート
```
src/dbtree/root.cpp:189:34: style: Consider using std::find_if algorithm instead of a raw loop. [useStlAlgorithm]
if( board->equal( url ) ){
^
```
> Root: Use std::find_if() instead of range based for statement

- src/article/drawareabase.cpp
スレビューをタッチスクリーン操作のスワイプで慣性スクロールしているときにタブを閉じるとコンソールにエラーメッセージが表示されるため修正します。
実行時のレポート (環境変数`GTK_TEST_TOUCHSCREEN=1`で確認)
```
(jdim:1024608): Gtk-CRITICAL **: 21:54:08.801: gtk_widget_remove_tick_callback: assertion 'GTK_IS_WIDGET (widget)' failed
```
> DrawAreaBase: Fix warning while closing thread view

- src/bbslist/bbslistviewbase.cpp
お気に入りにPartスレッドを登録しているときスレビュー内のURLから次スレ(次のPart)を開く、または前スレからスレ情報を引き継ぐとお気に入りに登録されたスレッドの更新が可能です。
しかし、更新を行ってもスレタイだけ前スレのまま変わらないことがありましたので処理を修正します。
https://mao.5ch.net/test/read.cgi/linux/1609398982/200
スレタイの末尾に空白が含まれているとスレタイが更新されませんでした。
状況の再現が難しいためissueは省略します。
> Fix updating thread title for replacing favorite

- jdim.metainfo.xml
- snap/snapcraft.yaml
ディストリビューション共通のメタデータとして設定したAppStreamコンポーネントIDを[freedesktop.orgが推奨する形式][*]（大文字を使わない）に修正します。
[*]: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic
> Additionally, even though uppercase letters are permitted in a component-ID, it is strongly encouraged to only use lowercase letters for the ID.
修正前のファイルをappstreamcliで検証した結果
```
I: com.github.jdimproved.JDim:4: cid-contains-uppercase-letter com.github.jdimproved.JDim
Validation was successful: infos: 1
```
> metadata: Fix AppStream component-ID to lowercase

- configure.ac
廃止されたスレッドライブラリを選択するconfigureオプションを削除します。
削除されたオプションは指定しても無視されてエラーは出なくなります。
- `--with-gthread`
- `--with-stdthred`
- `--with-thread=posix|glib|std`
- `--with-gtkmm3`
- `--with-oniguruma`
- `--with-pcre`
- `--with-regex=pcre`
- `--with-openssl`
関連のissue: #228, #229, #361
> Remove obsolete configure options

- INSTALL
- configure.ac
- docs/manual/make.md
- meson.build
- meson_options.txt
- src/jdlib/jdregex.cpp
- src/jdlib/jdregex.h
- src/replacestrmanager.cpp
廃止予定の正規表現ライブラリのビルドオプション`--with-regex=posix`を削除します。
削除されたオプションは指定するとエラーになり./configureが失敗します。
関連のissue: #521
> Remove deprecated build option --with-regex=posix

- src/article/drawareabase.cpp
- src/message/messageviewbase.cpp
GTKのバージョン要件の変更(3.22以上)により使われなくなったコードを削除します。
関連のissue: #443, #566
> Remove obsolete gtk codes for less than version 3.22

- CONTRIBUTING.md
- INSTALL
- README.md
- configure.ac
- docs/manual/make.md
- meson.build
使用するC++標準規格をC++17に更新します。
合わせてドキュメントのコンパイラ要件やエラー回避のtipsも更新します。
コントリビュートガイドを更新しC++14を利用するように案内します。
さらにC++17の機能についてgcc-6の実装を条件に利用可能とします。
関連のissue: #527
> Migrate cpp_std to c++17

- configure.ac
- meson.build
- src/environment.cpp
- src/jdlib/misctrip.cpp
- src/sound/playsound.cpp
ビルド構成時のヘッダーファイル検査を[`__has_include()`][1]で置き換えます。
- `<alsa/asoundlib.h>`
- `<crypt.h>`
- `<sys/utsname.h>`
[1]: https://cpprefjp.github.io/lang/cpp17/has_include.html
> Use __has_include() instead of config macro

- src/skeleton/dragtreeview.cpp
- src/skeleton/selectitempref.cpp
GTK4で廃止される[`Gtk::TreeView::set_rules_hint()`][1]の呼び出しを取り除きます。
`Gtk::TreeView`の背景縞模様はGTKテーマが制御する問題となったためアプリケーション側の設定は非推奨になりました。
[1]: https://developer.gnome.org/gtk3/stable/GtkTreeView.html#gtk-tree-view-set-rules-hint
関連のissue: #443
> Get rid of calling deprecated Gtk::TreeView::set_rules_hint()

- src/skeleton/popupwin.cpp
GTK4で廃止される[`Gdk::DeviceManager`][1]のかわりに`Gdk::Seat`を使います。
```
```
コンパイラのレポート
```
../src/skeleton/popupwin.cpp:51:34: error: 'class Gdk::Display' has no member named 'get_device_manager'
51 |     Gdk::Display::get_default()->get_device_manager()->get_client_pointer()->get_position( x_mouse, y_mouse );
|                                  ^~~~~~~~~~~~~~~~~~
```
[1]: https://developer.gnome.org/gdk3/stable/GdkDisplay.html#gdk-display-get-device-manager
関連のissue: #443
> PopupWin: Use Gdk::Seat instead of Gdk::DeviceManager

- src/article/articleviewbase.cpp
- src/article/drawareabase.cpp
- src/jdlib/miscgtk.cpp
- src/jdlib/miscgtk.h
- src/skeleton/edittreeview.cpp
- src/skeleton/tabnote.cpp
- src/skeleton/treeviewbase.cpp
- src/skeleton/view.cpp
GTK4で廃止される[`Gtk::Widget::get_pointer()`][1]のかわりに`Gdk::Window::get_device_position()`を使います。
参考
https://stackoverflow.com/questions/24844489/how-to-use-gdk-device-get-position
```
```
コンパイラのレポート
```
../src/article/articleviewbase.cpp:1012:9: error: 'get_pointer' was not declared in this scope; did you mean 'gpointer'?
1012 |         get_pointer( x, y );
|         ^~~~~~~~~~~
|         gpointer
../src/article/articleviewbase.cpp:1014:22: error: 'class SKELETON::PopupWin' has no member named 'get_pointer'
1014 |         m_popup_win->get_pointer( x, y );
|                      ^~~~~~~~~~~
../src/article/drawareabase.cpp:3188:20: …
```
> Use Gdk::Window::get_device_position() instead of Gtk::Widget::get_pointer()

- src/skeleton/tabnote.cpp
Fixes #575
画像埋め込み表示でタブの上にサムネイルがあるときタブがクリック操作を受け付けなくなる不具合を修正します。
> TabNotebook: Fix tab click

- src/skeleton/aamenu.cpp
Fixes #576
Wayland環境で書き込みビューのアスキーアート入力候補を表示するときカーソル位置から離れた場所に出る不具合を修正します。
> AAMenu: Fix display position for ascii art preview on Wayland

- src/setupwizard.cpp
Waylandなど新しいウインドウプロトコルに対応するためセットアップウィザートのサイズと表示位置の指定を削除してデスクトップ環境に任せます。
APIでスクリーン中央にダイアログを配置するよう設定しますが実際の位置はデスクトップが決めます。
> SetupWidzard: Delegate dialog size and position to desktop environment

- src/config/aboutconfig.cpp
- src/control/mousekeypref.cpp
- src/fontcolorpref.cpp
- src/skeleton/prefdiag.cpp
- src/skeleton/prefdiag.h
GTKのAPIが更新され複数モニターがある環境が前提となったためスクリーンの長さをもとにウインドウサイズを求める方法は不適当になりました。
そのためダイアログのウインドウサイズを子要素の自然な長さから設定するように変更します。
This reverts commit c6d57f203e79dd8c7e65f94f4a3233c4b7f1a760.
GTK4で廃止される`Gdk::Screen::get_width/height()`を利用する関数を削除します。
コンパイラのレポート (非推奨のシンボルを無効化)
```
../src/skeleton/prefdiag.cpp:103:51: error: 'class Gdk::Screen' has no member named 'get_width'
103 |     const int width = static_cast< int >( screen->get_width() * ratio );
|                                                   ^~~~~~~~~
../src/skeleton/prefdiag.cpp:104:52: error: 'class Gdk::Screen' has no member named 'get_height'
104 |     const int height = static_cast< int >( screen->get_height() * ratio );
|                                                    ^~~~~~~~~~
```
> Change size setting for dialog box to use child natural size

- src/dbtree/boardbase.cpp
- src/dbtree/boardbase.h
> BoardBase: Fix member initialization

- src/skeleton/loadable.cpp
- src/skeleton/loadable.h
> Loader: Fix member initialization

- src/dbtree/articlebase.cpp
- src/dbtree/articlebase.h
> ArticleBase: Fix member initialization

- src/message/messageviewbase.cpp
- src/message/messageviewbase.h
> MessageViewBase: Fix member initialization

- src/article/articleadmin.cpp
- src/article/articleadmin.h
> ArticleAdmin: Fix member initialization

- src/article/articleviewsearch.cpp
- src/article/articleviewsearch.h
> ArticleViewSearch: Fix member initialization

- src/article/caret.h
> CARET_POSITION: Fix member initialization

- src/article/layouttree.cpp
- src/article/layouttree.h
> LayoutTree: Fix member initialization

- src/article/toolbar.cpp
- src/article/toolbar.h
> ArticleToolBar: Fix member initialization

- src/article/toolbarsearch.cpp
- src/article/toolbarsearch.h
> SearchToolBar: Fix member initialization

- src/bbslist/bbslistadmin.cpp
- src/bbslist/bbslistadmin.h
- src/bbslist/bbslistviewbase.cpp
- src/bbslist/bbslistviewbase.h
- src/bbslist/selectdialog.cpp
- src/bbslist/selectdialog.h
- src/bbslist/toolbar.cpp
- src/bbslist/toolbar.h
> bbslist: Fix member initialization

- src/control/mousekeypref.cpp
- src/control/mousekeypref.h
> MouseKeyDiag: Fix member initialization

- src/cssmanager.cpp
- src/cssmanager.h
> Css_Manager: Fix member initialization

- src/dbimg/delimgcachediag.cpp
- src/dbimg/delimgcachediag.h
- src/dbimg/img.cpp
- src/dbimg/img.h
> dbimg: Fix member initialization

- src/dbtree/root.cpp
- src/dbtree/root.h
- src/dbtree/settingloader.cpp
- src/dbtree/settingloader.h
> dbtree: Fix member initialization

- src/dndmanager.h
> DND_Manager: Fix member initialization

- src/history/historymanager.cpp
- src/history/historymanager.h
- src/history/historymenu.cpp
- src/history/historymenu.h
- src/history/historysubmenu.h
- src/history/viewhistory.cpp
- src/history/viewhistory.h
> history: Fix member initialization

- src/iomonitor.cpp
- src/iomonitor.h
> IOMonitor: Fix member initialization

- src/image/imageadmin.h
- src/image/imageareabase.cpp
- src/image/imageareabase.h
- src/image/imageviewpopup.cpp
- src/image/imageviewpopup.h
- src/image/imagewin.cpp
- src/image/imagewin.h
> image: Fix member initialization

- src/jdlib/confloader.cpp
- src/jdlib/confloader.h
- src/jdlib/constptr.h
- src/jdlib/heap.cpp
- src/jdlib/heap.h
- src/jdlib/refptr_lock.h
- src/jdlib/ssl.cpp
- src/jdlib/ssl.h
> jdlib: Fix member initialization

- src/message/logitem.h
- src/message/post.cpp
- src/message/post.h
- src/message/toolbar.cpp
- src/message/toolbar.h
Fix member initialization to use default member initializer or constructor. Fill zeroes for not having initial values. Remove unnecessary include directives.
> message: Fix member initialization

- src/skeleton/aamenu.h
Fix member initialization to use default member initializer or constructor. Fill zeroes for not having initial values.
> AAMenu: Fix member initialization

- src/xml/dom.cpp
- src/xml/dom.h
Fix member initialization to use default member initializer or constructor. Fill zeroes for not having initial values.
> Dom: Fix member initialization

- src/winmain.cpp
- src/winmain.h
Fix member initialization to use default member initializer or constructor. Fill zeroes for not having initial values.
> JDWinMain: Fix member initialization

- src/message/logitem.h
Fix loop condition to not overwrite last null char for avoiding buffer overrun.
> LogItem: Fix off-by-one error for buffer copy

- src/skeleton/aboutdiag.cpp
- src/skeleton/aboutdiag.h
Remove empty member function `AboutDiag::slot_close_button()`.
> AboutDiag: Remove empty member function

- src/skeleton/admin.cpp
- src/skeleton/admin.h
- src/skeleton/compentry.cpp
- src/skeleton/compentry.h
- src/skeleton/detaildiag.cpp
- src/skeleton/detaildiag.h
- src/skeleton/dragnote.cpp
- src/skeleton/dragnote.h
- src/skeleton/edittreeview.cpp
- src/skeleton/edittreeview.h
- src/skeleton/editview.cpp
- src/skeleton/editview.h
- src/skeleton/lockable.h
- src/skeleton/login.cpp
- src/skeleton/login.h
- src/skeleton/menubutton.cpp
- src/skeleton/menubutton.h
- src/skeleton/tabswitchmenu.cpp
- src/skeleton/tabswitchmenu.h
- src/skeleton/toolbar.cpp
- src/skeleton/toolbar.h
- src/skeleton/treeviewbase.cpp
- src/skeleton/treeviewbase.h
- src/skeleton/undobuffer.cpp
- src/skeleton/undobuffer.h
Fix member initialization to use default member initializer and constructor. Fill no-specific initial values with zeroes. Remove
unnecessary include directives.
> skeleton: Fix member initialization

- .github/workflows/ccpp.yml
- test/meson.build
Fixes #613
Since Meson 0.57, `test` subcommand will [only rebuild test program][1]. In JDim, this causes build error because generating rule of the test program does not include `buildinfo.h`. Therefore, fix the rule to include the header file.
Fix GitHub Actions CI settings to build the executable file explicitly.
Error message
```
In file included from ../src/environment.cpp:10:
../src/jdversion.h:10:10: fatal error: buildinfo.h: No such file or directory
10 | #include "buildinfo.h"
|          ^~~~~~~~~~~~~
```
[1]: https://mesonbuild.com/Release-notes-for-0-57-0.html#meson-test-only-rebuilds-test-dependencies
> Fix build error for meson 0.57

- configure.ac
- meson.build
- src/jdlib/misctime.cpp
- test/gtest_jdlib_misctime.cpp
Fixes #611 
Remove conditional compilation from the function that parses datetime string to `time_t`. Change input string requirement to [RFC 7232][3] [IMF-fixdate][4] (used for HTTP request) to limit timezone only to GMT.
New format: `"%a, %d %b %Y %T GMT"`
The conditional compilation had been necessary, because the function had platform-specific code that parses timezone name by `strptime()` (POSIX does not provide [`%Z` format][1]).
[1]: https://pubs.opengroup.org/onlinepubs/9699919799/functions/strptime.html
[3]: https://tools.ietf.org/html/rfc7232#section-2.2
[4]: https://tools.ietf.org/html/rfc7231#section-7.1.1.1
Tests assume that `time_t` epoch (i.e. `0`) is Unix epoch (1970-01-01T00:00:00 UTC), however [C/C++ standards have not defined it][2].
[2]: …
> Update MISC::datetotime() to remove conditional compilation

- src/jdlib/misctime.cpp
- src/jdlib/misctime.h
使われてない`gettimeofday()`の秒を文字列で取得する関数を削除します。
> Remove unused MISC::get_sec_str()

- src/login2ch.cpp
- src/login2ch.h
- src/loginbe.cpp
- src/loginbe.h
`malloc`/`free`で確保しているバッファを`std::string`で置き換える。
メモリは自動的に確保されるが挙動の変化を抑えるため修正前と同じ量を予約しておく。
関連のpull request: #159
> Replace char buffer with std::string for CORE::Login2ch/Be

- src/dbtree/board2ch.cpp
- src/dbtree/board2chcompati.cpp
- src/dbtree/board2chcompati.h
- src/dbtree/boardbase.cpp
- src/dbtree/boardbase.h
- src/dbtree/boardjbbs.cpp
- src/dbtree/nodetree2chcompati.cpp
- src/dbtree/nodetree2chcompati.h
- src/dbtree/nodetreejbbs.cpp
- src/dbtree/nodetreejbbs.h
- src/dbtree/nodetreemachi.cpp
- src/dbtree/nodetreemachi.h
- src/dbtree/root.cpp
- src/dbtree/root.h
- スマートポインターの生成にヘルパー関数を使いnewをコードから取り除きます。
- クラスメンバーをスマートポインターに更新してnew/deleteによるメモリ割り当てを整理します。
> dbtree: Use std::unique_ptr instead of new/delete

- src/message/messageadmin.cpp
- src/message/messageadmin.h
- src/message/messageviewbase.cpp
- src/message/messageviewbase.h
- src/message/post.cpp
- src/message/post.h
クラスメンバーをスマートポインターに更新してnew/deleteによるメモリ割り当てを整理します。
> message: Use std::unique_ptr instead of new/delete

- src/searchmanager.cpp
- src/searchmanager.h
クラスメンバーをスマートポインターに更新してnew/deleteによるメモリ割り当てを整理します。
> Search_Manager: Use std::unique_ptr instead of new/delete

- src/article/articleviewbase.cpp
- src/bbslist/bbslistviewbase.cpp
- src/board/boardviewbase.cpp
- src/dbimg/imgroot.cpp
- src/history/historysubmenu.cpp
- src/image/imageviewbase.cpp
- src/menuslots.cpp
- src/prefdiagfactory.cpp
- src/prefdiagfactory.h
- src/setupwizard.cpp
- src/skeleton/toolbar.cpp
関数の戻り値をスマートポインターに更新してnew/deleteによるメモリ割り当てを整理します。
> PrefDiagFactory: Use std::unique_ptr instead of new/delete

- src/dbimg/delimgcachediag.cpp
- src/main.cpp
- src/message/logitem.h
- src/message/logmanager.cpp
- src/message/messageviewbase.cpp
[非推奨][1]とされている`gettimeofday()`のかわりに`std::time()`を使います。[リファレンス][1]には`clock_gettime()`を使用すると書いてありますがコンマ以下の時間(`tv_usec`)を使っていないためシンプルな`std::time()`を選択します。
[1]: https://pubs.opengroup.org/onlinepubs/9699919799/functions/gettimeofday.html
> Use std::time() instead of gettimeofday()

- src/dbtree/boardbase.cpp
- src/dbtree/boardbase.h
コンマ以下の時間(`tv_usec`)を使用していないため`struct timeval`のクラスメンバーを`std::time_t`に交換します。
> BoardBase: Use std::time_t instead of struct timeval

- src/article/drawareabase.cpp
- src/article/drawareabase.h
非推奨とされている[`gettimeofday()`][1]のかわりに`std::chrono`を使います。
経過時間を測定するため標準で提供されているクロックのうち[monotonicなタイプ][2]を選択します。
[1]: https://pubs.opengroup.org/onlinepubs/9699919799/functions/gettimeofday.html
[2]: https://en.cppreference.com/w/cpp/chrono/steady_clock
> DrawAreaBase: Use std::chrono::steady_clock instead of gettimeofday()

- src/cache.cpp
- src/jdlib/loader.cpp
- src/jdlib/misctime.cpp
- src/jdlib/misctime.h
非推奨とされている[`gettimeofday()`][1]のかわりに`std::chrono`を使います。
経過時間を測定するため標準で提供されているクロックのうち[monotonicなタイプ][2]を選択します。
includeディレクティブの変更でコンパイルエラーが発生したためロジックを変更していないソースファイルのヘッダーを整理しています。
[1]: https://pubs.opengroup.org/onlinepubs/9699919799/functions/gettimeofday.html
[2]: https://en.cppreference.com/w/cpp/chrono/steady_clock
> misctime: Use std::chrono::steady_clock instead of gettimeofday()

- src/jdlib/misctime.h
FreeBSD 12.2でコンパイルエラーが発生したため修正します。
コンパイラのレポート
```
../src/jdlib/misctime.cpp:28:17: error: member access into incomplete type 'const struct timeval'
sstr << ( tv.tv_sec >> 16 ) << " " << ( tv.tv_sec & 0xffff ) << " " << tv.tv_usec;
^
../src/jdlib/misctime.h:28:44: note: forward declaration of 'MISC::timeval'
std::string timevaltostr( const struct timeval& tv );
^
```
https://next2ch.net/linux/1613035222/99
> Fix compile error on FreeBSD

- src/dbtree/articlebase.cpp
- src/dbtree/articlebase.h
Fixes #625 
小数点以下の時間を使用していないため`struct timeval`型のクラスメンバーを`std::time_t`で置き換えます。
micro秒部分(`tv_usec`)の解析が省略されて固定値(`0`)で処理されるため一部の未使用データが失われますがプログラムに
影響はありません。
非推奨とされている[`gettimeofday()`][1]のかわりに`std::time()`を使います。
[1]: https://pubs.opengroup.org/onlinepubs/9699919799/functions/gettimeofday.html
> ArticleBase: Use std::time_t instead of struct timeval

- src/article/articleadmin.cpp
- src/article/articleadmin.h
- src/article/articleviewbase.cpp
- src/article/articleviewbase.h
- src/article/drawareabase.cpp
- src/article/drawareabase.h
- src/article/layouttree.cpp
- src/article/layouttree.h
> article: Use std::unique_ptr instead of new/delete

- src/winmain.cpp
- src/winmain.h
> JDWinMain: Use std::unique_ptr instead of new/delete

- src/core.cpp
- src/core.h
クラスのメンバーをスマートポインターに更新してnew/deleteによる
メモリ割り当てを整理します。
> Core: Use std::unique_ptr instead of new/delete

- src/bbslist/bbslistadmin.cpp
- src/bbslist/bbslistadmin.h
- src/bbslist/bbslistviewbase.cpp
- src/bbslist/bbslistviewbase.h
- src/bbslist/selectdialog.cpp
- src/bbslist/selectdialog.h
> bbslist: Use std::unique_ptr instead of new/delete

- src/board/boardadmin.cpp
- src/board/boardadmin.h
- src/board/preference.cpp
- src/board/preference.h
> board: Use std::unique_ptr instead of new/delete

- src/control/buttonpref.cpp
- src/control/buttonpref.h
- src/control/keypref.cpp
- src/control/keypref.h
- src/control/mousekeypref.cpp
- src/control/mousekeypref.h
- src/control/mousepref.cpp
- src/control/mousepref.h
メンバー関数の戻り値をスマートポインターに取り替えてnew/deleteを整理します。
> MouseKeyPref: Use std::unique_ptr instead of new/delete

- src/history/historymanager.cpp
- src/history/historymanager.h
クラスのメンバーをスマートポインターに取り替えてnew/deleteを削除します。
> HistoryManager: Use std::unique_ptr instead of new/delete

- src/image/imageviewpopup.cpp
- src/image/imageviewpopup.h
子ウィジェットを追加削除する処理があるため`Gtk::manage()`によるメモリ管理ではdeleteを整理できません。
> ImageViewPopup: Use std::unique_ptr instead of new/delete

- src/message/messageviewbase.cpp
- src/message/messageviewbase.h
> MessageViewBase: Use std::unique_ptr instead of new/delete

- src/skeleton/admin.cpp
- src/skeleton/admin.h
- src/skeleton/detaildiag.cpp
- src/skeleton/detaildiag.h
- src/skeleton/dragnote.cpp
- src/skeleton/dragnote.h
- src/skeleton/dragtreeview.cpp
- src/skeleton/dragtreeview.h
- src/skeleton/editview.cpp
- src/skeleton/editview.h
- src/skeleton/loadable.cpp
- src/skeleton/loadable.h
> skeleton: Use std::unique_ptr instead of new/delete

- src/bbslist/editlistwin.cpp
> EditListWin: Set window display position to center

- src/skeleton/menubutton.cpp
- src/skeleton/menubutton.h
- src/skeleton/toolmenubutton.cpp
- src/skeleton/toolmenubutton.h
> skeleton: Use delegating constructors instead of setup function

- src/jdlib/miscutil.cpp
- src/message/post.cpp
- src/skeleton/textloader.cpp
ローカル変数のiconvオブジェクトをメモリの動的割り当てから静的割り当てに変更します。
> Use static allocation for local iconv var instead of new/delete

- src/config/aboutconfig.cpp
- src/config/configitems.cpp
- src/dbimg/imgroot.cpp
- src/main.cpp
ローカル変数のdialogオブジェクトをメモリの動的割り当てから静的割り当てに変更します。
> Use static allocation for local dialog var instead of new/delete

- src/skeleton/window.cpp
- src/skeleton/window.h
ダミーウインドウのかわりに`Gtk::Window::unset_transient_for()`([gtkmm 2.20から追加][1])を使ってtransient設定を解除します。
[1]: https://developer.gnome.org/gtkmm/3.24/classGtk_1_1Window.html#a8765c60eaa06575d86d877cd5ba75d6d
> JDWindow: remove dummy window for transient setting

- README.md
- docs/manual/start.md
- src/skeleton/window.cpp
Fixes #645 
ウインドウ表示の画像ビューでフォーカスによる展開縮小が正常に動作しない不具合を修正します。
- 展開: 画像ビューをフォーカスしてもウインドウが展開しない
- 縮小: ウインドウが完全に折り畳まれず画像の上部が表示されたままになる
Wayland環境では画像ウインドウの展開縮小が正常に動作せず、フォーカスが外れたときウインドウの幅が広がります。
埋め込み表示またはXWaylandでは問題ありません。
> JDWindow: Fix expanding image view window by focus-in

- src/image/imageadmin.cpp
- src/message/messageadmin.cpp
- src/skeleton/admin.cpp
- src/skeleton/admin.h
- src/skeleton/menubutton.cpp
- src/skeleton/menubutton.h
- src/skeleton/popupwin.cpp
- src/skeleton/popupwin.h
- src/skeleton/tablabel.cpp
- src/skeleton/tablabel.h
- src/skeleton/window.cpp
- src/skeleton/window.h
> skeleton: Use std::unique_ptr instead of new/delete part2

- src/dbimg/imgroot.cpp
- src/dbimg/imgroot.h
クラスのメンバーをスマートポインターに更新してnew/deleteによるメモリ割り当てを整理します。また、未使用のメンバー関数を整理します。
> ImgRoot: Use std::unique_ptr instead of new/delete

- src/history/viewhistory.cpp
- src/history/viewhistory.h
> ViewHistory: Use std::unique_ptr instead of new/delete

- src/compmanager.cpp
- src/compmanager.h
std::vectorの要素型をポインターから実値(value)に変更してメモリの割り当てを単純化します。
> Completion_Manager: Simplify memory allocation for std::vector elements

- src/message/logmanager.cpp
- src/message/logmanager.h
`std::list`の要素をポインターから実値に変更してメモリ割り当てとソースコードを整理します。
C++17から[不完全型を`std::list`に指定できる][1]ようになりました。
[1]: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4371.html
> Log_Manager: Use incomplete type support for std::list

- src/history/historymanager.cpp
- src/history/historymanager.h
- src/history/viewhistory.h
`std::list`の要素をポインターから実値に変更してメモリ割り当てとソースコードを整理します。
C++17から[不完全型を`std::list`に指定できる][1]ようになりました。
関連のpull request: #653
[1]: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4371.html
> History_Manager: Use incomplete type support for std::list

- src/article/drawareabase.cpp
- src/article/drawareabase.h
`std::list`の要素をポインターから実値に変更してメモリ割り当てとソースコードを整理します。
C++17から[不完全型を`std::list`に指定できる][1]ようになりました。
関連のpull request: #653 
[1]: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4371.html
> DrawAreaBase: Use incomplete type support for std::list

- src/skeleton/toolbar.cpp
- src/skeleton/window.cpp
ツールバーのラベルのスタイル切り替えをcssの再読み込みからcss class名の切り替えに変更します。
ステータスバーのラベルのスタイル切り替えをcssの再読み込みからcss class名の切り替えに変更します。
> Switch css class name instead of reload css

- src/skeleton/compentry.cpp
- src/skeleton/popupwinbase.cpp
- src/skeleton/popupwinbase.h
ポップアップウインドウの境界線を描画するかわりにcss設定を使います。
> PopupWinBase: Uss css setting instead of drawing border lines

- src/skeleton/dragnote.cpp
- src/skeleton/tabnote.cpp
`Gtk::Notebook`に配置されてるページを取り除くときdeleteされるように`Gtk::manage()`によるメモリ管理を使います。
`Gtk::Notebook`に配置されてるタブを取り除くときdeleteされるように`Gtk::manage()`によるメモリ管理を使います。
> notebook: Use Gtk::manage() instead of operator delete

- src/dbtree/boardbase.cpp
- src/dbtree/boardbase.h
メンバー変数の型をポインターから実値に変更してメモリの動的割り当てを回避します。
また、[範囲ベースfor文の制限緩和][*]を利用してループを整理します。
[*]: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0184r0.html
> BoardBase: Use concrete type member instead of dynamic allocation

- src/dbtree/articlehash.cpp
- src/dbtree/articlehash.h
- src/dbtree/board2ch.cpp
- src/dbtree/board2chcompati.cpp
- src/dbtree/boardbase.cpp
- src/dbtree/boardbase.h
- src/dbtree/boardjbbs.cpp
- src/dbtree/boardlocal.cpp
- src/dbtree/boardmachi.cpp
> ArticleHash: Use std::unique_ptr instead of raw pointer

- src/image/imageadmin.cpp
- src/image/imageadmin.h
> ImageAdmin: Use std::unique_ptr instead of raw pointer

- src/dbtree/root.cpp
- src/dbtree/root.h
> Root: Use std::unique_ptr instead of raw pointer

- src/dbtree/boardfactory.cpp
- src/dbtree/boardfactory.h
- src/dbtree/root.cpp
メンバー関数の戻り値をスマートポインターに更新してnew/deleteによるメモリ割り当てを整理します。
> BoardFactory: Use std::unique_ptr instead of raw pointer

- src/config/aboutconfig.cpp
- src/config/configitems.cpp
- src/config/configitems.h
- src/config/defaultconf.h
- src/config/globalconf.cpp
- src/config/globalconf.h
- src/environment.cpp
- src/environment.h
- src/skeleton/aboutdiag.cpp
- src/skeleton/prefdiag.cpp
Client-Side Decoration(CSD)の設定を追加します。
デスクトップ(ウインドウマネージャ)が制御していたタイトルバーをアプリケーションの領域として使う概念です。
CSDはデスクトップ環境との関係が強いためabout:configに項目を追加します。
- 0: CSDを使わない
- 1: CSDを使う
- 2: デスクトップに合わせる (デフォルト)
「デスクトップに合わせる」にするとCSDが導入されたデスクトップ環境では「使う」になります。
ダイアログボックスにCSDサポートを追加します。CSDが使われる条件は下記の2通りです。
- about:config「Client-Side Decorationを使うか」の値が`1`(使う)
GtkSettings `gtk-dialogs-use-header`の値が`true`
- about:config「Client-Side Decorationを使うか」の値が`2`(合わせる)
デスクトップ環境がGNOME
GtkSettings `gtk-dialogs-use-header`の値が`true`
関連のissue: #602
> dialog: Add Client-Side Decoration support

- src/bbslist/bbslistviewbase.cpp
- src/linkfiltermanager.cpp
- src/skeleton/edittreeview.cpp
- src/xml/document.cpp
- src/xml/dom.h
子要素数を取得するメンバー関数を実装します。
これまでは子要素のリストを複製してサイズを取得していましたが直接取得できるようにします。
また、`childNodes().size()`を呼び出していた箇所を`size()`に修正します。
> Dom: Implement member function size()

- src/aamanager.cpp
- src/bbslist/bbslistview.cpp
- src/bbslist/bbslistviewbase.cpp
- src/dbtree/root.cpp
- src/history/historymanager.cpp
- src/linkfiltermanager.cpp
- src/replacestrmanager.cpp
- src/usrcmdmanager.cpp
- src/xml/document.cpp
- src/xml/document.h
- src/xml/dom.cpp
- src/xml/dom.h
- test/gtest_xml_dom.cpp
- 使われてないメンバー関数のdelete宣言を取り除いてヘッダーを整理します。
- `insertBefore()`の機能をフルに使っていなかったためシンプルにした関数に交換します。
新しい`emplace_front()`は[C++ standard container][a]のAPIを参考にしていますが同等の機能ではありません。
- 目的に応じてconst/non-const版を使い分けられるように両バージョンのメンバー関数を用意します。
- 子要素を走査するためのメンバー関数`begin()`と`end()`を実装します。また、実装した関数を利用してクライアントコードも更新します。これまでは子要素のリストを複製して走査を行っていましたが直接イテレートできるようにします。また、使われなくなった`childNodes()`を削除します。
[a]: https://en.cppreference.com/w/cpp/container
> Refactor Dom part3

- src/history/historysubmenu.cpp
- src/skeleton/admin.cpp
- src/skeleton/admin.h
- src/skeleton/menubutton.cpp
- src/skeleton/menubutton.h
- src/usrcmdpref.cpp
- GTK3.22から廃止予定になった`Gtk::Menu::popup()`のかわりに`popup_at_poitner()`を使います。
この修正でメニューを表示したときに出る警告も表示されなくなります。
非推奨シンボルを無効化したときのコンパイルエラー
```
../src/history/historysubmenu.cpp:213:21: error: 'class Gtk::Menu' has no member named 'popup'
213 |         m_popupmenu.popup( 0, gtk_get_current_event_time() );
|                     ^~~~~
../src/skeleton/admin.cpp:2211:20: error: 'class Gtk::Menu' has no member named 'popup'
2211 |         popupmenu->popup( 0, gtk_get_current_event_time() );
|                    ^~~~~
../src/usrcmdpref.cpp:271:11: error: 'class Gtk::Menu' has no member named 'popup'
271 |     menu->popup( 0, gtk_get_current_event_time() );
|           ^~~~~
```
- GTK3.22から廃止予定になった`Gtk::Menu::popup()`のかわりに`popup_at_widget()`を使います。
この修正でメニューを表示したときに出る警告も表示されなくなります。
非推奨シンボルを無効化したときのコンパイルエラー …
> Replace Gtk::Menu::popup() with new API

- src/message/post.cpp
HTMLソースのプリントはデバッグに移動しエラーメッセージを出力するように修正します。
> Post: Fix error message for HTTP response

- src/skeleton/dragnote.cpp
Closes #675
Wayland環境でタブをドラッグしたときドロップ位置を示す矢印マークが遠く離れた位置に表示される不具合を修正します。
> DragableNoteBook: Fix DnD destination mark position on Wayland

- src/jdlib/loader.cpp
**このPRはアイデア検証用でありマージしません。**
HTTPリクエストヘッダーに Accept, Accept-Language, DNT, Upgrade-Insecure-Requestsを追加します。
https://mao.5ch.net/test/read.cgi/linux/1615781919/419
https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/Accept
https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/Accept-Language
https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/DNT
https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/Upgrade-Insecure-Requests
---
edit(2021-04-19): URLのユーザー名を訂正
```
git clone -b idea-fix-http-request --depth 1 https://github.com/ma8ma/JDim.git temp
cd temp
meson debugdir
meson compile -C debugdir
./debugdir/src/jdim
cd ../
rm -rf temp
```
※ git pullなどでmasterブランチを更新してから行うことを推奨します。
```
git chechout master
git pull
curl -L https://github.com/JDimproved/JDim/pull/676.patch | patch -p1
meson …
```
> Add several missing headers to HTTP request

- src/config/defaultconf.h
Fixes #679
初期設定のスレタイ検索サイト https://ff5ch.syoboi.jp の検索結果が2021年4月中旬から変更されてスレッド抽出に失敗するようになりました。
そのためabout:config「スレタイ検索用のアドレス」と「スレタイ検索時にアドレスとスレタイを取得する正規表現」のデフォルト設定を更新します。
```
^(?=[^\t\n]+\t[^\t\n]+\t([^\t\n]+))([^\t\n]+)\t([^\t\n]+)
```
- まず行頭`^`をマッチさせる
- 次にlook ahead`(?=...)`を使って3列目をグループ1にキャプチャ
- そのあと改めて行頭から1列目、2列目をグループ2、グループ3にキャプチャ
https://mao.5ch.net/test/read.cgi/linux/1615781919/451
https://mao.5ch.net/test/read.cgi/linux/1615781919/482-484
> Fix initial settings for thread title search (2021-04)

- src/aamanager.cpp
- src/aamanager.h
`id2shortcut()`は[]アクセスでデフォルト値を代入する可能性があるためそのままnon-constにします。
> AAManager: Add const qualifier to member function

- src/article/toolbar.h
クラスのメンバー関数のうち宣言だけで定義がないものを削除します。
> ArticleToolBar: Remove not implemented member functions

- src/bbslist/bbslistviewbase.cpp
- src/bbslist/bbslistviewbase.h
> BBSListViewBase: Add const qualifier to member function

- src/bbslist/selectdialog.cpp
- src/bbslist/selectdialog.h
> SelectListDialog: Add const qualifier to member function

- src/board/boardviewbase.h
クラスのメンバー関数のうち宣言だけで定義がないものを削除します。
関連のpull request: #687
> BoardViewBase: Remove not implemented member function

- src/article/layouttree.cpp
Fixes #681
「あぼ〜ん」を表示するレイアウトデータにフォントIDを設定します。
レス番号と名前部分の「あぼ〜ん」はメール欄、本文の「あぼ〜ん」はデフォルトフォントになります。
これまで未設定だったため「あぼ〜ん」のレスで予期しない表示(1)が発生していました。
(1): メール欄をマウスクリックするとスレビュー画面上部にある「あぼ〜ん」されたレスのフォントがメール欄に変わってしまう
> LayoutTree: Set font IDs for abone layout nodes

- src/control/mousekeyconf.cpp
- src/control/mousekeyconf.h
> MouseKeyConf: Add const qualifier to member function part1

- src/control/mouseconfig.cpp
- src/control/mouseconfig.h
- src/control/mousekeyconf.cpp
- src/control/mousekeyconf.h
- `MouseKeyConf::get_str_motions()`
- `MouseKeyConf::get_default_motions()`
> MouseKeyConf: Add const qualifier to member function part2

- src/control/keyconfig.cpp
- src/control/keyconfig.h
> KeyConfig: Add const qualifier to member function

- src/control/mousekeypref.cpp
- src/control/mousekeypref.h
> InputDiag: Add const qualifier to member function

- src/dbimg/delimgcachediag.cpp
- src/dbimg/delimgcachediag.h
メンバー変数やメンバー関数を使用しないメンバー関数をstaicにして保守性を向上させます。
> DelImgCacheDiag: Add static keyword to member function

- src/dbimg/img.cpp
- src/dbimg/img.h
> Img: Add const qualifier to member function

- src/dbimg/imgroot.cpp
- src/dbimg/imgroot.h
> ImgRoot: Add const qualifier to member function

- src/dbtree/frontloader.cpp
- src/dbtree/frontloader.h
- src/dbtree/ruleloader.cpp
- src/dbtree/ruleloader.h
- src/dbtree/settingloader.cpp
- src/dbtree/settingloader.h
- src/searchloader.cpp
- src/searchloader.h
- src/skeleton/textloader.h
> TextLoader: Add const qualifier to member function

- src/iomonitor.h
> IOMonitor: Add const qualifier to member function

- src/jdlib/confloader.cpp
- src/jdlib/confloader.h
- src/jdlib/loader.cpp
- src/jdlib/loader.h
- src/jdlib/ssl.h
- ConfLoader: Add const qualifier to member function
- Loader: Add const qualifier to member function
- JDSSL: Add const qualifier to member function
> jdlib: Add const qualifier member function

- src/linkfilterpref.h
- src/urlreplacemanager.cpp
- src/urlreplacemanager.h
- src/usrcmdmanager.cpp
- src/usrcmdmanager.h
- src/usrcmdpref.h
- LinkFilterDiag: Add const qualifier to member function
- Urlreplace_Manager: Add const qualifier to member function
- Usrcmd_Manager: Add const qualifier to member function
- UsrCmdDiag: Add const qualifier to member function
> filtering: Add const qualifier member function

- src/dbtree/articlehash.cpp
- src/dbtree/articlehash.h
> ArticleHash: Add const qualifier to member function

- src/jdlib/miscgtk.cpp
- src/jdlib/miscgtk.h
const型で必要な操作ができる引数にconst修飾子を追加します。
> MISC::get_pointer_at_window(): Add const qualifier to argument

- src/image/imagewin.cpp
- src/image/imagewin.h
- src/message/messagewin.cpp
- src/message/messagewin.h
- src/skeleton/window.cpp
- src/skeleton/window.h
- src/winmain.cpp
- src/winmain.h
> JDWindow: Add const qualifier to member function

- src/jdlib/loader.cpp
HTTPリクエストから`DNT: 1`を取り除きます。
トラッキングを拒否すると書き込みに失敗する掲示板があると報告がありました。
修正にあたり不具合報告や動作検証をしていただきありがとうございました。
https://mao.5ch.net/test/read.cgi/linux/1615781919/539
https://mao.5ch.net/test/read.cgi/linux/1615781919/585-589n
> Loader: Get rid of DNT: 1 from HTTP request header

- src/skeleton/aamenu.cpp
- src/skeleton/aamenu.h
- src/skeleton/compentry.cpp
- src/skeleton/compentry.h
- src/skeleton/edittreeview.cpp
- src/skeleton/edittreeview.h
- src/skeleton/iconpopup.h
- src/skeleton/label_entry.cpp
- src/skeleton/label_entry.h
- src/skeleton/selectitempref.cpp
- src/skeleton/selectitempref.h
- src/skeleton/tablabel.cpp
- src/skeleton/tablabel.h
- src/skeleton/toolbar.cpp
- src/skeleton/toolbar.h
- src/skeleton/view.cpp
- src/skeleton/view.h
- AAMenu: Add const qualifier to member function
- EditTreeView: Add const qualifier to member function
- IconPopup: Add const qualifier to member function
- LabelEntry: Add const qualifier to member function
- SelectItemPref: Add const qualifier to member function
- TabLabel: Add const qualifier to member function
- SKELETON::ToolBar: Add const qualifier to member function
- SKELETON::View: Add const qualifier to member function
- CompletionEntry: Add const qualifier to member function
> skeleton: Add const qualifier member function part1

- src/message/messageadmin.cpp
Fixes #714
埋め込み表示中の書き込みビューに入力したテキストをビュー左端からマウスで選択しようとするとマウスカーソルがペインの幅調節に変わり選択ができない不具合を修正します。
入力欄の周りに余白が追加されるGTKテーマだと不具合は起きませんがGTKのデフォルトテーマAdwaitaで発生していました。
https://mao.5ch.net/test/read.cgi/linux/1594134444/621-623n
> MessageAdmin: Fix unexpected mouse cursor on text selection

- src/skeleton/dragnote.cpp
- src/skeleton/dragnote.h
> DragableNoteBook: Add const qualifier to member function

- src/skeleton/panecontrol.h
> PaneControl: Add const qualifier to member function

- src/skeleton/toolbar.cpp
- src/skeleton/toolbar.h
使われてないツールバーの子要素があるか真偽値を返す関数`is_empty()`を削除します。
> SKELETON::ToolBar: Remove unused member function

- src/message/messageadmin.cpp
- src/message/messageadmin.h
- src/message/messageviewbase.cpp
- src/message/messageviewbase.h
- src/message/toolbar.cpp
- src/message/toolbar.h
- MessageToolBar: Add const qualifier to member function
- MessageViewBase: Add const qualifier to member function
- MessageAdmin: Add const qualifier to member function 
> message: Add const qualifier member function

- .github/workflows/ccpp.yml
- configure.ac
- meson.build
- src/jdlib/misctrip.cpp
`crypt`関数のスレッドセーフなバージョンが使える環境では`crypt_r`を使うように変更します。
- <https://linux.die.net/man/3/crypt_r>
- <https://www.freebsd.org/cgi/man.cgi?query=crypt_r&apropos=0&sektion=0&manpath=FreeBSD+12-current&arch=default&format=html>
> misctrip: Add configure check for thread-safe crypt_r

- src/dbtree/nodetreebase.h
例外を投げないメンバー関数に`noexcept`をつけます。
> NodeTreeBase: Add noexcept qualifier to member function

- src/dbtree/nodetreebase.h
> NodeTreeBase: Add delete declaration to unimplemented member function

- src/dbtree/nodetreebase.cpp
- src/dbtree/nodetreebase.h
- `NodeTreeBase::empty()`
- `NodeTreeBase::get_res_number()`
- `NodeTreeBase::check_anchor()`
- `NodeTreeBase::check_link_impl()`
- `NodeTreeBase::check_link()`
> NodeTreeBase: Add const qualifier to member function part1

- src/bbslist/bbslistviewbase.cpp
- src/bbslist/bbslistviewbase.h
メンバー関数の引数に`const`をつけられるとcppcheckに指摘されたため修正します。
cppcheckのレポート
```
src/bbslist/bbslistviewbase.cpp:2140:62: style: Parameter 'it' can be declared with const [constParameter]
bool BBSListViewBase::is_etcboard( Gtk::TreeModel::iterator& it )
^
```
> BBSListViewBase: Add const qualifier to member function argument

- src/dbtree/nodetreebase.cpp
- src/dbtree/nodetreebase.h
- `NodeTreeBase::res_header()`
constメンバー関数の実装は重複を避ける手法を使います。
https://stackoverflow.com/questions/123758/123995#123995
> NodeTreeBase: Add const qualifier to member function part2

- src/dbtree/nodetreebase.cpp
- src/dbtree/nodetreebase.h
- `NodeTreeBase::get_name()`
- `NodeTreeBase::get_abone()`
- `NodeTreeBase::get_res_str()`
- `NodeTreeBase::get_id_name()`
- `NodeTreeBase::get_urls()`
- `NodeTreeBase::get_res_reference()`
> NodeTreeBase: Add const qualifier to member function part3

- src/dbtree/nodetreebase.cpp
- src/dbtree/nodetreebase.h
- `NodeTreeBase::get_res_with_url()`
- `NodeTreeBase::get_id_num_name()`
- `NodeTreeBase::get_highly_referened_res()`
> NodeTreeBase: Add const qualifier to member function part4

- src/dbtree/nodetreebase.cpp
- src/dbtree/nodetreebase.h
- `NodeTreeBase::get_res_str_name()`
- `NodeTreeBase::get_num_name()`
- `NodeTreeBase::get_res_name()`
- `NodeTreeBase::get_time_str()`
- `NodeTreeBase::get_res_query()`
- `NodeTreeBase::get_res_id_name()`
- `NodeTreeBase::is_refer_posted()`
> NodeTreeBase: Add const qualifier to member function part5

- src/dbimg/img.cpp
- src/dbimg/imginterface.h
- src/dbimg/imgroot.cpp
- src/dbimg/imgroot.h
- src/image/imageviewbase.cpp
- src/image/preference.cpp
Fixes #727 
起動時にWebPに対応しているか確認してサポートしているときは`.webp`で終わるURLを画像リンクとして扱います。
NOTE:   GTKにはGdkPixbufのWebPサポートが含まれていません。WebPを表示するには[サードパーティライブラリ][2]をインストールする必要があります。
[2]: https://github.com/aruiz/webp-pixbuf-loader
起動時にAVIFに対応しているか確認してサポートしているときは`.avif`で終わるURLを画像リンクとして扱います。
NOTE:  GTKにはGdkPixbufのAVIFサポートが含まれていません。AVIFを表示するにはGdkPixbufを有効にした[libavif][1]をインストールする必要があります。
libavifのパッケージが導入されたLinuxディストロ
- [Debian](https://tracker.debian.org/pkg/libavif)
- [Fedora](https://src.fedoraproject.org/rpms/libavif)
- [Ubuntu](https://launchpad.net/ubuntu/+source/libavif)
[1]: https://github.com/AOMediaCodec/libavif
関数が処理できるサイズより小さい場合は関数呼び出しを行わず判定しません。
> Add WebP and AVIF support

- src/dbtree/article2ch.cpp
- src/dbtree/article2ch.h
- src/dbtree/article2chcompati.cpp
- src/dbtree/article2chcompati.h
- src/dbtree/articlebase.h
- src/dbtree/articlejbbs.cpp
- src/dbtree/articlejbbs.h
- src/dbtree/articlemachi.cpp
- src/dbtree/articlemachi.h
> ArticleBase: Add const qualifier to member function part1

- src/dbtree/article2ch.cpp
- src/dbtree/article2ch.h
- src/dbtree/article2chcompati.cpp
- src/dbtree/article2chcompati.h
- src/dbtree/articlebase.h
- src/dbtree/articlejbbs.cpp
- src/dbtree/articlejbbs.h
- src/dbtree/articlemachi.cpp
- src/dbtree/articlemachi.h
- `ArticleBase::url_subbbscgi()`
> ArticleBase: Add const qualifier to member function part2

- src/dbtree/articlebase.cpp
- src/dbtree/articlebase.h
- `ArticleBase::get_num_bookmark()`
- `ArticleBase::get_num_posted()`
> ArticleBase: Add const qualifier to member function part3

- src/dbtree/articlebase.h
- `ArticleBase::get_abone_list_id()`
- `ArticleBase::get_abone_list_name()`
- `ArticleBase::get_abone_list_word()`
- `ArticleBase::get_abone_list_regex()`
> ArticleBase: Add const qualifier to member function part4

- src/dbtree/articlebase.cpp
- src/dbtree/articlebase.h
- `ArticleBase::get_abone_chain()`
- `ArticleBase::get_abone_transparent()`
- `ArticleBase::enable_load()`
- `ArticleBase::is_finished()`
- `ArticleBase::get_org_url()`
> ArticleBase: Add const qualifier to member function part5

- src/dbtree/articlebase.cpp
- src/dbtree/articlebase.h
- `ArticleBase::get_date_modified()`
- `ArticleBase::get_hour()`
- `ArticleBase::get_time_modified()`
- `ArticleBase::get_access_time_str()`
- `ArticleBase::get_speed()`
> ArticleBase: Add const qualifier to member function part6

- src/dbtree/article2ch.cpp
- src/dbtree/article2ch.h
- src/dbtree/articlebase.cpp
- src/dbtree/articlebase.h
- src/dbtree/articlejbbs.h
- src/dbtree/articlelocal.cpp
- src/dbtree/articlelocal.h
- src/dbtree/articlemachi.cpp
- src/dbtree/articlemachi.h
- `ArticleBase::enable_check_update()`
- `ArticleBase::equal()`
- `ArticleBase::is_load_olddat()`
> ArticleBase: Add const qualifier to member function part7

- src/dbimg/img.cpp
- src/jdlib/loader.cpp
- src/jdlib/loaderdata.h
HTTPリクエストの`Accept`ヘッダーに`image/webp`があるとWebP対応の有無に関係なくWebPデータが送られてきて画像が表示できない問題がありました。
そのため画像をリクエストするときは`Accept`から`image/webp`を外します。画像以外のリクエストは変更しません。
背景
効率がよい画像形式を受け入れる(Accept)クライアントに対してURLの拡張子と異なる画像形式でデータを送信するサイトがあります。
現状の実装では拡張子の偽装チェックが誤検知するためコンテントネゴシエーションによる画像の軽量化は利用しません。
https://next2ch.net/test/read.cgi/linux/1613035222/273-280
関連のissue: #727
関連のpull request: #736
> Img: Get rid of image/webp from Accept header for requesting image

- src/skeleton/toolbar.cpp
- src/skeleton/toolbar.h
ツールバーにある閉じるボタンを押すと再びツールバーを表示したときボタンがフォーカスされたままになっている問題があり、これを回避する修正で廃止予定の機能が使われています。
このため修正を更新してGTK4で廃止される`Gtk::StyleContext::get_border_color()`と`Gtk::StyleContext::get_background_color()`を使わない方法に変更します。
コンパイラのレポート
```
../src/skeleton/toolbar.cpp:996:45: error: 'class Gtk::StyleContext' has no member named 'get_border_color'; did you mean 'get_border'?
1036 |     const Gdk::RGBA border_color = context->get_border_color( Gtk::STATE_FLAG_NORMAL );
|                                             ^~~~~~~~~~~~~~~~
|                                             get_border
../src/skeleton/toolbar.cpp:997:41: error: 'class Gtk::StyleContext' has no member named 'get_background_color'
1037 |     const Gdk::RGBA bg_color = context->get_background_color( Gtk::STATE_FLAG_NORMAL );
| …
```
> SKELETON::Toolbar: Update close button flat style

- src/control/controlutil.cpp
- src/control/mousekeyconf.cpp
- src/control/mousekeyconf.h
一時的なバックアップ用のメンバー変数とバックアップ・復元の関数を実装します。さらにグローバル変数を用いた設定のバックアップ・復元を関数呼び出しに交換します。
> MouseKeyConf: Use member variables to backup instead of global vars

- src/dbimg/img.cpp
- src/dbimg/imginterface.h
- src/dbimg/imgroot.cpp
- src/dbimg/imgroot.h
GdkPixbufローダーが対応していない画像URLは拡張子のチェックで通常リンクになります。しかし拡張子が偽装されていると画像として読み込みが行われ分かりにくいエラーメッセージが表示されます。(画像サイズを取得出来ません)
そのため画像データのシグネチャ確認を修正し読み込みが未対応のときのエラーメッセージを追加します。
https://next2ch.net/test/read.cgi/linux/1613035222/273
> Img: Add error message for unsupported image with fake extension

- src/dbtree/spchar_decoder.cpp
- src/dbtree/spchar_tbl.h
Fixes #749 
U+2028 LINE SEPARATOR をDAT読み込み時に半角空白 U+0020 に変換します。
U+2028を描画処理に渡すと改行とレイアウトが乱れます。
webブラウザはU+2028を空白として表示するためJDimも挙動を合わせます。
> Convert line separator to whitespace for drawing thread view tidily

- src/skeleton/editview.cpp
書き込みビューのコンテキストメニューにあるスペースと数値文字参照の変換を`&nbsp;`から`&#160;`に変更します。文字実態参照で入力するとエスケープされるサイトがありました。
> EditTextView: Replace space conversion "&nbsp;" with "&#160;"

- src/aamanager.cpp
文字列の末尾から先頭へ逆順に検索する関数を使い検索開始の位置を0(先頭)に指定することで検索の試行を1回にします。
```
int position = 0;
bool found{ haystack.rfind(needle, position) == 0 };
```
<https://stackoverflow.com/questions/1878001/>
> AAManager: Optimize finding start string

- src/core.cpp
> Core: Optimize finding start string
