JDimproved/JDim

- src/jdlib/miscutil.cpp
> std:stringアクセスの別修正

- src/jdlib/loader.cpp
chunkedなHTTPレスポンスを解釈する際にchunkの終わりの\r\nの解釈中にバッファの終わりに到達すると変な挙動をするのを修正します。
subject.txtが時々おかしくなるのは多分これが原因です。
> Fix Loader::skip_chunk.

- src/bbslist/toolbar.cpp
- src/skeleton/aamenu.cpp
- src/skeleton/compentry.cpp
- src/skeleton/toolbar.cpp
現在alphaバージョンであるgtk3版からいくつかのコミットを抽出してリクエストします。gtk3版のブランチは変更量が多すぎるので安定している変更を分けたいと思います。
gtk3版で起こる挙動の不具合を修正するパッチをgtk2版に適応します。gtk2版の挙動を明らかに変更する修正は含まれていません。
gtk2版で問題となってないものはgtk3版のみに適用するように条件コンパイルを追加する。
> Fix behaviors

- src/jdlib/ssl.cpp
条件コンパイルがスパゲティになっているので整理します。
GnuTLS 3.4.6以上は新しい初期化にまとめ、未満は従来の初期化に差し戻します。
修正にあたり不具合報告や動作検証をしていただきありがとうございました。
https://mao.5ch.net/test/read.cgi/linux/1540656394/701-737
> Tweak JDLIB::JDSSL::connect()

- src/dbtree/nodetree2ch.cpp
例えば，JDim 側で板 URL が ```http://hoge.5ch.net/piyo/``` と認識されており，また移転前の板 URL が ```http://foo.5ch.net/piyo/``` となっている板があったとして，```http://foo.5ch.net/test/read.cgi/piyo/1234567890/``` という URL のスレッド(```hoge``` サーバには当該スレッドは無いとする)を見たいとすると，現時点での JDim は ```http://hoge.5ch.net/piyo/dat/1234567890.dat``` にアクセスし，そこで取得出来なかった場合はそのまま取得処理が終了してしまいます。
そこでこの変更では，先ほどの URL から dat を取得出来なかった場合に，旧 URL(すなわち，```http://foo.5ch.net/piyo/dat/1234567890.dat```)からの dat の取得を試みるようにしました。
これにより，[2chproxy.pl](https://github.com/yama-natuki/2chproxy.pl) のような read.cgi の HTML から dat に変換する機能を備えているプロキシを併用すると，旧サーバにしか存在しないような過去ログも JDim で読めるようになり便利になると思います。
> Add downloading dat from old URL

- configure.ac
- src/jdlib/jdiconv.cpp
- src/jdlib/misctrip.cpp
- src/jdversion.h
\*BSDでJDimをビルドできるようコードを修正します。
https://mao.5ch.net/test/read.cgi/linux/1551877588/101
https://mao.5ch.net/test/read.cgi/linux/1551877588/120
> Fix *BSD compile error

- src/article/articleview.cpp
- src/article/articleview.h
- src/article/articleviewbase.cpp
- src/article/articleviewbase.h
- src/article/articleviewsearch.cpp
- src/article/articleviewsearch.h
- src/bbslist/bbslistviewbase.h
- src/board/boardview.cpp
- src/board/boardview.h
- src/board/boardviewbase.cpp
- src/board/boardviewbase.h
- src/cssmanager.cpp
- src/cssmanager.h
- src/dbtree/articlebase.cpp
- src/dbtree/articlebase.h
- src/jdlib/constptr.h
- src/jdlib/refptr_lock.h
- src/message/messageviewbase.cpp
- src/message/messageviewbase.h
- src/skeleton/loadable.cpp
- src/skeleton/loadable.h
- src/skeleton/view.cpp
- src/skeleton/view.h
- src/xml/dom.cpp
- src/xml/dom.h
- src/xml/domlist.h
> Add const qualifier to member functions

- docs/manual/2019.md
- src/jdlib/confloader.cpp
- src/linkfiltermanager.cpp
玉葱版からのパッチです。
範囲ベースfor文を使ってループをリファクタリングします。
> Use range-based for

- src/article/drawareabase.cpp
malloc/freeによるバッファ確保をstd::stringで置き換えます。
std::stringで自動的にメモリを確保するようになりましたが挙動を維持するためバッファサイズの条件は残ます。
> Replace char buffer with std::string

- docs/manual/operation.md
マニュアルに記載されてなかったスレビューの操作「表示しているスレのキャッシュを削除してタブを閉じる」の説明を追加します。
> Add a description for undocumented operation to the manual

- src/article/drawareabase.cpp
玉葱版からパッチの一部を取り込みます。
ローカル変数を追加して処理を書き直します。
> Refactor ARTICLE::DrawAreaBase

- docs/manual/2020.md
- src/environment.cpp
malloc/freeで領域を確保しているstruct utsnameをローカル変数で置き換えます。
> Replace dynamic allocation with local variable for struct utsname

- src/jdlib/jdmigemo.cpp
- src/jdlib/jdmigemo.h
- src/jdlib/jdregex.cpp
- src/winmain.cpp
ローマ字入力を日本語検索のための正規表現に変換する関数(migemo)をリファクタリングします。
calloc/freeで確保しているバッファをstd::stringで置き換えます。
> Refactor migemo functions

- docs/manual/2020.md
> Split history sections

- src/config/configitems.cpp
- src/config/configitems.h
メンバ変数の初期化を変更してcppcheckの警告 `(warning) Member variable 'ConfigItems::restore_board' is not initialized in the constructor.` を修正します。
暗黙的だったコピーコンストラクタを明示的にデフォルト定義します。
<details>
<summary>cppcheckのログ：長いので畳む</summary>
```
[src/config/configitems.cpp:62]: (warning) Member variable 'ConfigItems::restore_board' is not initialized in the constructor.
[src/config/configitems.cpp:62]: (warning) Member variable 'ConfigItems::restore_article' is not initialized in the constructor.
[src/config/configitems.cpp:62]: (warning) Member variable 'ConfigItems::restore_image' is not initialized in the constructor.
[src/config/configitems.cpp:62]: (warning) Member variable 'ConfigItems::manage_winpos' is not initialized in the constructor.
[src/config/configitems.cpp:62]: (warning) Member variable …
```
> ConfigItems: Fix member initialization

- src/article/drawareabase.cpp
Fixes #294
スレビューでURLにマウスオーバーすると予期しないジャンプが発生する問題を修正します。
https://mao.5ch.net/test/read.cgi/linux/1584619744/287
> Fix unexpected jump by mouse over url

- src/article/articleviewetc.cpp
- src/article/articleviewpreview.cpp
- src/board/boardviewsidebar.cpp
- src/data_info.h
- src/image/imageviewbase.cpp
- src/jdlib/timeout.cpp
- src/jdlib/timeout.h
- src/skeleton/iconpopup.h
- src/skeleton/tabnote.cpp
- src/skeleton/tabnote.h
メンバ初期化子リストを使うようにcppcheckに指摘されたため修正します。
> Fix to use member initializer lists

- src/article/preference.cpp
- src/article/preference.h
- src/board/preference.cpp
- src/board/preference.h
- src/skeleton/imgbutton.cpp
- src/skeleton/imgbutton.h
- src/skeleton/imgtogglebutton.cpp
- src/skeleton/imgtogglebutton.h
値渡しではなくconst参照渡しにするべきとcppcheckに指摘されたためコンストラクタの引数を修正します。
> Fix constructor parameter to const reference

- src/article/articleviewbase.cpp
- src/article/articleviewbase.h
- src/article/articleviewinfo.h
- src/article/articleviewpreview.cpp
- src/article/articleviewpreview.h
- src/dbimg/img.cpp
- src/dbimg/img.h
- src/dbtree/root.cpp
- src/dbtree/root.h
- src/image/imageadmin.cpp
- src/image/imageadmin.h
- src/jdlib/jdregex.cpp
- src/jdlib/jdregex.h
- src/prefdiagfactory.cpp
- src/prefdiagfactory.h
- src/usrcmdmanager.cpp
- src/usrcmdmanager.h
値渡しではなくconst参照渡しにするべきとcppcheckに指摘されたため関数の引数を修正します。
> Fix function parameter to const reference

- src/board/preference.cpp
- src/dbtree/board2ch.cpp
- src/dbtree/board2ch.h
- src/dbtree/boardbase.cpp
- src/dbtree/boardbase.h
- src/dbtree/interface.cpp
- src/dbtree/interface.h
- src/dbtree/nodetreebase.cpp
- src/dbtree/ruleloader.cpp
- src/dbtree/settingloader.cpp
- src/message/post.cpp
HTTP cookie関連の関数名を変更して #317 の修正前にコードを整理します。
> Rename cookie functions

- src/dbtree/board2chcompati.h
> Remove unnecessary using declaration for member function

- src/board/preference.cpp
- src/dbtree/board2chcompati.cpp
- src/dbtree/board2chcompati.h
- src/dbtree/boardbase.h
- src/dbtree/interface.cpp
- src/dbtree/interface.h
- src/message/post.cpp
- src/message/post.h
#317 の修正です。
HTTP POSTリクエストへ追加されるキーワードの処理を更新します。
- 書き込み用キーワードの解析を更新してサイト対応とパフォーマンスの改善をする
- スレ立てと書き込みで異なるキーワードを使うサイトに対応するためスレ立て用キーワードを書き込み用から別ける
> Improve analyzation of keywords for writing and newarticle

- src/bbslist/selectdialog.cpp
- src/jdlib/miscutil.cpp
- src/xml/dom.cpp
不変の条件式があるとcppcheckに指摘されたため削除します。
cppcheckのレポート
```
src/bbslist/selectdialog.cpp:52:9: style: Condition '!active_row' is always true [knownConditionTrueFalse]
if( ! active_row && name == SESSION::get_dir_select_favorite() ) active_row = m_vec_path.size();
^
src/bbslist/selectdialog.cpp:47:22: note: Assignment 'active_row=0', assigned value is 0
int active_row = 0;
^
src/bbslist/selectdialog.cpp:52:9: note: Condition '!active_row' is always true
if( ! active_row && name == SESSION::get_dir_select_favorite() ) active_row = m_vec_path.size();
^
src/jdlib/miscutil.cpp:1804:18: style: Condition 'in1' is always true [knownConditionTrueFalse]
if ( in1 ) in2 = static_cast< unsigned char >( str1[ pos + 1 ] );
^
src/jdlib/miscutil.cpp:1801:17: note: Assuming that condition 'in1==239' is not …
```
> Remove invariable condition expression

- src/dbtree/root.cpp
板一覧の読み込みにプロキシ設定を適用するように修正します。
2ch系サイトには「2ch読み込み用」、それ以外は「その他のサーバ用」の設定を「利用する」がonのときに適用します。
加えて、ユーザーエージェントやHTTPクッキーの送信も行うように変更します。
関連のissue: #332
> Apply proxy settings to loading bbslist

- src/jdlib/loader.cpp
プロキシと連携をとるため2ch系サイトへのhttpsリクエストを一律にハックしてhttpで接続していますが(dc7d540a9b)、サイトがhttps化されるとプロキシを利用しないときに接続が拒否(400 Bad Request)される[可能性][1]があります。
そのためハックしない(=__httpsで接続__)条件を以下のように変更します。
修正前: httpsから始まるURL and 2ch系サイトでない
修正後: httpsから始まるURL and (__プロキシを使わない__ or 2ch系サイトでない)
[1]: https://mao.5ch.net/test/read.cgi/linux/1584619744/439-468 "一時的に5chがhttps化されたときエラーが発生した"
関連のissue: #332
> Improve https hack for proxy connection

- INSTALL
- docs/manual/make.md
migemoによる検索機能に関する注意点と未掲載のconfigureオプションの説明をドキュメントに追加します。
> Add description for migemo build option

- docs/manual/2020.md
- src/jdversion.h
> Bump version to 0.4.0-beta

- src/dbtree/root.cpp
std::find_if()が使えるとcppcheckに指摘されたためループ文を修正します。
cppcheckのレポート
```
src/dbtree/root.cpp:221:116: style: Consider using std::find_if algorithm instead of a raw loop. [useStlAlgorithm]
if( is_2ch( board->get_root() ) && url.find( board->get_path_board() + "/" ) != std::string::npos ){
^
```
> Root: Use std::find_if() instead of iterator loop

- INSTALL
- README.md
- docs/manual/make.md
- meson.build
mesonを使ったJDimのビルド方法をより詳しく説明するためmeson.buildの説明を追加して、さらにPull RequestのURLをリンクします。
> Add more specific description for building by meson

- src/core.cpp
- src/core.h
> Core: Remove member functions which are no longer in use

- README.md
- docs/manual/start.md
32bit OSの古いMATE環境で実行するときの注意点をドキュメントに追加します。
関連のコミット： https://github.com/JDimproved/JDim/commit/ffbce60ede
> Add note in the case of running on old MATE desktop

- src/config/aboutconfig.cpp
- src/control/mousekeypref.cpp
- src/fontcolorpref.cpp
- src/skeleton/prefdiag.cpp
- src/skeleton/prefdiag.h
GTK3で追加されたメンバ関数のコンパイル条件を整理します。
関連のissue: #229
> prefdiag: Remove compile conditions for adding member function

- src/article/drawareabase.cpp
GTK 3.9.2未満の環境ではスレビュー描画のダブルバッファリングを手動で行っていましたが動作環境が更新され不要になりましたので削除します。
関連のissue: #229 
関連のコミット: ffbce60ede
GTK/GDKのダブルバッファリングについて参考文献:
https://developer.gnome.org/gtk3/stable/GtkWidget.html#gtk-widget-set-double-buffered
> DrawAreaBase: Remove double bufferd processing for gtk < 3.9.2

- docs/manual/2020.md
> manual: Update histories

- src/setupwizard.cpp
> setupwizard: Fix setting mnemonic widget for PageFont

- src/jdlib/loader.cpp
> Loader: Fix typo for error message

- meson.build
mesonの構成時にビルドオプションの設定状況が分かりやすいようにまとめて表示します。
> meson: Add summary for build configuration

- src/bbslist/bbslistviewbase.cpp
- src/bbslist/bbslistviewbase.h
板一覧で使われる板やスレッドのURLをTreeViewの要素から取得するように変更します。
> BBSListViewBase: Get URL from TreeView instead of DBTREE interfaces

- src/dbtree/nodetreebase.cpp
`NodeTreeBase::add_one_dat_line()`のdat解析処理を更新して解析が不完全に終わったときは旧dat形式で試すようにします。
> NodeTreeBase: Update DAT parsing to try the old format if failure

- INSTALL
- README.md
- docs/manual/make.md
- meson.build
将来の正式サポートを見据えてmesonのサポート状況を暫定に更新します。
> meson: Update support to provisional

- src/main.cpp
多重起動防止のダイアログボックスに表示するメッセージを修正しロックファイルについて説明を追加します。
https://next2ch.net/test/read.cgi/linux/1573309956/93
> Modify dialog message for multiple start

- test/README.md
Mesonを使ったテストのやり方をREADMEに追加します。
> Add meson description to test/README.md

- CONTRIBUTING.md
CONTRIBUTING.mdを更新してGitHub Discussionsの利用を案内します。
> Update contributing guide for using discussions

- src/dbtree/board2ch.cpp
- src/dbtree/board2ch.h
- src/dbtree/board2chcompati.cpp
- src/dbtree/board2chcompati.h
- src/dbtree/boardbase.cpp
- src/dbtree/boardbase.h
- src/dbtree/boardjbbs.cpp
- src/dbtree/boardjbbs.h
- src/dbtree/boardlocal.cpp
- src/dbtree/boardlocal.h
- src/dbtree/boardmachi.cpp
- src/dbtree/boardmachi.h
- src/dbtree/settingloader.h
> board: Add const qualifier to member function

- snap/snapcraft.yaml
Snapのビルド設定を差し戻し更新します。
関連のpull request: #549
> Restore snapcraft configuration

- INSTALL
- README.md
- docs/manual/make.md
- test/README.md
Mesonを使ってビルドする方法へのリンクを[Pull request][388]から[Discussions][556]へ変更します。
[388]: https://github.com/JDimproved/JDim/issues/388
[556]: https://github.com/JDimproved/JDim/discussions/556
> Change tips link for building by Meson

- CONTRIBUTING.md
CONTRIBUTING.mdのバグ報告へのリンクをIssueテンプレートへ変更します。
> Fix bug report link for CONTRIBUTING.md

- src/board/boardadmin.cpp
- src/board/boardadmin.h
- src/board/boardviewbase.cpp
- src/board/boardviewbase.h
- src/board/preference.cpp
- src/board/preference.h
> board: Fix member initialization

- src/sound/playsound.cpp
~~クラスのメンバー~~ローカル変数を`std::vector`に取り替えてnew/deleteを削除します。
> Play_Sound: Use std::vector instead of new/delete

- src/skeleton/admin.cpp
> Admin: Remove unnecessary if-statements

- src/dbtree/articlehash.cpp
- src/dbtree/articlehash.h
保持する必要がないクラスメンバーを削除してnew/deleteによるメモリ割り当てを整理します。
> ArticleHash: Remove unnecessary member variable

- src/board/boardviewbase.cpp
if文中のstd::stringの値について条件を整理します。
> BoardViewBase: Simplify if statement condition

- src/article/articleviewbase.cpp
- src/article/articleviewbase.h
> ArticleViewBase: Add const qualifier to member function

- src/article/caret.h
> CARET_POSITION: Add const qualifier to member function

- src/article/layouttree.h
> LayoutTree: Add const qualifier to member function

- src/article/drawareabase.cpp
- src/article/drawareabase.h
> DrawAreaBase: Add const qualifier to member function

- src/board/boardviewbase.cpp
- src/board/boardviewbase.h
- src/board/boardviewlog.cpp
- src/board/boardviewlog.h
- src/board/boardviewnext.cpp
- src/board/boardviewnext.h
- src/board/boardviewsidebar.cpp
- src/board/boardviewsidebar.h
- src/skeleton/treeviewbase.cpp
- src/skeleton/treeviewbase.h
> BoardViewBase: Add const qualifier to member function

- src/control/mousekeyitem.h
> MouseKeyItem: Add const qualifier to member function

- src/control/buttonconfig.cpp
- src/control/buttonconfig.h
> ButtonConfig: Add const qualifier to member function

- src/core.cpp
- src/core.h
- src/image/imageadmin.cpp
- src/image/imageadmin.h
- src/skeleton/admin.cpp
- src/skeleton/admin.h
> Core: Add const qualifier to member function

- src/dbtree/root.cpp
- src/dbtree/root.h
> Root: Add const qualifier to member function

- src/skeleton/aboutdiag.cpp
- src/skeleton/aboutdiag.h
> AboutDiag: Add const qualifier to member function

- src/skeleton/treeviewbase.cpp
- src/skeleton/treeviewbase.h
> TreeViewBase: Add const qualifier to member function

- src/image/imageareabase.h
- src/image/imageareaicon.cpp
- src/image/imageareaicon.h
- src/image/imageview.h
- ImageAreaBase: Add const qualifier to member function
- ImageAreaIcon: Add const qualifier to member function
- ImageViewMain: Add const qualifier to member function
> image: Add const qualifier member function

- src/dbtree/nodetreebase.cpp
- src/dbtree/nodetreebase.h
メンバー変数やメンバー関数を使用しないメンバー関数を静的メンバーにして保守性を向上させます。
- `NodeTreeBase::remove_imenu()`
- `NodeTreeBase::convert_amp()`
> NodeTreeBase: Add static keyword to member function

- src/dbtree/articlebase.h
例外を投げないメンバー関数に`noexcept`をつけます。
> ArticleBase: Add noexcept qualifier to member function

- src/article/articleviewbase.cpp
> ArticleViewBase: Optimize finding start string

- src/article/drawareabase.cpp
> DrawAreaBase: Optimize finding start string

- src/article/preference.cpp
- src/bbslist/bbslistviewbase.cpp
- src/board/boardviewbase.cpp
- src/cache.cpp
文字列先頭が一致するか検索する関数の引数をcharに変更して最適化します。
文字列先頭が一致するか検索する関数の引数をcharに変更して最適化します。
> Optimize finding start string part3

- src/cssmanager.cpp
> Css_Manager: Optimize finding start string

- src/environment.cpp
長さ1の文字列を検索する処理は文字列ではなく文字を検索するように最適化します。
> environment: Optimize finding start string

- src/message/messageview.cpp
- src/message/messageviewbase.cpp
投稿内容に不備があったとき表示するメッセージを修正し分かりやすくします。
https://next2ch.net/test/read.cgi/linux/1613035222/391
> message: Improve error messages for incomplete input

- src/jdlib/jdiconv.cpp
- src/jdlib/loader.cpp
- src/jdlib/miscgtk.cpp
- src/jdlib/miscutil.cpp
> jdlib: Optimize finding start string

- src/message/logmanager.cpp
- src/message/messageviewbase.cpp
- src/message/post.cpp
> message: Optimize finding start string

- src/aamanager.cpp
https://stackoverflow.com/questions/14579957/std-container-c-move-to-front
> AAManager: Update iterator for loop

- src/article/articleadmin.cpp
> ArticleAdmin: Update iterator for loop

- src/article/articleviewbase.cpp
> ArticleViewBase: Update iterator for loop

- src/article/articleviewsearch.cpp
> ArticleViewSearch: Update iterator for loop

- src/article/drawareabase.cpp
> DrawAreaBase: Update iterator for loop

- src/article/font.cpp
> font: Update iterator for loop

- src/article/layouttree.cpp
> LayoutTree: Update iterator for loop

- src/bbslist/bbslistview.cpp
> BBSListViewMain: Update iterator for loop

- src/bbslist/bbslistviewbase.cpp
- src/bbslist/selectdialog.cpp
> bbslist: Update iterator for loop

- src/board/boardviewbase.cpp
> BoardViewBase: Update iterator for loop

- src/control/control.cpp
> Control: Update iterator for loop

- src/control/mousekeyconf.cpp
> MouseKeyConf: Update iterator for loop

- src/control/mousekeypref.cpp
> MouseKeyPref: Update iterator for loop

- src/cssmanager.cpp
> Css_Manager: Update iterator for loop

- src/dbtree/articlebase.cpp
> ArticleBase: Update iterator for loop

- src/dbtree/article2ch.cpp
- src/dbtree/boardbase.cpp
デバッグプリントで正しい関数名を出力するように訂正します。
文字列の検索で検索開始位置を最適化します。
> Improve miscellaneous codes part1

- src/dbtree/boardbase.cpp
要素の削除を含むforループのイテレーター進行処理を修正します。
> BoardBase: Update iterator for loop

- src/dbtree/root.cpp
URLを抽出する正規表現を更新します。
関連のissue: #76
> Root: Update regex for URL

- src/dbtree/root.cpp
板一覧に登録されたURLのうちhttp:などスキームが省略されているものはbbsmenuのスキームを使うように修正します。
関連のissue: #76
> Root: Correct board URLs which are missing scheme

- src/board/boardviewbase.cpp
スレッド速度の更新をスレ追加に加えてスレ更新でも行うように修正します。
関連のissue: #76
> BoardViewBase: Improve update of thread speed

- src/dbtree/root.cpp
要素の削除を含むforループのイテレーター進行処理を修正します。
> Root: Update iterator for loop part1

- src/dbtree/root.cpp
> Root: Update iterator for loop part2

- src/dbtree/root.cpp
> Root: Update iterator for loop part3

- src/dbtree/root.cpp
> Root: Update iterator for loop part4

- src/dbtree/root.cpp
> Root: Update iterator for loop part5

- src/jdlib/tfidf.cpp
> tfidf: Update iterator for loop

- src/loginbe.cpp
> LoginBe: Update iterator for loop

- src/menuslots.cpp
> menuslots: Update iterator for loop

- src/message/post.cpp
> Post: Update iterator for loop

- src/searchmanager.cpp
> Search_Manager: Update iterator for loop

- src/session.cpp
> session: Update iterator for loop

- src/skeleton/admin.cpp
> Admin: Update iterator for loop

- src/skeleton/backforwardbutton.cpp
> BackForwardButton: Update iterator for loop

- src/skeleton/compentry.cpp
> CompletionEntry: Update iterator for loop

- src/skeleton/edittreeview.cpp
> EditTreeView: Update iterator for loop

- src/skeleton/toolbar.cpp
> SKELETON::ToolBar: Update iterator for loop

- src/skeleton/treeviewbase.cpp
> JDTreeViewBase: Update iterator for loop

- src/updatemanager.cpp
> CheckUpdate_Manager: Update iterator for loop

- src/jdlib/loader.cpp
POSTメソッドのとき起こる問題点を修正します。
- request bodyの後にヘッダーUpgrade-Insecure-Requestsが追加される問題を修正します。
- request bodyの後にある余分な改行(\r\n)を削ります。
> Loader: Correct HTTP header position in request

- src/message/post.cpp
書き込み確認のcookieチェックで読み込み用の設定を参照していた箇所を書き込み用の設定を参照するように修正します。
> Post: Fix cookie check for posting

- docs/manual/2021.md
- meson.build
- src/jdversion.h
> Bump version to 0.7.0-beta

- src/dbtree/nodetreebase.cpp
URL変換処理に使う変数をリファクタリングします。
置換処理の実行で`std::string`に代入しているため固定長バッファへのコピーを省略して整理します。
> NodeTreeBase: Refactor local variable for urlreplace

- src/dbtree/nodetreebase.cpp
`const char*`と文字列の長さがペアになっているローカル変数を`std::string_view`に交換してまとめす。
> NodeTreeBase: Use std::string_view instead of const pointer and size

- src/bbslist/bbslistview.cpp
- src/bbslist/bbslistviewbase.cpp
while文をrange-based forやオブジェクトのメソッドに置き換えてコードを整理します。
> bbslist: Improve while loop

- src/core.cpp
while文をrange-based forやオブジェクトのメソッドに置き換えてコードを整理します。
関連のpull request: #968
> Core: Improve while loop

- src/cssmanager.cpp
while文をrange-based forやオブジェクトのメソッドに置き換えてコードを整理します。
関連のpull request: #968
> Css_Manager: Improve while loop

- src/environment.cpp
Replace while loop with range-based for statement or object member function to organize codes.
related pull request: #968
> environment: Improve while loop

- src/linkfilterpref.cpp
Replace while loop with range-based for statement or object member function to organize codes.
related pull request: #968
> LinkFilterPref: Improve while loop

- src/skeleton/edittreeview.cpp
Replace while loop with range-based for statement or object member function to organize codes.
related pull request: #968
> EditTreeView: Improve while loop

- snap/snapcraft.yaml
Snap版の動作環境にパッケージ作成者(JDimproved project)の情報を追加します。
関連のpull request: #1000
> Snap: Add packager information to operating environment

- snap/snapcraft.yaml
> Snap: Fix typo for packager information

- src/message/messageviewbase.cpp
SETTING.TXT の項目に BBS_UNICODE=change がある板では掲示板に使われている文字エンコーディングが対応していないUnicode文字を書き込むことができません。
そのため、書き込みビューでプレビュー表示するときに BBS_UNICODE の値をチェックして"change"のときは文字エンコーディングが対応していないUnicode文字を文字参照の形式(`&#nnnn;`)で表示するように変更します。
この修正は5ch以外の掲示板が対象です。
5chでは 2022-04-30 から BBS_UNICODE が無効になり設定値に関係なくUnicode文字を書き込めるようになりました。
関連のissue: #76 
関連のpull request: #1023
> message: Change showing preview in the case of BBS_UNICODE=change

- src/article/articleviewbase.cpp
5ch.net BEユーザーのリンクを更新します。
関連のissue: #76
> ArticleBiewBase: Update BE user link

- src/dbtree/articlebase.cpp
スレの状態が全レス既読なら読み込み処理を行わないように変更します。
関連のissue: #76
> ArticleBase: Skip loading article if already read

- src/dbtree/nodetreebase.cpp
NODE構造体のメンバーにアクセスする処理にnullチェックを追加します。
関連のissue: #76
> NodeTreeBase: Add null checks

- src/jdlib/jdiconv.cpp
- src/jdlib/jdiconv.h
`Encoding`列挙型を引数に取る`JDLIB::Iconv`クラスのコンストラクターを追加します。
> Iconv: Add constructors with enum Encoding parameters

- src/dbtree/nodetreebase.cpp
`parse_html()`で処理するテキストデータのうちUTF-8の文字を表すバイト列をまとめてバッファに追加するように変更します。
関連のissue: #76
> NodeTreeBase: Modify parse_html() to collect UTF-8 byte seq into buffer

- src/dbtree/nodetreebase.cpp
大きな入力データに対応とバッファに使うメモリを節約するため`receive_data()`に渡された入力データを改行文字で区切りながら順々に処理するように変更します。
バッファの大きさは半分になりますが大きい入力が渡されても一回の関数呼び出しで処理します。
関連のissue: #76
> NodeTreeBase: Update receive_data() to improve processing large data

- src/dbtree/nodetreebase.cpp
HTMLを解析してノードツリーを構築する処理を更新してHTML `<b>` 要素の中にあるテキストを太字で表示するように変更します。
関連のissue: #76
> NodeTreeBase: Implement bold display for text inside HTML <b> elements

- src/dbtree/nodetreebase.cpp
HTMLを解析してノードツリーを構築する処理を更新してHTML`<span>`と`<mark>`要素で指定された文字色と背景色を表示できるようにCSSの読み込みを実装します。
- `<span>` はCSSのクラス名を取得して対応する色設定があれば適用します。
- `<mark>` は要素に対する色設定を適用します。
関連のissue: #76
> NodeTreeBase: Implement color display for HTML <span> and <mark> elements

- src/dbtree/nodetreebase.cpp
DATやHTMLに含まれる名前欄を解析してノードツリーを構築する関数を修正してループを抜けるときのカウンター、バッファにテキストをコピーする
処理を更新します。
webブラウザと太字・細字の表示が異なる部分がありますが互換性のため既存の挙動を維持します。
関連のissue: #76
> NodeTreeBase::parse_name(): Update loop condition and text copy

- src/dbtree/nodetreebase.cpp
DATやHTMLに含まれる日付とID、及びBEなどを解析してノードツリーを構築する関数を更新します。
- BE linkのアンカーを "?" 一文字からBPのテキスト部分に変更します。
- 日付や時刻を含まないまたは1文字(IDの末尾だけ)はIDノードにします。
関連のissue: #76
> NodeTreeBase: Update fucntion to parse date, ID, and BE link

- src/main.cpp
リソースがリークしているとcppcheckに指摘されたためアプリケーションの終了時にFILEを閉じるように修正します。
```
src/main.cpp:367:9: error: Resource leak: tmp [resourceLeak]
tmp = freopen( logfile.c_str(), "ab", stderr );
^
src/main.cpp:370:5: error: Resource leak: tmp [resourceLeak]
}
^
```
> Fix resource leak for logging

- src/jdlib/jdsocket.cpp
アライメントが異なる型へポインターをキャストしているとgccに指摘されたためキャストを使わない方法で修正します。
gcc 12のレポート
```
../src/jdlib/jdsocket.cpp:226:28: warning: cast from ‘sockaddr*’ to ‘sockaddr_in*’ increases required alignment of target type [-Wcast-align]
226 |             auto addr_in = reinterpret_cast<sockaddr_in*>( ainf->ai_addr );
|                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/jdlib/jdsocket.cpp:123:16: warning: cast from ‘sockaddr*’ to ‘sockaddr_in*’ increases required alignment of target type [-Wcast-align]
123 |         src = &reinterpret_cast<sockaddr_in*>( ainf->ai_addr )->sin_addr;
|                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/jdlib/jdsocket.cpp:126:16: warning: cast from ‘sockaddr*’ to ‘sockaddr_in6*’ increases required alignment of target type …
```
> Socket: Fix casting of pointers to types with different alignments

- README.md
より早くビルドする方法としてREADMEにUnity buildの方法を追加します。
関連のissue: https://github.com/JDimproved/JDim/issues/1177
> readme: Add Unity build tips for how to faster builds

- src/dbtree/nodetree2ch.cpp
5ch.net過去ログの読み込みを修正して処理条件を整理してまとめます。
旧URLと過去ログサーバーの読み込み処理を統合して５ちゃんねるのお知らせに記載されている[アクセス方法][1]に合わせます。
1. 現役サーバーから稼働中のスレッドを読み込む
2. 現役サーバーからDAT落ちしたスレッドを読み込む
3. 旧URLがある場合、過去ログサーバーからスレッドを読み込む
[1]: https://agree.5ch.net/test/read.cgi/operate/9240230711/3
> NodeTree2ch: Fix loading of past log DATs to organize DAT URLs

- src/dbtree/nodetree2ch.cpp
"プロキシを使わない接続で過去ログが見つからなかったときは2ch読み込み用プロキシを使う"
設定の動作を修正して過去ログサーバ(サーバ移転前のURL)へのプロキシ接続に対応します。
5chの過去ログサーバには現役サーバと同じようにread.cgiにアクセスするとスレを表示するがdatは取得できない板やスレッドがあるようです。
このタイプは現役サーバのURLでアクセスしてもレスを取得することができません。
そのためプロキシ接続で現役サーバからdatを取得できなかったときは過去ログサーバから取得を試みる仕組みを導入します。
Closes #1229
> Extend proxy support for accessing kako log server in fallback

- src/dbtree/nodetreebase.cpp
`std::any_of()`が使えるとcppcheckに指摘されたためforループ文を修正します。
```
src/dbtree/nodetreebase.cpp:3467:67: style: Consider using std::any_of algorithm instead of a raw loop. [useStlAlgorithm]
if( name_str.find( name ) != std::string_view::npos ) {
^
src/dbtree/nodetreebase.cpp:3477:67: style: Consider using std::any_of algorithm instead of a raw loop. [useStlAlgorithm]
if( name_str.find( name ) != std::string_view::npos ) {
^
src/dbtree/nodetreebase.cpp:3487:67: style: Consider using std::any_of algorithm instead of a raw loop. [useStlAlgorithm]
if( name_str.find( name ) != std::string_view::npos ) {
^
src/dbtree/nodetreebase.cpp:3554:61: style: Consider using std::any_of algorithm instead of a raw loop. [useStlAlgorithm]
if( res_str.find( word ) != std::string::npos ) {
^ …
```
> NodeTreeBase: Use std::any_of() instead of range-based for loops

- src/searchloader.cpp
- src/skeleton/textloader.cpp
板のローカルルールやSETTING.TXTが文字化けしていた不具合を修正します。
Closes #1273
> TextLoader: Add default encoding to fix Mojibake

- src/jdlib/jdsocket.cpp
ソケットの読み込み、書き込みが準備完了するまで待機する処理にpoll(2)を使うように変更します。
pollは引数の入力データを変更しないため呼び出し毎に入力を再設定する必要がありません。
pollはPOSIX.1-2001の一部であり最近のUnix系OSでは利用可能です。
サーバーが重たく受信に時間がかかっているときにCPUの使用率が上がると報告があったため使用するAPIを変更します。
https://mao.5ch.net/test/read.cgi/linux/1689151433/759
> Socket: Use poll(2) instead of select(2) for IO event notify

- src/jdlib/jdsocket.cpp
板やスレの読み込みを中止しても通信がキャンセルされないことがある不具合を修正します。
linuxではselect(2)やpoll(2)を使ってsocketのファイルディスクリプタを待つと読み込みの準備完了ができたと通知がきた場合でも読み込みがブロックされることがあるとマニュアルに書かれています。
間違った準備完了でIO待機を抜ける状況では読み込みブロックとIO待機が繰り返されて読み込み中止の確認が不能になっていました。
<https://linuxjm.osdn.jp/html/LDP_man-pages/man2/select.2.html>
Closes #1281
> Socket: Fix stop check for IO event notify

- src/skeleton/loadable.cpp
- src/skeleton/loadable.h
> Loadable: Add const qualifier to member function

- src/bbslist/bbslistview.cpp
- src/bbslist/bbslistviewbase.cpp
- src/bbslist/bbslistviewbase.h
- src/bbslist/favoriteview.cpp
- src/bbslist/historyview.cpp
板一覧などサイドバーのビューをXMLに保存するする処理を変更して除外するディレクトリを複数指定できるようにします。
> BBSListViewBase: Update save function to be able to exclude multi dirs

- src/skeleton/treeviewbase.cpp
スレ一覧でスレを複数選択してあぼーんすると不具合が発生することがあるため修正します。
修正する不具合
- 複数選択してスレあぼーんしたとき異常終了することがある
- 複数選択してスレあぼーんしたとき選択したスレがあぼーんされなかったり選択してないスレがあぼーんされる
Closes #1374
> JDTreeViewBase: Fix bug when multiple threads are selected to abone

- src/dbtree/board2ch.cpp
about:config の「2chのクッキーを保存する」を"はい"にしてセッションの復元を行うときにHTTP通信で取得したクッキーの管理を行うクラス(CookieManager)のオブジェクトに「2chのクッキー」や「BBSPINKのクッキー」の値を挿入してクッキーの状態を一つにまとめます。
保存されたクッキーのドメインは掲示板サイトのトップ(.5ch.net, .bbspink.com)になります。
修正前のバージョンではHTTP通信で取得したクッキーと保存したクッキーが別個に管理されています。
そのため「2chのクッキーを保存する」を"はい"にするとクッキーの重複や矛盾が発生する可能性があります。
2024年3月下旬ころに[ドングリシステム][1]という名前のユーザーを識別する仕組みが[5ch.netに導入されると発表][2]がありました。
これはHTTP Cookieにユーザーの識別子を埋め込んで識別する仕組みのようです。
2024-04-06 現在では専用ブラウザでの利用に際し、修正や更新が必要かどうかについて[情報が公開されていません。][3]
現時点ではクッキー管理を整理してクッキーの重複や矛盾が発生しないように修正しておきます。
[1]: https://donguri.5ch.net/
[2]: https://kes.5ch.net/test/read.cgi/donguri/1711214587/
[3]: https://kes.5ch.net/test/read.cgi/donguri/1712311717/
> Board2ch: Unify HTTP cookie for saved and received cookies

- src/jdlib/imgloader.cpp
ファイルの読み込み操作に失敗すると、ストリームのファイル位置が不確定になるとscan-buildに指摘されたため`std::ifstream`を使ってエラー検出を追加します。
scan-build-19のレポート
```
[145/287] Compiling C++ object src/jdlib/libjdlib.a.p/imgloader.cpp.o
../../../src/jdlib/imgloader.cpp:143:42: warning: File position of the stream might be 'indeterminate' after a failed operation. Can cause undefined behavior [unix.Stream]
143 |             const std::size_t readsize = fread( data, 1, bufsize, f );
|                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
```
> Fix scan-build warning for unix.Stream
