src/dbtree/article2chcompati.cpp, src/dbtree/articlebase.cpp, src/dbtree/articlejbbs.cpp, src/dbtree/boardbase.cpp, src/dbtree/boardjbbs.cpp, src/dbtree/boardmachi.cpp, src/dbtree/nodetreebase.cpp, src/dbtree/nodetreemachi.cpp, src/dbtree/root.cpp
文字列先頭が一致するか検索する関数の引数をcharに変更して最適化します。
=> dbtree: Optimize finding start string

docs/manual/2021.md, meson.build, src/jdversion.h
=> Bump version to 0.6.0-beta

src/skeleton/admin.cpp, src/skeleton/dragtreeview.cpp, src/skeleton/view.cpp
=> skeleton: Optimize finding start string

src/dbtree/boardbase.cpp, src/dbtree/boardlocal.cpp, src/icons/iconmanager.cpp, src/login2ch.cpp, src/usrcmdmanager.cpp, src/xml/dom.cpp
文字列が一致するか比較する処理を`std::string::operator ==()`を使って最適化します。
=> Optimize finding start string part11

snap/snapcraft.yaml
Snap版が利用している[gnome-3-34-1804][1] extensionはCPUアーキテクチャーi386に対応していません。前のバージョンの[gnome-3-28-1804][2]はi386に対応＆JDimの動作環境もサポートしています。そのため一時的に設定を切り替えてi386向けのSnapパッケージをビルドしてリリースします。
[1]: https://snapcraft.io/gnome-3-34-1804
[2]: https://snapcraft.io/gnome-3-28-1804
関連のpull request: #549
=> Set snapcraft config for i386 (2021-06)

snap/snapcraft.yaml
Revert "Set snapcraft config for i386 (2021-06)"
This reverts commit 67cc779bb9b14f39e21268c3b53666fb73d7f97c.
Snapのビルド設定をgnome-3-38-1804 extensionを使うように差し戻します。
関連のpull request: #771
=> Restore snapcraft configuration (2021-06)

README.md, docs/manual/start.md, src/main.cpp
コマンドラインオプションの`--norestore`は"前回異常終了した時にバックアップファイルを復元しない"と[説明][2]されていますが[前の修正][1]でセッションの保存処理が変更されたため実際には何もしません。
オプションはもう不要であるため廃止予定にして機能を整理する準備をします。
関連のissue: #772
[1]: https://github.com/JDimproved/JDim/commit/58df294f91a7dacf2b80b9497265869bdb37353f
[2]: https://jdimproved.github.io/JDim/start/#run
=> Deprecate command-line option --norestore

docs/index.md, docs/manual/2021.md, docs/manual/link-20210710.md, jdim.metainfo.xml, meson.build, src/jdversion.h
0.6.0リリースのために変更履歴やバージョン番号を修正します。
- バージョン番号の更新
- メタデータを更新
- 前のマニュアルへのリンクに0.6.0を追加する
- 更新履歴に0.6.0リリースの項目を追加する
TODO
関連のissue: #657
=> Release 0.6.0

configure.ac
Fixes #521
廃止されたPOSIX regexを選択するconfigureオプションを削除します。
~~削除されたオプションは指定しても無視されてエラーは出なくなります。~~
削除されたオプションを指定すると一般的なエラー(regular expression library not found)が表示されます。
- `--with-regex=posix`
=> Remove obsolete --with-regex=posix for ./configure

README.md, docs/manual/start.md, src/cache.cpp, src/cache.h, src/main.cpp
Fixes #772
`--norestore`は"前回異常終了した時にバックアップファイルを復元しない"ようにするオプションですが[以前の修正][1]でセッションの保存処理が変更されバックアップを作成しなくなったため実際には何もしません。
そのためオプションを削除してバックアップの復元処理を整理します。
[1]: https://github.com/JDimproved/JDim/commit/58df294f91a7dacf2b80b9497265869bdb37353f
コマンドラインオプションの整理により使わなくなったバックアップ用のファイルパスを返す関数を削除します。
- `CACHE::path_xml_listmain_bkup()`
- `CACHE::path_xml_favorite_bkup()`
=> Remove deprecated command-line option --norestore

INSTALL, configure.ac, docs/Gemfile, docs/_config.yml, docs/manual/make.md, meson.build
正規表現ライブラリOnigurumaのサポートを廃止予定にします。
Onigurumaは名前付きキャプチャなど正規表現の拡張機能に対応していますがライブラリAPIがGlib regexと異なるため両方に対応するとコードが複雑になりメンテナンスが難しくなります。そのため両対応を断念し正規表現をGTKに付属しているGlib regexにまとめます。
関連のissue: #697
=> Deprecate oniguruma regex option

src/article/preference.cpp, src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, test/gtest_jdlib_miscutil.cpp
リストから空文字列を除き`suffix`でつなげて返す補助関数を追加します。
他のプログラミング言語にある`join()`と動作が異なるため関数の名前は`concat_with_suffix()`にします。
例
```
{"aa", "", "bb", "cc"}, '!' -> "aa!bb!cc!"
```
=> ARTICLE::Preferences: Update iterator for loop

src/jdlib/loader.cpp, src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, test/gtest_jdlib_miscutil.cpp
Fixes #791 
HTTPヘッダーの解析を改良するため文字列を走査して最初に検索語句と一致する位置を返す関数を追加します。ASCIIの文字は大文字小文字の違いを無視します。見つからない場合は`std::string::npos`を返します。
HTTPヘッダーのフィールド名は大文字小文字関係なく受け付けるように変更します。HTTPのRFCでは大文字小文字を区別しない([HTTP/1.1][1])、小文字のみ([HTTP/2.0][2])と定義されていますがこれまでの実装では区別してたためヘッダーの解析に失敗して正常に表示できないサイトがありました。
[1]: https://datatracker.ietf.org/doc/html/rfc2616#section-4.2
[2]: https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2
=> Loader: Fix HTTP header analyzing to ignoring case

src/board/boardadmin.cpp, src/board/boardviewnext.cpp, src/board/preference.cpp
=> board: Update iterator for loop

src/control/controlutil.cpp
=> controlutil: Update iterator for loop

src/core.cpp
=> Core update iter for loop

src/dbimg/delimgcachediag.cpp
=> DelImgCacheDiag: Update iterator for loop

src/dbimg/img.cpp, src/dbimg/imgroot.cpp
=> dbimg: Update iterator for loop

src/dbtree/board2chcompati.cpp, src/dbtree/boardjbbs.cpp, src/dbtree/boardmachi.cpp
=> dbtree: Update iterator for loop part1

src/dbtree/root.cpp
URLにhttp\://などのスキームが先頭以外の部分にないかチェックする方法を整理します。
関連のissue: #76
=> Root: Fix check for URL scheme

src/skeleton/admin.h
仮想関数として使われていない`SKELETON::Admin::close_view(View*)`を非仮想のメンバー関数にします。
関連のissue: #76
=> Admin: Drop virtual function from SKELETON::Admin::close_view(View*)

src/dbtree/nodetreebase.cpp
=> NodeTreeBase: Update iterator for loop part1

src/dbtree/articlebase.cpp, src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
`NodeTreeBase::get_urls()`を画像URL用に更新してコードを整理します。
関連のissue: #76
=> NodeTreeBase: Update NodeTreeBase::get_imglinks()

src/dbtree/nodetreebase.cpp
=> NodeTreeBase: Update iterator for loop part2

src/buildinfo.h.sh, src/meson.build
ビルドディレクトリをソースディレクトリ(gitリポジトリ)の外に作った場合gitを使ったビルド情報の取得に失敗します。
そのためソースディレクトリに移動してgitコマンドを実行するようにスクリプトを修正します。
=> meson: Change current directory to get build information

src/dbtree/nodetreebase.cpp
**NodeTreeBase: Update iterator for loop part3**
**NodeTreeBase: Update iterator for loop part4**
**NodeTreeBase: Update iterator for loop part5**
=> NodeTreeBase: Update iterator for loop part3

src/dbtree/nodetreemachi.cpp
=> NodeTreeMachi: Update iterator for loop

src/board/boardviewbase.cpp, src/board/preference.cpp, src/board/preference.h, src/config/configitems.cpp, src/config/configitems.h, src/config/defaultconf.h, src/config/globalconf.cpp, src/config/globalconf.h, src/dbtree/board2chcompati.cpp, src/dbtree/board2chcompati.h, src/dbtree/boardbase.cpp, src/dbtree/boardbase.h, src/dbtree/interface.cpp, src/dbtree/interface.h, src/globalabonethreadpref.h
板にある未取得スレッドの内、nレス以下のものをあぼ〜んにする機能を追加します。
また、設定の上限を定数から最大表示可能レス数の値に変更します。
元となった玉葱版パッチを元に改変しています。
設定ファイルのnレス以下の項目は名前を変更したため互換性がありません。
- `abone_min_number_thread` -> `abone_low_number_thread`
- `aboneminnumberthread` -> `abonelownumberthread`
関連のissue: #76
=> Add thread abone config for low number of res

docs/manual/skin.md, src/jdlib/miscgtk.cpp
スタイルシート(`jd.css`)による[スレビューのカスタマイズ][skin]を更新してサポートする[色キーワード][1]を追加します。
- 色のプロパティ値は大文字小文字を区別しません。
- 色キーワードにCSS2.1, CSS3, CSS4の対応を追加します。
webブラウザと異なり未知のキーワードや不正な値は変換して扱われます。
[1]: https://developer.mozilla.org/ja/docs/Web/CSS/color_value#color_keywords
[skin]: https://jdimproved.github.io/JDim/skin/
`std::find_if()`による線形探索のかわりの文字列の辞書順ソートを利用した二分探索に変更して検索効率を改善します。
関連のissue: #76
=> Improve named color support for jd.css

src/linkfilterpref.cpp
=> LinkFilterPref: Update iterator for loop

src/dbtree/boardbase.cpp, src/dbtree/root.cpp
Fixes #848 
bbsmenuや板のサーバー移転処理で302 Foundを受信したときリダイレクト先に移転するよう修正します。
302が処理できず不完全な状態で移転が止まり板が開けないことがありした。
https://mao.5ch.net/test/read.cgi/linux/1613107502/916-919n
=> Fix URL redirection for bbsmenu and board to handle 302 Found

src/sound/playsound.cpp, src/sound/playsound.h
alsa-libのヘッダーファイル `alsa/asoundlib.h` は[2001年][1]から導入されているため現状サポートしているディストロでは利用可能です。
そのためヘッダーのチェックを整理してcppcheckのレポート(誤検知?)を解消します。
cppcheck 2.3のレポート
```
src/sound/playsound.cpp:15:0: error: failed to evaluate #if condition, division/modulo by zero [preprocessorErrorDirective]
#if __has_include(<alsa/asoundlib.h>)
^
```
[1]: https://github.com/alsa-project/alsa-lib/commit/0a8749a8026976e85ff486aa7872a05c2f0e150b
=> playsound: Remove __has_include macro for <alsa/asoundlib.h> 

src/message/logmanager.cpp
for文のイテレーターインクリメントを修正します。
リストの要素を削除する処理で返り値をイテレーターに代入していますがループ周回時のインクリメントで余計にすすめていました。
=> Log_Manager: Fix iterator loop

src/article/drawareabase.cpp
`Pango::GlyphString`を使ったスレビューのテキスト描画処理の一部をより効率のよいAPI([`Pango::GlyphString::get_width()`][1])に変更します。
[1]: https://developer-old.gnome.org/pangomm/stable/classPango_1_1GlyphString.html#a9dc40d79a0ab939aadfc32ecf48cd20b
=> DrawAreaBase: Improve performance for drawing Pango::GlyphString

src/article/font.cpp
既に条件が判明している比較があるとcppcheck 2.6.1に指摘されたため条件文を修正します。
0がfalseの条件になっているif文があるためツールがintで真偽値を扱っていると診断したようです。
cppcheckのレポート
```
src/article/font.cpp:91:18: style: Condition 'byte==1' is always true [knownConditionTrueFalse]
if( byte == 1 && strict_of_char ){
^
src/article/font.cpp:82:9: note: Assuming condition 'byte' is true
if( byte && c32 < kMaxCacheCodePoint ){
^
src/article/font.cpp:91:18: note: Condition 'byte==1' is always true
if( byte == 1 && strict_of_char ){
^
```
=> font: Fix known condition true/false

src/board/boardviewlog.cpp
既に条件が判明している比較があるとcppcheck 2.6.2に指摘されたため条件文を修正します。直前のif文で条件をチェックしています。
cppcheckのレポート
```
src/board/boardviewlog.cpp:171:14: style: Condition '!id.empty()' is always true [knownConditionTrueFalse]
else if( ! id.empty() ){
^
src/board/boardviewlog.cpp:168:17: note: Assuming that condition 'id.empty()' is not redundant
if( id.empty() || row ) BoardViewBase::update_item( url, id );
^
src/board/boardviewlog.cpp:171:14: note: Condition '!id.empty()' is always true
else if( ! id.empty() ){
^
```
=> BoardViewLog: Fix known condition true/false

src/dbtree/root.cpp
既に条件が判明している比較があるとcppcheck 2.6.2に指摘されたため条件文を修正します。イテレーターをデリファレンスした後に比較しています。
cppcheckのレポート
```
src/dbtree/root.cpp:1126:20: style: Condition 'it==list_etc.end()' is always false [knownConditionTrueFalse]
if( it == list_etc.end() ) break;
^
```
=> Root: Fix known condition true/false

src/control/mousekeypref.cpp
値を代入した後使っていないとcppcheck 2.6.2に指摘されたため値をセットするメンバー関数に置き換えます。
cppcheckのレポート
```
src/control/mousekeypref.cpp:557:85: style: Variable 'row[get_colums().m_col_drawbg]' is assigned a value that is never used. [unreadVariable]
if( motions != get_default_motions( id ) ) row[ get_colums().m_col_drawbg ] = true;
^
src/control/mousekeypref.cpp:558:47: style: Variable 'row[get_colums().m_col_drawbg]' is assigned a value that is never used. [unreadVariable]
else row[ get_colums().m_col_drawbg ] = false;
^
src/control/mousekeypref.cpp:625:85: style: Variable 'row[get_colums().m_col_drawbg]' is assigned a value that is never used. [unreadVariable]
if( motions != get_default_motions( id ) ) row[ get_colums().m_col_drawbg ] = true;
^
src/control/mousekeypref.cpp:626:47: style: Variable …
```
=> MouseKeyPref: Use set_value function instead of operator[]

src/jdlib/miscutil.cpp
AddressSanitizerでバッファオーバーフローを検知した箇所にヌル終端のチェックを追加します。また、同様のコードがあったためそれも修正します。
バックトレースから抜粋
```
AddressSanitizer: heap-buffer-overflow on address 0x603000dcff4a at pc 0x559327b6d0ee bp 0x7ffff20d0510 sp 0x7ffff20d0500
0x559327b6d0ed in MISC::str_to_uint(char const*, unsigned long&, unsigned long&) ../src/jdlib/miscutil.cpp:637
```
=> miscutil: Fix heap buffer overflow

src/replacestrpref.cpp, src/skeleton/edittreeview.cpp
値を代入した後使っていないとcppcheck 2.6.2に指摘されたため値をセットするメンバー関数に置き換えます。
cppcheckのレポート
```
src/replacestrpref.cpp:356:40: style: Variable 'row[m_columns.m_col_replace]' is assigned a value that is never used. [unreadVariable]
row[ m_columns.m_col_replace ] = dlg.get_replace();
^
```
値を代入した後使っていないとcppcheck 2.6.2に指摘されたため値をセットするメンバー関数に置き換えます。
cppcheckのレポート
```
src/skeleton/edittreeview.cpp:598:33: style: Variable 'row[m_columns.m_name]' is assigned a value that is never used. [unreadVariable]
row[ m_columns.m_name ] = text;
^
```
=> Use set_value function instead of operator[] part2

src/jdlib/miscutil.cpp, src/linkfilterpref.cpp, src/skeleton/edittreeview.cpp
ローカル変数にconstを付けれるとcppcheck 2.6.2に指摘されたため修正します。
cppcheckのレポート
```
src/linkfilterpref.cpp:134:36: style: Variable 'list_item' can be declared with const [constVariable]
std::vector< LinkFilterItem >& list_item = CORE::get_linkfilter_manager()->get_list();
^
```
ローカル変数にconstを付けれるとcppcheck 2.6.2に指摘されたため修正します。
cppcheckのレポート
```
src/jdlib/miscutil.cpp:1251:10: style: Variable 'table' can be declared with const [constVariable]
char table[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
^
```
ローカル変数にconstを付けれるとcppcheck 2.6.2に指摘されたため修正します。
cppcheckのレポート
```
src/skeleton/edittreeview.cpp:94:13: style: Variable 'order' can be declared with const [constVariable]
int order[]={
^
```
=> Add const qualifier to local variable found by cppcheck

src/skeleton/edittreeview.cpp, src/skeleton/edittreeview.h
メンバー関数の引数にconstを付けれるとcppcheck 2.6.2に指摘されたため修正します。
cppcheckのレポート
```
src/skeleton/edittreeview.cpp:1110:61: style: Parameter 'list_path' can be declared with const [constParameter]
void EditTreeView::delete_path( std::list< Gtk::TreePath >& list_path, const bool force )
^
```
=> EditTreeView: Add const qualifier to function parameter

src/board/preference.cpp, src/board/preference.h, src/dbtree/board2ch.cpp, src/dbtree/boardbase.cpp, src/dbtree/boardbase.h, src/dbtree/interface.cpp, src/dbtree/interface.h
Fixes #872 
板設定にUser-Agent(UA)設定を実装します。UAが板に設定されているときは全体設定(about:config)のUAにかわって板のアクセスで使います。設定したUAはキャッシュに保存され次回起動時に読み込まれます。
板のUA設定が未実装のバージョンで起動すると設定が失われます。
板のプロパティにUser-Agent(UA)の設定を追加して板にアクセスするとき使う
UAを変更できるようにします。
- 板のプロパティの"プロキシ設定"タブを"ネットワーク設定"に名称変更する
- ネットワーク設定にUAを設定する入力欄を追加する
- ダイアログのOKボタンを押すと入力したUAが適用される
- 空欄または不適切な文字(non-ASCII)がある状態でOKを押すと設定が消去される
- 入力可能な長さは200文字に制限される
- プロパティで設定したUAは対象の板にアクセスするとき使われる
=> Implement User-Agent configuration for board

src/board/preference.cpp, src/board/preference.h
板のプロパティのクッキーとキーワードを表示する欄をサイズ調整します。
欄が小さくスクロールバーが表示されて見づらくなっていました。
=> board: Improve dialog layout for displaying cookie and keyword

src/bbslist/bbslistviewbase.cpp
`std::find_if()`が使えるとcppcheck 2.6.2に指摘されたためループ文を修正します。
cppcheckのレポート
```
src/bbslist/bbslistviewbase.cpp:3164:13: style: Consider using std::find_if algorithm instead of a raw loop. [useStlAlgorithm]
{
^
```
=> BBSListViewBase: Use std::find_if() instead of range based for

src/jdlib/miscutil.cpp
イテレーターを終端チェックする前にデリファレンスしているとcppcheck 2.6.2に指摘されたため修正します。
cppcheckのレポート
```
src/jdlib/miscutil.cpp:609:26: warning: Either the condition 'it==list_num.end()' is redundant or there is possible dereference of an invalid iterator: it. [derefInvalidIteratorRedundantCheck]
const int num = *it;
^
src/jdlib/miscutil.cpp:610:39: note: Assuming that condition 'it==list_num.end()' is not redundant
if( num_from + i != num || it == list_num.end() ){
^
src/jdlib/miscutil.cpp:609:26: note: Dereference of an invalid iterator
const int num = *it;
^
```
=> miscutil: Fix dereference invalid iterator

src/dbtree/root.cpp
ローカル変数の名前が関数をシャドーイングしているとcppcheck 2.6.2に指摘されたため修正します。
cppcheckのレポート
```
src/dbtree/root.cpp:706:15: style: Local variable 'stat' shadows outer function [shadowFunction]
const int stat = is_moved( root, path_board, name, &board, etc );
^
/usr/include/x86_64-linux-gnu/sys/stat.h:205:12: note: Shadowed declaration
extern int stat (const char *__restrict __file,
^
src/dbtree/root.cpp:706:15: note: Shadow variable
const int stat = is_moved( root, path_board, name, &board, etc );
^
```
=> Root: Rename local variable to avoid shadow function

src/jdlib/loader.cpp
C言語スタイルのキャストを使っているとcppcheck 2.6.2に指摘されたため修正します。また、IPアドレスのデバッグプリントをIPv6に対応します。
参考文献
https://man7.org/linux/man-pages/man3/inet_ntop.3.html
cppcheckのレポート
```
src/jdlib/loader.cpp:1039:44: style: C-style pointer casting detected. C++ offers four different kinds of casts as
replacements: static_cast, const_cast, dynamic_cast and reinterpret_cast. A C-style cast could evaluate to any of
those automatically, thus it is considered safer if the programmer explicitly states which kind of cast is expected.
See also: https://www.securecoding.cert.org/confluence/display/cplusplus/EXP05-CPP.+Do+not+use+C-style+casts. [cstyleCast]
<< ", ip =" << inet_ntoa( (  ( sockaddr_in* )( res->ai_addr ) )->sin_addr ) << std::endl;
^
```
=> Loader: Use reinterpret_cast instead of C-style pointer casting

src/article/drawareabase.cpp, src/article/drawareabase.h
`DrawAreaBase::is_separator_on_screen()`が使われていないとcppcheck 2.6.2に指摘されたため整理します。
commit 327b431a1b6726f94ece668cba4264d3d32a1c9a (2008-11)で削除されてから使われていませんでした。
cppcheckのレポート
```
src/article/drawareabase.cpp:506:0: style: The function 'is_separator_on_screen' is never used. [unusedFunction]
```
=> DrawAreaBase: Remove unused member function is_separator_on_screen()

src/board/boardviewbase.cpp, src/board/boardviewbase.h, src/skeleton/view.h, src/skeleton/viewnote.h
`BoardViewBase::redraw_scrollbar()`が使われていないとcppcheck 2.6.2に指摘されたため整理します。
commit c67716bef729d8f88ac5df9e1c61da29ab785ec6 (2020-07)で削除されてから使われていませんでした。
cppcheckのレポート
```
src/board/boardviewbase.cpp:1225:0: style: The function 'redraw_scrollbar' is never used. [unusedFunction]
```
=> BoardViewBase: Remove unused member function redraw_scrollbar()

src/history/historymanager.cpp, src/history/historymanager.h
`History_Manager::replace_current_url_viewhistory()`が使われていないとcppcheck 2.6.2に指摘されたため整理します。
commit db8adb132a82fe5c4b024e1691f2e0d6995564b3 (2010-09)で呼び出し元が削除されてから使われていませんでした。
cppcheckのレポート
```
src/history/historymanager.cpp:431:0: style: The function 'replace_current_url_viewhistory' is never used. [unusedFunction]
```
=> History_Manager: Remove unused replace_current_url_viewhistory()

src/jdlib/miscutil.cpp
文字列をパーセントエンコーディングに変換する処理で16進数表記のA-Fを小文字から大文字に変更します。
[RFC3986][1]では大文字を使うべきと書かれています。
> For consistency, URI producers and normalizers should use uppercase hexadecimal digits for all percent-encodings.
https://next2ch.net/test/read.cgi/linux/1613035222/557
https://mao.5ch.net/test/read.cgi/linux/1615781919/869
[1]: https://datatracker.ietf.org/doc/html/rfc3986#section-2.1
=> miscutil: Fix percent encoding to use uppercase

README.md
コンパイラ最適化の例に使用しているCPUが古く実行不可能ではありませんが現実的には厳しいためより新しい世代(sandy bridge)のものに更新します。
=> readme: Update example cpu for compiler optimization

src/main.cpp
XSMP(セッション管理)の初期化に失敗したときAPIから取得したエラーメッセージをコンソールに出力するように修正します。
=> Add error message for XSMP initialization failure to console log

src/skeleton/editcolumns.cpp, src/skeleton/editcolumns.h
`EditColumns::copy_row()`が使われていないとcppcheck 2.6.2に指摘されたため整理します。
commit 94c0d66bf11bb86ed160a1511448c69e38c95101 (2008-12) で呼び出し元が削除されてから使われていませんでした。
cppcheckのレポート
```
src/skeleton/editcolumns.cpp:49:0: style: The function 'copy_row' is never used. [unusedFunction]
```
=> EditColumns: Remove unused member function copy_row()

snap/snapcraft.yaml
Snap版が利用している[gnome-3-34-1804 extension][1]はCPUアーキテクチャーi386に対応していません。
前のバージョンの[gnome-3-28-1804][2]はi386に対応＆JDimの動作環境もサポートしています。
そのため一時的に設定を切り替えてi386向けのSnapパッケージをビルドしてリリースします。
[1]: https://snapcraft.io/gnome-3-34-1804
[2]: https://snapcraft.io/gnome-3-28-1804
=> Set snapcraft config for i386 (2022-01)

snap/snapcraft.yaml
This reverts commit d45707a07c171782c74bced3f0ae07af1da263da.
Snapのビルド設定をgnome-3-38-1804 extensionを使うように差し戻します。
=> Revert "Set snapcraft config for i386 (2022-01) (#893)"

.github/workflows/ccpp.yml, CONTRIBUTING.md, INSTALL, README.md, configure.ac, docs/manual/make.md, meson.build
2018年以降にリリースされたディストロでは使われていない古いgcc(バージョン7未満)のサポートを終了します。
合わせてgnutlsやopensslのバージョン要件とLinuxの推奨環境も更新します。
また、CI設定からサポートしなくなったコンパイラを利用するビルドを取り除いて整理します。
- glibmm >= 2.56.0
- gnutls >= 3.5.18
- openssl >= 1.1.0
- gcc >= 7 または clang >= 6.0
- Linux Kernel >= 4.4.0 (推奨環境)
Ubuntu 18.04より古いプラットフォームではビルドと実行が困難になります。
CONTRIBUTING.mdの"C++ソースコードを修正するときの注意"を更新してC++17を使うように案内します。また注意する点としてJDimの動作環境に合わない標準ライブラリをリストします。
関連のissue: #777
=> Update requirements for dependencies (gcc >= 7)

.github/workflows/ccpp.yml, INSTALL, configure.ac, docs/manual/make.md, meson.build, meson_options.txt, src/Makefile.am, src/jdlib/jdregex.cpp, src/jdlib/jdregex.h, src/meson.build, test/Makefile.am
廃止予定の正規表現ライブラリのビルドオプション`--with-regex`を削除します。
削除されたオプションを指定すると./configureがエラーになり中断されます。
また、CI設定から正規表現ライブラリを指定するテストを取り除いて整理します。
Onigurumaのサポート終了により使われなくなったコードを削除します。
関連のissue: #697
=> Remove deprecated build option for regex

src/article/drawareabase.cpp, src/bbslist/bbslistviewbase.cpp, src/board/boardviewbase.cpp
switch文にあるfallthrough箇所のコンパイラ警告を抑制するため書いていたコメントをC++17の属性`[[fallthrough]]`に置き換えます。
=> Replace fallthrough comments with C++17 attribute

src/skeleton/admin.cpp
null pointerにアクセスしているとscan-build(llvm-13)に指摘されたためチェックを追加します。
scan-buildのレポート
```
[202/318] Compiling C++ object src/skeleton/libskeleton.a.p/admin.cpp.o
../../../src/skeleton/admin.cpp:1439:36: warning: Called C++ object pointer is null [core.CallAndMessage]
if( view == current_view ) view->redraw_view();
^~~~~~~~~~~~~~~~~~~
1 warning generated.
```
=> Admin: Add null pointer check

src/bbslist/editlistwin.cpp, src/bbslist/selectdialog.cpp, src/iomonitor.cpp, src/skeleton/aboutdiag.cpp
`sigc::mem_fun()`に渡す`this`をポインターから参照(`*this`)に変更します。
ポインター版のオーバーロードは廃止予定になっています。
=> Change first argument of sigc::mem_fun() to reference value *this

src/bbslist/selectdialog.cpp, src/board/boardviewbase.cpp, src/core.cpp, src/replacestrpref.cpp, src/skeleton/menubutton.cpp
`sigc::mem_fun()`を使ってメンバー関数をシグナルに接続するように変更します。
`sigc::trackable`を継承したオブジェクトが破棄されるとき接続が解除されます。
https://developer-old.gnome.org/libsigc++/2.10/group__mem__fun.html#details
=> Replace lambda with sigc::mem_fun() for signal connection

docs/manual/operation.md, src/jdlib/jdregex.cpp, src/jdlib/jdregex.h, src/searchmanager.cpp, test/Makefile.am, test/gtest_jdlib_jdregex.cpp, test/meson.build
正規表現の名前付きキャプチャ機能をラッパークラスに実装します。
グループ名またはグループ番号でマッチした文字列を取得する関数を追加します。
グループ名のみの取得APIは実際に使う箇所がないため今回は実装しません。
about:configの `スレタイ検索時にアドレスとスレタイを取得する正規表現`に名前付きキャプチャ対応を追加します。(暫定サポート)
設定した正規表現パターンにグループ名が有れば名前付きキャプチャ、無ければグループ番号で対象を取得します。また、互換性のためグループ番号は現状を維持します。
取得対象     | グループ番号 | グループ名 | 備考
---          | ---          | ---        | ---
スレURL      | 1            | url        | 必須
スレタイトル | 2            | subject    | 必須
レス数       | 3            | number     | オプション
関連のissue: #697
=> Regex: Implement named captures

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
=> Use std::string_view for NodeTreeBase::create_node_multispace()

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
=> Use std::string_view for NodeTreeBase::create_node_anc()

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
=> Use std::string_view for NodeTreeBase::create_node_thumbnail()

src/icons/iconmanager.cpp
「お気に入りに追加」ボタンのアイコンが分かりにくいためXDGアイコンを"emblem-favorite"に変更します（テーマによって異なるが星やハートマークなどが表示される）。
読み込み失敗したときは変更前の"edit-copy"を使います。
https://next2ch.net/test/read.cgi/linux/1613035222/678-680
=> ICON_Manager: Change APPENDFAVORITE icon

src/board/boardviewbase.cpp
スレ一覧のショートカットキーで呼び出す「お気に入りに追加」のダイアログにキャンセルボタンとアクセラレータキーを追加して利便性を向上させます。
https://next2ch.net/test/read.cgi/linux/1613035222/686-689
=> BoardViewBase: Add accelerator keys to dialog

src/jdlib/Makefile.am, src/jdlib/jdregex.cpp, src/jdlib/jdregex.h, src/jdlib/span.h, src/searchmanager.cpp, test/Makefile.am, test/gtest_jdlib_span.cpp, test/meson.build
C++20 [`std::span`][1] のサブセットを実装します。
配列型のビュークラスで所有権を持たず参照するオブジェクトの寿命は管理しません。
- 順方向イテレーターはポインターを使って実装
- テンプレート引数の整数によるサイズ指定は未実装
[1]: https://en.cppreference.com/w/cpp/container/span
vectorの移動やコピーがない関数の引数を配列のビュークラスに交換します。
関連のpull request: ma8ma#64
=> Implement `JDLIB::span<T>` class

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
=> Use std::string_view for NodeTreeBase::create_node_img()

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
=> Use std::string_view for NodeTreeBase::create_node_link()

src/icons/iconmanager.cpp
前のアイコン変更(571af0f3fd)ではテーマごとにアイコンの意味合いが違っていました（星は重要性、ハートはポジティブ感情）。
そのため再度「お気に入りに追加」ボタンのアイコンを変更し"bookmark-new"にします（星や栞にプラス記号が付いて表示される）。
読み込み失敗したときは変更前の"edit-copy"を使います。
https://next2ch.net/test/read.cgi/linux/1613035222/694-697
=> ICON_Manager: Change APPENDFAVIRITE icon (retake)

src/article/articleadmin.cpp, src/article/articleadmin.h, src/board/boardadmin.cpp, src/board/boardadmin.h, src/skeleton/admin.cpp, src/skeleton/admin.h
タブの右クリックメニューに「お気に入りに追加」を実装します。
メニュー項目を選択すると追加先を選択するダイアログを呼び出します。
また、仮想板や抽出ビューのタブはお気に入りに追加を選択不可にします。
XXX: 選択不可の条件は誤判定になる可能性がある (ソースを参照)
https://next2ch.net/test/read.cgi/linux/1613035222/676
関連のissue: #910
=> Admin: Add append-favorite to tab context menu

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
変更不可の文字列のポインターと長さを渡しているメンバ関数の引数を
`std::string_view`に交換して整理します。
=> Use std::string_view for NodeTreeBase::create_node_thumbnail() part2 part3

src/core.cpp
履歴ビューの板一覧、板履歴、最近閉じた板、最近閉じた画像はタブで開いても空欄で何も表示されないためタブや仮想板を作れないように変更します。
=> Core: Disable virtual board for non-thread's histories

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
=> Use std::string_view for NodeTreeBase::create_node_sssp()

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
=> Use std::string_view for NodeTreeBase::create_node_img() part2

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
=> Use std::string_view for NodeTreeBase::create_node_anc() part2

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
以前の修正(63d5b6c6a1f)で`NodeTreeBase::check_link()`の実装をインライン定義と`NodeTreeBase::check_link_impl()`に分割して最適化していました。
2022年の環境では最適化の効果が体感できないためコードを整理します。
=> Merge implementation of NodeTreeBase::check_link()

src/skeleton/aboutdiag.cpp
GTK4で[`Gtk::Widget::override_font()`][w]が廃止されたため[`Pango::Attribute`][a]を使って`AboutDiag`のバージョン番号を大きく表示するように修正します。
[w]: https://developer-old.gnome.org/gtkmm/3.24/classGtk_1_1Widget.html#abebbcb37aa062683ca2593f0555b31ae
[a]: https://developer-old.gnome.org/pangomm/2.46/classPango_1_1Attribute.html
=> AboutDiag: Use Pango::Attribute to show version number bigger

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
=> Use std::string_view for NodeTreeBase::create_node_link() part2

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
=> Use std::string_view for NodeTreeBase::create_node_text()

src/iomonitor.cpp, src/iomonitor.h
デバッグビルドで使えるFIFOを介した終了コマンドを削除します。
デフォルトのビルドではデバッグビルドが無効になっているためコマンドを使う機会がほとんどありませんでした。
=> IOMonitor: Remove quit command for debug build

src/article/drawareabase.cpp, src/jdlib/misccharcode.cpp, src/jdlib/misccharcode.h, src/jdlib/miscutil.cpp, test/Makefile.am, test/gtest_jdlib_misccharcode.cpp, test/meson.build
UTF-8で符号化された文字のバイト数を返す関数を追加する。
また、バイト数を取得するコードを実装した関数に更新する。
=> Implement MISC::utf8bytes()

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
=> Use std::string_view for NodeTreeBase::parse_name()

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
=> Use std::string_view for NodeTreeBase::parse_mail()

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
=> Use std::string_view for NodeTreeBase::parse_date_id()

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
=> Use std::string_view for NodeTreeBase::parse_write()

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
=> Use std::string_view for NodeTreeBase::parse_html()

src/main.cpp
接続が閉じられたソケットに書き込むと強制終了するため原因となるシグナル(SIGPIPE)を無視するように設定します。
=> Set signal action to ignore SIGPIPE for preventing crash

src/iomonitor.cpp, src/iomonitor.h, src/main.cpp
メンバー関数のパラメータ型をリファクタリングして関数実装を整理します。
=> IOMonitor: Refactor parameter type of member function

src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, src/replacestrmanager.cpp
=> Use std::string_view for MISC::chref_decode()

src/dbtree/nodetreebase.cpp, src/replacestrmanager.cpp, src/replacestrmanager.h
変更不可の文字列のポインターと長さを渡しているメンバー関数の引数を`std::string_view`に交換して整理します。
=> Use std::string_view for ReplaceStr_Manager::replace()

src/jdlib/miscutil.cpp, src/jdlib/miscutil.h
第1引数(haystack)はヌル終端を保証する必要があるため`const std::string&`を維持します。
=> Use std::string_view for MISC::ascii_ignore_case_find()

src/article/drawareabase.cpp
既に条件が判明している比較があるとcppcheck 2.7.1に指摘されたため条件文を修正します。直前のif文で条件をチェックしています。
cppcheckのレポート
```
src/article/drawareabase.cpp:2979:13: style: Condition 'm_vscrbar' is always true [knownConditionTrueFalse]
if( m_vscrbar && ( m_scrollinfo.mode == SCROLL_NOT || m_scrollinfo.mode == SCROLL_NORMAL ) ){
^
```
=> DrawAreaBase: Fix known condition true/false

src/article/drawareabase.cpp, src/article/font.cpp, src/article/font.h
フォントの文字幅を取得するUnicode文字をUTF-8バイト列＆長さ渡しからUTF-32コードポイント渡しに変更してエンコーディングの変換処理を整理します。
フォントの文字幅を登録するUnicode文字をUTF-8バイト列＆長さ渡しからUTF-32コードポイント渡しに変更してエンコーディングの変換処理を整理します。
=> Update function parameters for font width caching

README.md, docs/manual/start.md
gcc(バージョン10以降)を使いAddressSanitizer(ASan)を有効にしてビルドすると書き込みのプレビューでトリップを表示するときにクラッシュすることがあります。
今のところ影響は開発者やメンテナーに限られているため直接修正はせずASanを有効にするときの注意と回避策をREADMEに追加して詳細は[github issueのリンク][1]に誘導します。
背景
リンカの`-Wl,--as-needed`フラグをつけて`-fsanitize=address`でコンパイルするとlibcryptではなくlibasanの中にあるcrypt, crypt_rがリンクされますが実体がなく呼び出すとSIGSEGVが発生します。
<https://bugzilla.redhat.com/show_bug.cgi?id=1827338>
[1]: https://github.com/JDimproved/JDim/issues/943
issue: #943
=> readme: Add information about crash with asan

src/jdlib/loader.cpp, src/jdlib/loader.h
=> Use std::string_view for Loader::analyze_header_option()

src/jdlib/loader.cpp, src/jdlib/loader.h
=> Use std::string_view for Loader::analyze_header_option_list()

src/article/drawareabase.cpp, src/jdlib/jdiconv.cpp, src/jdlib/misccharcode.cpp, src/jdlib/misccharcode.h, src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, test/gtest_jdlib_misccharcode.cpp
jdlib/miscutil.h の`MISC::utf8toucs2()` のかわりに jdlib/misccharcode.h にUTF-8バイト列からUTF-32のコードポイントを返す関数を実装する。
関連のissue: #76
=> Implement MISC::utf8toutf32()

src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, test/gtest_jdlib_miscutil.cpp
=> Use std::string_view for MISC::remove_str(str, start, end)

src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, src/skeleton/editview.cpp, test/gtest_jdlib_miscutil.cpp
=> Use std::string_view for MISC::replace_str()

src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, test/gtest_jdlib_miscutil.cpp
=> Use std::string_view for MISC::replace_str_list()

src/article/drawareabase.cpp, src/jdlib/misccharcode.cpp, src/jdlib/misccharcode.h, src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, src/skeleton/editview.cpp, test/gtest_jdlib_misccharcode.cpp
jdlib/miscutil.h の`MISC::get_ucs2mode()`のかわりに jdlib/misccharcode.h にUnicodeコードポイントの大まかな種類を返す関数を追加する。
さらに`MISC::get_ucs2mode()`を呼び出している箇所を更新する。
関連のissue: #76
=> Implement MISC::get_unicodeblock()

src/icons/iconmanager.cpp
アイコンの読み込みを修正して起動時にクラッシュしないようにします。
アイコンが見つからないときは同名のsymbolic iconを探してsymbolicも見つからないときは代替のアイコン(点線の矩形)を表示するようにします。
JDimで使用するアイコンはGNOME(GTK3)のデフォルトテーマで使われている[Adwaita Icon Theme][1]を参照しています。
新しいバージョンのGNOMEでは[symbolic icon][2]を使うように更新されたためテーマから[color iconが削除][3]されました。
そのため最新のGNOME環境(v42)ではアイコンの読み込みに失敗してJDimが起動しない問題がありました。
[1]: https://gitlab.gnome.org/GNOME/adwaita-icon-theme/
[2]: https://developer.gnome.org/hig/guidelines/ui-icons.html
[3]: https://www.spinics.net/lists/fedora-devel/msg298835.html
関連のissue: #954
=> ICON_Manager: Fix icon loading to prevent crash on start

meson.build
OpenBSDでmesonを実行すると`crypt(3)`でエラーになると報告がありました。
mesonはlibcryptライブラリを探しますが[OpenBSDのcrypt関数][1]は実体がlibcにあるためチェック漏れしていたようです。
そのためライブラリが見つからないときは直接crypt関数を探すように修正します。
https://mevius.5ch.net/test/read.cgi/unix/1568040383/740
[1]: https://man.openbsd.org/crypt.3
=> meson: Fix check for crypt(3) to improve OpenBSD support

src/jdlib/miscutil.cpp, src/jdlib/miscutil.h
`MISC::count_str()`が使われていないとcppcheck 2.6.2に指摘されたため整理します。
commit 548112fe697b38fdcdb403ebb7f99c8839fb6790 (2008-08)
で呼び出し元が削除されてから使われていませんでした。
cppcheckのレポート
```
src/jdlib/miscutil.cpp:525:0: style: The function 'count_str' is never used. [unusedFunction]
```
=> Remove unused MISC::count_str()

src/jdlib/miscutil.cpp, src/jdlib/miscutil.h
=> Use std::string_view for MISC::remove_str(str, pattern)

src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, test/gtest_jdlib_miscutil.cpp
=> Use std::string_view for MISC::cut_str()

src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, test/gtest_jdlib_miscutil.cpp
=> Use std::string_view for MISC::replace_newlines_to_str()

src/iomonitor.cpp, src/iomonitor.h, src/main.cpp
GTK4で廃止される`Gtk::Main`を`Gtk::Application`に置き換えます。
コードは最小限の変更で維持します。
`{Gio,Gtk}::Application`の機能を更に利用して起動処理を行うように変更します。
**特徴**
* コマンドライン引数の処理に`Gio::Application`のAPIを利用する影響で  フラグオプションに引数をつけてもエラーにならず無視される
* GUI環境でなくともコマンドラインの`--help`, `--version`が利用できる
* `Gio::Application`のアプリケーションIDによるメイン/サブの  プロセス管理は使用せず従来のロックファイル(fifo)による制御を維持する
**未修正の問題**
signal(SIGINT SIGHUP...)が発生し強制終了するとfifoが削除されず残る
**参考文献**
* https://developer-old.gnome.org/glibmm/2.66/classGio_1_1Application.html
* https://developer-old.gnome.org/gtkmm/3.24/classGtk_1_1Application.html
* https://gitlab.com/inkscape/inkscape/-/blob/INKSCAPE_1_1_2/src/inkscape-application.h
* http://transit.iut2.upmf-grenoble.fr/doc/gtkmm-3.0/tutorial/html/chapter-building-applications.html#sec-buildapp-trivial-app
関連のissue: #782 
関連のpull request: …
=> Implement App class to use GtkApplication features

src/dbtree/nodetreebase.cpp, src/dbtree/spchar_decoder.cpp, src/jdlib/misccharcode.cpp, src/jdlib/misccharcode.h, src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, test/gtest_jdlib_misccharcode.cpp
jdlib/miscutil.h の`MISC::ucs2toutf8()`の代替としてjdlib/misccharcode.h にUnicodeのコードポイントからUTF-8のバイト列へ
変換する関数を追加する。さらに`MISC::ucs2toutf8()`はもう必要ないので削除する。
=> Implement MISC::utf32toutf8()

src/article/articleviewbase.cpp, src/board/preference.cpp, src/cssmanager.cpp, src/environment.cpp, src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, src/message/logitem.h, src/message/logmanager.cpp, src/xml/dom.cpp, test/gtest_jdlib_miscutil.cpp
関数の名称が紛らわしいため名前を変更します。さらに実装を自作のループから`std::string`のメンバー関数に置き換えてコードを整理します。
=> Rename function MISC::remove_spaces() to MISC::ascii_trim()

src/usrcmdpref.cpp, src/usrcmdpref.h
GTK4で廃止される`Gtk::ActionGroup`をGTK3から導入された`Gio::SimpleActionGroup`に置き換えます。
ショットカットキーの表示はユーザーコマンドのダイアログボックスには効果がないため削除します。
```
```
<details>
```
../src/usrcmdpref.h:54:28: error: 'UIManager' is not a member of 'Gtk'
54 |         Glib::RefPtr< Gtk::UIManager > m_ui_manager;
|                            ^~~~~~~~~
../src/usrcmdpref.h:54:28: error: 'UIManager' is not a member of 'Gtk'
../src/usrcmdpref.h:54:38: error: template argument 1 is invalid
54 |         Glib::RefPtr< Gtk::UIManager > m_ui_manager;
|                                      ^
../src/usrcmdpref.cpp:98:40: error: incomplete type …
```
=> UsrCmdPref: Use Gio::SimpleActionGroup instead of Gtk::ActionGroup

src/jdlib/misccharcode.cpp, src/jdlib/misccharcode.h, src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, src/message/logitem.h, test/gtest_jdlib_misccharcode.cpp
WAVE DASH(U+301C)などのWindows系UTF-8文字をUnix系文字と相互変換する関数`MISC::utf8_fix_wavedash()` を jdlib/miscutil.h からjdlib/misccharcode.h へ移動し、実装をリファクタリングする。
関連のissue: #76
=> Move MISC::utf8_fix_wavedash() from miscutil to misccharcode

src/jdlib/misccharcode.cpp, src/jdlib/misccharcode.h, test/gtest_jdlib_misccharcode.cpp
関数名をより正確に変更します。また、引数を更新して処理を効率化します。
追加された長さチェックはヌル終端の保証がある `const std::string&`なら不要ですが他の`is_*`関数との一貫性のため`std::string_view`を使います。
=> Update function MISC::is_euc() to MISC::is_eucjp()

src/jdlib/misccharcode.cpp, src/jdlib/misccharcode.h, test/gtest_jdlib_misccharcode.cpp
関数の引数を更新して処理を効率化します。呼び出し元の処理のため空文字列に対する返り値は他の`is_*`関数と逆(false)になっています。
関連のpull request: #971
=> Update function MISC::is_jis()

src/jdlib/misccharcode.cpp, src/jdlib/misccharcode.h, test/gtest_jdlib_misccharcode.cpp
関数の引数を更新して処理を効率化します。
追加された長さチェックはヌル終端の保証がある`const std::string&`なら不要ですが他の`is_*`関数との一貫性のため`std::string_view`を使います。
関連のpull request: #971
=> Update function MISC::is_sjis()

src/jdlib/misccharcode.cpp, src/jdlib/misccharcode.h, test/gtest_jdlib_misccharcode.cpp
関数の引数を更新して処理を効率化します。
追加された長さチェックはヌル終端の保証がある`const std::string&`なら不要ですが他の`is_*`関数との一貫性のため`std::string_view`を使います。
関連のpull request: #971
=> Update function MISC::is_utf8()

src/article/drawareabase.cpp
構造体のリストを走査して条件を満たしたとき返す値を固定値で補正していましたがリストの前後要素を一時変数に保持しておくことで変数値をそのまま返すように修正します。
関連のpull request: #76
=> DrawAreaBase: Modify loop to return the variable value just as it is

src/jdlib/loader.cpp, src/jdlib/loader.h, test/Makefile.am, test/gtest_jdlib_loader.cpp, test/meson.build
Chunked transfer encodingのデコード処理を見直してHTTPの仕様により近くなるよう改善したものを追加します。
* サイズ部の終端はCRLFを探すようにしてLFのみの入力は無効にする
* サイズ部の解析は入力の長さ制限を撤廃して解析結果のチェックを追加する
* 最後のチャンク(長さ0)を読み込んだらトレーラー部は解析せず処理を完了する
新たに実装したChunked transfer encodingのデコード処理を導入して前の実装を削除します。
関連のissue: #975
=> Loader: Improve proccesing for Chunked transfer encording

src/jdlib/ssl.cpp
OpenSSLを使うコードを更新してバージョン3.0に対応します。
* ライブラリからエラーメッセージを取得
* 非推奨となったTLS 1.2未満のプロトコルはサポートしない
* サーバー証明書の検証を行う
* 読み込み書き込み処理の再試行を追加
関連のissue: #975
=> Update OpenSSL client codes to support version 3.0

src/skeleton/selectitempref.cpp
Replace while loop with range-based for statement or object member function to organize codes.
related pull request: #968
=> SelectItemPref: Improve while loop

src/jdlib/loader.cpp, test/gtest_jdlib_loader.cpp
`ChunkedDecoder::decode()`の処理が完了した後にさらに入力を渡して呼び出すと終了条件を満たせず無限ループする問題を修正します。
関連のpull request: #981
=> ChunkedDecoder: Fix condition for breaking loop

src/history/historysubmenu.cpp, src/skeleton/admin.cpp, src/skeleton/admin.h, src/skeleton/menubutton.cpp, src/skeleton/menubutton.h, src/usrcmdpref.cpp
GTK 3.24.6 未満のバージョンではメニューのスクロールが出来なくなることがあるため条件コンパイルで以前の実装へ差し戻します。
Debian busterのGTK3のバージョンが3.24.5で影響を受けていました。
原因となった修正
* 8d8b246df9d8a517bba039896b65697c01a6fe99
* 81bfe64cacc292dc5f181a8e2623cb412d865112
関連のissue(GNOME)
https://gitlab.gnome.org/GNOME/gtk/-/issues/1651
関連のissue(JDim)
#985
=> Revert Gtk::Menu API to fix menu scrolling on older GTK

src/article/articleviewbase.cpp
外側の関数をシャドーイングするローカル変数があるとcppcheck 2.8に指摘されたため修正します。
cppcheckのレポート
```
src/article/articleviewbase.cpp:673:19: style: Local variable 'width_client' shadows outer function [shadowFunction]
const int width_client = m_drawarea->width_client();
^
src/article/articleviewbase.cpp:690:19: style: Local variable 'height_client' shadows outer function [shadowFunction]
const int height_client = m_drawarea->height_client();
^
```
=> ArticleViewBase: Fix local variable names that shadow outer function

src/image/imageadmin.cpp, src/skeleton/msgdiag.cpp, src/skeleton/prefdiag.cpp
外側の関数をシャドーイングするローカル変数があるとcppcheck 2.8に指摘されたため修正します。
cppcheckのレポート
```
src/image/imageadmin.cpp:122:14: style: Local variable 'lock' shadows outer function [shadowFunction]
bool lock = false;
^
src/skeleton/msgdiag.cpp:83:24: style: Local variable 'slot_timeout' shadows outer function [shadowFunction]
sigc::slot< bool > slot_timeout = sigc::bind( sigc::mem_fun(*this, &MsgDiag::slot_timeout), 0 );
^
src/skeleton/prefdiag.cpp:100:24: style: Local variable 'slot_timeout' shadows outer function [shadowFunction]
sigc::slot< bool > slot_timeout = sigc::bind( sigc::mem_fun(*this, &PrefDiag::slot_timeout), 0 );
^
```
関連のpull request: #988
=> Fix local variable names that shadow outer function part2

src/skeleton/window.cpp
値が既知の条件があるとcppcheck 2.8に指摘されたため修正します。
```
src/skeleton/window.cpp:621:17: style: Condition '!is_maximized_win()' is always true [knownConditionTrueFalse]
if( ! is_maximized_win() && ! is_iconified_win() && get_window() ) set_win_pos();
^
```
関連のpull request: #988
=> JDWindow: Fix known condition true/false

src/dbtree/board2chcompati.cpp
open2ch.netに書き込みを行うと404 Not Foundになる問題を修正します。
修正前は書き込みで確認ページが表示されたときページに埋め込まれたURL、またはデフォルトの"/test/subbbs.cgi"を使って再度投稿していました。
open2chは確認ページにURLが埋め込まれていないためデフォルト設定を使いますが"subbbs.cgi"が存在しないためエラーになっていました。
["subbbs.cgi"は廃止][1]されているためデフォルト設定を"/test/bbs.cgi"に変更することで修正します。
関連のissue: #991 
[1]: https://info.5ch.net/?curid=686
=> Board2chCompati: Modify default subbbs.cgi path to /test/bbs.cgi

src/skeleton/admin.cpp, src/skeleton/admin.h, src/skeleton/tabswitchmenu.cpp, src/skeleton/tabswitchmenu.h
タブの右クリックメニューの構築を更新して廃止予定の`GtkAction`や`GtkUIManager`のかわりに`GAction`、`GtkBuilder`、`GMenu`を使った方法にします。
合わせて、GTK4で廃止される`GtkMenu`への依存を減らすためメニューラベルにアクセラレーターキーやマウスジェスチャーの表示を追加する処理を削除します。
参考文献
* https://wiki.gnome.org/HowDoI/GAction
* https://wiki.gnome.org/HowDoI/GMenu
関連のissue: #977
=> Admin: Update context menu construction to use Gio::Menu

src/article/drawareabase.h, src/jdlib/loader.cpp, src/jdlib/miscutil.cpp, src/message/messageviewbase.cpp
C言語スタイルのポインターキャストではなくC++のキャストを使うべきとcppcheck 2.8に指摘されたため修正します。
> C-style pointer casting detected. C++ offers four different kinds of casts as replacements: static_cast, const_cast, dynamic_cast and reinterpret_cast. A C-style cast could evaluate to any of those automatically, thus it is considered safer if the programmer explicitly states which kind of cast is expected. See also: https://www.securecoding.cert.org/confluence/display/cplusplus/EXP05-CPP.+Do+not+use+C-style+casts. [cstyleCast]
cppcheckのレポート
```
src/article/drawareabase.h:516:42: style: C-style pointer casting detected. (snip) [cstyleCast]
const unsigned char* tmpchar = ( const unsigned char* ) str;
^
src/jdlib/loader.cpp:1502:63: style: C-style pointer casting detected. (snip) [cstyleCast]
if( byte_out && m_loadable ) …
```
=> Fix C-style pointer cast part1

src/jdlib/jdiconv.cpp, src/jdlib/jdiconv.h
C言語スタイルのポインターキャストではなくC++のキャストを使うべきとcppcheck 2.8に指摘されたため修正します。
> C-style pointer casting detected. C++ offers four different kinds of casts as replacements: static_cast, const_cast, dynamic_cast and reinterpret_cast. A C-style cast could evaluate to any of those automatically, thus it is considered safer if the programmer explicitly states which kind of cast is expected. See also: https://www.securecoding.cert.org/confluence/display/cplusplus/EXP05-CPP.+Do+not+use+C-style+casts. [cstyleCast]
cppcheckのレポート
```
src/jdlib/jdiconv.cpp:26:16: style: C-style pointer casting detected. (snip) [cstyleCast]
m_buf_in = ( char* )malloc( BUF_SIZE_ICONV_IN );
^
src/jdlib/jdiconv.cpp:27:17: style: C-style pointer casting detected. (snip) [cstyleCast]
m_buf_out = ( char* )malloc( BUF_SIZE_ICONV_OUT );
^ …
```
=> Iconv: Fix C-style pointer cast part2

src/jdlib/loader.cpp, src/jdlib/loader.h
C言語スタイルのポインターキャストではなくC++のキャストを使うべきとcppcheck 2.8に指摘されたため修正します。
> C-style pointer casting detected. C++ offers four different kinds of casts as replacements: static_cast, const_cast, dynamic_cast and reinterpret_cast. A C-style cast could evaluate to any of those automatically, thus it is considered safer if the programmer explicitly states which kind of cast is expected. See also: https://www.securecoding.cert.org/confluence/display/cplusplus/EXP05-CPP.+Do+not+use+C-style+casts. [cstyleCast]
cppcheckのレポート
```
src/jdlib/loader.cpp:923:13: style: C-style pointer casting detected. (snip) [cstyleCast]
m_buf = ( char* )malloc( m_lng_buf + mrg );
^
src/jdlib/loader.cpp:1459:21: style: C-style pointer casting detected. (snip) [cstyleCast]
m_buf_zlib_in = ( Bytef* )malloc( sizeof( Bytef ) * …
```
=> Loader: Fix C-style pointer cast part3

src/article/drawareabase.cpp
代入した値を使ってないとcppcheck 2.8に指摘されたため代入を取り除きます。
```
src/article/drawareabase.cpp:2735:24: style: Variable 'n_byte' is assigned a value that is never used. [unreadVariable]
n_byte = 0;
^
src/article/drawareabase.cpp:2740:28: style: Variable 'n_byte' is assigned a value that is never used. [unreadVariable]
n_byte += byte_char;
^
```
関連のpull request: #988
=> DrawAreaBase: Get rid of variable assignments which never used

src/history/historymanager.cpp
変数のスコープ範囲を減らすことができるとcppcheck 2.8に指摘されたため静的変数を関数の外に移動します。
> style: The scope of the variable 'nullitems' can be reduced. Warning: Be careful when fixing this message, especially when there are inner loops. Here is an example where cppcheck will write that the scope for 'i' can be reduced:
> ```cpp
> void f(int x)
> {
>     int i = 0;
>     if (x) {
>         // it's safe to move 'int i = 0;' here
>         for (int n = 0; n < 10; ++n) {
>             // it is possible but not safe to move 'int i = 0;' here
>             do_something(&i);
>         }
>     }
> }
> ```
> When you see this message it is always safe to reduce the variable scope 1 level. [variableScope]
```
src/history/historymanager.cpp:467:44: style: The scope of the variable 'nullitems' can be reduced. (snip) [variableScope] …
```
=> History_Manager: Move static variable to outside of fucntion

src/board/boardviewbase.cpp, src/board/boardviewbase.h, src/control/controlutil.cpp, src/control/controlutil.h
コントロールIDに対応するアクセラレーターキーを`Gio::MenuItem`に追加する関数を実装します。
スレ一覧の右クリックメニューの構築を更新して廃止予定の`GtkAction`や`GtkUIManager`のかわりに`GAction`、`GtkBuilder`、`GMenu`を使った方法にします。
合わせて、GTK4で廃止される`GtkMenu`への依存を減らすためメニューラベルにアクセラレーターキーやマウスジェスチャーの表示を追加する処理を削除します。
カスタマイズ可能な通常メニューはアクセラレーターキーの表示を維持します。
参考文献
* https://wiki.gnome.org/HowDoI/GAction
* https://wiki.gnome.org/HowDoI/GMenu
関連のissue: #977
=> BoardViewBase: Update context menu construction to use Gio::Menu

src/bbslist/bbslistview.cpp, src/bbslist/bbslistviewbase.cpp, src/bbslist/bbslistviewbase.h, src/bbslist/favoriteview.cpp, src/bbslist/historyview.cpp, src/bbslist/selectlistview.cpp
サイドバーの右クリックメニューの構築を更新して廃止予定の`GtkAction`や`GtkUIManager`のかわりに`GAction`、`GtkBuilder`、`GMenu`を使った方法にします。
サイドバーの種類によっては使わないメニューがあるため構築を分けることでメモリ使用量を削減します。
合わせて、GTK4で廃止される`GtkMenu`への依存を減らすためメニューラベルにアクセラレーターキーやマウスジェスチャーの表示を追加する処理を削除します。
関連のissue: #977
=> BBSListViewBase: Update context menu construction to use Gio::Menu

src/image/imageviewicon.cpp, src/image/imageviewicon.h
画像ビューのアイコン背景色切り替えを更新して廃止予定の`Gtk::Widget::override_background_color()`をCSSによる設定に置き換えます。
選択されたアイコンの背景色は`$XDG_CONFIG_HOME/gtk-3.0/gtk.css`にCSSセレクタ`#jdim-imageview-icon.selected`の設定を追加することで変更できます。(テスト用のため変更の可能性がある)
=> ImageViewIcon: Use CSS styling instead of depreacted function

src/image/imageviewpopup.cpp, src/image/imageviewpopup.h
画像ポップアップの文字色、背景色の設定を更新して廃止予定の`Gtk::Widget::override_background_color()`や`override_color()`をCSSによる設定に置き換えます。
スタイルは`$XDG_CONFIG_HOME/gtk-3.0/gtk.css`にCSSセレクタ`#jdim-imageview-popup`の設定を追加することで変更できます。(テスト用のため変更の可能性がある)
キャッシュに[`jd.css`][1]を置くことで画像ポップアップのスタイルを設定できますがmarginの値がpaddingとして反映されます。
これはCSSとして正しくない動作ですがとりあえず修正前の動作を維持します。
[1]: https://jdimproved.github.io/JDim/skin/#stylesheet
関連のpull request: #1004
=> ImageViewPopup: Use CSS styling instead of depreacted function

docs/README.md, docs/manual/2022.md, meson.build, src/jdversion.h
オンラインマニュアルの履歴は項目の末尾にissue番号がついていますが位置が揃わず番号が見にくいため項目の先頭に表示するように履歴を生成するスクリプトを変更します。
また、マニュアルの更新方法は大きな変更がなく安定しているためREADMEの草案段階の表示は消します。
関連のissue: #951
=> Bump version to 0.8.0-beta

README.md, docs/manual/start.md
2023年1月のリリースでSnap i386(32bit)版の更新を終了することをドキュメントに記載します。
Snap i386版パッケージの基盤となっているUbuntu Core 18(Ubuntu 18.04 LTS)は2023年4月にサポートが終了します。新しいバージョンのUbuntu Core 20はi386をサポートしていないためSnap i386版の更新を行うことができません。
そのため2023年初頭のリリースをもってSnap i386版パッケージの更新を終了しSnapパッケージのベースをCore 20へ移行します。
関連のissue: #890
=> Prenotice end of update for snap i386 after 2023

src/bbslist/bbslistviewbase.cpp
if文の条件が繰り返し現れているとcppcheck 2.8に指摘されたため修正します。
cppcheckのレポート
```
src/bbslist/bbslistviewbase.cpp:403:17: style: Expression is always false because 'else if' condition matches previous condition at line 402. [multiCondition]
else if( id == "popup_menu" ) menu_ui = popup_menu;
^
```
=> BBSListViewBase: Fix duplicate if-coindition

src/skeleton/toolbar.cpp
ツールバーのボタンのフラット表示切り替えを更新してGTK4で廃止される`Gtk::Button::set_relief()`をCSSによる設定に置き換えます。
この修正はGTK3の実装を踏襲しています。
https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gtk/gtkbutton.c#L1588
関連のpull request: #1004
=> ToolBar: Use CSS styling for switching flat buttons

src/skeleton/toolbar.cpp, src/skeleton/toolbar.h
書き込みボタンからフォーカスが外れたときに実行するシグナルハンドラを削除します。
commit bf79a502b539bb9a3304d1e84f85ab49508ea3d4 (2020-08)
で処理が削除され何もしない状態になっていました。
=> ToolBar: Remove signal handler slot_focusout_write_button()

src/article/drawareabase.cpp, src/bbslist/bbslistviewbase.cpp, src/board/preference.cpp, src/browserpref.h, src/config/configitems.cpp, src/control/mousekeypref.cpp, src/core.cpp, src/cssmanager.cpp, src/dbtree/boardbase.cpp, src/dbtree/boardjbbs.cpp, src/dbtree/boardmachi.cpp, src/dbtree/nodetreemachi.cpp, src/jdlib/confloader.cpp, src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, src/message/post.cpp, src/passwdpref.h, src/proxypref.h, src/usrcmdmanager.cpp, test/gtest_jdlib_miscutil.cpp
以前変更した`MISC::ascii_trim()`[1]と同じく関数名を変更して何を行うのか分かりやすくします。
[1]: commit https://github.com/JDimproved/JDim/commit/62abdbfc55c9e1df8d92d862cfb33c33b8a01b90
`utf8_trim()`は入力に半角スペース(U+0020)が含まれてないときはトリミングが実行されない挙動になっています。
この挙動が合っているかどうか検証を考えていますが今のところはコメントとテストケースを追加して補足しておきます。
=> Rename function `MISC::remove_space()` to `MISC::utf8_trim()`

snap/snapcraft.yaml
Snap版が利用している[gnome-3-34-1804 extension][1]はCPUアーキテクチャーi386に対応していません。
前のバージョンの[gnome-3-28-1804][2]はi386に対応＆JDimの動作環境もサポートしています。
そのため一時的に設定を切り替えてi386向けのSnapパッケージをビルドしてリリースします。
[1]: https://snapcraft.io/gnome-3-34-1804
[2]: https://snapcraft.io/gnome-3-28-1804
=> Set snapcraft config for i386 (2022-07)

snap/snapcraft.yaml
This reverts commit 377dc0788f52c85c33614f415f1e990c34ace9b1.
Snapのビルド設定をgnome-3-38-1804 extensionを使うように差し戻します。
=> Revert "Set snapcraft config for i386 (2022-07) (#1012)"

src/jdlib/miscutil.cpp
std::stringの構築でnullの可能性があるポインターを渡しているとscan-build(clang 14)に指摘されたためポインターのチェックを修正します。
scan-buildのレポート
```
[179/322] Compiling C++ object src/jdlib/libjdlib.a.p/miscutil.cpp.o
../../../src/jdlib/miscutil.cpp:1632:23: warning: The parameter must not be null [cplusplus.StringChecker]
std::string env = getenv( name );
^~~~~~~~~~~~~~
```
=> miscutil: Fix std::string construction from pointer

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h, test/Makefile.am, test/gtest_dbtree_nodetreebase.cpp, test/meson.build
テストコードで呼び出すため関数をpublicにします。
比較演算の左辺値がgarbage valueであるとscan-build(llvm-14)に指摘されたためチェックを変更します。(偽陽性?)
scan-buildのレポート
```
[189/323] Compiling C++ object src/dbtree/libdbtree.a.p/nodetreebase.cpp.o
(snip)
../../../src/dbtree/nodetreebase.cpp:3672:23: warning: The left operand of '==' is a garbage value [core.UndefinedBinaryOperatorResult]
if( text[ i ] == '&' &&
~~~~~~~~~ ^
```
=> NodeTreeBase: Refactor convert_amp()

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h, test/gtest_dbtree_nodetreebase.cpp
テストコードで呼び出すため関数をpublicにします。
機能の改善
* URLが http[s]://jump.[25]ch.net/? で始まるときも削除するように変更します。
* 削除した残りにURLスキームが含まれているときは使います。
比較演算の左辺値がgarbage valueであるとscan-build(llvm-14)に指摘されたためチェックを変更します。
scan-buildのレポート
```
[187/322] Compiling C++ object src/dbtree/libdbtree.a.p/nodetreebase.cpp.o
../../../src/dbtree/nodetreebase.cpp:3643:13: warning: The left operand of '==' is a garbage value [core.UndefinedBinaryOperatorResult]
if ( *p == 's' ) p++;
~~ ^
../../../src/dbtree/nodetreebase.cpp:3653:28: warning: The left operand of '==' is a garbage value [core.UndefinedBinaryOperatorResult]
if ( p[cs_len] == '\0' ) return false;
~~~~~~~~~ ^
```
新規機能のテストケースを追加します。
=> NodeTreeBase: Improve remove_imenu()

src/dbtree/board2ch.cpp, src/dbtree/board2ch.h
2022-04-30 以降、5chでは SETTING.TXT の項目[`BBS_UNICODE`が無効][1]になったため設定値に関係なく空文字列を返すように変更します。
5chに書き込むときUnicodeモードの表示や動作がoffになります。
"pass" を返すほうが適切な値か？
[1]: https://agree.5ch.net/test/read.cgi/operate/1642399917/922
=> Board2ch: Change return value of get_unicode() to empty string

src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, src/message/messageviewbase.cpp, test/gtest_jdlib_miscutil.cpp
`MISC::html_escape()`の挙動を変更してHTMLで特別な意味を持つ記号(& " < >) *のみ* を文字実体参照へエスケープします。
また、これまでの挙動に依存しているコードは動作が変わらないように修正します。
関連のissue: #76
=> Update misc html escape

src/article/articleviewbase.cpp, src/article/articleviewsearch.cpp
抽出ビューやログ検索ビューで表示する板名に対してHTMLの特殊文字をエスケープするように修正します。
関連のissue: #76
=> article: Escape board name for extraction view

src/article/layouttree.cpp
連続半角スペースを表示しない設定のときは水平タブ(U+0009)を空白(U+0020)として表示します。
関連のissue: #76
=> LayoutTree: Show HTAB as single space if not multispace mode

src/message/post.cpp
投稿失敗のエラーメッセージ抽出を更新してSamba24の秒数を取得するパターンを変更します。
5chではSamba24は[既に廃止][1]されていますがぜろちゃんねるプラスを利用する掲示板などで導入されています。
https://info.5ch.net/?curid=1247#.E9.80.A3.E7.B6.9A.E6.8A.95.E7.A8.BF
[1]: https://info.5ch.net/index.php/Samba24
=> Post: Update error message extraction to support samba24

src/jdlib/ssl.cpp
接続が閉じられたソケットに書き込むと強制終了するため原因となるシグナル(SIGPIPE)を無効にするよう設定します。
https://gnutls.org/manual/html_node/Session-initialization.html
=> GnuTLS: Set GNUTLS_NO_SIGNAL to ignore SIGPIPE for preventing crash

src/board/boardviewbase.cpp, src/board/boardviewbase.h
スレ一覧に表示するスレタイトルをPANGO Markupで装飾して表示するように変更します。
https://docs.gtk.org/Pango/pango_markup.html
関連のissue: #76
=> BoardViewBase: Use PANGO markup to display thread subject

src/board/boardviewbase.cpp, src/board/boardviewbase.h
This reverts commit 3ec7460fd17307adac2116a5846587d413e0cdea.
コンソールにGTK警告が表示されたため原因のコミットを一旦差し戻します。
error log
```
(jdim:556244): Gtk-WARNING **: 20:58:40.881:
Failed to set text from markup due to error parsing markup:
1 行目にエラーがあります: エンティティ名“copy”は不明です
```
https://next2ch.net/test/read.cgi/linux/1613035222/979-981
=> Revert "BoardViewBase: Use PANGO markup to display thread subject (#1033)"

.github/workflows/ccpp.yml, README.md
Ubuntu 18.04のテスト環境が[使えなくなる][a]ため前倒しで18.04のサポートを放棄します。
次のリリースまで動作環境の変更は行いませんが18.04では問題が起こるかもしれません。
2019年より前にリリースされたディストリビューションを利用されている場合は更新をお願いいたします。
[a]: https://github.com/JDimproved/JDim/issues/1035
CIで利用しているアクションのバージョンを最新版に更新します。
Mesonのテスト実行するときに詳細な結果を出力するように設定します。
GitHub ActionsのCI設定を更新してUbuntu18.04のジョブ削減とUbuntu22.04のジョブを追加します。
[20 jobs][b]を超えると実行待機が発生するため廃止予定オプションとコンパイラオプションはテストから除外しています。
ディストロとツールチェーンの組み合わせも網羅していません。
Ubuntu18.04 は 2022-12-01 の[サポート終了][c]に向けてジョブの強制キャンセルが計画されているため失敗やキャンセルになってもCIが継続するように設定します。
コンパイラ: gcc-8 ~ gcc-11, clang-7.0 ~ clang-14 (clang-12は除く)
ディストロ: Ubuntu18.04, Ubuntu20.04, Ubuntu22.04
ビルドツール: Autotools, Meson
<details>
<summary>ビルドの構成 (20 jobs)</summary>
Mesonを利用したビルド (12 jobs)
Ubuntu18.04
- gcc-7
Ubuntu20.04
- gcc-8
- gcc-9
- gcc-10
- clang-7
- clang-8
- …
=> Abandon Ubuntu 18.04 support

src/article/articleadmin.cpp, src/article/articleview.cpp, src/article/articleviewbase.cpp, src/article/articleviewetc.cpp, src/article/preference.cpp, src/bbslist/bbslistviewbase.cpp, src/board/boardviewbase.cpp, src/board/boardviewnext.cpp, src/dbtree/articlebase.cpp, src/history/historymanager.cpp, src/image/preference.cpp, src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, src/message/messageview.cpp, src/skeleton/admin.cpp, src/usrcmdmanager.cpp, test/gtest_jdlib_miscutil.cpp
文字参照をデコードする際に前の文字を見て空白の処理を決定するように関数の引数を追加します。
また、修正に合わせて関数を呼び出している箇所の実引数を追加します。
入力された文字列をコピーしてプレーンテキスト化(HTMLタグを取り除き、文字参照をデコード)して返す関数を追加します。
スレタイトルをプレーンテキストに変換して表示するように修正します。
=> Convert thread subject to plain text

src/article/articleview.cpp, src/article/articleviewetc.cpp, src/board/boardviewbase.cpp, src/board/boardviewbase.h, src/cssmanager.cpp, src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, src/message/messageview.cpp, src/skeleton/toolbar.cpp, src/skeleton/toolbar.h, src/skeleton/view.h, test/gtest_jdlib_miscutil.cpp
CSSのデフォルト設定に"mark"クラスセレクタを追加します。
"mark"クラスセレクタは主にスレタイトルの装飾で使われています。
入力された文字列をコピーしてPango Markupテキスト化(`<mark>`と`<span>`タグの色を設定して文字参照をデコード)して返す関数を追加します。
https://docs.gtk.org/Pango/pango_markup.html
ツールバーに表示するラベルやツールチップにPango Markupの装飾を適用する仕組みを実装します。
ツールバーのラベルとツールチップに表示するスレタイトルをPango Markupで装飾して表示するように変更します。
スレ一覧に表示するスレタイトルをPango Markupで装飾して表示するように変更します。
関連のissue: #76
=> Use Pango Markup to display thread subject

src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, src/replacestrmanager.cpp, src/replacestrpref.cpp, test/gtest_jdlib_miscutil.cpp
文字列をコピーし部分文字列に一致する箇所を置換して返す関数を実装します。
部分文字列はASCIIの大文字小文字を無視して一致します。
正規表現を使わずにASCIIの大文字小文字を無視して文字列置換するオプションを追加します。
関連のissue: #76
=> ReplaceStrPref: Add ignore case option without regex

src/config/aboutconfig.cpp, src/config/configitems.cpp, src/config/configitems.h, src/config/defaultconf.h, src/config/globalconf.cpp, src/config/globalconf.h, src/skeleton/toolbar.cpp
スレッドの状態が変わったときにツールバーのスレタイトル色を変える設定を追加します。
修正前は色を変える状態で固定されていました。
関連のissue: #76
=> toolbar: Add setting that changes color for thread subject per state

src/core.cpp
スレッドの状態が変わったときにステータスバーの色を変える設定がオフになっているときはステータスバーをデフォルト色に戻します。
=> statusbar: Reset default color if setting turned off

src/jdlib/misctrip.cpp, src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, test/gtest_jdlib_miscutil.cpp
- 改行 CRLF は LF に変換します。
関連のissue: #76
=> Use std::string_view for MISC::url_decode()

src/xml/dom.cpp
XMLを解析するモードのときはタグ名の大文字と小文字を区別するように変更します。
関連のissue: #76
=> Dom: Distinguish letter cases for tag name on XML parse mode

README.md, docs/manual/start.md
情報が古くなったため古いMATE環境で実行するときの注意を取り除きます。
=> docs: Get rid of the note for running on old MATE desktop

snap/snapcraft.yaml
snapのベースをcore20([gnome-3-38-2004][1])に移行します。
対応CPUアーキテクチャ: amd64, arm64, armhf
関連のissue: https://github.com/JDimproved/JDim/issues/890
[1]: https://forum.snapcraft.io/t/the-gnome-3-38-extension/22923
=> snap: Migrate base to core20

snap/snapcraft.yaml
snapcraft.ioのJDimビルドが失敗したためビルドに必要なパッケージを再度追加します。
エラーログ
```
Run-time dependency gtkmm-3.0 found: NO
../src/meson.build:77:0: ERROR: Could not generate cargs for gtkmm-3.0:
Package sigc++-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `sigc++-2.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'sigc++-2.0', required by 'glibmm-2.4', not found
```
関連のpull request: #1047
=> snap: Fix build error

src/article/preference.cpp, src/article/preference.h, src/board/boardviewbase.cpp, src/dbtree/articlebase.cpp, src/dbtree/articlebase.h, src/dbtree/board2ch.cpp, src/dbtree/board2chcompati.cpp, src/dbtree/boardbase.cpp, src/dbtree/boardjbbs.cpp, src/dbtree/boardmachi.cpp, src/dbtree/interface.cpp, src/dbtree/interface.h, src/dbtree/nodetree2ch.cpp, src/dbtree/nodetree2ch.h, src/dbtree/nodetreebase.h
スレッドのプロパティに最大レス数を設定する項目を追加します。
未設定のときは板のプロパティにある最大レス数の値を参照します。
(デフォルトは`0`:未設定)
`ArticleBase::is_finished()`の動作を "キャッシュはあるが規定のレス数を 越えていて、かつ全てのレスが既読ならtrueを返す" から "キャッシュが新着がない状態で存在し、さらに規定の最大レス数を越えているならtrueを返す" に変更します。
関連のissue: #76
=> article: Add config for number of max res to thread property

src/core.cpp, src/dbtree/articlebase.cpp, src/dbtree/articlebase.h, src/dbtree/interface.cpp, src/dbtree/interface.h, src/dbtree/nodetree2ch.cpp, src/dbtree/nodetree2ch.h, src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
5chのスレ立てで指定された`!extend:`コマンドの結果から`MAX LINE`(最大レス数)を解析して設定する処理を追加します。
5chのスレ立てで指定された`!extend:`コマンドの結果から`MAX VOLUME`(最大DATサイズ,単位はキロバイト)を解析して設定する処理を追加します。
https://info.5ch.net/?curid=2759
関連のissue: #76
=> NodeTree2ch: Add parse_extattr() to parse the result of "!extend:"

src/dbtree/root.cpp, src/jdlib/miscutil.cpp, src/jdlib/miscutil.h
bbsmenuを解析してDOM構築するときname属性の値に含まれるHTML文字参照をデコードするように変更します。
関連のissue: #76
=> Root: Decode HTML char reference for bbsmenu

src/dbtree/root.cpp
板移転を行うとき移転元と移転先の板のルートパスが同じときはバックアップ処理をしないように変更します。
関連のissue: #76
=> Root: Avoid moving files if board root path source and dest are same

src/board/boardviewbase.cpp
ローカル変数にconstを付けれるとcppcheck 2.9に指摘されたため修正します。
cppcheckのレポート
```
src/board/boardviewbase.cpp:1430:36: style: Variable 'iter' can be declared as reference to const [constVariable]
for( Gtk::TreeModel::iterator& iter : list_it ) {
^
src/board/boardviewbase.cpp:1790:44: style: Variable 'iter' can be declared as reference to const [constVariable]
for( Gtk::TreeModel::iterator& iter : list_it ) {
^
src/board/boardviewbase.cpp:2376:36: style: Variable 'iter' can be declared as reference to const [constVariable]
for( Gtk::TreeModel::iterator& iter : list_it ) {
^
src/board/boardviewbase.cpp:2581:40: style: Variable 'iter' can be declared as reference to const [constVariable]
for( Gtk::TreeModel::iterator& iter : list_it ) {
^
src/board/boardviewbase.cpp:2602:36: style: Variable 'iter' can be …
```
=> BoardViewBase: Add const qualifier to local variables

src/bbslist/bbslistviewbase.cpp, src/history/viewhistory.cpp, src/image/imageviewbase.cpp
ローカル変数にconstを付けれるとcppcheck 2.9に指摘されたため修正します。
cppcheckのレポート
```
src/bbslist/bbslistviewbase.cpp:2007:25: style: Variable 'iter' can be declared as reference to const [constVariable]
for( Gtk::TreeIter& iter : m_treeview.get_selected_iterators() ) {
^
src/bbslist/bbslistviewbase.cpp:2047:25: style: Variable 'iter' can be declared as reference to const [constVariable]
for( Gtk::TreeIter& iter : m_treeview.get_selected_iterators() ) {
^
src/history/viewhistory.cpp:112:16: style: Variable 'item' can be declared as reference to const [constVariable]
for( auto& item : m_items ) {
^
src/image/imageviewbase.cpp:1225:17: style: Variable 'sizemenus' can be declared as const array [constVariable]
std::string sizemenus[] =
^
```
関連のpull request: #1055
=> Add const qualifier to local variables part2

src/jdlib/miscutil.cpp, src/message/logitem.h
非効率な`std::string::substr()`の呼び出しがあるとcppcheck 2.9に指摘されたため`resize()`に置き換えます。
cppcheckのレポート
```
src/message/logitem.h:45:87: performance: Ineffective call of function 'substr' because a prefix of the string is assigned to itself. Use resize() or pop_back() instead. [uselessCallsSubstr]
if( newthread && url.find( ID_OF_NEWTHREAD ) != std::string::npos ) url = url.substr( 0, url.find( ID_OF_NEWTHREAD ) );
^
src/jdlib/miscutil.cpp:733:41: performance: Ineffective call of function 'substr' because a prefix of the string is assigned to itself. Use replace() instead. [uselessCallsSubstr]
if( pos != outstr_length ) outstr = outstr.substr( 0, pos ) + "...";
^
```
関連のpull request: #1055
=> Use std::string::resize() instead of substr()

src/skeleton/tabnote.cpp
値が既知の条件があるとcppcheck 2.9に指摘されたため修正します。
cppcheckのレポート
```
src/skeleton/tabnote.cpp:194:19: style: Condition 'x>=tab_x' is always true [knownConditionTrueFalse]
if( x >= tab_x && x <= tab_x + tab_w ){
^
src/skeleton/tabnote.cpp:190:19: note: Assuming that condition 'x<tab_x' is not redundant
if( x < tab_x ){
^
src/skeleton/tabnote.cpp:194:19: note: Condition 'x>=tab_x' is always true
if( x >= tab_x && x <= tab_x + tab_w ){
^
```
関連のpull request: #1055
=> TabNotebook: Fix known condition true/false

src/jdlib/heap.cpp, src/jdlib/heap.h
HEAPの使用状況を初期状態に戻すメンバー関数`clear()`を修正して確保したメモリブロックを解放せずに使用状況だけリセットするようにします。
=> Modify HEAP::clear() to not free allocated blocks

src/article/articleview.cpp, src/article/articleview.h, src/article/articleviewetc.cpp, src/article/articleviewetc.h, src/article/articleviewsearch.cpp, src/article/articleviewsearch.h, src/bbslist/bbslistviewbase.cpp, src/bbslist/bbslistviewbase.h, src/board/boardviewbase.cpp, src/board/boardviewbase.h, src/core.cpp, src/dbtree/articlebase.h, src/dbtree/interface.cpp, src/dbtree/interface.h, src/message/messageviewbase.cpp, src/message/messageviewbase.h, src/replacestrpref.cpp, src/skeleton/admin.cpp, src/skeleton/admin.h, src/skeleton/view.h
スレッドをURLで指定してNodeTreeを削除する関数を実装します。
ビューの再レイアウトを行うときレイアウトの元になるデータから再構築するオプションをメンバー関数に追加します。
スレビューの再レイアウトで"completely"が指定されたときスレッドのデータ(NodeTree)を削除し再構築を行う処理を追加します。
置換文字列設定のダイアログでOKを押して閉じたときスレッドのツリー情報を再構築して置換処理の変更を反映するように修正します。
関連のissue: #76
=> ReplaceStr: Rebuild nodetree to relayout completely if ok clicked

src/article/articleview.cpp, src/article/articleview.h, src/article/drawareabase.h
スレビューの再レイアウト処理をすべてのタブで実行する実装だとタブ数が増えたとき処理時間が増加し一時的にフリーズすることがありました。
そのため表示中(mapped)ではないタブは処理を予約してタブが表示されるときに再レイアウトを行うように変更します。
=> ArticleViewMain: Reserve relayout if the view is not mapped

src/dbtree/nodetreebase.cpp
文字列をコピーする必要がない箇所では`std::string_view`を使って参照します。
=> NodeTreeBase: Use std::string_view instead of std::string

src/dbtree/nodetreebase.cpp
HTMLの`<li>`タグを判定する処理でインデックスがずれている箇所を修正します。
関連のissue: #76
=> NodeTreeBase: Fix parsing <li> tag

INSTALL, README.md, configure.ac, docs/manual/make.md, meson.build
[RFC 0012][*]に基づきビルドツールAutotoolsのサポートは2023年7月のリリースをもって終了することをドキュメントに記載します。
[*]: https://github.com/JDimproved/rfcs/blob/master/docs/0012-end-of-autotools-support.md
=> Prenotice end of support for Autotools

INSTALL, docs/manual/make.md
[RFC 0006][*]に基づきgccのバージョンが8未満のプラットフォームはサポート終了予定になることをドキュメントに記載します。
これはDebianbuster(2019年)より前にリリースされたディストリビューションが該当します。
また、Debian busterの環境を目安として必須・推奨環境の更新予定を追加します。
関連のissue: #1017 
[*]: https://github.com/JDimproved/rfcs/blob/master/docs/0006-platform-support.md
=> Deprecate platforms where gcc version less than 8

src/article/drawareabase.cpp
テキストノードの次のノードが改行でなければ wrap するか確認するように修正します。
関連のissue: #76
=> DrawAreaBase: Fix layout to wrap text if next node is not line feed

src/jdlib/loader.cpp, src/jdlib/loader.h, test/gtest_jdlib_loader.cpp
gzip圧縮されたデータを展開してコールバック関数に渡すデコーダークラスを実装します。
Loaderクラスのgzip展開を行うメンバー関数をGzipDecoderクラスのメンバー変数で置き換えます。
また、使わなくなったメンバー関数を削除します。
=> Loader: Implement GzipDecoder class

src/jdlib/confloader.h, src/main.cpp
使っていない #include ディレクティブを取り除きます。
関連のissue: #76
=> Get rid of unused headers

src/article/drawareabase.cpp
スレビュー閲覧中にJDimがクラッシュしたためnullチェックを追加します。
状況の再現が難しかったためコードを逆上って原因の特定はできていません。
GDBのレポート
```
Thread 1 "jdim" received signal SIGSEGV, Segmentation fault.
0x00005555559940d3 in ARTICLE::DrawAreaBase::exec_scroll (this=0x55555855b000) at ../src/article/drawareabase.cpp:3098
3098                if( layout ) y = layout->rect->y;
```
=> DrawAreaBase: Add null check to read LAYOUT::rect

src/dbtree/nodetreebase.cpp, src/dbtree/spchar_decoder.cpp, src/dbtree/spchar_decoder.h, src/jdlib/miscutil.cpp
commit https://github.com/JDimproved/JDim/commit/14b72ea6f28dfa25a16b8efe6c7ca4a0e7ffc223 (2012-11)
の修正以来使われていない`only_check`引数を取り除いてコードを整理します。
出力文字列を格納するパラメータ`out_char`の型を`JDLIB::span<char>`に変更してバッファの長さが足りているか`assert()`を使って確認します。
=> dbtree: Modify function parameters for DBTREE::decode_char()

src/dbtree/spchar_decoder.cpp, src/dbtree/spchar_decoder.h, src/dbtree/spchar_tbl.h, test/Makefile.am, test/gtest_dbtree_spchar_decoder.cpp, test/meson.build
[W3C][1]や[WHATWG][2]のリファレンスを参考に名前付き文字参照の変換を追加します。
[1]: https://dev.w3.org/html5/spec-LC/named-character-references.html
[2]: https://html.spec.whatwg.org/entities.json
関連のissue: #76
=> Improve entity reference table for DBTREE::decode_char()

meson.build, src/article/meson.build, src/config/meson.build, src/control/meson.build, src/jdlib/meson.build, src/meson.build, src/sound/meson.build, test/meson.build
`HAVE_CONFIG_H`マクロをプロジェクト全体に設定する方法からconfig.h 依存関係にまとめる方法に変更します。
`GTK_DOMAIN`マクロをプロジェクト全体に設定する方法からgtkmm 依存関係にまとめる方法に変更します。
=> Meson: Create dependency to organize macro

src/dbtree/nodetreebase.cpp, src/dbtree/spchar_decoder.cpp, src/jdlib/miscutil.cpp, src/jdlib/miscutil.h
戻り値の型を char32_t へ変更してソースコードの可読性を向上させます。
=> Change return type int with char32_t for MISC::decode_spchar_number()

src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, test/gtest_jdlib_miscutil.cpp
コードポイントが数値文字参照の無効・解析エラーなら規定の値へ変換する関数を実装します。
また、サロゲートペアの数値文字参照を表示する機能を追加するため上位サロゲートを返すオプション引数を付けます。
=> Implement MISC::sanitize_numeric_charref()

src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, test/gtest_jdlib_miscutil.cpp
「&#数字;」形式の数値文字参照をコードポイント(char32_t)に変換する処理を分割して数値文字参照の解析エラーとなる値もそのまま返す関数を実装します。
オリジナル`MISC::decode_spchar_number()`は`MISC::decode_spchar_number_raw()`を呼び出すように変更します。
=> Implement MISC::decode_spchar_number_raw()

test/gtest_jdlib_miscutil.cpp
AddressSanitizerのチェックによりテストがクラッシュしました。
テストケースの引数を正しい値に直して修正します。
Thanks @mtasaka for reporting crashes.
Close #1078
=> Fix crashes for testing MISC::decode_spchar_number()

src/dbtree/spchar_decoder.cpp, src/dbtree/spchar_decoder.h, test/gtest_dbtree_spchar_decoder.cpp
`DBTREE::decode_char()`からHTML 文字実体参照をUTF-8文字列にデコードする処理を別の関数に分割します。
=> Implement DBTREE::decode_char_name()

src/dbtree/spchar_decoder.cpp, src/dbtree/spchar_decoder.h, src/dbtree/spchar_tbl.h, test/gtest_dbtree_spchar_decoder.cpp
HTMLの仕様ではサロゲート(U+D800 - U+DFFF)の数値文字参照は不正な値として U+FFFD REPLACEMENT CHARACTER に変換されます。
仕様と異なりますが利便性を良くするためサロゲートが上下の順に並んでいるとき2つを合わせてデコードするフラグ引数を関数に追加します。
=> Add surrogate pair handling to DBTREE::decode_char_number()

src/config/aboutconfig.cpp, src/config/configitems.cpp, src/config/configitems.h, src/config/defaultconf.h, src/config/globalconf.cpp, src/config/globalconf.h, src/dbtree/spchar_decoder.cpp
about:coifig に不正な数値文字参照をデコードするオプションを追加します。
「はい」に設定するとサロゲートを表す数値文字参照が上下の順に並んでいるとき2つを合わせてデコード処理を行います。
デフォルト設定「いいえ」のときは不正な値としてそれぞれ U+FFFD REPLACEMENT CHARACTER に変換されます。
=> Add correct_character_reference option to about:config

.github/workflows/ccpp.yml
GitHub Actions の CI に AddressSanitizer を有効にしてテストする job を追加してかわりに Ubuntu 18.04 の job を取り除きます。
追加するjobの構成
* OS: Ubuntu 22.04
* Compiler: g++ 11
関連のissue: #1078
=> CI: Add a job which uses AddressSanitizer

docs/manual/2022.md, meson.build, src/jdversion.h
=> Bump version to 0.9.0-beta

snap/snapcraft.yaml
Snap版が利用している[gnome-3-38-2004 extension][1]はCPUアーキテクチャーi386に対応していません。
前のバージョンの[gnome-3-28-1804][2]はi386に対応＆JDimの動作環境もサポートしています。
そのため一時的に設定を切り替えてi386向けのSnapパッケージをビルドしてリリースします。
関連のissue: #890
[1]: https://snapcraft.io/gnome-3-38-2004
[2]: https://snapcraft.io/gnome-3-28-1804
=> Set snapcraft config for i386 (2022-12)

snap/snapcraft.yaml
This reverts commit 59faae9b972e208a7f16226a466f104fcb6f6071.
Snapのビルド設定をgnome-3-38-2004 extensionを使うように差し戻します。
=> Revert "Set snapcraft config for i386 (2022-12)"

configure.ac, meson.build, meson_options.txt
廃止された正規表現のライブラリを選択するビルドオプションを消去します。
関連のissue: https://github.com/JDimproved/JDim/issues/697
=> Clean up obsolete build option for regex

src/jdlib/misccharcode.cpp
std::uint8_t is used in src/jdlib/misccharcode.cpp, gcc13 now causes error without cstdint.
gcc13開発版でビルドするとエラーが出たので、その修正です。
```
../src/jdlib/misccharcode.cpp:201:40: error: ‘uint8_t’ is not a member of ‘std’; did you mean ‘wint_t’?
201 | inline bool utf8_head_multi_byte( std::uint8_t x ) { return static_cast<std::uint8_t>( x - 0xC2 ) <= ( 0xF4 - 0xC2 ); }
|                                        ^~~~~~~
|                                        wint_t
../src/jdlib/misccharcode.cpp:204:36: error: ‘uint8_t’ is not a member of ‘std’; did you mean ‘wint_t’?
204 | inline bool utf8_head_bytes2( std::uint8_t x ) { return static_cast<std::uint8_t>( x - 0xC2 ) <= ( 0xDF - 0xC2 ); }
|                                    ^~~~~~~
|                                    wint_t …
```
=> buidfix: add missing cstdint to misccharcode.cpp

src/jdlib/jdiconv.cpp, src/jdlib/jdiconv.h
出力バッファの長さが不足したときサイズを拡大してiconvの変換処理を続行するように修正します。
出力バッファの初期サイズは入力に対して2倍以上の長さを確保します。
修正前は出力バッファの長さが不足したとき変換処理を中断して途中結果を返していました。
関連のissue: #76
=> Iconv: Grow buffer size to continue iconv if output buffer is shortage

src/dbtree/nodetreejbbs.cpp, src/dbtree/nodetreemachi.cpp, src/jdlib/jdiconv.h
固定長のバッファ(`char*`)から`std::string`へ置き換えたコードはバッファ長の制限を取り除きます。
=> dbtree: Get rid of buffer length limitation

src/jdlib/jdiconv.cpp, src/jdlib/jdiconv.h, test/gtest_jdlib_jdiconv.cpp
UTF-8へ変換する処理のとき変換できないバイト列を U+FFFD へ置き換えます。
関連のissue: #76
=> Iconv: Use U+FFFD REPLACEMENT CHARACTER on converting to UTF-8

src/config/aboutconfig.cpp, src/config/configitems.cpp, src/config/configitems.h, src/config/defaultconf.h, src/config/globalconf.cpp, src/config/globalconf.h, src/jdlib/jdiconv.cpp, src/jdlib/jdiconv.h, test/gtest_jdlib_jdiconv.cpp
不正なShift_JIS(MS932)文字列をUTF-8と見なすオプションを about:config に追加します。
関連のissue: #76
=> Iconv: Add about:config option that wrong sjis assumes to be utf8

src/control/mousekeypref.h, src/skeleton/menubutton.h
overrideしている仮想関数にキーワードを追加します。
gcc 12のレポート
```
In file included from ../src/bbslist/toolbar.cpp:11:
../src/skeleton/menubutton.h:62:12: warning: ‘virtual void SKELETON::MenuButton::on_clicked()’ can be marked override [-Wsuggest-override]
62 |       void on_clicked();
|            ^~~~~~~~~~
In file included from ../src/control/keypref.h:11,
from ../src/prefdiagfactory.cpp:33:
../src/control/mousekeypref.h:60:22: warning: ‘virtual bool CONTROL::InputDiag::on_key_press_event(GdkEventKey*)’ can be marked override [-Wsuggest-override]
60 |         virtual bool on_key_press_event (GdkEventKey* event);
|                      ^~~~~~~~~~~~~~~~~~
../src/control/mousekeypref.h:61:22: warning: ‘virtual bool CONTROL::InputDiag::on_button_press_event(GdkEventButton*)’ can be marked override …
```
=> Add override keyword to virtual function declarations

src/dbtree/boardbase.cpp, src/dbtree/nodetree2chcompati.cpp, src/dbtree/nodetreejbbs.cpp, src/dbtree/nodetreemachi.cpp, src/dbtree/root.cpp, src/jdlib/jdiconv.cpp, src/jdlib/jdiconv.h, src/jdlib/miscutil.cpp, src/message/messageviewbase.cpp, src/message/post.cpp, src/skeleton/textloader.cpp, test/gtest_jdlib_jdiconv.cpp
`JDLIB::Iconv`クラスで使うバッファを`std::vector<char>`から`std::string`に変更します。
`convert()`の引数と戻り値を整理して内部バッファのconst参照を直接返すように修正します。
合わせて`convert()`を呼び出すコードを整理します。
=> Iconv: Change convert() return type to const std::string&

src/Makefile.am, src/article/articleviewbase.cpp, src/jdencoding.h, src/jdlib/misccharcode.cpp, src/jdlib/misccharcode.h
文字エンコーディングを表す列挙型`CodeSet`をスコープを持つ列挙型(enum class)`Encoding`に更新します。
また、テキストから文字エンコーディングを検出する関数の名称を`detect_encoding()`に変更して返り値を`int`から`Encoding`にします。
ソースコードの文字エンコーディングを表す識別子には encoding や charset を使います。
関連のissue: #76
=> Update character encoding enumeration to Encoding

src/cache.cpp, src/core.cpp
ローカル変数の名前を変更して関数をシャドーイングしないように修正します。
```
src/cache.cpp:535:17: style: Local variable 'path_root' shadows outer function [shadowFunction]
std::string path_root = CACHE::path_root();
^
src/cache.cpp:554:17: style: Local variable 'path_img_root' shadows outer function [shadowFunction]
std::string path_img_root = CACHE::path_img_root();
^
src/cache.cpp:584:17: style: Local variable 'path_img_root' shadows outer function [shadowFunction]
std::string path_img_root = CACHE::path_img_protect_root();
^
src/cache.cpp:633:17: style: Local variable 'path_board_root' shadows outer function [shadowFunction]
std::string path_board_root = CACHE::path_board_root( url );
^
src/cache.cpp:656:17: style: Local variable 'path_logroot' shadows outer function [shadowFunction]
std::string …
```
=> Rename local variables to avoid shadowing outer function

test/gtest_jdlib_miscutil.cpp
URLエンコード(パーセント符号化)の処理を行う関数にテストを追加して動作をチェックします。
- Add test cases for `MISC::url_encode()`
- Add test cases for `MISC::charset_url_encode()`
- Add test cases for `MISC::charset_url_encode_split()`
=> Add test cases for percent encoding functions

src/cache.cpp, src/dbtree/article2ch.cpp, src/dbtree/board2ch.cpp, src/dbtree/nodetree2ch.cpp, src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, test/gtest_jdlib_miscutil.cpp
`MISC::url_encode()`の引数を`std::string_view`を使うように変更します。
=> Change MISC::url_encode() parameters to use std::string_view

src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, test/gtest_jdlib_miscutil.cpp
[URLの規格][1]を参考にして`@`(U+0040)をパーセント符号化するように関数の動作を変更します。
> The application/x-www-form-urlencoded percent-encode set contains all code points, except the ASCII alphanumeric, U+002A (*), U+002D (-), U+002E (.), and U+005F (_).
[1]: https://url.spec.whatwg.org/#application-x-www-form-urlencoded-percent-encode-set
=> Change MISC::url_encode() behavior to decode @ mark

src/jdlib/jdiconv.cpp
architectureによって、char型がsignedなのかunsignedなのか異なるので、
char型の数値比較の時は、明示的にunsigned型を使うよう修正する。
Fixes: #1106
=> Iconv::convert: use unsigned char for numerical comparison

src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, test/gtest_jdlib_miscutil.cpp
文字列を _application/x-www-form-urlencoded_ の形式でパーセント符号化する関数を実装します。
webブラウザのform要素の動作に合わせてURLの規格と異なる変換処理があります。
改行がCR単体のプラットフォームは古いMac OSのみなので無視しています。
- 半角英数字(`0-9 A-Z a-z`)と一部記号(`* - . _`)は変換しない
- 改行LF(U+000A)は `%0D%0A` に変換する
- 改行CR(U+000D)は読み飛ばして無視する
- 半角空白(U+0020)は `+` に置換する
- それ以外はパーセント記号ではじまる16進表記 `%XX` に変換 (A-Fは大文字)
=> Implement MISC::url_encode_plus()

src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, test/gtest_jdlib_miscutil.cpp
webブラウザのform要素と動作を合わせるため `MISC::charset_url_encode_split()` のパーセント符号化処理を変更します。
変更点
- 入力の先頭にある半角空白 (U+0020) を `+` に変換する
- 全角空白 (U+3000) を `+` ではなくパーセント符号化する
- 改行CR (U+000D) は読み飛ばして無視する
=> Change MISC::charset_url_encode_split() to HTML form compliant

src/core.cpp, src/menuslots.cpp
真偽値の論理積(`&&`)を行うべき式がビット単位のAND(`&`)になっている箇所があったため修正します。
clang-14 のレポート
```
../src/core.cpp:607:55: warning: use of bitwise '&' with boolean operands [-Wbitwise-instead-of-logical]
( CONFIG::get_restore_board()
~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/menuslots.cpp:592:19: warning: use of bitwise '&' with boolean operands [-Wbitwise-instead-of-logical]
bool status = CONFIG::get_restore_board() & CONFIG::get_restore_article() & CONFIG::get_restore_image();
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
&&
```
=> Use logical and instead of bitwise and

src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, src/usrcmdmanager.cpp, test/gtest_jdlib_miscutil.cpp
`MISC::charset_url_encode_split()`はsplitとついていますが返り値とは関係ない内部の操作を表していて分かりにくい名称になっています。
そのため関数の名称を変更してインターフェースをオーバーロードとしてまとめて整理します。
=> Rename MISC::charset_url_encode_split() with url_encode_plus()

src/dbtree/article2ch.cpp, src/dbtree/article2chcompati.cpp, src/dbtree/articlejbbs.cpp, src/dbtree/articlemachi.cpp, src/dbtree/board2ch.cpp, src/dbtree/board2chcompati.cpp, src/dbtree/boardjbbs.cpp, src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, src/loginbe.cpp, test/gtest_jdlib_miscutil.cpp
`MISC::url_encode_plus()`の関数オーバーロードと同様に`MISC::charset_url_encode()`を`MISC::url_encode()`に名称変更してまとめることでコードを整理します。
=> Rename MISC::charset_url_encode() with url_encode()

src/dbtree/article2ch.cpp, src/dbtree/article2chcompati.cpp, src/dbtree/articlejbbs.cpp, src/dbtree/articlemachi.cpp, src/dbtree/board2ch.cpp, src/dbtree/board2chcompati.cpp, src/dbtree/boardjbbs.cpp, src/dbtree/nodetree2ch.cpp, src/loginbe.cpp
HTMLフォームのデータ(application/x-www-form-urlencoded)を作成する処理ではより適切にパーセント符号化する`MISC::url_encode_plus()`を使うように変更します。
=> Apply MISC::url_encode_plus() to encode HTML form data

src/article/drawareabase.cpp, src/dbtree/boardbase.cpp
forループを`std::find_if()`を使ったコードに書き換えます。
```
src/article/drawareabase.cpp:3650:29: style: Consider using std::find_if algorithm instead of a raw loop. [useStlAlgorithm]
if( ( *it ).select ){
^
src/dbtree/boardbase.cpp:1542:52: style: Consider using std::find_if algorithm instead of a raw loop. [useStlAlgorithm]
if( article->get_subject() == subject ){
^
```
=> Use std::find_if() instead of for loops

src/jdencoding.h, src/jdlib/misccharcode.cpp, src/jdlib/misccharcode.h, test/gtest_jdlib_misccharcode.cpp
`Encoding`列挙型から文字エンコーディングを表すヌル終端文字列を取得する関数を実装します。
`Encoding`の列挙子にない値が指定されたときは "ISO-8859-1" (LATIN1) を返します。
Add test cases `MISC::encoding_to_cstr()`
=> Implement MISC::encoding_to_cstr()

src/jdlib/misccharcode.cpp, src/jdlib/misccharcode.h, test/gtest_jdlib_misccharcode.cpp
文字エンコーディングを表すヌル終端文字列から`Encoding`列挙型を取得する関数を実装します。
`Encoding`の列挙子と一致しない文字列が渡されたときは`Encoding::unknown` を返します。
Add test cases for MISC::encoding_from_cstr()
=> Implement MISC::encoding_from_cstr()

src/jdlib/jdiconv.cpp, src/jdlib/jdiconv.h
`JDLIB::Iconv`クラスを使うコードの更新によって使わなくなった文字列で文字エンコーディングを指定するコンストラクターを削除します。
=> Iconv: Remove unused constructors with std::string parameters

src/dbtree/articlebase.cpp, src/dbtree/boardbase.cpp
板やスレッドの情報を保存したファイルにある文字エンコーディング情報の互換性を確保するため設定の読み込みを修正します。
情報を保存したinfoファイルから読みこんだ文字エンコーディングの情報を`Encoding`列挙型に変換した結果が`Encoding::unknown`になるときは無視して設定しないように変更します。
この修正で`ISO-8859-1` (LATIN1)を利用する掲示板は文字エンコーディング設定を読み込めなくなります。
2ch互換のサイトでISO-8859-1は利用されていないため問題になる可能性は低いです。
=> Ignore Encoding::unknown read from info file

src/dbtree/articlebase.cpp, src/dbtree/boardbase.cpp, src/jdlib/misccharcode.cpp, src/jdlib/misccharcode.h, test/gtest_jdlib_misccharcode.cpp
関数の引数を`const char*`から`std::string_view`に変更して関数の名称も更新します。
=> Rename MISC::encoding_from_cstr() to encoding_from_sv()

src/jdlib/jdiconv.cpp, src/jdlib/misccharcode.cpp, src/jdlib/misccharcode.h, test/gtest_jdlib_misccharcode.cpp
`MISC::encoding_from_cstr()`が返す文字エンコーディング名の中には広く使われている名称ではなく特定の実装や拡張を表すものがあります。
エンコーディングの背景事情を知っていないと分かりにくいためUIや情報ファイルで使う文字エンコーディング名を返す関数と`JDLIB::Iconv`クラスで使う文字エンコーディング名を返す関数を分割します。
互換性のため`MISC::encoding_from_sv()`は両方の関数が返す文字列を解析するように修正します。
Add test cases for `MISC::encoding_to_iconv_cstr()`
以下の2つのコミットは前方互換性が無くなります。
- edcd3bd2df13d72f49b93b872af955045735b758 (2023-03-04)
Use enum `Encoding` for conversion functions and encoding settings (#1118)
- 93749e7cb271636373b63c0084ef7cfa998e09f3 (2023-03-04)
`Iconv`: Remove unused constructors with `std::string` parameters (#1119)
これらのコミットは https://github.com/JDimproved/JDim/pull/1120 の修正がないため文字エンコーディング名の読み込みに失敗したときISO-8859-1を使うように設定されてしまいます。
=> Split MISC::encoding_to_cstr() and encoding_to_iconv_cstr()

src/article/preference.cpp, src/article/preference.h, src/board/preference.cpp, src/board/preference.h, src/config/aboutconfig.cpp, src/config/configitems.cpp, src/config/configitems.h, src/config/defaultconf.h, src/config/globalconf.cpp, src/config/globalconf.h
板のプロパティにテキストエンコーディングを切り替える設定を追加します。
この設定は実験的なサポートで安全ではありません。
スレビューのプロパティに文字エンコーディングを切り替える設定を追加します。
この設定は実験的なサポートで安全ではありません。
スレ一覧やスレビューのプロパティにあるテキストエンコーディングの設定は安全でないため about:config に設定欄の有効・無効を切り替える項目を追加します。(デフォルト設定では無効にする)
無効のときは設定欄(コンボボックス)を隠してエンコーディングの情報だけ表示します。
関連のissue: #76
=> Add unsafe character encoding options

src/jdlib/misccharcode.cpp, src/jdlib/misccharcode.h, test/gtest_jdlib_misccharcode.cpp
Webで使われる文字エンコーディングのラベルから`Encoding`列挙型を取得する関数を実装します。
入力文字列とラベルの比較は繋ぎの記号(`-`, `_`)を取り除き大文字小文字を無視して行います。
`Encoding`の列挙子と一致しない文字列が渡されたときは`Encoding::unknown`を返します。
Add test cases for `MISC::encoding_from_web_charset()`
https://encoding.spec.whatwg.org/#names-and-labels
=> Implement MISC::encoding_from_web_charset()

src/bbslist/bbslistviewbase.cpp, src/board/preference.cpp, src/browserpref.h, src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, src/passwdpref.h, src/proxypref.h, test/gtest_jdlib_miscutil.cpp
`MISC::utf8_trim()`に渡す文字列を複製しなくても長さや範囲を調整できるようにするため関数の引数を`std::string_view`に変更します。
=> Modify MISC::utf8_trim() parameter to use std::string_view

src/skeleton/loadable.cpp, src/skeleton/loadable.h
HTTPヘッダーのContent-Typeを解析してテキストの文字エンコーディングを検出する機能を追加します。
関連のissue: https://github.com/JDimproved/JDim/issues/76
=> Loadable: Add character encoding detection by HTTP header Content-Type

src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, test/gtest_jdlib_miscutil.cpp
HTMLのmeta要素からテキストのエンコーディング(charset)を表す文字列を取得する関数を実装します。
charsetが見つからないときは空文字列を返します。
Add test cases for `MISC::parse_charset_from_html_meta()`
=> Implement MISC::parse_charset_from_html_meta()

src/skeleton/loadable.cpp
`SKELETON::Loadable`クラスの文字エンコーディング検出を拡張してHTML meta要素のcharsetを解析しテキストの文字エンコーディングを検出する機能を追加します。
Webの規格に合わせるためHTTPヘッダーのContent-TypeにcharsetがありJDimで利用できるときはヘッダーの値を優先して使います。
MIME typeがHTMLでないコンテンツやHTML meta要素のcharsetがJDimで利用できないエンコーディング、
またはHTMLの先頭1024バイト以内にmeta要素がなかったときは解析を打ち切り`Loadable`クラスに設定されたデフォルト値を使います。
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
=> Loadable: Add character encoding detection by HTML meta element

src/dbtree/board2chcompati.cpp
スレタイトル一覧のテキストを解析する処理で空白文字のトリミングと`&lt;`と`&gt;`の文字参照をデコードする処理を取り除きます。
関連のissue: #76
=> Board2chCompati: Update parse_subject()

src/skeleton/textloader.cpp
実際のwebページを参考にテキストの読み込みに使うバッファを調整してメモリ確保するサイズ(byte)を 1024 * 1024 から 256 * 1024 に減らします。
関連のissue: #76
=> TextLoader: reduce memory allocation for buffer

INSTALL, docs/manual/make.md, meson.build
GTestの依存関係を探す処理を更新してバージョン要件を1.10.0以上にします。
また、ライブラリ `gtest_main` を使うようにmeson.buildを変更します。
変更前は `dependency()` の [`main` キーワード引数][1] を利用してGTestが提供する `main()` とリンクしていました。
GTest 1.10.0のころから pkg-config のサポートが追加されているため `main` キーワードを使わなくてもテストをビルドできるようになりました。
この修正でMeson実装の一つである [muon][2] を使ってJDimのビルドやテストが可能になります。
`dependency()` の `main` キーワードは今のところ古いGTestのサポート以外では使われていないようです。
[1]: https://mesonbuild.com/Dependencies.html#gtest-and-gmock
[2]: https://sr.ht/~lattis/muon/
=> meson: Update version requirement for GTest (>= 1.10.0)

src/jdlib/misctrip.cpp
C言語のキャスト構文を使ったポインターの型変換をC++のキャストに
置き換えます。
```
src/jdlib/misctrip.cpp:66:12: style: C-style pointer casting detected.
C++ offers four different kinds of casts as replacements: static_cast,
const_cast, dynamic_cast and reinterpret_cast. A C-style cast could
evaluate to any of those automatically, thus it is considered safer if
the programmer explicitly states which kind of cast is expected.
See also: https://www.securecoding.cert.org/confluence/display/cplusplus/EXP05-CPP.+Do+not+use+C-style+casts. [cstyleCast]
SHA1( (const unsigned char *)key.c_str(), key.length(), digest.data() );
^
```
=> Fix C-style pointer cast

src/dbimg/img.cpp, src/dbimg/img.h, src/dbtree/boardbase.cpp, src/dbtree/boardbase.h, src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h, src/dbtree/nodetreemachi.cpp, src/dbtree/nodetreemachi.h, src/dbtree/root.cpp, src/dbtree/root.h, src/jdlib/loader.cpp, src/login2ch.cpp, src/login2ch.h, src/loginbe.cpp, src/loginbe.h, src/message/post.cpp, src/message/post.h, src/skeleton/loadable.cpp, src/skeleton/loadable.h, src/skeleton/textloader.cpp, src/skeleton/textloader.h, test/gtest_jdlib_loader.cpp
`Loadable::receive_data()`の引数を`std::string_view`を使うように変更します。
この変更で入力バッファはヌル終端の保証が無くなるため、ヌル終端が前提になっている実装やテストのコードを修正します。
`DBIMG::Img`クラスのダウンロード処理で画像でないデータを受信したときに行う404 Not Foundを探す処理を以下の条件に変更します。
- 404 -> Not -> Found の順に単語が並んでいる
- Not は Not, NOT, not, nOT のどれかに一致する
- Found は Found, FOUND, found, fOUND のどれかに一致する
=> Loadable: Change receive_data() parameters to use std::string_view

src/loginbe.cpp, src/skeleton/textloader.cpp
`Loadable`から派生したクラスで受信したデータを格納するために使われるバッファは`std::string`に変更されているためデータを追加するとバッファのサイズが拡張されます。
そのためバッファのサイズ制限を取り除いてコードを整理します。
=> Get rid of size limitation for std::string

src/dbtree/nodetreemachi.cpp
まちBBS(machi.to)のDATデータに変換するための正規表現パターンを修正します。
関連のissue: #76
=> NodeTreeMachi: Fix regex pattern for DAT conversion

src/jdlib/loader.cpp
IPv6を使用してプロキシ接続を行うと失敗する不具合を修正します。
変更を差し戻したためプロキシのホスト名からポート番号を解析する機能は削除されます。
https://next2ch.net/test/read.cgi/linux/1654053581/60-61
Fixes #1140
=> Loader: Fix proxy connection using IPv6

src/article/articleview.cpp, src/article/articleviewbase.cpp, src/board/preference.cpp, src/dbtree/article2ch.cpp, src/dbtree/articlejbbs.cpp, src/dbtree/interface.cpp, src/dbtree/interface.h, src/usrcmdmanager.cpp
名前空間`DBTREE`のオブジェクトが保持している文字列データを返すインターフェース関数のうち一部を修正します。
戻り値の型を`const std::string&`に変更することで関数呼び出しでコピーが発生しないようにします。
`const std::string&`を返す`DBTREE`のインターフェース関数を呼び出す箇所では値ではなくconst参照を受け取るように修正しコピーを回避します。
関連のissue: #76
=> dbtree: Modify interface function return type to use const reference

src/article/articleviewbase.cpp
ID抽出表示で新方式のID(12文字)の末尾情報を表示するように更新します。
参考文献
`https://info.5ch.net/index.php/BBS_SLIP`
=> ArticleViewBase: Support 12 chars ID in ID extraction view

src/dbtree/nodetree2ch.cpp, src/dbtree/nodetree2chcompati.cpp
DATデータの続きがあるか更新チェックを行うためHTTP HEADでリクエストするときは取得したDATデータより後ろの部分を要求するように範囲を調整します。
2ch系の掲示板でDATデータの続きを取得するときは1byte前からレジュームして '\n' が返ってこなかったらあぼーんがあったと判定しています。
関連のissue: #76
=> dbtree: Modify HTTP request range for checking DAT update

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
`add_raw_lines()`の引数を`std::string&`に置き換えてコードを整理します。
=> NodeTreeBase: Use std::string& for add_raw_lines() parameter type

src/dbtree/nodetree2ch.cpp, src/dbtree/nodetree2ch.h, src/dbtree/nodetree2chcompati.cpp, src/dbtree/nodetree2chcompati.h, src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h, src/dbtree/nodetreemachi.cpp, src/dbtree/nodetreemachi.h
`process_raw_lines()`の引数を`std::string&`に置き換えてコードを整理します。
=> NodeTreeBase: Use std::string& for process_raw_lines() parameter type

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
保留された受信データをDATに変換する処理をメンバー関数にしてコードを整理します。
関連のissue: #76
=> NodeTreeBase: Implement sweep_buffer()

src/dbtree/nodetreebase.cpp
バッファにコピーする入力データのサイズ調整を修正します。
9c0edee8be0ab16afacfe5681a22c6faad9e2219
`NodeTreeBase: Update receive_data() to improve processing large data`
で追加した変更は改行 '\n' が見つからなかった場合の処理が正しくありませんでした。
=> NodeTreeBase: Fix input data size adjustment in buffer copying

src/dbtree/nodetreebase.cpp
デフォルト名無しかどうか判定する比較で末尾の空白文字を無視して行うように修正します。
=> NodeTreeBase: Modify default name detection to ignore trailing whitespace

src/dbtree/nodetreebase.cpp
確保したバッファを再利用するためロード実行前に呼ぶ初期化関数からメモリを開放する処理を取り除きます。
=> NodeTreeBase: Get rid of freeing memory from init_loading() to reuse buffers

src/article/layouttree.cpp, src/dbtree/node.h, src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h, src/dbtree/spchar_decoder.cpp, src/dbtree/spchar_tbl.h, src/jdlib/miscutil.cpp, test/gtest_dbtree_spchar_decoder.cpp
ノードツリー構築のうち空白文字の処理を更新してゼロ幅(非)接合子と双方向テキストをテキスト表示に反映するようにします。
この修正で Emoji ZWJ Sequences (複数の絵文字を連結して1文字として見せる絵文字) の表示に対応します。
Shift\_JIS をはじめ Unicode と異なる符号化文字集合の文字エンコーディングが使われているwebサイトでは絵文字がHTML文字参照にエンコードされています。
GTK3 は Unicode(UTF-8) に対応していますがJDimの文字参照デコードの実装がzwjなどに未対応でした。
* 連続する空白をまとめるように変更します。
* U+200C(zwnj), U+200D(zwj), U+200E(lrm), U+200F(rlm) をテキスト表示に反映するように処理を変更します。
関連のissue: #76
=> NodeTreeBase: Update whitespace handling in node tree construction

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
HTMLを解析してノードツリーを構築する処理を更新してHTML`<a>`要素が相対URLのときは絶対URLに変換するように変更します。
また、JavaScript疑似プロトコルのBE linkも同じく変換します。
関連のissue: #76
=> NodeTreeBase: Convert relative URLs in HTML <a> elements

src/article/drawareabase.cpp, src/dbtree/node.h, src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
HTMLを解析してノードツリーを構築する処理にHTMLタグやCSSで指定された文字色と背景色を表示に反映するためのコードを実装します。
関連のissue: #76
=> NodeTreeBase: Implement code for coloring via HTML and CSS

src/cssmanager.cpp, src/cssmanager.h, src/image/imageviewpopup.cpp, src/jdlib/miscutil.cpp
const参照でCSSプロパティを返すメンバー関数を実装します。
また、実装した関数を使いCSSプロパティを使う箇所をconst参照に変えてコピーしないように修正します。
=> Css_Manager: Implement get_property() function returning const reference

src/config/configitems.cpp, src/config/configitems.h, src/config/defaultconf.h, src/config/globalconf.cpp, src/config/globalconf.h, src/dbtree/nodetreebase.cpp, src/fontcolorpref.cpp, src/fontcolorpref.h
スレビューでHTMLタグで指定された文字色・背景色を使用するための処理と設定を追加します。
関連のissue: #76
=> Add support for using HTML tag-specified text color in thread view

src/cssmanager.cpp, src/cssmanager.h
`get_classid()`に渡す文字列の型を`const std::string&`から`std::string_view`に変更して文字列リテラルを渡したときにコピーが発生しないように変更します。
=> Css_Manager: Change get_classid() parameter type to use std::string_view

src/config/aboutconfig.cpp, src/config/configitems.cpp, src/config/configitems.h, src/config/defaultconf.h, src/config/globalconf.cpp, src/config/globalconf.h, src/dbtree/nodetreebase.cpp
URLのパーセントエンコーディングをデコードして表示するスレビューのオプションをabout:configに追加します。
関連のissue: #76
=> Add URL Percent-Encoding decoding option to about:config

src/dbtree/interface.cpp, src/dbtree/root.cpp, src/dbtree/root.h
外部板に追加した2ch,5chの板を2ちゃんねる互換板ではなく2ch,5chの板として処理するように変更します。
- 手動で追加した板でもユーザーエージェントやプロキシなどネットワーク通信の2ch,5ch向け全体設定を利用するように変更します。
- 2ch,5chの板は板移転する前のURLを外部板に追加できる状態だったため追加するときに板移転の処理を行って重複してないか判定します。
関連のissue: #76
=> Root: Treat manually added 2ch/5ch boards as native boards

src/dbtree/nodetreebase.cpp
スレッドの読み込みでHTTP 416 Range Not Satisfiableが返ってきたときはスレッドが壊れた(復旧不可能)と判定してエラーの表示になっていました。
しかし、ネットワーク設定の変更などで読み込みが再開できる可能性があるため416が返ってきてもスレッドが壊れたと判定しないように修正します。
関連のissue: #76
=> NodeTreeBase: Do not mark thread as broken on HTTP 416 error

src/dbtree/nodetree2ch.cpp, src/login2ch.cpp, src/passwdpref.h
2chやbbspinkのログ取得に使用されていたRokkaシステムは廃止されたため接続処理を削除してコードを整理します。
2chログイン機能はサイトの更新に対応していないため現在機能していません。
そのためログイン処理を削除し、現在サポート中止していることを通知するメッセージを表示するように修正します。
=> Remove Rokka support

src/dbtree/nodetree2chcompati.cpp, src/dbtree/nodetree2chcompati.h
DATをキャッシュに保存する前の前処理を修正して廃止されたrawモードの処理を取り除きます。
- 先頭にrawモードのステータスが入っていたら取り除く処理
- ステータス行のスキップ処理
関連のissue: #76
=> NodeTree2chCompati: Get rid of raw mode processing

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
DATやHTMLを解析してノードツリーを構築する関数を修正してHTML`<a>`要素を無条件で解析するように変更します。
関連のissue: #76
=> NodeTreeBase: Modify parsing HTML to unconditionally parse <a> elements

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
`std::string_view`からポインターを取得する箇所でスコープ外のローカル変数を示すポインターを使用していると指摘されたため引数を`const char*`と`std::size_t`に分けてメンバー関数に渡すようにコードを書き換えてcppcheckのレポートを抑制します。
```
src/dbtree/nodetreebase.cpp:2083:31: error: Using object that points
to local variable 'str_mail' that is out of scope. [invalidLifetime]
(snip)
```
=> NodeTreeBase: Suppress code analysis report about invalid lifetime

src/dbtree/nodetreebase.cpp
ラムダ関数の引数の名前がメンバー関数の引数の名前をシャドーイングしているとgccに指摘されたため修正します。
gcc 12のレポート
```
../src/dbtree/nodetreebase.cpp:561:54: warning: declaration of ‘const std::string& query’ shadows a parameter [-Wshadow]
561 |     const auto make_pattern = []( const std::string& query ) {
|                                   ~~~~~~~~~~~~~~~~~~~^~~~~
../src/dbtree/nodetreebase.cpp:554:66: note: shadowed declaration is here
554 | std::list< int > NodeTreeBase::get_res_query( const std::string& query, const bool mode_or ) const
|                                               ~~~~~~~~~~~~~~~~~~~^~~~~
```
=> NodeTreeBase: Fix parameter name shadowing

src/article/drawareabase.cpp, src/environment.cpp, src/skeleton/edittreeview.cpp
役に立たないキャストを行っているとgccに指摘されたため修正します。
gcc 12のレポート
```
../src/article/drawareabase.cpp:3189:64: warning: useless cast to type ‘int’ [-Wuseless-cast]
3189 |                     else if( mode == LIVE_SCRMODE_STEADY ) y = ( int ) ( current_y + CONFIG::get_live_speed() );
|                                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/skeleton/edittreeview.cpp:271:46: warning: useless cast to type ‘class Gtk::TreePath’ [-Wuseless-cast]
271 |             Gtk::TreeRow row = get_row( Gtk::TreePath( m_jump_path ) );
|                                              ^~~~~~~~~~~~~~~~~~~~~~~
../src/environment.cpp:35:51: warning: useless cast to type ‘std::string’ {(snip)} [-Wuseless-cast]
35 | std::string ENVIRONMENT::get_jdbbs(){ return …
```
=> Fix compiler warnings for useless cast

src/dbtree/nodetreebase.cpp
5chやbbspinkのスレを表示したときレスアンカーが表示されない問題を修正します。
https://next2ch.net/test/read.cgi/linux/1654053581/82-84
Closes #1178
=> NodeTreeBase: Fix bug missing reply anchors in 5ch threads

src/article/drawareabase.cpp
AddressSanitizerを有効にしてスレビューを表示したときに`Pango::FontMetrics`のオブジェクトが開放されずメモリリークが発生したためC APIに書き直して修正します。
AddressSanitizerのレポート
```
Direct leak of 40 byte(s) in 1 object(s) allocated from:
#0 0x7fd2d34decaf in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
#1 0x7fd2d1fa1948 in g_malloc (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x5f948) (BuildId: 88d7a1c8d79fc1becb2737be566dd98523394d55)
#2 0x55c83a6e64a6 in ARTICLE::DrawAreaBase::init_font() ../src/article/drawareabase.cpp:357
#3 0x55c83a6f14b7 in ARTICLE::DrawAreaBase::clear_screen() ../src/article/drawareabase.cpp:742
(snip)
Direct leak of 40 byte(s) in 1 object(s) allocated from:
#0 0x7fd2d34decaf in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:69
#1 0x7fd2d1fa1948 in g_malloc …
```
=> DrawAreaBase: Fix memory leak for PangoFontMetrics

src/jdlib/miscgtk.cpp, src/jdlib/miscgtk.h
`snprintf()`の書式'%x'に対して符号付きの整数(int)を渡しているとgccに指摘されたため正しい型(unsigned int)に変更します。
gcc 12のレポート
```
../src/jdlib/miscgtk.cpp:190:41: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 4 has type ‘int’ [-Wformat=]
190 |     snprintf( str_value, CHAR_BUF, "#%04x%04x%04x", l_rgb[ 0 ], l_rgb[ 1 ], l_rgb[ 2 ] );
|                                      ~~~^           ~~~~~~~~~~
|                                         |                    |
|                                         unsigned int         int
|                                      %04x
../src/jdlib/miscgtk.cpp:190:45: warning: format ‘%x’ expects argument of type ‘unsigned int’, but argument 5 has type ‘int’ [-Wformat=]
190 |     snprintf( str_value, CHAR_BUF, "#%04x%04x%04x", l_rgb[ 0 ], l_rgb[ 1 ], l_rgb[ 2 ] …
```
=> Fix snprintf() format mismatch by changing param type to unsigned int

src/bbslist/bbslistviewbase.cpp, src/skeleton/edittreeview.cpp
浮動点少数リテラルがfloat型に暗黙変換されて精度が下がるとコンパイラーに警告されたためリテラルをfloat型に書き換えて修正します。
gcc 12のレポート
```
../src/bbslist/bbslistviewbase.cpp:1899:69: warning: conversion from ‘double’ to ‘float’ changes value from ‘1.0000000000000001e-1’ to ‘1.00000001e-1f’ [-Wfloat-conversion]
1899 |     if( CONFIG::get_scroll_tree() ) m_treeview.scroll_to_row( path, 0.1 );
|                                                                     ^~~
../src/bbslist/bbslistviewbase.cpp:2801:45: warning: conversion from ‘double’ to ‘float’ changes value from ‘1.0000000000000001e-1’ to ‘1.00000001e-1f’ [-Wfloat-conversion]
2801 |             m_treeview.scroll_to_row( path, 0.1 );
|                                             ^~~
```
=> Fix implicit narrowing conversion for floating point literal

src/article/drawareabase.cpp, src/cssmanager.cpp, src/image/imageadmin.cpp, src/jdlib/tfidf.cpp
比較演算子の'=='や'!='を使ってdouble型の数値が等しい、等しくないをチェックするのは安全でないとgccに指摘されたため絶対値と計算機イプシロンを使った比較に書き換えて修正します。
一部の比較式については整数にキャストして行います。
gcc 12のレポート
```
../src/article/drawareabase.cpp:2976:13: warning: comparing floating-point with ‘==’ or ‘!=’ is unsafe [-Wfloat-equal]
2976 |         if( dy ){
|             ^~
../src/article/drawareabase.cpp:3021:66: warning: comparing floating-point with ‘==’ or ‘!=’ is unsafe [-Wfloat-equal]
3021 |             if( event->direction == GDK_SCROLL_DOWN && current_y == adjust->get_upper() - adjust->get_page_size() ) return;
|                                                        ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/cssmanager.cpp:565:11: warning: comparing floating-point with ‘==’ or ‘!=’ is unsafe [-Wfloat-equal]
565 |     if( ! height ) …
```
=> Fix comparing floating point with '==' or '!='

docs/manual/2023.md, meson.build, src/jdversion.h
=> Bump version to 0.10.0-beta

CONTRIBUTING.md, src/bbslist/favoriteview.cpp, src/bbslist/historyview.cpp, src/login2ch.cpp, src/loginbe.cpp, src/skeleton/editview.cpp, src/skeleton/editview.h, src/skeleton/tabswitchmenu.h, src/skeleton/undobuffer.h, src/xml/document.cpp, src/xml/dom.cpp
Mesonを使った[Unity build][unitybuild]をサポートするためコンパイラーを修正します。
関連のissue: #1177
複数のソースファイルを結合してコンパイルするunity buildを実行すると無名enumの列挙子が衝突してコンパイルエラーになるためenumをconstexpr定数に変更して入れ子の名前空間の中に置くことで修正します。
複数のソースファイルを1つに結合してコンパイルするunity buildを実行すると型の名前が衝突してコンパイルエラーになるため構造体の名前を変更して修正します。
複数のソースファイルを1つに結合してコンパイルするunity buildを実行すると同じヘッダーファイルを複数回includeして定義エラーになるためインクルードガードを追加して修正します。
複数のソースファイルを1つに結合してコンパイルするunity buildを実行するとマクロが再定義されてコンパイラー警告がでたためマクロをconstexpr定数に変更して入れ子の名前空間の中に置くことで修正します。
ビルドツールMesonの機能Unity buildを利用するときの注意をガイドに追加します。
[unitybuild]: https://mesonbuild.com/Unity-builds.html
=> Fix compile errors on Unity build

src/core.h
未使用のprivateメンバー変数があるとclangに指摘されたため取り除きます。
clang 15のレポート
```
../src/core.h:108:24: error: private field 'm_menuitem_prevview' is not used [-Werror,-Wunused-private-field]
Gtk::MenuItem* m_menuitem_prevview{};
^
```
=> Core: Get rid of unused private field

src/login2ch.cpp
未使用の変数があるとclang 16に指摘されたため `#if 0` ... `#endif` でコメントアウトしてコンパイラー警告を抑制します。
clang-16のレポート
```
[244/323] Compiling C++ object src/jdim.p/login2ch.cpp.o
../src/login2ch.cpp:23:23: warning: unused variable 'kSizeOfRawData' [-Wunused-const-variable]
constexpr std::size_t kSizeOfRawData = 64 * 1024;
^
1 warning generated.
[283/323] Compiling C++ object test/gtest_jdim.p/.._src_login2ch.cpp.o
../src/login2ch.cpp:23:23: warning: unused variable 'kSizeOfRawData' [-Wunused-const-variable]
constexpr std::size_t kSizeOfRawData = 64 * 1024;
^
1 warning generated.
```
=> Login2ch: Fix compile error about unused const variable

.github/workflows/weekly.yml
GitHub Actionsのworkflowに Unity build を有効にしてビルドするjobを追加して定期的に実行します。
追加するjobはパッチをマージする要件にはしないのでPull requestを開いたときやmasterブランチにpushしたときには実行しません。
スケジュール: 毎週月曜日 00:00 UTC
Ubuntu | Compiler | Unity size | Meson option
---    | ---      | ---        | ---
22.04  | gcc 12   | 1000       | -Dwerror=true
22.04  | clang 15 | 1000       | -Dwerror=true
関連のissue: https://github.com/JDimproved/JDim/issues/1177
GitHub Actionsのworkflowに meson のかわりに [muon][1] を使ってJDimをビルドするjobを追加して定期的に実行します。
追加するjobはパッチをマージする要件にはしないのでPull requestを開いたときやmasterブランチにpushしたときには実行しません。
- muonは作者のgitリポジトリ(masterブランチ)からビルドして使います。
- muonのビルドにはmesonを使いブートストラッピングは省略します。
関連のissue: https://github.com/JDimproved/JDim/issues/897
[1]: https://git.sr.ht/~lattis/muon
=> Add weekly CI for Unity build and muon

src/jdlib/loader.cpp, src/jdlib/misccharcode.cpp, src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, src/main.cpp
doxygenによるHTML生成を実行したときに出る警告を修正します。
doxygenのレポート
```
/home/ma8ma/var/repos/JDim/src/jdlib/misccharcode.cpp:195: warning: Found unknown command '\x1B'
/home/ma8ma/var/repos/JDim/src/jdlib/miscutil.cpp:537: warning: argument 'str_in' of command @param is not found in the argument list of MISC::replace_newlines_to_str(const std::string &str, std::string_view replace)
/home/ma8ma/var/repos/JDim/src/jdlib/miscutil.cpp:537: warning: The following parameter of MISC::replace_newlines_to_str(const std::string &str, std::string_view replace) is not documented:
parameter 'str'
/home/ma8ma/var/repos/JDim/src/jdlib/miscutil.cpp:1071: warning: Unsupported xml/html tag <mark> found
/home/ma8ma/var/repos/JDim/src/jdlib/miscutil.cpp:1596: warning: explicit link request to '数字' could not be resolved …
```
=> docs: Fix doxygen warnings

src/dbtree/nodetree2ch.cpp
[2023-07-11][1] から5ch.netのDATファイルへのアクセスが開放されたため過去ログ読み込みに対応します。
新しい過去ログサーバが稼働するまで過去ログを読めないスレッドが一部あります。
DAT落ちしたスレに対してスレ再取得を行うとスレのデータが消えて無くなることがあります。
[1]: https://agree.5ch.net/test/read.cgi/operate/9240230711/3
=> Implement reading past logs with access to 5ch.net DAT files

src/dbtree/nodetreebase.cpp
スレッド読み込み中に異常終了したため`std::string_view`の部分文字列を取得する処理を修正します。
gcc12.2 gdbのバックトレース
```cpp
#10 0x0000555555c32acf in std::__sv_check(unsigned long, unsigned long, char const*)
(__size=243, __pos=244, __s=0x55555598ca42 "basic_string_view::substr") at /usr/include/c++/12/string_view:67
#11 0x0000555555c32fa2 in std::basic_string_view<char, std::char_traits<char> >::substr(unsigned long, unsigned long) const
(this=0x7fffe97fe210, __pos=244, __n=18446744073709551615) at /usr/include/c++/12/string_view:311
#12 0x0000555555c7d072 in DBTREE::NodeTreeBase::parse_date_id(DBTREE::NODE*, std::basic_string_view<char, std::char_traits<char> >)
(gdb) frame 12
#12 0x0000555555c7d072 in DBTREE::NodeTreeBase::parse_date_id (this=0x5555577c19f0, header=0x555558e6bbe8,
2019                str = str.substr( …
```
=> Fix crash on NodeTreeBase::parse_date_id()

.github/workflows/weekly.yml
Weekly CIのmuonジョブを更新してgit cloneしたmuonリポジトリの情報とビルドしたmuonのバージョンをjobのログに出力するようにします。
関連のpull request: https://github.com/JDimproved/JDim/pull/1189
https://github.com/ma8ma/JDim/pull/78
=> Weekly CI: Add logging for cloned muon repository and built version

src/jdlib/miscutil.cpp, test/gtest_jdlib_miscutil.cpp
whitespace だけの文字列の入力に対して、その whitespace を全て
正しく除去したものを返すよう修正する。
修正前は、そのような文字列の入力に対しては変更前の文字列を返していたが、
これを空白の文字列を新たに作成し、それを返すよう変更する。
従って、以下の変更を一部修正する。
https://github.com/JDimproved/JDim/commit/62abdbfc55c9e1df8d92d862cfb33c33b8a01b90
これに応じて、対応するテストをAsciiTrimTestの中に追加する。
[1] https://mao.5ch.net/test/read.cgi/linux/1689151433/302
Fixes #1213
=> jdlib/miscutil: fix return value of ascii_trim for whitespace-only string (#1213)

src/config/configitems.cpp, src/config/configitems.h, src/config/defaultconf.h, src/config/globalconf.cpp, src/config/globalconf.h, src/dbtree/nodetree2ch.cpp, src/proxypref.h
プロキシを使わない接続で過去ログが見つからなかったときは2ch読み込み用プロキシを使う設定を実装します。
この設定は実験的なサポートのため変更または廃止の可能性があります。
プロキシを使わない接続で過去ログが見つからなかったときは2ch読み込み用プロキシを使う設定のオプションを実装します。
このオプションは実験的なサポートのため変更または廃止の可能性があります。
プロキシを使わない接続で過去ログが見つからなかったときは2ch読み込み用プロキシを使う処理を実装します。
この機能は実験的なサポートのため変更または廃止の可能性があります。
Closes #1202
Closes ma8ma/JDim#80
=> Add handling to use 2ch proxy if past logs not available without proxy

src/jdlib/jdsocket.cpp
OpenBSDで定義されないマクロをデフォルトの値(0)で定義します。
マクロの定義条件は汎用的にしたためOpenBSDであるかチェックはしません。
参考にしたコミット
https://github.com/nodejs/node/commit/75340f3c524cbe8602ba8f5a48b8bf8572bad8f1
https://mevius.5ch.net/test/read.cgi/unix/1568040383/850-851n
=> Socket: Define AI_V4MAPPED for OpenBSD

src/message/logmanager.cpp
先頭に空白行が連続する書き込みをすると、5chの仕様ではそれらを
削除したものが帰ってくるので、Log_Manager::check_write で
簡易チェックをするとき、先頭の連続する改行は読み飛ばす
不具合報告:
https://next2ch.net/test/read.cgi/linux/1654053581/112-113
Closes #1220
=> Log_Manager::check_write: skip heading continuous newlines for early-check

src/dbtree/nodetreebase.cpp
DATに含まれるHTMLの解析処理を修正して`<a>`要素がレスアンカーであるか判定する処理を追加します。
板URLとスレURLのドメインやパスが一致しないスレ、例えば2chスレ過去ログ板にあるスレはレスアンカー部分の`<a>`にあるhref属性とスレURLが異なるためアンカーのリンクが正常に動作しませんでした。
Closes #1219
=> Add logic to identify `<a>` elements as reply anchors in HTML parsing

src/article/drawareabase.cpp
スレを更新したときに異常終了したためgdbで調べたところLAYOUT構造体のメンバーにアクセスしたときnullptrを参照していました。
そのためメンバーにアクセスする処理の前にnullチェックを追加して修正します。
gdb のバックトレース
```
Thread 1 "jdim" received signal SIGSEGV, Segmentation fault.
ARTICLE::DrawAreaBase::exec_draw_screen (this=0x55555cd359c0,
y_redraw=0, height_redraw=723)
at ../src/article/drawareabase.cpp:1820
1820                if( header->rect->y <= pos_y && header->next_header->rect->y >= pos_y )  break;
(gdb) p header
$1 = (ARTICLE::LAYOUT *) 0x55555d4969a8
(gdb) p header->rect
$2 = (ARTICLE::RECTANGLE *) 0x0
```
=> DrawAreaBase: Add null check to fix segfault

src/article/drawareabase.cpp, src/article/drawareabase.h
メンバー関数の戻り値を使っていないとcppcheckに指摘されたためcairommのオブジェクトから一時的に借りる処理を修正して生ポインターの変数を使うように変更します。
```
src/article/drawareabase.cpp:4713:14: warning: Return value of function m_cr.release() is not used. [ignoredReturnValue]
m_cr.release();
^
src/article/drawareabase.cpp:4724:10: warning: Return value of function m_cr.release() is not used. [ignoredReturnValue]
m_cr.release();
^
```
=> DrawAreaBase: Use cairo_t instead of std::unique_ptr<cairo_t>

src/dbtree/nodetreebase.cpp
HTML`<a>`要素のhref属性を解析する処理を修正しschema-less URL (net\_path)をリンクとして解析します。
修正前は板のプロパティでローカルルールを見たときリンクが表示されずクリックで開くことができませんでした。
Closes #1225
=> NodeTreeBase: Fix schema-less URL parsing

src/dbimg/imginterface.cpp
```
src/dbimg/imginterface.cpp:83:17: style: Variable 'img' can be declared as pointer to const [constVariablePointer]
DBIMG::Img* img = DBIMG::get_img( url );
^
src/dbimg/imginterface.cpp:99:17: style: Variable 'img' can be declared as pointer to const [constVariablePointer]
DBIMG::Img* img = DBIMG::get_img( url );
^
src/dbimg/imginterface.cpp:156:17: style: Variable 'img' can be declared as pointer to const [constVariablePointer]
DBIMG::Img* img = DBIMG::get_img( url );
^
src/dbimg/imginterface.cpp:164:17: style: Variable 'img' can be declared as pointer to const [constVariablePointer]
DBIMG::Img* img = DBIMG::get_img( url );
^
src/dbimg/imginterface.cpp:172:17: style: Variable 'img' can be declared as pointer to const …
```
=> dbimg: Add const qualifier to pointer variables in local scope

src/history/historymanager.cpp
```
src/history/historymanager.cpp:398:18: style: Variable 'history' can be declared as pointer to const [constVariablePointer]
ViewHistory* history = get_viewhistory( url );
^
src/history/historymanager.cpp:471:18: style: Variable 'history' can be declared as pointer to const [constVariablePointer]
ViewHistory* history = get_viewhistory( url );
^
src/history/historymanager.cpp:480:18: style: Variable 'history' can be declared as pointer to const [constVariablePointer]
ViewHistory* history = get_viewhistory( url );
^
src/history/historymanager.cpp:511:18: style: Variable 'history' can be declared as pointer to const [constVariablePointer]
ViewHistory* history = get_viewhistory( url );
^ …
```
=> History_Manager: Add const qualifier to pointer variables in local scope

src/dbtree/boardbase.cpp
```
src/dbtree/boardbase.cpp:705:18: style: Variable 'article' can be declared as pointer to const [constVariablePointer]
ArticleBase* article = get_article_fromURL( url );
^
src/dbtree/boardbase.cpp:2196:23: style: Variable 'art' can be declared as pointer to const [constVariablePointer]
for( ArticleBase* art : m_list_subject ) {
^
src/dbtree/boardbase.cpp:2347:23: style: Variable 'article' can be declared as pointer to const [constVariablePointer]
for( ArticleBase* article : m_hash_article ) {
^
```
=> BoardBase: Add const qualifier to pointer variables in local scope

src/skeleton/admin.cpp, src/skeleton/dragnote.cpp, src/skeleton/tabnote.cpp
```
src/skeleton/dragnote.cpp:337:25: style: Variable 'tablabel' can be declared as pointer to const [constVariablePointer]
SKELETON::TabLabel* tablabel = m_notebook_tab.get_tablabel( page );
^
src/skeleton/tabnote.cpp:177:29: style: Variable 'tab' can be declared as pointer to const [constVariablePointer]
SKELETON::TabLabel* tab = get_tablabel( i );
^
src/skeleton/tabnote.cpp:214:25: style: Variable 'tablabel' can be declared as pointer to const [constVariablePointer]
SKELETON::TabLabel* tablabel = get_tablabel( page );
^
src/skeleton/tabnote.cpp:544:29: style: Variable 'tab' can be declared as pointer to const [constVariablePointer]
SKELETON::TabLabel* tab = get_tablabel( page );
^
src/skeleton/admin.cpp:354:29: style: …
```
=> skeleton: Add const qualifier to pointer variables in local scope

src/dbtree/nodetreebase.cpp
datデータからHTML要素を解析する処理のうち`<a>`要素のhref属性を探す処理を修正します。
修正前は`<a>`タグの中で最初に現れる属性がhrefであると決め打ちしていたためhrefの前に別の属性があるリンクではURLが間違って設定される問題がありました。
href属性の判定は速度を重視するため不完全なチェックです。`<a>`タグに含まれる'='、global属性、data属性で誤判定する可能性があります。
https://next2ch.net/test/read.cgi/linux/1654053581/127
Closes #1236
=> NodeTreeBase: Fix HTML href attribute parsing

src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
`set_num_id_name()`を呼び出すループ処理を修正して効率を高めます。
ただし、コンパイラーが最適化を行っている場合は効果は微小です。
関連のissue: #1233
=> Improve performance for NodeTreeBase::set_num_id_name()

src/article/drawareabase.cpp
スレッドの何番目の投稿と発言数をテキストに変換してバッファにコピーする処理を修正して数値の表示可能な桁数を最大5桁にします。
5桁より大きな数値は99999と表示するようにします。
何番目の投稿と発言数用のバッファは固定サイズなので
表示可能な最大値を超えないように切り詰めます。
Close #1233
Close ma8ma/JDim#83
=> Set upper limitation to 99999 for displaying post count

src/jdlib/miscutil.h, test/gtest_jdlib_miscutil.cpp
haystackの末尾がneedleと一致するかチェックする文字列の操作を実装します。合わせてテストケースを追加し動作を確認します。
新しい規格のC++20には同等の操作を行うメンバー関数`std::string::ends_with()`や`std::string_view::ends_with()`がありますがJDimが利用する規格はC++17であるため自前で実装します。
=> Implement MISC::ends_with(haystack, needle)

src/dbtree/root.cpp
まちBBSのURLのうち地方名サブドメインが付いてないURLをまちBBSとして扱うように修正します。
まちBBSのURLは地方名サブドメインが付いてるタイプとサブドメインが無いタイプの2種類あります。
修正前は地方名サブドメインが付いてないURLを登録して開くとHTTPリダイレクトが発生して読み込みに失敗していました。
例
- `https://tokyo.machi.to/tokyo/`
- `https://machi.to/tokyo/`
参考文献
https://www.machi.to/bbs/read.cgi/tawara/1416672649/65
Closes #1242
=> Root: Support machi.to URL without subdomain

src/dbtree/nodetreebase.cpp, test/gtest_dbtree_nodetreebase.cpp
まちBBS(machi.to)のスレッドにあるURLからリンク先の確認ページを表示するURLを取り除くように修正します。
修正前はまちBBSでofflaw.cgiを使わないモードでスレッドを読み込むと通常リンク(青)をクリックしたときリンク先の確認ページが開かれるようになっていました。
Closes #1241
=> Remove link confirmation page for URLs in machi.to threads

src/dbtree/root.cpp
5ch.netのURLのうちサブドメインが付いてないURLを5ch.netとして扱うように修正します。
5ch.netのサブドメインが付いていないURLはサブドメインが付いているURLにHTTPリダイレクトします。
板のローカルルールにある他の板へリンクなどサブドメインの無いURLが使われているところがあります。
修正前はサブドメインが無い5ch.netの板URLを開くとwebブラウザで開かれていました。
例
- `https://agree.5ch.net/operate/`
- `https://5ch.net/operate`
Closes #1243
=> Root: Support 5ch.net URL without subdomain

src/bbslist/bbslistadmin.cpp, src/board/boardviewbase.cpp, src/dndmanager.cpp
```
src/bbslist/bbslistadmin.cpp:262:22: style: Variable 'view' can be declared as pointer to const [constVariablePointer]
BBSListViewBase* view = dynamic_cast< BBSListViewBase* >( get_view( url ) );
^
src/board/boardviewbase.cpp:1888:30: style: Variable 'art' can be declared as pointer to const [constVariablePointer]
DBTREE::ArticleBase* art = row[ m_columns.m_col_article ];
^
src/dndmanager.cpp:43:24: style: Variable 'manager' can be declared as pointer to const [constVariablePointer]
CORE::DND_Manager* manager = CORE::get_dnd_manager();
^
```
=> Add const qualifier to pointer variables in local scope part6

src/dbtree/boardbase.cpp, src/dbtree/boardbase.h, src/dbtree/boardlocal.h, src/dbtree/interface.cpp, src/dbtree/interface.h, src/dbtree/root.cpp, src/dbtree/root.h, src/searchmanager.cpp, src/searchmanager.h
キャッシュ内のログ検索をキャンセルできない不具合を修正します。
前の修正でキャンセルを伝達するフラグ変数をconst参照渡しから値渡しに変更していたためキャンセルになったかチェック不能になっていました。
バグが入ったコミット
commit 9313fb246bd8612fd50c1d21dfaa1fd5d9f3d182
Closes #1249
=> Fix cancel operation on log search in the cache

src/dbtree/boardbase.cpp
`std::any_of()`が使えるとcppcheckに指摘されたためforループ文を修正します。
```
src/dbtree/boardbase.cpp:1557:9: style: Consider using std::any_of algorithm instead of a raw loop. [useStlAlgorithm]
for( const std::string& word : m_list_abone_word_thread ) {
^
src/dbtree/boardbase.cpp:1565:0: style: Consider using std::any_of algorithm instead of a raw loop. [useStlAlgorithm]
if( regex.exec( pat, article->get_subject(), offset, icase, newline, usemigemo, wchar ) ) return true;
^
src/dbtree/boardbase.cpp:1571:9: style: Consider using std::any_of algorithm instead of a raw loop. [useStlAlgorithm]
for( const std::string& word : CONFIG::get_list_abone_word_thread() ) {
^
src/dbtree/boardbase.cpp:1579:0: style: Consider using std::any_of algorithm instead of a raw loop. [useStlAlgorithm]
if( …
```
=> BoardBase: Use std::any_of() instead of range-based for loops

src/iomonitor.cpp, src/jdlib/jdiconv.cpp, src/jdlib/jdsocket.cpp, src/jdlib/jdsocketopenssl.h
関数を呼び出した後にerrnoの値をチェックする箇所では関数を呼び出す前に errno を 0 にリセットします。
参考文献
- <https://linuxjm.osdn.jp/html/LDP_man-pages/man3/errno.3.html>
- <https://www.jpcert.or.jp/sc-rules/c-err30-c.html>
=> Reset errno to zero before calling functions

src/board/preference.cpp, src/board/preference.h, src/fontcolorpref.cpp, src/fontcolorpref.h, src/proxypref.h
ディスプレイ解像度が小さい環境で板のプロパティを開いたときウインドウがデスクトップ画面からはみ出さないようにスクロールバーを追加します。
修正前はディスプレイ解像度が小さい場合ウインドウの一部が画面外にはみ出して見たり操作したりすることが困難になっていました。
ディスプレイ解像度が小さい環境でフォントと色の詳細設定を開いたときウインドウがデスクトップ画面からはみ出さないようにスクロールバーを追加します。
修正前はディスプレイ解像度が小さい場合ウインドウの一部が画面外にはみ出して見たり操作したりすることが困難になっていました。
ディスプレイ解像度が小さい環境でプロキシ設定を開いたときウインドウがデスクトップ画面からはみ出さないように"ポート番号"の入力欄のサイズを変更します。
修正前はディスプレイ解像度が小さい場合ウインドウの一部が画面外にはみ出して見たり操作したりすることが困難になっていました。
Closes #1255
=> Adjust window size for small display

INSTALL, docs/manual/make.md, src/article/drawareabase.cpp, src/article/drawareabase.h, src/config/aboutconfig.cpp, src/config/configitems.cpp, src/config/configitems.h, src/config/defaultconf.h, src/config/globalconf.cpp, src/config/globalconf.h
about:config に「スレビューのテキストを描画する方法 ( 0: PangoGlyphString 1: PangoLayout )」を追加します。
ビルドオプション(`-Dpangolayout=enabled`)は削除せず残しデフォルト設定の方法を指定します。
修正前は描画方法をビルドオプションで指定していました。
2つの方法(PangoLayoutとPangoGlyphString)はpangoライブラリで実装できるため設定で変更できる仕組みを導入して利便性を向上させます。
Closes #1258
=> Add thread view text drawing method choice to about:config

src/environment.cpp
`std::find_if()`が使えるとcppcheckに指摘されたためforループ文を修正します。
```
src/environment.cpp:261:13: style: Consider using std::find_if algorithm instead of a raw loop. [useStlAlgorithm]
{
^
```
=> environment: Use std::find_if() instead of range-based for loops

src/dbtree/root.cpp
`std::find_if()`が使えるとcppcheckに指摘されたためforループ文を修正します。
```
src/dbtree/root.cpp:1442:77: style: Consider using std::find_if algorithm instead of a raw loop. [useStlAlgorithm]
&& url.find( table.old_path_board + "/" ) != std::string::npos ){
^
```
=> Root: Use std::find_if() instead of range-based for loops

src/skeleton/admin.cpp, src/skeleton/admin.h
メンバー関数のポインター型引数にconstを付けられるとcppcheckに指摘されたため修正します。
```
src/skeleton/admin.cpp:958:34: style: Parameter 'view' can be declared as pointer to const [constParameterPointer]
void Admin::update_status( View* view, const bool force )
^
```
=> Admin: Add const qualifier to pointer parameter in member function

src/linkfilterpref.cpp, src/linkfilterpref.h
親クラスのメンバー関数と名前が重複しているとcppcheckに指摘されたため子クラスのメンバー関数の名前を変更します。
cppcheck 2.12.1のレポート
```
src/linkfilterpref.h:29:23: warning: The class 'LinkFilterDiag' defines member function with name 'get_url' also defined in its parent class 'PrefDiag'. [duplInheritedMember]
Glib::ustring get_url() const { return m_entry_url.get_text(); }
^
src/skeleton/prefdiag.h:32:28: note: Parent function 'PrefDiag::get_url'
const std::string& get_url() const { return m_url; }
^
src/linkfilterpref.h:29:23: note: Derived function 'LinkFilterDiag::get_url'
Glib::ustring get_url() const { return m_entry_url.get_text(); }
^
```
=> LinkFilterDiag: Rename member function to avoid conflict with parent member

src/dbtree/boardbase.cpp
掲示板のsubject.txtを取得して解析する部分を修正して板のテキストエンコーディングを設定する処理を変更します。
about:config の「(安全でない) スレ一覧とスレビューのプロパティにあるエンコーディング設定を有効にする」が"はい"のときはHTTPヘッダーやHTMLデータに含まれるエンコーディング情報を無視して板のプロパティで設定されたエンコーディングを優先します。
2023-10-01 時点では、5chのagreeやkesサーバーにある板からsubject.txtを取得するとHTTPのContent-Typeにはcharset=utf-8が指定されています。
しかし、送られてきたテキストデータはshift_jisで符号化されているため文字化けが発生します。
修正前は板のプロパティでテキストエンコーディングを変更して文字化けを直しても再びsubject.txtを取得したときにエンコーディングが再判定されて文字化けが再発する問題がありました。
関連のissue: #1265
=> BoardBase: Ignore encoding analysis when encoding setting is enabled

src/board/preference.cpp, src/board/preference.h, src/dbtree/article2ch.cpp, src/dbtree/article2ch.h, src/dbtree/article2chcompati.cpp, src/dbtree/article2chcompati.h, src/dbtree/articlebase.h, src/dbtree/articlejbbs.cpp, src/dbtree/articlejbbs.h, src/dbtree/articlemachi.cpp, src/dbtree/articlemachi.h, src/dbtree/board2ch.cpp, src/dbtree/board2ch.h, src/dbtree/board2chcompati.cpp, src/dbtree/board2chcompati.h, src/dbtree/boardbase.cpp, src/dbtree/boardbase.h, src/dbtree/boardjbbs.cpp, src/dbtree/boardjbbs.h, src/dbtree/boardmachi.cpp, src/dbtree/boardmachi.h, src/dbtree/interface.cpp, src/dbtree/interface.h, src/message/messageview.cpp, src/message/messageview.h, src/message/messageviewbase.cpp, src/message/messageviewbase.h, src/message/post.cpp
板のプロパティに「UTF-8で書き込む」実験的なオプションを追加します。
掲示板がUTF-8の書き込みに対応してるか確認して使用してください。
このオプションは実験的なサポートのため変更または廃止の可能性があります。
名前欄に絵文字を入力して5ch.netに書き込むと名前に含まれる絵文字が文字参照の形で表示されます。
絵文字などShift_JISで表現できない文字はHTML文字参照に変換して送信しますが`&`が`&amp;`に変換されて文字参照がエスケープされるため元の文字にデコードできません。
UTF-8でURLエンコードすると文字参照を使わず送信することが可能です。
板に「UTF-8で書き込む」フラグ設定を実装します。
板の「UTF-8で書き込む」フラグ設定がtrueなら書き込みメッセージのURLエンコードをUTF-8に変更し、HTTP POSTリクエストのContent-Typeにcharset=utf-8を追加します。
Closes #1264
=> Add experimental 'Write in UTF-8' option to board preferences

src/dbtree/board2ch.cpp, src/dbtree/board2ch.h
親クラスのメンバー関数を呼び出しているだけのメンバー関数があるとcppcheckに指摘されたため子クラスのメンバーを整理します。
cppcheck 2.12.1のレポート
```
src/dbtree/board2ch.h:64:21: style: The function 'url_bbscgi_new' overrides a function in a base class but just delegates back to the base class. [uselessOverride]
std::string url_bbscgi_new() const override;
^
src/dbtree/board2chcompati.h:45:21: note: Virtual function in base class
std::string url_bbscgi_new() const override;
^
src/dbtree/board2ch.h:64:21: note: Function in derived class
std::string url_bbscgi_new() const override;
^
src/dbtree/board2ch.h:67:21: style: The function 'url_subbbscgi_new' overrides a function in a base class but just delegates back to the base class. [uselessOverride]
std::string url_subbbscgi_new() const override;
^
src/dbtree/board2chcompati.h:48:21: note: Virtual …
```
=> Board2ch: Get rid of useless override member functions

src/board/preference.cpp, src/board/preference.h
板のプロパティのユーザーインターフェースをを編集してテキストエンコーディング設定の位置を調整します。
関連のissue: https://github.com/JDimproved/JDim/issues/1265
=> Modify board preferences to adjust text encoding setting position

src/board/preference.cpp, src/board/preference.h, src/dbtree/articlebase.cpp, src/dbtree/articlebase.h, src/dbtree/board2chcompati.cpp, src/dbtree/boardbase.cpp, src/dbtree/boardbase.h, src/dbtree/boardjbbs.cpp, src/dbtree/boardmachi.cpp, src/dbtree/interface.cpp, src/dbtree/interface.h, src/dbtree/nodetree2ch.cpp, src/dbtree/nodetree2chcompati.cpp, src/dbtree/nodetreejbbs.cpp, src/dbtree/nodetreemachi.cpp, src/jdencoding.h, src/jdlib/loaderdata.cpp, src/jdlib/loaderdata.h, src/skeleton/loadable.cpp, src/skeleton/loadable.h
板のプロパティにエンコーディングを判定する方法を選択するオプションを実装します。
この設定はユーザーがテキストエンコーディングを選択するオプションが有効のときは利用できません。
このオプションは実験的なサポートのため変更または廃止の可能性があります。
* デフォルト設定を使う (初期設定)
* HTTPヘッダーのエンコーディング情報を使う
修正前の動作は「HTTPヘッダーのエンコーディング情報を使う」ですが、修正後は「デフォルト設定を使う」が初期設定になり動作が変更されます。
板やスレの読み込むときに行うテキストエンコーディング変換にデフォルト設定のエンコーディングを使うモードを実装します。
このモードは板のプロパティのエンコーディングを判定する方法にある「デフォルト設定を使う」設定を選択しているときに使用されます。
関連のissue: #1265
=> Introduce encoding detection option when encoding choose is disabled

src/dbtree/nodetreemachi.cpp
まちBBSのスレ一覧から未読スレを開くとスレタイトルが文字化けする不具合を修正します。
以前の修正でスレタイトルのエンコーディング変換に間違いがありBoardMachiのエンコーディングを使うところがNodeTreeMachiが管理するエンコーディングになっていました。
commit 93749e7cb271636373b63c0084ef7cfa998e09f3
https://next2ch.net/test/read.cgi/linux/1654053581/172
Closes #1273
=> NodeTreeMachi: Fix subject encoding

src/article/drawareabase.cpp
スレ一覧のタブをクリックしたときにクラッシュしたためgdbのバックトレースを参考にポインターのデリファレンスを修正します。
gdbのレポート
```
Thread 1 "jdim" received signal SIGSEGV, Segmentation fault.
0x0000555555b22f3c in ARTICLE::DrawAreaBase::exec_draw_screen (
this=0x5555675008d0, y_redraw=0, height_redraw=723)
at ../src/article/drawareabase.cpp:1853
1853        while( header && header->rect->y < pos_y + height_view ){
(gdb) p header
$1 = (ARTICLE::LAYOUT *) 0x555567911a68
(gdb) p header->rect
$2 = (ARTICLE::RECTANGLE *) 0x0
```
=> DrawAreaBase: Fix segfault

src/board/preference.cpp, src/board/preference.h, src/jdencoding.h, src/skeleton/loadable.cpp
板のプロパティにあるエンコーディングを判定する方法に「テキストからエンコーディングを推測する」オプションを追加します。
このオプションはユーザーがテキストエンコーディングを選択する設定が有効のときは利用できません。
このオプションは実験的なサポートのため変更または廃止の可能性があります。
板やスレを読み込むときに行うテキストエンコーディング変換に「テキストからエンコーディングを推測する」モードを実装します。
このモードは板のプロパティのエンコーディングを判定する方法にある「テキストからエンコーディングを推測する」オプションを選択しているときに使用されます。
エンコーディングを推測した結果が正しいとは限らないため利用の際は注意してください。
関連のissue: #1265
=> add guess encoding from text option

src/article/preference.cpp, src/board/preference.cpp, src/board/preference.h, src/dbtree/articlebase.cpp, src/dbtree/articlebase.h, src/dbtree/boardbase.cpp, src/dbtree/boardbase.h, src/dbtree/interface.cpp, src/dbtree/interface.h, src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
板のプロパティにある「あぼ〜ん設定(スレビュー)」タブにある「注意」タブを「一般」タブに名称変更します。
その中に「連続投稿したIDをスレのNG IDに追加する」を追加してあぼ〜んにする連続投稿回数を設定できるようにします。
設定可能な値は 0(未設定) から 1000 までの範囲で初期設定は 0 です。
- 連続投稿したIDをあぼーんする設定が優先されるためスレのプロパティにあるNG IDからIDを削除しても再び登録されることがあります。
- このオプションは実験的なサポートのため変更または廃止の可能性があります。
板の設定「連続投稿したIDをスレのNG IDに追加」の設定値を保存する処理を追加します。また、板のプロパティの設定欄に値を反映するように実装します。
全体設定は影響が大きく使い勝手の悪さが予測されるため実装しません。
スレ主(>>1)が作品を連続投稿していくスレなどあぼーんが不適切な状況があります。
スレ設定は使いどころがあるかもしれませんが需要が不明なため見送ります。
連続投稿したIDをスレのNG IDに追加する処理を実装します。
実験的な機能の影響範囲を小さくするためこの修正では板のNG IDに追加しません。
Closes #1278
=> Add abone setting for consecutive posts to board preferences

src/global.h
異なる列挙型の値で算術演算しているとコンパイラーの警告で指摘されたためconstexpr定数に変更して修正します。
clang-16のレポート
```
/home/ma8ma/var/repos/worktree/jdim-charlie/weverythingclang16-unity1k/../src/image/imageview.cpp:181:55: warning: arithmetic between different enumeration types ('(unnamed enum at /home/ma8ma/var/repos/worktree/jdim-charlie/weverythingclang16-unity1k/../src/image/imageview.cpp:38:1)' and '(unnamed enum at ../src/global.h:9:1)') [-Wanon-enum-enum-conversion]
if( m_redraw_count >= ( IMGWIN_REDRAWTIME / TIMER_TIMEOUT ) ) {
~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~
/home/ma8ma/var/repos/worktree/jdim-charlie/weverythingclang16-unity1k/../src/message/messageviewbase.cpp:145:36: warning: arithmetic between different enumeration types ('(unnamed enum at /home/ma8ma/var/repos/worktree/jdim-charlie/weverythingclang16-unity1k/../sr …
```
=> Fix compiler warnings for -Wanon-enum-enum-conversion

src/article/drawareabase.cpp, src/global.h
無名列挙型の値がdobule型の変数と算術演算しているとコンパイラーの警告で指摘されたためconstexpr定数に変更して修正します。
clang-17のレポート
```
src/image/imageadmin.cpp:978:41: warning: compound assignment of floating-point type 'double' from enumeration type '(unnamed enum at ../src/global.h:10:1)' [-Wenum-float-conversion]
978 |         if( scroll == SCROLL_LEFT ) pos -= ICON_SIZE;
|                                     ~~~ ^  ~~~~~~~~~
src/image/imageadmin.cpp:979:18: warning: compound assignment of floating-point type 'double' from enumeration type '(unnamed enum at ../src/global.h:10:1)' [-Wenum-float-conversion]
979 |         else pos += ICON_SIZE;
|              ~~~ ^  ~~~~~~~~~
src/article/drawareabase.cpp:2305:47: warning: arithmetic between enumeration type '(unnamed enum at /home/ma8ma/var/repos/JDim/weverythingclang17-unity/../src/arti …
```
=> Fix compiler warnings for -Wenum-float-conversion

src/skeleton/dragtreeview.cpp, src/skeleton/editview.cpp, src/skeleton/toolbar.cpp, src/skeleton/window.cpp
C++17からinline変数が導入されたことによりクラスのconstepxr staticメンバー変数のout-of-line定義が重複になり廃止予定になったとコンパイラーに指摘されたため取り除きます。
clang-17のレポート
```
src/skeleton/dragtreeview.cpp:35:37: warning: out-of-line definition of constexpr static data member is redundant in C++17 and is deprecated [-Wdeprecated-redundant-constexpr-static-def]
35 | constexpr const char* DragTreeView::s_css_classname;
|                                     ^
src/skeleton/editview.cpp:783:33: warning: out-of-line definition of constexpr static data member is redundant in C++17 and is deprecated [-Wdeprecated-redundant-constexpr-static-def]
783 | constexpr const char* EditView::s_css_classname;
|                                 ^
src/skeleton/toolbar.cpp:33:32: warning: out-of-line definition of constexpr static data member is redundant in C++17 …
```
=> Fix compiler warning for -Wdeprecated-redundant-constexpr-static-def

src/aamanager.cpp, src/article/articleadmin.cpp, src/bbslist/bbslistadmin.cpp, src/board/boardadmin.cpp, src/compmanager.cpp, src/config/globalconf.cpp, src/core.cpp, src/cssmanager.cpp, src/dbimg/imginterface.cpp, src/dbtree/interface.cpp, src/dispatchmanager.cpp, src/dndmanager.cpp, src/history/historymanager.cpp, src/icons/iconmanager.cpp, src/image/imageadmin.cpp, src/linkfiltermanager.cpp, src/login2ch.cpp, src/loginbe.cpp, src/main.cpp, src/message/logmanager.cpp, src/message/messageadmin.cpp, src/searchmanager.cpp, src/sound/soundmanager.cpp, src/updatemanager.cpp, src/urlreplacemanager.cpp, src/usrcmdmanager.cpp
静的でないグローバル変数に変数宣言がないとコンパイラーに指摘されたため静的変数に変更してコンパイラー警告を修正します。
```
src/aamanager.cpp:17:18: warning: no previous extern declaration for non-static variable 'instance_aamanager' [-Wmissing-variable-declarations]
src/article/articleadmin.cpp:36:24: warning: no previous extern declaration for non-static variable 'instance_articleadmin' [-Wmissing-variable-declarations]
src/bbslist/bbslistadmin.cpp:21:24: warning: no previous extern declaration for non-static variable 'instance_undo_buffer_favorite' [-Wmissing-variable-declarations]
src/bbslist/bbslistadmin.cpp:41:24: warning: no previous extern declaration for non-static variable 'instance_bbslistadmin' [-Wmissing-variable-declarations]
src/board/boardadmin.cpp:33:20: warning: no previous extern declaration for …
```
=> Fix compiler warnings for -Wmissing-variable-declarations part1

src/article/caret.h
ユーザー定義のデストラクタを持つクラスはコピーコンストラクタを暗黙的に生成するのは非推奨とコンパイラーに指摘されたため修正します。
メンバー変数は[基本型(fundamental types)][1]のみのでリソース管理を行わないのでコンストラクタ、デストラクタを削除して暗黙の生成に変更します。
[1]: https://en.cppreference.com/w/cpp/language/types
```
src/article/caret.h:22:9: warning: definition of implicit copy assignment operator for 'CARET_POSITION' is deprecated because it has a user-declared destructor [-Wdeprecated-copy-with-dtor]
22 |         ~CARET_POSITION() noexcept = default;
|         ^
```
=> Fix compiler warning for -Wdeprecated-copy-with-dtor

src/article/articleviewbase.cpp, src/jdlib/jdsocket.cpp
switch文で明示的に処理されていない列挙型の値があるとコンパイラーに指摘されたため追加します。
```
src/jdlib/jdsocket.cpp:252:13: warning: enumeration values 'none' and 'http' not explicitly handled in switch [-Wswitch-enum]
252 |     switch( protocol ) {
|             ^~~~~~~~
src/article/articleviewbase.cpp:2417:21: warning: enumeration value 'unknown' not explicitly handled in switch [-Wswitch-enum]
2417 |             switch( enc )
|                     ^~~
```
=> Fix compiler warnings for -Wswitch-enum

src/main.cpp
noreturn属性をつけることができる関数があるとコンパイラーに指摘されたため修正します。
```
src/main.cpp:47:1: warning: function 'sig_handler' could be declared with attribute 'noreturn' [-Wmissing-noreturn]
47 | {
| ^
```
=> Fix compiler waning for -Wmissing-noreturn

src/history/historymenu.h, src/history/historysubmenu.h, src/jdlib/imgloader.h, src/message/toolbar.h, src/skeleton/dragnote.h, src/skeleton/editcolumns.h, src/skeleton/jdtoolbar.h, src/skeleton/msgdiag.h, src/skeleton/prefdiag.h, src/skeleton/tabswitchbutton.h, src/skeleton/toolbar.h, src/skeleton/toolbarnote.h, src/skeleton/vbox.h, src/skeleton/view.h, src/skeleton/viewnote.h, src/xml/document.h
オーバーライドしたデストラクタにoverrideキーワードが付いていないと
コンパイラーに指摘されたため修正します。
```
src/history/historymenu.h:24:9: warning: '~HistoryMenu' overrides a destructor but is not marked 'override' [-Wsuggest-destructor-override]
src/history/historysubmenu.h:29:9: warning: '~HistorySubMenu' overrides a destructor but is not marked 'override' [-Wsuggest-destructor-override]
src/jdlib/imgloader.h:42:17: warning: '~ImgLoader' overrides a destructor but is not marked 'override' [-Wsuggest-destructor-override]
src/message/toolbar.h:24:9: warning: '~MessageToolBarBase' overrides a destructor but is not marked 'override' [-Wsuggest-destructor-override]
src/message/toolbar.h:55:9: warning: '~MessageToolBar' overrides a destructor but is not marked 'override' …
```
=> Fix compiler warnings for -Wsuggest-destructor-override part1

src/dbtree/root.h, test/gtest_dbtree_root.cpp, test/meson.build
引数のURLドメインが2ch.net, 5ch.net, bbspink.comの掲示板であるかチェックする関数のテストを追加します。
関数はRootクラスのprivateメンバーですがテストのためpublicに変更します。
`is_2ch()`は静的メンバー関数(static)として定義されています。
引数のURLドメインがしたらば掲示板であるかチェックする関数のテストを追加します。
関数はRootクラスのprivateメンバーですがテストのためpublicに変更します。
`is_JBBS()`は静的メンバー関数(static)として定義されています。
引数のURLドメインがまちBBSの掲示板であるかチェックする関数のテストを追加します。
関数はRootクラスのprivateメンバーですがテストのためpublicに変更します。
`is_machi()`は静的メンバー関数(static)として定義されています。
引数のURLドメインがVIPサービスの掲示板であるかチェックする関数のテストを追加します。
関数はRootクラスのprivateメンバーですがテストのためpublicに変更します。
`is_vip2ch()`は静的メンバー関数(static)として定義されてます。
引数のURLスキーマがfile:スキームであるかチェックする関数のテストを追加します。
関数はRootクラスのprivateメンバーですがテストのためpublicに変更します。
`is_local()`は静的メンバー関数(static)として定義されています。
=> Root: Add test cases for is_xxx()

test/gtest_jdlib_miscutil.cpp
引数のURLからホスト名を取得する関数のテストを追加します。
=> Add test cases for MISC::get_hostname()

src/jdlib/miscutil.cpp, src/jdlib/miscutil.h
引数のURLからホスト名を取得する関数の引数型を`std::string`から`std::string_view`に変更します。
修正前は`std::string_view`を使いたい処理の中で`get_hostname()`を呼び出す部分があると一時的な`std::string`を作る必要があったため`std::string_view`が利用にしくい問題がありました。
=> Change function argument type for MISC::get_hostname()

src/dbtree/boardfactory.cpp, src/dbtree/root.cpp, src/dbtree/root.h, src/type.h, test/gtest_dbtree_root.cpp
掲示板のURLのうち板を表す部分が5ch.netと共通するおーぷん２ちゃんねる(open2ch.net)は掲示板の種類を別のタイプに分けて板移転の対象にならないようにします。
合わせて、引数のURLドメインがおーぷん２ちゃんねるの掲示板であるかチェックする関数のテストを追加します。
`is_open2ch()`は静的メンバー関数(static)として定義されてます。
掲示板のURLのうち板を表す部分が5ch.netと共通するNext2ch(next2ch.net)は掲示板の種類を別のタイプに分けて板移転の対象にならないようにします。
合わせて、引数のURLドメインがNext2chの掲示板であるかチェックする関数のテストを追加します。
`is_next2ch()`は静的メンバー関数(static)として定義されてます。
掲示板のURLのうち板を表す部分が5ch.netと共通する2ちゃんねる(2ch.sc)は掲示板の種類を別のタイプに分けて板移転の対象にならないようにします。
合わせて、引数のURLドメインがの2ちゃんねる(2ch.sc)掲示板であるかチェックする関数のテストを追加します。
`is_2chsc()`は静的メンバー関数(static)として定義されてます。
=> Root: Add board types for open2ch.net and next2ch.net and 2ch.sc

.github/workflows/weekly.yml, src/config/globalconf.h
migemoとUnity buildを組み合わせてビルドするとコンパイルエラーになる場合があったためヘッダーファイルに#includeを追加して修正します。
ninjaのエラーログ
```
In file included from src/jdim.p/jdim-unity0.cpp:42:
/home/(snip)/errdir/../src/winmain.cpp:89:29: error: ‘get_migemodict_path’ is not a member of ‘CONFIG’
89 |     jdmigemo::init( CONFIG::get_migemodict_path() );
|                             ^~~~~~~~~~~~~~~~~~~
In file included from test/gtest_jdim.p/gtest_jdim-unity0.cpp:42:
/home/(snip)/errdir/../src/winmain.cpp:89:29: error: ‘get_migemodict_path’ is not a member of ‘CONFIG’
89 |     jdmigemo::init( CONFIG::get_migemodict_path() );
|                             ^~~~~~~~~~~~~~~~~~~
```
`CONFIG::get_migemodict_path()`は src/config/globalconf.h の中で`HAVE_MIGEMO_H`マクロが定義されているときに宣言されます。
`HAVE_MIGEMO_H`マクロは config.h で定義されますが globalconf.h はconfig.h …
=> config: Add include "config.h" to src/config/globalconf.h

src/article/drawareabase.h, src/bbslist/addetcdialog.h, src/bbslist/editlistwin.h, src/board/columns.h, src/replacestrpref.h, src/setupwizard.h, src/skeleton/aboutdiag.h, src/skeleton/compentry.h, src/skeleton/editview.h, src/skeleton/filediag.h, src/skeleton/imgtoolbutton.h, src/skeleton/label_entry.h, src/skeleton/login.h, src/skeleton/notebook.h, src/skeleton/popupwin.h, src/skeleton/tabnote.cpp, src/skeleton/tabswitchmenu.h, src/skeleton/toolmenubutton.h
オーバーライドしたデストラクタにoverrideキーワードが付いていないとコンパイラーに指摘されたため修正します。
```
src/article/drawareabase.h:278:9: warning: '~DrawAreaBase' overrides a destructor but is not marked 'override' [-Wsuggest-destructor-override]
src/bbslist/addetcdialog.h:27:9: warning: '~AddEtcDialog' overrides a destructor but is not marked 'override' [-Wsuggest-destructor-override]
src/bbslist/editlistwin.h:29:9: warning: '~EditListWin' overrides a destructor but is not marked 'override' [-Wsuggest-destructor-override]
src/board/columns.h:69:9: warning: '~TreeColumns' overrides a destructor but is not marked 'override' [-Wsuggest-destructor-override]
src/replacestrpref.h:114:9: warning: '~ReplaceStrPref' overrides a destructor but is not marked 'override' …
```
=> Fix compiler warnings for -Wsuggest-destructor-override part2

.github/workflows/weekly.yml
GitHub Actions にstep構文の間違いがあると指摘されたため修正します。
```
Annotations
1 error
Error: .github#L1
every step must define a `uses` or `run` key
```
https://github.com/JDimproved/JDim/actions/runs/7232497358
=> Fix GitHub Actions workflows weeky CI

docs/index.md, docs/manual/external.md, src/bbslist/addetcdialog.cpp, src/bbslist/addetcdialog.h, src/bbslist/bbslistview.cpp, src/bbslist/bbslistviewbase.cpp, src/bbslist/bbslistviewbase.h, src/cache.cpp, src/cache.h, src/dbtree/bbsmenu.cpp, src/dbtree/bbsmenu.h, src/dbtree/interface.cpp, src/dbtree/interface.h, src/dbtree/meson.build, src/dbtree/root.cpp, src/dbtree/root.h, src/global.h, src/icons/iconfiles.h, src/icons/iconid.h, src/icons/iconmanager.cpp, src/type.h, src/xml/dom.h, src/xml/tools.cpp, test/gtest_xml_dom.cpp
外部BBSMENUのディレクトリと設定ファイルのファイルパスを表す文字列を返す関数を実装します。
`Dom`オブジェクトが持つchildノードのうち`pred(child)`がtrueを返すものをすべて削除するメンバー関数を実装します。
`remove_if()`はchild自体もdeleteして開放します。また、削除したchildの数を返します。
* Add test case for `XML::Dom::remove_if()`
BBSMENUの取得と板一覧のデータを構築するクラスを実装します。
`DBTREE::Root`クラスを元にして実装した関数があるため src/dbtree/bbsmenu.cpp のライセンスは GPL-2.0-only になります。
メンバー関数のうち`BBSMenu::path_bbsmenu_boards_xml()`は新規に書かれたコードなので抽出して GPL-2.0-or-later でライセンスすることが可能です。
`Root`クラスに外部BBSMENUを取り扱うためのメンバーとメンバー関数を実装します。
外部BBSMENUの登録条件はURLの重複を許可しませんがBBSMENU名は重複できます。
`Root`クラスに実装された外部BBSMENUの機能にアクセスするインターフェース関数を実装します。
外部BBSMENUを追加/編集するダイアログボックスを実装します。
`AddEtcBBSMenuDialog`クラスは新規に書かれたコードなので抽出して GPL-2.0-or-later でライセンスすることが可能です。
外部BBSMENUを追加するためのGUIを実装します。
- 板一覧の一番上に「外部BBSMENU」サブディレクトリを追加します。
- …
=> Implement external BBSMENU

docs/manual/2023.md, meson.build, src/jdversion.h
=> Bump version to 0.11.0-beta

src/dbtree/bbsmenu.h
親クラス Loadable のmove constructorは暗黙的に削除されているため
子クラス BBSMenu のmove constructorに対してclangが警告を出しました。
BBSMenu のコピーやムーブは今のところ行っていないためmove constructorをdeleteに変更して修正します。
clang-16のレポート
```
In file included from ../src/bbslist/bbslistview.cpp:11:
../src/dbtree/bbsmenu.h:63:5: error: explicitly defaulted move constructor is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
BBSMenu( BBSMenu&& ) noexcept(kSupportNoexceptDefaultCtor)= default;
^
../src/dbtree/bbsmenu.h:35:17: note: move constructor of 'BBSMenu' is implicitly deleted because base class 'SKELETON::Loadable' has a deleted move constructor
class BBSMenu : public SKELETON::Loadable
^
../src/skeleton/loadable.h:71:40: note: copy constructor of 'Loadable' is implicitly deleted because field 'm_loader' has a deleted copy constructor …
```
=> BBSMenu: Fix compiler warning for -Wdefaulted-function-deleted

src/jdlib/jdiconv.cpp
iconvを初期化する処理でエラーを正しく判定していなかった不具合を修正します。
errnoの値をチェックする前に値を0にリセットしていたためエラーの検知ができなくなっていました。
FreeBSD のiconvはエンコーディング EUCJP-MS をサポートしていない
場合があるようです。JDimでは EUCJP-MS が使えないとき EUCJP に
フォールバックして処理を続行しますが上記の不具合によって
機能していませんでした。
https://mao.5ch.net/test/read.cgi/linux/1640504277/328-333n
=> Iconv: Fix incorrect reset for errno value

src/bbslist/addetcdialog.h
オーバーライドしたデストラクタにoverrideキーワードが付いていないとコンパイラーに指摘されたため修正します。
```
src/bbslist/addetcdialog.h:54:9: warning: '~AddEtcBBSMenuDialog' overrides a destructor but is not marked 'override' [-Wsuggest-destructor-override]
54 |         ~AddEtcBBSMenuDialog() noexcept = default;
|         ^
```
関連のpull request: #1305
=> Fix compiler warning for -Wsuggest-destructor-override part3

.github/pull_request_template.md
ファイル作成したときにライセンス表示が抜けていたため FSFAP を追記します。
関連のpull request: #1299
=> Add license to pull_request_template.md

src/dbtree/root.cpp
BBSMENUのデータが無い場合は空データをbbsmenu.txtに保存しますが意図しないエラーメッセージが表示されるため修正して抑制します。
修正前も抑制のロジックを導入していましたが別のローカル変数と取り違えていました。
ローカル変数の名前が冗長で紛らわしいため短く変更します。
また、if文の初期化(if statement with initializer)を利用して変数のスコープを限定します。
関連のpull request: #1307
=> Root: Suppress error message for saving empty bbsmenu.txt

src/dbtree/root.cpp, src/dbtree/root.h
メンバー関数の中で呼び出しているテンプレート関数はインスタンス化が必要だが利用可能な定義がないとclangに警告されたためメンバー関数をclass定義の外に移動します。
clang 17のレポート
```
../src/dbtree/root.h:186:36: warning: instantiation of function 'DBTREE::Root::slot_analyze_board_xml<DBTREE::Root>' required here, but no definition is available [-Wundefined-func-template]
186 |         void analyze_board_xml() { slot_analyze_board_xml( *this ); }
|                                    ^
../src/dbtree/root.h:175:14: note: forward declaration of template entity is here
175 |         void slot_analyze_board_xml( T& bbsmenu );
|              ^
../src/dbtree/root.h:186:36: note: add an explicit instantiation declaration to suppress this warning if 'DBTREE::Root::slot_analyze_board_xml<DBTREE::Root>' is explicitly instantiated in another translation unit
186 |         void …
```
=> Root: Move analyze_board_xml() definition to cpp file

src/article/preference.cpp, src/cache.cpp, src/cssmanager.cpp, src/cssmanager.h, src/dbtree/nodetreebase.cpp, src/jdlib/jdiconv.cpp, src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, src/session.cpp, src/viewfactory.cpp, src/viewfactory.h
ローカル変数のポインターにconstを付けられるとcppcheckに指摘されたため修正します。
cppcheck 2.13のレポート
```
src/cache.cpp:1122:20: style: Variable 'direntry' can be declared as pointer to const [constVariablePointer]
struct dirent *direntry;
^
src/jdlib/jdiconv.cpp:138:11: style: Variable 'buf_out_end' can be declared as pointer to const [constVariablePointer]
char* buf_out_end = out_buf.data() + out_buf.size();
^
src/session.cpp:1156:31: style: Variable 'base_view' can be declared as pointer to const [constVariablePointer]
ARTICLE::ArticleViewBase* base_view = nullptr;
^
src/dbtree/nodetreebase.cpp:3704:31: style: Variable 'tmphead' can be declared as pointer to const [constVariablePointer]
NODE* tmphead = res_header( anc_from++ );
^
src/dbtree/nodetreebase.cpp:3785:27: style: Variable 'tmphead' can be declared as pointer …
```
=> Fix codes that are reported by cppcheck 2.13.0

src/bbslist/addetcdialog.cpp
外部BBSMENUを登録・編集するダイアログの項目ラベルを調整してカンマ(:)を追加します。
JDimにある既存の設定や他のアプリケーションにある設定を調べたところカンマを付けているものが多くありました。
関連のpull request: #1307
=> Tweak config label for external BBSMENU dialog

src/message/messageviewbase.cpp
書き込みログをファイルに保存する前にスレタイに含まれる文字参照をデコードするように修正します。
修正前はスレタイに含まれている文字参照のアンパサンド(&)が二重にエスケープされて保存される状態だったのでログを見たとき文字参照の状態で表示される問題がありました。
これまでに保存されたログは文字参照のまま変わらず表示されるため過去のログを直すにはログファイル(log/postlog)を手動で編集する必要があります。
Closes #1319
=> Decode character reference in thread subject to fix postlog saving

src/bbslist/addetcdialog.cpp
外部BBSMENUを登録・編集するダイアログの項目ラベルに誤りがあったため訂正します。
関連のpull request: #1307
=> Tweak config label for external BBSMENU dialog part2

src/control/mousekeypref.cpp
名前空間CONTROLの中にある変数をシャドーイングしているとコンパイラーに指摘されたため変数名を変更します。
```
src/control/mousekeypref.cpp:84:21: warning: declaration shadows a variable in namespace 'CONTROL' [-Wshadow]
84 |         std::string control_label;
|                     ^
src/control/mousekeypref.cpp:133:21: warning: declaration shadows a variable in namespace 'CONTROL' [-Wshadow]
133 |         std::string control_label;
|                     ^
```
=> Fix compiler warnings for -Wshadow

test/gtest_xml_dom.cpp
ラムダ式の引数がローカル変数の名前をシャドーイングしているとコンパイラーに指摘されたため修正します。
```
test/gtest_xml_dom.cpp:253:29: warning: declaration shadows a local variable [-Wshadow-uncaptured-local]
253 |         []( const XML::Dom* child ) { return child->getAttribute( "pet" ) == "dog"; } );
|                             ^
```
=> Fix compiler warning for -Wshadow-uncaptured-local

src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, src/main.cpp
Doxygenのコメントに誤りがあるとコンパイラーに指摘されたため修正します。
```
src/jdlib/miscutil.cpp:1071:26: warning: HTML tag 'span' requires an end tag [-Wdocumentation-html]
1071 |  * @details `<mark>`と`<span>`タグの色を設定して文字参照をデコードして返す。
|                        ~^~~~~
src/jdlib/miscutil.h:105:42: warning: unknown command tag name [-Wdocumentation-unknown-command]
105 |     /// str に含まれる改行文字(`\r\n`)を replace に置き換え
|                                 ^~
src/main.cpp:479:15: warning: parameter 'hint' not found in the function declaration [-Wdocumentation]
479 |  * @param[in] hint  未使用
|               ^~~~
```
=> Fix compiler warnings for -Wdocumentation and related warnings

src/bbslist/addetcdialog.cpp, src/bbslist/addetcdialog.h
外部板追加/編集ダイアログにある項目名と入力欄をグリッドレイアウトに変更してレイアウト調整します。
=> BBSLIST::AddEtcDialog: Use Gtk::Grid to adjust UI layout

src/article/preference.cpp, src/article/preference.h
スレのプロパティにある一般タブをグリッドレイアウトに変更してレイアウト調整します。
=> ARTICLE::Preferences: Use Gtk::Grid to adjust UI layout

src/linkfilterpref.cpp
moveしたあとの変数にアクセスしているとcppcheckに指摘されたため修正します。
cppcheck 2.13.0のレポート (with inconclusive option)
```
src/linkfilterpref.cpp:218:26: warning: inconclusive: Access of moved variable 'item'. [accessMoved]
std::cout << item.url << " " << item.cmd << std::endl;
^
src/linkfilterpref.cpp:216:34: note: Calling std::move(item)
list_item.push_back( std::move( item ) );
^
src/linkfilterpref.cpp:218:26: note: Access of moved variable 'item'.
std::cout << item.url << " " << item.cmd << std::endl;
^
```
=> Fix code that accesses the moved variable

src/article/articleviewbase.h, src/article/drawareabase.h, src/bbslist/addetcdialog.h, src/config/globalconf.cpp, src/control/mouseconfig.cpp, src/dbtree/article2chcompati.cpp, src/dbtree/articlejbbs.cpp, src/dbtree/articlemachi.cpp, src/dbtree/frontloader.cpp, src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h, src/dbtree/root.cpp, src/dbtree/ruleloader.cpp, src/dbtree/settingloader.cpp, src/jdlib/jdsocket.h, src/jdlib/misccharcode.cpp, src/jdlib/miscgtk.cpp, src/jdlib/miscgtk.h, src/session.cpp, src/session.h, src/skeleton/dragnote.cpp, src/skeleton/dragnote.h, src/xml/dom.h
関数の宣言と定義で仮引数の名前が異なっているとcppcheckに指摘されたため名前を整理して揃えます。
cppcheck 2.13.0のレポート (with inconclusive option)
```
src/article/articleviewbase.cpp:2014:60: style: inconclusive: Function 'slot_leave_notify' argument 1 names different: declaration 'ev' definition 'event'. [funcArgNamesDifferent]
src/bbslist/addetcdialog.cpp:15:114: style: inconclusive: Function 'AddEtcDialog' argument 4 names different: declaration '_id' definition 'id'. [funcArgNamesDifferent]
src/bbslist/addetcdialog.cpp:15:137: style: inconclusive: Function 'AddEtcDialog' argument 5 names different: declaration '_passwd' definition 'passwd'. [funcArgNamesDifferent]
src/bbslist/addetcdialog.cpp:15:89: style: inconclusive: Function 'AddEtcDialog' argument 3 names different: declaration '_name' definition 'name'. …
```
=> Organize function parameter names part1,2,3

.github/workflows/ccpp.yml, .github/workflows/weekly.yml
Node.js 16 を使う actions が非推奨になったと警告が表示されたため [actions/checkout@v4][ac4] に移行します。
ジョブのログ
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3.
For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
[ac4]: https://github.com/actions/checkout/tree/v4
=> Migrate GitHub workflow actions/checkout to v4

src/dbtree/nodetree2chcompati.cpp, src/dbtree/nodetree2chcompati.h
2ch互換板のdat落ちしたスレにアクセスしたとき別のURLへ移転通知されたときはURLリダイレクトの処理を行うように変更します。
この修正によりリダイレクトをサポートする掲示板では過去ログを読み込むようになります。
Closes #1334
=> NodeTree2chCompati: Handle URL redirect to support reading kako log

src/image/preference.cpp, src/image/preference.h
画像のプロパティにある項目の名称と値をグリッドレイアウトに変更してレイアウト調整します。
=> IMAGE::Preferences: Use Gtk::Grid to adjust UI layout

src/passwdpref.h
パスワード設定の2chタブにある項目の名称と値をグリッドレイアウトに変更してレイアウト調整します。
パスワード設定のBEタブにある項目の名称と値をグリッドレイアウトに変更してレイアウト調整します。
=> passwdpref: Use Gtk::Grid to adjust UI layout

src/dbtree/nodetreemachi.cpp
まちBBSでofflaw.cgiを使ってdatを読み込むとき"あぼーん"されたレスであるかチェックする処理を追加します。
あぼーんされたレスはレス番号以外のデータが定形のワードに置換されているため、日付とIDのセクションに"ID:"が含まれていない場合はあぼーんされたレスと判定します。
ウェブアーカイブに保存されている[offlaw.cgiの仕様][1]では2008-03-15の時点でログフォーマットにIDが含まれています。
[1]: http://web.archive.org/web/20100923093314/http://machi.to/offlaw.txt
=> NodeTreeMachi: Add abone check on offlaw.cgi mode

src/bbslist/selectdialog.cpp, src/bbslist/selectdialog.h
お気に入り追加先選択のダイアログにある項目の名称と入力欄をグリッドレイアウトに変更して要素を整列します。
=> BBSLIST::SelectListDialog: Use Gtk::Grid to adjust UI layout

src/livepref.cpp, src/livepref.h
実況設定のダイアログにある項目の名称と入力欄をグリッドレイアウトに変更して要素を整列します。
=> CORE::LivePref: Use Gtk::Grid to adjust UI layout

src/bbslist/selectdialog.cpp, src/bbslist/selectdialog.h
お気に入り追加先選択のダイアログで名前の値を取得する処理が項目のラベル("名前:")を取得していたため修正します。
バグが入ったコミット: 9974da79dd6e553613bde9fe1e91ffe1d48ab165
=> BBSLIST::SelectListDialog: Fix getting name value

src/image/preference.cpp
画像のプロパティの値が長いときはウインドウに収まらない末尾の部分を省略記号(…)に置き換えます。
修正前はテキストの長さに合わせてウインドウの最小サイズが水平方向に大きくなっていました。
バグが入ったコミット: 388d7bdc726f9f5bf970936cf8b11b7647c58131
=> IMAGE::Preferences: Set ellipsis sign to end of the property value

src/dbimg/img.cpp
スレビューの右クリックメニューにある"選択範囲の画像を開く"コマンドを使うと2つ目以降の画像は参照元スレ名と参照元レスがつかない不具合を修正します。
Closes #1347
=> Img: Fix disappears referrer name and response on downloading

src/board/preference.cpp, src/board/preference.h
板のプロパティのダイアログにある一般タブをグリッドレイアウトに変更して要素を整列します。
設定項目のラベルと入力欄や値の組が並んでいるUIがありますがレイアウトが揃っておらず視認性があまり良くありません。
そのためグリッドレイアウトの導入やラベルのアライメントを設定して項目を整列します。
ラベルのテキストは左揃えにします。 いくつかのアプリケーションを調べてみましたが設定のラベルは左揃えが多く右揃えはKDEのアプリケーションで採用されていました。
=> BOARD::Preferences: Use Gtk::Grid to adjust UI layout

src/control/control.cpp
bool変数をビット演算しているとcppcheckに指摘されたため修正します。
cppcheck 2.13.0のレポート (with inconclusive option)
```
src/control/control.cpp:160:42: style: inconclusive: Boolean expression 'ctrl' is used in bitwise operation. Did you mean '&&'? [bitwiseOnBoolean]
event.state = ( GDK_CONTROL_MASK & ctrl ) | ( GDK_SHIFT_MASK & shift ) | ( GDK_MOD1_MASK & alt );
^
src/control/control.cpp:160:70: style: inconclusive: Boolean expression 'shift' is used in bitwise operation. Did you mean '&&'? [bitwiseOnBoolean]
event.state = ( GDK_CONTROL_MASK & ctrl ) | ( GDK_SHIFT_MASK & shift ) | ( GDK_MOD1_MASK & alt );
^
src/control/control.cpp:160:98: style: inconclusive: Boolean expression 'alt' is used in bitwise operation. Did you mean '&&'? [bitwiseOnBoolean]
event.state = ( GDK_CONTROL_MASK & ctrl ) | ( GDK_SHIFT_MASK & …
```
=> Control: Fix bitwise operations for bool value to ternary operator

src/article/toolbar.cpp, src/config/aboutconfig.cpp, src/config/configitems.cpp, src/config/configitems.h, src/config/defaultconf.h, src/config/globalconf.cpp, src/config/globalconf.h, src/skeleton/toolbar.cpp, src/skeleton/toolbar.h
about:config に「スレビューの検索クエリをタブ間で共有する」設定(はい・いいえ)を追加します。
- 「はい」はスレビューの検索バーの入力状態がタブ間で共有される
- 「いいえ」は検索バーの入力状態はタブ毎に保持される(従来の動作)
デフォルト設定は「いいえ」(従来の動作)にします。
この機能は実験的なサポートとして追加します。
設定や動作は変更または廃止の可能性があります。
スレビューの検索クエリをタブ間で共有する機能を実装します。
需要や必要性が明らかでないためスレビュー以外の検索クエリは従来の通り別個に保持する仕組みを維持します。
Closes #1352
=> Add "Share thread view search query among tabs" to about:config

docs/manual/urlreplace.md, src/urlreplacemanager.cpp
(i.)imgur.com の画像URLに imgur.com のリファラを送信する設定をURL変換のデフォルト設定ファイルに追加します。
2024-02-27 ころからリファラを設定せずに imgur.com にアクセスすると画像データではなくHTMLテキストが送られてきて読み込みに失敗するようになりました。
imgur.com は広く利用されており新規キャッシュでURL変換の設定をするユーザーは少なくないと予想されるためデフォルト設定に追加します。
オンラインマニュアルにあるURL変換の設定例のうち imgur.com の例にリファラを追加し、補足説明を書いておきます。
https://mao.5ch.net/test/read.cgi/linux/1640504277/356
Closes #1353
=> Add imgur.com URL to default setting file for urlreplace.conf

src/article/articleviewbase.h, src/dbtree/articlebase.h, src/dbtree/nodetreebase.h, src/skeleton/admin.h, src/skeleton/edittreeview.h, src/skeleton/loadable.h, src/skeleton/view.h
メンバー関数定義の後ろに余分なセミコロンが付いているとclangに指摘されたため取り除きます。
```
src/article/articleviewbase.h:163:96: warning: extra ';' after member function definition [-Wextra-semi]
src/article/articleviewbase.h:164:108: warning: extra ';' after member function definition [-Wextra-semi]
src/dbtree/articlebase.h:281:72: warning: extra ';' after member function definition [-Wextra-semi]
src/dbtree/nodetreebase.h:314:62: warning: extra ';' after member function definition [-Wextra-semi]
src/skeleton/admin.h:194:76: warning: extra ';' after member function definition [-Wextra-semi]
src/skeleton/admin.h:249:84: warning: extra ';' after member function definition [-Wextra-semi]
src/skeleton/edittreeview.h:98:54: warning: extra ';' after member function definition [-Wextra-semi] …
```
=> Fix compiler warnings for -Wextra-semi

docs/manual/urlreplace.md
括弧の後ろに日本語に句点(IDEOGRAPHIC FULL STOP)が付いていたので取り除きます。
関連のpull request: #1355
=> manual: Get rid of japanese full stop after parentheses

src/article/layouttree.cpp, src/article/layouttree.h, src/config/configitems.cpp, src/config/configitems.h, src/config/defaultconf.h, src/config/globalconf.cpp, src/config/globalconf.h, src/core.cpp, src/core.h, src/dbtree/articlebase.cpp, src/dbtree/articlebase.h, src/dbtree/node.h, src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h, src/menuslots.cpp, test/gtest_dbtree_nodetreebase.cpp
あぼ〜んした判定理由を表す`Abone`列挙型と`Abone`変数から理由のテキストを取得する関数を実装します。
現状の実装では連続投稿したIDをスレのNG IDに追加する処理は判定できないため除外しています。
あぼーんしたレスに判定理由を表示する状態かどうか表す設定を実装します。
デフォルト設定は判定理由を表示しない(既存の動作)です。
あぼーんしたレスの判定理由を表示する処理を実装します。
連続投稿したIDをスレのNG IDに追加する処理はスレのNG IDリストを利用してあぼーんにするため連続投稿ではなくスレのNG IDと判定されます。
あぼーんしたレスの判定理由の表示・非表示を切り替えるチェックメニューをメニュバーの`設定(C)`＞`あぼ〜ん(A)`の中に追加します。
この機能は実験的なサポートとして追加します。
設定や動作は変更または廃止の可能性があります。
Closes #1357
=> Implement option to display reasons for abone posts

src/config/aboutconfig.cpp, src/config/aboutconfig.h
about:config に検索ボックスを開閉するトグルボタンを追加します。
また、検索ボックスを開くキーボードショートカットキー(Ctrl+F)も実装します。
検索ボックスに入力したキーワードで設定項目のフィルタリングを行います。
設定項目のラベルにキーワードが含まれていればその項目を表示します。
検索ボックスを閉じたりキーワードが空欄のときはフィルタリングが解除されます。
検索はキーワードの前後にある空白を取り除いて単純な比較で実行するため正規表現や大文字小文字の無視、migemoを使ってローマ字から日本語の検索などは行いません。
また、キーワードの中に空白が含まれていても全体を1つのキーワードとして検索します。
Closes #1360
=> AboutConfig: Implement search box on about:config to filter rows

src/article/articleview.cpp, src/article/articleviewbase.cpp, src/article/drawareabase.cpp, src/article/layouttree.cpp, src/board/boardviewbase.cpp, src/control/controlutil.cpp, src/control/mousekeyconf.cpp, src/core.cpp, src/dbtree/bbsmenu.cpp, src/dbtree/boardbase.cpp, src/dbtree/root.cpp, src/image/imageview.cpp, src/image/imageviewicon.cpp, src/jdlib/loader.cpp, src/searchloader.cpp, src/skeleton/tablabel.cpp, src/skeleton/treeviewbase.cpp, src/usrcmdpref.cpp
ステートメントの後ろに余分なセミコロンが付いており効果がないとclangに指摘されたため取り除きます。
<details>
<summary>clang-17のレポート (file pathを一部省略)</summary>
```
src/article/articleview.cpp:488:103: warning: empty expression statement has no effect; remove unnecessary ';' to silence this warning [-Wextra-semi-stmt]
src/article/articleview.cpp:672:104: warning: empty expression statement has no effect; remove unnecessary ';' to silence this warning [-Wextra-semi-stmt]
src/article/articleview.cpp:694:80: warning: empty expression statement has no effect; remove unnecessary ';' to silence this warning [-Wextra-semi-stmt]
src/article/articleviewbase.cpp:1042:49: warning: empty expression statement has no effect; remove unnecessary ';' to silence this warning [-Wextra-semi-stmt]
src/article/articleviewbase.cpp:3760:30: warning: empty …
```
=> Fix compiler warnings for -Wextra-semi-stmt part1,2

src/article/drawareabase.cpp, src/skeleton/dragnote.cpp
ローカル変数が初期されていない状態で使用されている可能性があるとclangに指摘されたため変数定義でゼロ初期化します。
```
src/article/drawareabase.cpp:4188:80: warning: variable 'pos' may be uninitialized when used here [-Wconditional-uninitialized]
src/skeleton/dragnote.cpp:530:27: warning: variable 'next_page' may be uninitialized when used here [-Wconditional-uninitialized]
```
=> Fix compiler warnings for -Wconditional-uninitialized

.github/workflows/ccpp.yml
AddressSanitizer を使うCIジョブ ASan-22 のテストでハングアップすることがありました。
ハングアップするとCIの制限時間が過ぎるまで実行が続くためテストのタイムアウトを設定して一定時間で実行を打ち切るようにします。
テストがタイムアウトしたときはジョブをスキップします。
ハングアップを確認したPull request: #1363
googletestのissue: google/googletest 4491
=> CI: Set timeout to ccpp job ASan-22

src/board/preference.cpp, src/board/preference.h, src/dbtree/board2chcompati.cpp, src/dbtree/board2chcompati.h, src/dbtree/boardbase.cpp, src/dbtree/boardbase.h, src/dbtree/interface.cpp, src/dbtree/interface.h, src/dbtree/settingloader.cpp, src/dbtree/settingloader.h, src/message/messageadmin.h, src/message/messageview.cpp, src/message/messageview.h, src/message/messageviewbase.cpp, src/message/messageviewbase.h, src/message/toolbar.cpp, test/gtest_message_messageviewbase.cpp, test/meson.build
板ごとの各種設定を記載しているテキストファイル(SETTING.TXT)の解析を更新してスレタイトルの最大バイト数(BBS\_SUBJECT\_COUNT)を取得します。
板のプロパティに「スレタイトルの最大バイト数」の項目を追加します。
未設定のときは0と表示します。
書き込みビューのbaseクラスに特殊文字で増加する文字数を計算して返す関数を実装します。
書き込み内容に含まれるいくつかの文字(=特殊文字)は変換されて文字数が増えます。
特殊文字       | 変換前 | 変換後   | 増加分の文字数
---            | ---    | ---      | ---
改行           | `'\n'`   | `" <br> "` | 5
引用符         | `'"'`    | `"&quot;"` | 5
不等号(より小) | `'<'`    | `"&lt;"`   | 3
不等号(より大) | `'>'`    | `"&gt;"`   | 3
新しいスレッドを作成する際に、スレタイトルのバイト数をカウントしてメインステータスバーに表示するように更新します。
スレタイトルのバイト数が板設定の最大バイト数を超えたときはメインステータスバーの色が変わります(about:configの設定でon/off可能)。
また、バイト数が超過しているときに投稿ボタンを押すとキャンセルされてダイアログで通知します。
板設定にスレタイトルの最大バイト数が設定されていないときはカウントや表示を行いません。
Closes #1362
=> Update to count bytes of thread subject when creating new thread

.github/workflows/ccpp.yml
This reverts commit a65876f7ede947e62d7b460c1a6c2a2a8642f1d8.
AddressSanitizerを使ったとき`AddressSanitizer:DEADLYSIGNAL`が出力され続けてハングアップする問題はGitHub Actionsのrunner-imagesに報告されています。
この不具合を回避する修正が入ったためCI job ASan-22の応急処置を差し戻します。
https://github.com/actions/runner-images/issues/9491#issuecomment-2010912636
=> Revert "CI: Set timeout to ccpp job ASan-22 (#1365)"

README.md, docs/manual/start.md
Ubuntu 22.04(23.10でも確認)の環境でAddressSanitizerを有効にしてビルドしたプログラムを実行すると`AddressSanitizer:DEADLYSIGNAL`を出力し続けてハングアップすることがあります。
この問題を回避する応急処置をREADME.mdに記載します。
関連のissue: #1363, #1365, #1369
=> Add workaround to README.md for AddressSanitizer:DEADLYSIGNAL hangup

src/article/drawareabase.cpp, src/config/configitems.cpp, src/control/controlutil.cpp, src/dbtree/spchar_decoder.cpp, src/environment.cpp, src/main.cpp, src/session.cpp, src/skeleton/edittreeview.cpp
関数のプロトタイプが宣言されていないとclangに指摘されたためstaticキーワードを追加して定義されたファイル限定で使われることを示します。
```
src/article/drawareabase.cpp:4076:6: warning: no previous prototype for function 'is_separate_char' [-Wmissing-prototypes]
src/config/configitems.cpp:36:13: warning: no previous prototype for function 'get_default_font' [-Wmissing-prototypes]
src/control/controlutil.cpp:793:19: warning: no previous prototype for function 'convert_mouse_motions' [-Wmissing-prototypes]
src/control/controlutil.cpp:804:19: warning: no previous prototype for function 'convert_mouse_motions_reverse' [-Wmissing-prototypes]
src/dbtree/spchar_decoder.cpp:18:6: warning: no previous prototype for function 'check_spchar' [-Wmissing-prototypes]
src/environment.cpp:110:13: warning: no previous prototype for …
```
=> Fix compiler warnings for -Wmissing-prototypes

src/article/drawareabase.cpp, src/image/imageadmin.cpp
longやunsigned longの変数をdoubleに暗黙的に変換している箇所は精度が失う可能性があるとclangに指摘されたため明示的にキャスト`static_cast<double>()`を使いコンパイラに意図した変更であると伝えます。
clang 17のレポート (file pathを一部省略)
```
src/article/drawareabase.cpp:5452:46: warning: implicit conversion from 'gint64' (aka 'long') to 'double' may lose precision [-Wimplicit-int-float-conversion]
5452 |     m_deceleration.elapsed += ( current_time - m_deceleration.last_time ) * kDecelerationRatio;
|                                 ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~   ~
src/image/imageadmin.cpp:850:44: warning: implicit conversion from 'size_type' (aka 'unsigned long') to 'double' may lose precision [-Wimplicit-int-float-conversion]
850 |         double upper =  m_list_view.size() * ICON_SIZE;
|                ~~~~~    ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
```
=> Fix compiler warnings for -Wimplicit-int-float-conversion

src/article/drawareabase.cpp, src/article/drawareabase.h, src/article/layouttree.cpp, src/control/controlutil.cpp, src/dbtree/nodetreebase.cpp, src/jdlib/misccharcode.cpp, src/jdlib/miscutil.cpp
整数型の変数をサイズが小さい整数型へ暗黙的に変換している箇所は精度が失う可能性があるとclangに指摘されたため明示的にキャスト`static_cast<...>()`を使ったり、整数型を変更してコンパイラに意図した変更であると伝えます。
clang 17のレポート (file pathを一部省略)
```
src/article/drawareabase.cpp:2444:33: warning: implicit conversion loses integer precision: 'const int' to 'char' [-Wimplicit-int-conversion]
src/article/drawareabase.cpp:2451:20: warning: implicit conversion loses integer precision: 'const int' to 'char' [-Wimplicit-int-conversion]
src/article/drawareabase.cpp:2460:20: warning: implicit conversion loses integer precision: 'const int' to 'char' [-Wimplicit-int-conversion]
src/article/drawareabase.cpp:2467:16: warning: implicit conversion loses integer precision: 'const int' to 'char' [-Wimplicit-int-conversion]
src/article/drawareabase.cpp:2471:12: warning: implicit conversion loses …
```
=> Fix compiler warnings for -Wimplicit-int-conversion part1

src/jdlib/cookiemanager.cpp, test/gtest_jdlib_cookiemanager.cpp
Cookie管理機能を更新して有効期限が切れたCookieを削除します。
5ch.netでは新しくドングリシステムが導入され、HTTPリクエストに含まれるCookieの識別子が一定期間で変更されるようになりました。
この変更時にCookieの有効期限が切れるため期限が切れたCookieを使ってレスを書き込むとエラーが発生します。
この修正では書き込みエラーを回避するために受信したCookieから有効期限を解析し、期限切れのCookieについては名前と値の組を削除するように変更します。
5ch.net has introduced a new acorn system, whereby the cookie identifier in the HTTP request is changed after a certain period of time.
When this change occurs, the cookie expires, so writing a response using an expired cookie will result in an error.
To avoid writing errors, this fix parses the expiration date from the received cookie and removes the name/value pairs for expired cookies.
=> SimpleCookieManager: Update Cookie management to remove expired Cookies

src/jdlib/misctime.cpp, test/gtest_jdlib_misctime.cpp
5ch.netが送信するHTTP Set-Cookieヘッダーのexpires属性の日付形式に対応するため解析処理を更新します。
5ch.netが送信するHTTP Set-Cookieヘッダーのexpires属性にはIMF-fixdate形式とほぼ同じ形式の日付文字列が設定されていますが、年月日の区切り文字にハイフンマイナス(-)が使われています。
この修正では、`MISC::datetotime()`がこの形式の日付文字列も解析できるようにハイフンマイナスを半角空白に置換する処理を追加しました。
これにより5ch.netのCookieの有効期限を正しく取得できるようになります。
The expires attribute in the HTTP Set-Cookie header sent by 5ch.net contains a date string in a format that is almost the same as IMF-fixdate, but it uses hyphens (-) instead of spaces as the separators between year, month, and day.
This commit adds a temporary replacement of hyphens with spaces to `MISC::datetotime()`, allowing it to parse the date format correctly.
This enables proper retrieval of cookie expiration dates from 5ch.net.
=> Improve date string parsing to handle 5ch.net's date format

src/dbtree/board2ch.cpp
about:configの「2chのクッキーを保存する」を"はい"にしたときに行われる2ch.net(5ch.net)のクッキーを更新する処理を修正します。
`Board2ch::update_hap()`では`Board2chCompati::cookie_for_request()`を使ってクッキーを取得していましたがこの関数は5ch.net以外のサイトにアクセスする際に使うプロキシ設定に依存するため適切なクッキーが取得できない可能性があります。
この修正では、プロキシ設定に依存しない`cookie_by_host()`関数を使うように変更します。
Previously, `Board2ch::update_hap()` method has used `Board2chCompati::cookie_for_request()` to retrieve cookies, but this function might not retrieve the correct cookie to depend proxy settings for accessing sites other than 5ch.net.
This commit changes to use the `cookie_by_host()` function, which does not depend on proxy settings. This ensures that the appropriate cookie is always retrieved.
=> Board2ch::update_hap(): Fix cookie retrieval method

src/aamanager.cpp, src/dbtree/nodetreebase.cpp, src/urlreplacemanager.cpp, test/gtest_jdlib_misccharcode.cpp
整数型の変数をサイズが小さい整数型へ暗黙的に変換している箇所は精度が失う可能性があるとclangに指摘されたため明示的にキャスト`static_cast<...>()`を使ったり、整数型を変更してコンパイラに意図した変更であると伝えます。
clang 17のレポート (file pathを一部省略)
```
src/aamanager.cpp:125:42: warning: implicit conversion loses integer precision: 'int' to 'char' [-Wimplicit-int-conversion]
125 |             if( id <= 9 ) shortcut = '0' + id;
|                                    ~ ~~~~^~~~
src/aamanager.cpp:127:37: warning: implicit conversion loses integer precision: 'int' to 'char' [-Wimplicit-int-conversion]
127 |                 shortcut = 'a' + id - base_a;
|                          ~ ~~~~~~~~~^~~~~~~~
src/aamanager.cpp:132:37: warning: implicit conversion loses integer precision: 'int' to 'char' [-Wimplicit-int-conversion]
132 |                 shortcut = 'A' + id - base_A;
| …
```
=> Fix compiler warnings for -Wimplicit-int-conversion part2

src/browsers.cpp, src/control/controllabel.h, src/control/keysyms.h, src/icons/iconfiles.h, src/jdlib/hkana.h
静的でないグローバル変数に変数宣言がないとclangに指摘されたため配列変数をconstexpr変数に変更してコンパイラー警告を修正します。
```
src/icons/iconfiles.h:15:10: warning: no previous extern declaration for non-static variable 'iconfiles' [-Wmissing-variable-declarations]
15 |     char iconfiles[][ MAX_ICON_FILES ]={
|          ^
src/control/controllabel.h:24:10: warning: no previous extern declaration for non-static variable 'mode_label' [-Wmissing-variable-declarations]
24 |     char mode_label[][ MAX_CONTROL_LABEL ] ={
|          ^
src/control/keysyms.h:23:13: warning: no previous extern declaration for non-static variable 'keysyms' [-Wmissing-variable-declarations]
23 |     KEYSYMS keysyms[] ={
|             ^
src/control/controllabel.h:24:5: note: declare 'static' if the variable is not intended to be used …
```
=> Fix compiler warning for -Wmissing-variable-declarations part2

src/article/articleadmin.cpp, src/bbslist/bbslistviewbase.cpp, src/board/boardadmin.cpp, src/board/boardviewbase.cpp, src/board/boardviewnext.cpp, src/config/configitems.cpp, src/control/control.cpp, src/control/controlutil.cpp, src/dbimg/img.cpp, src/history/viewhistory.cpp, src/image/imageadmin.cpp, src/image/imagearea.cpp, src/image/imageareaicon.cpp, src/image/imageareapopup.cpp, src/jdlib/imgloader.cpp, src/jdlib/jdiconv.cpp, src/jdlib/misctrip.cpp, src/jdlib/miscutil.cpp, src/message/logmanager.cpp, src/message/messageviewbase.cpp, src/skeleton/undobuffer.cpp, src/sound/playsound.cpp
C言語スタイルのキャストを使用しているとclangに指摘されたためC++スタイルのキャスト`static_cast<...>(value)`に変更したりキャストを外したりしてコンパイラー警告を修正します。
```
src/sound/playsound.cpp:171:34: warning: use of old-style cast [-Wold-style-cast]
src/sound/playsound.cpp:217:40: warning: use of old-style cast [-Wold-style-cast]
src/dbimg/img.cpp:638:33: warning: use of old-style cast [-Wold-style-cast]
src/dbimg/img.cpp:694:22: warning: use of old-style cast [-Wold-style-cast]
src/dbimg/img.cpp:695:22: warning: use of old-style cast [-Wold-style-cast]
src/dbimg/img.cpp:698:23: warning: use of old-style cast [-Wold-style-cast]
src/dbimg/img.cpp:699:24: warning: use of old-style cast [-Wold-style-cast]
src/history/viewhistory.cpp:278:48: warning: use of old-style cast [-Wold-style-cast] …
```
=> Fix compiler warnings for -Wold-style-cast part1,2,3

src/aamanager.cpp, src/cssmanager.cpp, src/dbtree/articlebase.cpp, src/dbtree/board2chcompati.cpp, src/dbtree/boardjbbs.cpp, src/dbtree/boardmachi.cpp, src/dbtree/nodetreebase.cpp, src/jdlib/misccharcode.cpp, src/jdlib/tfidf.cpp, src/main.cpp, src/skeleton/dragnote.cpp, src/skeleton/dragtreeview.cpp, src/skeleton/edittreeview.cpp, src/skeleton/menubutton.cpp, src/skeleton/tabnote.cpp, src/skeleton/treeviewbase.cpp, src/usrcmdpref.cpp
C言語スタイルのキャストを使用しているとclangに指摘されたためC++スタイルのキャスト`static_cast<...>(value)`に変更してコンパイラー警告を修正します。
```
src/dbtree/articlebase.cpp:1513:25: warning: use of old-style cast [-Wold-style-cast]
src/dbtree/articlebase.cpp:1523:30: warning: use of old-style cast [-Wold-style-cast]
src/dbtree/articlebase.cpp:721:50: warning: use of old-style cast [-Wold-style-cast]
src/dbtree/board2chcompati.cpp:310:23: warning: use of old-style cast [-Wold-style-cast]
src/dbtree/boardjbbs.cpp:292:23: warning: use of old-style cast [-Wold-style-cast]
src/jdlib/misccharcode.cpp:150:13: warning: use of old-style cast [-Wold-style-cast]
src/jdlib/misccharcode.cpp:157:21: warning: use of old-style cast [-Wold-style-cast]
src/jdlib/misccharcode.cpp:158:21: warning: use of old-style cast …
```
=> Fix compiler warnings for -Wold-style-cast part4,5,6,7,8

src/article/drawareabase.cpp, src/article/preference.cpp, src/cssmanager.cpp, src/history/historysubmenu.cpp, src/history/historysubmenu.h
C言語スタイルのキャストを使用しているとclangに指摘されたためC++スタイルのキャスト`static_cast<...>(value)`に変更してコンパイラー警告を修正します。
```
src/cssmanager.cpp:520:116: warning: use of old-style cast [-Wold-style-cast]
src/cssmanager.cpp:521:124: warning: use of old-style cast [-Wold-style-cast]
src/cssmanager.cpp:522:118: warning: use of old-style cast [-Wold-style-cast]
src/cssmanager.cpp:523:127: warning: use of old-style cast [-Wold-style-cast]
src/cssmanager.cpp:622:48: warning: use of old-style cast [-Wold-style-cast]
src/cssmanager.cpp:623:50: warning: use of old-style cast [-Wold-style-cast]
src/cssmanager.cpp:624:46: warning: use of old-style cast [-Wold-style-cast]
src/cssmanager.cpp:625:52: warning: use of old-style cast [-Wold-style-cast]
src/cssmanager.cpp:639:66: warning: use of old-style …
```
=> Fix compiler warnings for -Wolg-style-cast part9,10,11

src/article/drawareabase.cpp
スレビューでマウスホイールを使ってスクロールしたときに異常終了することがあったため修正します。
修正前は値の範囲を調べる変数を間違えていました。
https://next2ch.net/linux/1654053581/195
Closes #1390
=> DrawAreaBase: Fix crash for mouse wheel scrolling to upper

.github/workflows/ccpp.yml
動作環境の更新でCIでテストするコンパイラーの更新を行っていなかったため更新します。
=> Update CI (gcc >= 9, clang >= 10)

src/config/configitems.cpp, src/config/configitems.h, src/config/defaultconf.h, src/config/globalconf.cpp, src/config/globalconf.h, src/dbimg/img.cpp, src/dbimg/img.h, src/dbimg/imghash.h, src/dbimg/imginterface.cpp, src/dbimg/imginterface.h, src/dbimg/imgroot.cpp, src/dbimg/imgroot.h, src/globalabonepref.h, src/image/imageareabase.cpp, src/image/preference.cpp, src/image/preference.h, src/imagehashtab.h, src/jdlib/miscgtk.cpp, src/jdlib/miscgtk.h
画像のハッシュ値を計算して類似する画像をあぼ〜んする機能を実装します。
NG 画像ハッシュの初期設定のしきい値を記憶する設定と値の取得・設定するインターフェース関数を実装します。
初期設定のデフォルト値は 30 です。
しきい値の取る範囲は 0 が最小(すべてのビットが一致する＝同一画像の判定)、128 が最大(すべてのビットが一致しない)となります。
また、マイナスの値は判定を行わない設定に使用します。
NG 画像ハッシュが有効か否かを表す真偽値(有効・無効)の設定を実装します。
有効にすると、画像のハッシュ値を計算してNG 画像ハッシュとの差がしきい値以下の画像をあぼ〜んします。
また、値の取得・設定するインターフェース関数を実装します。
設定のデフォルト値は無効です。
GdkPixbufの画像データをグレイスケール(白黒)画像に変換する関数を実装します。
画像データクラス(`DBIMG::Img`)に画像のハッシュ値(dHash)を記憶するメンバー変数を追加します。
また、ハッシュ値の取得・設定を行う処理やキャッシュ情報ファイルの保存・読み込みを行う処理を実装します。
画像データベースのルートクラス(`DBIMG::ImgRoot`)にあぼーんした画像のハッシュ値(NG 画像ハッシュ)を記憶するメンバー変数を追加します。
また、以下の処理を実装しインターフェース関数を作成します。
- NG 画像ハッシュのリストを取得する
- 画像データベースにNG 画像ハッシュを登録、更新する
- NG 画像ハッシュの設定ファイルを保存・読み込む
- 画像のハッシュ値がNG 画像ハッシュとマッチするかテストする
- NGのしきい値がマイナスの値ならテストしない
- ハミング距離がしきい値以下のときはあぼーんする
- …
=> Implement base system of the NG image hash

src/article/articleviewbase.cpp, src/bbslist/bbslistviewbase.cpp, src/dbimg/img.cpp, src/dbimg/img.h, src/dbimg/imginterface.cpp, src/dbimg/imginterface.h, src/dbimg/imgroot.cpp, src/history/historysubmenu.cpp
NG 画像ハッシュであぼーんされた画像は判定理由をキャッシュ情報ファイルに記録するように変更します。
また、NG 画像ハッシュであぼーんされた画像のURLをクリックしたときに出るダイアログボックスや、URLをマウスオーバーしたときに出るポップアップにあぼーんされた理由を表示するように変更します。
`NG 画像ハッシュ XXX XXX (しきい値: NNN)<br>(URL) の類似画像です。`
修正前は画像URLをあぼーんしたのか、NG 画像ハッシュであぼーんしたのか判別が付かない状態でした。
NG 画像ハッシュの情報を記録することで画像やスレッドの状態が判断できるようにします。
JDimをビルドするときに`JDIM_DEVTOOLS`マクロを定義すると開発者向けの機能が有効にます。
有効にするとNG 画像ハッシュのあぼーん判定理由を記録するときにハッシュ値を比較した計算結果(相違度)が追加されます。
=> Record abone reason for NG image hash and show it on dialog or popup

src/article/drawareabase.cpp, src/config/aboutconfig.cpp, src/config/configitems.cpp, src/config/configitems.h, src/config/defaultconf.h, src/config/globalconf.cpp, src/config/globalconf.h, src/image/imageareabase.cpp, src/image/imageareaicon.cpp, src/image/imageareaicon.h
about:config に「画像をモザイクで開くときはグレースケール(白黒)で表示する」設定(はい・いいえ)を追加します。
- 「はい」は画像をモザイクで開くときはグレースケール(白黒)で表示する
- 「いいえ」は画像をモザイクで開くときはカラーで表示する(従来の動作)
デフォルト設定は「いいえ」(従来の動作)にします。
この機能は実験的なサポートとして追加します。
設定や動作は変更または廃止の可能性があります。
about:config の「画像をモザイクで開くときはグレースケール(白黒)で表示する」設定が"はい"のときに画像をグレースケール化する処理を実装します。
画像をモザイクで表示するとき元の画像の色彩の印象をそのまま受けます。
白黒で表示すると印象が和らぐかもしれません。
=> Implement grayscale display for mosaic images

src/article/articleviewbase.cpp, src/article/articleviewbase.h, src/bbslist/bbslistviewbase.cpp, src/core.cpp, src/dbimg/img.cpp, src/dbimg/img.h, src/dbimg/imginterface.cpp, src/dbimg/imginterface.h, src/dbimg/imgroot.cpp, src/history/historysubmenu.cpp
あぼーんされた画像URLをクリックしたとき出る「あぼーんされています」のダイアログを修正して一時的にモザイクで表示する選択肢を追加します。
ダイアログの選択肢で「はい」を選択して画像を表示すると、JDimを再起動する、あぼ〜んを解除する、またはモザイクを解除するまでNG 画像ハッシュの適用外となります。
part1はGUIの修正で一時的にモザイクで表示する実処理はpart2で実装します。
画像を表示するとき一時的にモザイクで表示するモードを実装します。
`DBIMG::download_img()`のモザイクで表示するかbool型で指定する引数をint型に変更してモザイク表示のモードを渡せるように変更します。
値  | モザイク表示のモード
--- | ---
0   | モザイク表示しない
1   | モザイク表示する
2   | 強制的にモザイク表示する
強制モザイクモードではJDimを終了する、あぼーんを解除する、またはモザイクを解除するまでNG 画像ハッシュの適用外となります。
=> Implement force mosaic mode for image abone

src/image/preference.cpp
画像のあぼーん理由があるときは画像のプロパティに備考欄を追加して理由を表示します。
=> IMAGE::Preferences: Add note property for abone reason

src/article/font.cpp
条件文の比較はASCIIの範囲`[0, 127]`を想定しているが、char型はCPUアーキテクチャによって符号の有無が変わるので明示的にunsigned char型へ変換して比較します。
また、C言語スタイルのキャストを使用しているとclangに指摘されたためC++スタイルのキャスト`static_cast<...>(value)`に変更してコンパイラー警告を修正します。
```
src/article/font.cpp:108:38: warning: use of old-style cast [-Wold-style-cast]
108 |             const int pre_char_num = ( int ) pre_char;
|                                      ^       ~~~~~~~~
```
=> font: Convert signedness for integer type to compare ASCII character

src/core.cpp, src/core.h, src/global.h, src/loginacorn.cpp, src/loginacorn.h, src/menuslots.cpp, src/meson.build, src/passwdpref.h, src/session.cpp, src/session.h
5ch.netのどんぐりシステムをサポートするためメールアドレスとパスワードで登録した警備員アカウントにログイン、ログアウトする処理と実装します。
また、ログインした後にアカウントの名前やIDを取得する処理を実装してどのアカウントでログインしたのか識別できるようにします。
今回の修正では警備員の登録はサポートしません。
パスワード設定のダイアログに「どんぐり警備員」のタブを実装します。
メールアドレスとパスワードを入力してOKを押してダイアログを閉じ、メニューバーからログインします。
また、ログイン中はアカウントの名前とID、HTTPクッキー(acorn)をタブに表示することでどのアカウントにログインしているのか判別できるようにします。
パスワード設定のダイアログの幅サイズにデフォルトの値を設定します。
修正前はラベルのテキストに合わせてダイアログのサイズが引き伸ばされて表示されていました。
メニューバーに5ch.netどんぐりシステムの警備員アカウントにログインするボタンを実装します。
また、ログインしている状態でJDimを終了したときは次回起動時に自動でログインするように処理を実装します。
ログイン中はメインウィンドウのタイトルバーに`[ どんぐり警備員 ]`と表示します。
この機能は実験的なサポートとして追加します。
設定や動作は変更または廃止の可能性があります。
=> Implement 5ch donguri system guard account login

docs/manual/2024.md, meson.build, src/jdversion.h
関連のissue: https://github.com/JDimproved/JDim/issues/1380
=> Bump version to 0.12.0-beta

src/article/drawareabase.cpp
書き込みログを開いて「前のレスに移動」するショートカットキーを使うと一時的にウインドウが固まる(ハングアップ)不具合を修正します。
また、書き込みログでは「次のレスに移動」する機能が一番下にスクロールする挙動なので「前のレスに移動」の機能を一番上にスクロールするように変更することで上下対称にします。
https://mao.5ch.net/test/read.cgi/linux/1640504277/800-809n
Thanks @mtasaka for reporting the issue.
Closes #1404
=> DrawAreaBase: Fix busy loop issue in go to previouse response command

src/article/drawareabase.cpp
0.12.0-beta20240617 では通常のスレッドの画面一番下の書き込みに移動後ショートカットキー「前のレスに移動」を使うと画面一番上に移動するようになっていたため1つづつ前のレスに移動するように修正します。
https://mao.5ch.net/test/read.cgi/linux/1640504277/827
Closes #1404
=> Fix behavior of 'Go to previous response' shortcut in normal threads

src/core.cpp, src/menuslots.cpp, src/passwdpref.h, src/session.cpp, src/session.h
5ch.netどんぐりシステムのメールアドレス登録した警備員のログインを切り替えるメニューバーの項目は表現が分かりにくいと指摘があったため、Gmailのメールアドレスに登録された警備員アカウントを強調するテキストに変更します。
また、タイトルバーに表示するどんぐりシステムにログイン中であることを示すステータス表示のテキストが長いため、[どんぐりベース][1]の表現[^2]を使うように変更します。
修正にあたり報告をしていただきありがとうございました。
https://mao.5ch.net/test/read.cgi/linux/1640504277/768
[1]: https://donguri.5ch.net/
[^2]: 「警備員」のテキストと黒丸(U+25CF BLACK CIRCLE)の組み合わせ
パスワード設定のタブのラベルは単純に「どんぐりシステム」へ変更します。
また、Gmail限定であることをラベルや入力欄のツールチップに表示します。
ソースコードのコメントを編集してメールアドレスに登録した警備員のログイン処理であると明示します。
また、将来の仕様変更でGmail限定でなくなる場合を考えメールアドレス登録と書きます。
(ソースコードのコメント内容を更新していくのは忘れやすいです)
関連のissue: https://github.com/JDimproved/JDim/issues/1376
=> Tweak labels for 5ch donguri system mail login

src/environment.cpp, src/environment.h, src/imagehashtab.h, src/jdversion.h
`全体あぼ〜ん設定(対象: スレビュー)`ダイアログの`NG 画像ハッシュ`タブにオンラインマニュアルのNG 画像ハッシュの設定についてまとめたページを開くリンクボタンを追加します。
関連のissue: https://github.com/JDimproved/JDim/issues/1388, https://github.com/JDimproved/JDim/pull/1409
=> ImageHashTab: Add online manual link button

meson.build, src/jdversion.h
開発中のバージョンであることを明らかにするためalpha版に更新します。
関連のissue:
https://github.com/JDimproved/JDim/issues/1411
=> Bump version to 0.13.0-alpha

src/dbimg/img.h, src/skeleton/window.h, src/xml/dom.h
クラスメンバー変数の文字列をコピーして返すメンバー関数はconst参照を返すべきとcppcheckに指摘されたため修正します。
cppcheck 2.14.2のレポート
```
src/xml/dom.h:100:21: performance: Function 'nodeName()' should return member 'm_nodeName' by const reference. [returnByReference]
std::string nodeName() const { return m_nodeName; }
^
src/xml/dom.h:101:21: performance: Function 'nodeValue()' should return member 'm_nodeValue' by const reference. [returnByReference]
std::string nodeValue() const { return m_nodeValue; }
^
src/dbimg/img.h:126:21: performance: Function 'get_abone_reason()' should return member 'm_abone_reason' by const reference. [returnByReference]
std::string get_abone_reason() const noexcept { return m_abone_reason; }
^
src/skeleton/window.h:83:21: performance: Function 'get_status()' should return member 'm_status' by const …
```
=> Return class member const reference string instead of string value

src/jdlib/tfidf.cpp
演算子の両側に同じ式が見つかったとcppcheckに指摘されたためチェックしたところ、変数名の誤りが見つかったため修正します。
関数の2つの引数の名前が似ていたため同じ引数に由来する数値で比較していました。
cppcheck 2.14.2のレポート
```
src/jdlib/tfidf.cpp:120:18: style: Finding the same expression on both sides of an operator is suspicious and might indicate a cut and paste or logic error. Please examine this code carefully to determine if it is correct. [knownConditionTrueFalse]
if( ! n || n != vec_tfidf1.size() ) return 0;
^
src/jdlib/tfidf.cpp:114:42: note: 'n' is assigned value 'vec_tfidf1.size()' here.
const std::size_t n = vec_tfidf1.size();
^
src/jdlib/tfidf.cpp:120:18: note: The comparison 'n != vec_tfidf1.size()' is always false because 'n' and 'vec_tfidf1.size()' represent the same value.
if( ! n || n != vec_tfidf1.size() ) return 0;
^
```
=> tfidf: Rename local variable that has been typo

src/article/drawareabase.cpp
C言語スタイルのキャストを使用しているとclangに指摘されたためC++スタイルのキャスト`static_cast<...>(value)`に変更してコンパイラー警告を修正します。
```
src/article/drawareabase.cpp:1574:41: warning: use of old-style cast [-Wold-style-cast]
src/article/drawareabase.cpp:1575:29: warning: use of old-style cast [-Wold-style-cast]
src/article/drawareabase.cpp:1576:29: warning: use of old-style cast [-Wold-style-cast]
src/article/drawareabase.cpp:1577:29: warning: use of old-style cast [-Wold-style-cast]
src/article/drawareabase.cpp:3041:31: warning: use of old-style cast [-Wold-style-cast]
src/article/drawareabase.cpp:3081:35: warning: use of old-style cast [-Wold-style-cast]
src/article/drawareabase.cpp:3092:72: warning: use of old-style cast [-Wold-style-cast]
src/article/drawareabase.cpp:3093:78: warning: use of …
```
=> Fix compiler warnings for -Wold-style-cast part12

docs/manual/operation.md, src/control/controlid.h, src/control/controllabel.h, src/control/controlutil.cpp, src/control/defaultconf.h, src/control/keyconfig.cpp, src/control/keypref.cpp, src/skeleton/admin.cpp
ショートカットキー設定に「最後のタブに移動」機能を追加します。
「最後のタブに移動」を実行すると一番最後(右端)のタブに表示を切り替えます。
デフォルト設定は無しとし、各ユーザーが設定できるようにします。
これは、新規ショートカットキーや既存のショートカットキーの変更は既存のユーザー設定と衝突する可能性があり、混乱を避けるためです。
10個以上タブを開いた際、ショートカットキーで最後(右端)のタブに移動する方法は以下の通りですが手間がかかります。
- (a) 「タブ1に移動」して「左のタブに移動」する
- (b) 「タブ9に移動」して「右のタブに移動」を繰り返す
Google ChromeやFirefoxなどのwebブラウザはショートカットキーAlt+9に「最後のタブに選択(移動)」が割り当てられており、同様の機能があれば便利です。
Closes #1427
=> control: Add shortcut key for "Go To Last Tab"

.github/workflows/weekly.yml
GitHub Actions の Weekly CI を変更して Muon build の互換性の無い変更に対応します。
Weekly CIの動作チェックを行うため手動でworkflowを実行する設定を追加します。
2024-08-13 以降の Muon はビルドに Meson 1.3.0 までの機能が[必要になったため][1]、 Meson のインストールを変更します。
依存関係のインストールから Ubuntu の Meson パッケージを取り除き、Python 3.12 のセットアップを追加して PyPI から Meson 1.3.0 をインストールします。
また、 ninja を使用していたビルドコマンドを、 Muon の muon samu に変更しました。
関連のaction:
https://github.com/JDimproved/JDim/actions/runs/10344214511
[1]: https://github.com/muon-build/muon/commit/3542fc6ff262a05b1b813fcd18abe52e2030d07a
=> Update GitHub Actions Weekly CI to solve Muon breaking changes

.github/workflows/weekly.yml
muon-master の job を実行したとき ninja build が見つからず失敗する設定ミスを修正します。
関連のaction:
https://github.com/JDimproved/JDim/actions/runs/10429894791
=> Fix GitHub Actions workflow Weekly CI

.github/workflows/weekly.yml
gtkmm-3.0 パッケージが見つからない問題を修正します。
https://github.com/JDimproved/JDim/actions/runs/10429968159
=> Fix GitHub Actions workflow Weekly CI part2

.github/workflows/weekly.yml
python3.12 をセットアップしてインストールした meson と ninja を使うと gtkmm-3.0 パッケージの解決に失敗します。
そのため muon の bootstrap.sh を使って muon をビルドしてテストするように変更します。
=> Weely CI: Use bootstrap.sh instead of meson for muon-master job

src/dbimg/img.cpp
imgurの画像にアクセスした際に`https://i.imgur.com/removed.png`へのHTTPリダイレクトが発生した場合、ダウンロードをキャンセルし、HTTP 404 Not Foundとして処理します。
画像共有サービスimgurにアップロードされた画像には、個別のURLが割り当てられます。
投稿者や運営が削除した画像のURLにアクセスすると、削除済みを示す画像へのHTTPリダイレクトが行われます。
削除済みを示す画像はサイズが小さいものの、HTTP通信に時間がかかり不要な画像データがキャッシュに残ってしまうため 404 Not Found にして通信やキャッシュを回避します。
Closes #1433
=> Img: Interrupt download for i.imgur.com/removed.png

src/control/mousekeypref.h
ショートカットキー設定ダイアログの設定一覧で上下の矢印キーを押しても選択項目が切り替わらない不具合を修正します。
マウスジェスチャ設定とマウスボタン設定のダイアログも同じ不具合がありましたので修正します。
修正前は、設定一覧の実装に独自にカスタマイズした`SKELETON::JDTreeViewBase`を使っていました。
このウィジェットは矢印キーなどの入力イベントを上書きしているためシグナルハンドラの接続で処理する必要があります。
しかし、設定ダイアログは`SKELETON::JDTreeViewBase`のカスタマイズ機能を使っていないため必要以上に複雑な実装になっています。
そこで`Gtk::TreeView`に戻して余計な機能を外し、デフォルトの入力イベントを復活させます。
Closes #1435
=> MouseKeyPref: Use Gtk::TreeView instead of SKELETON::JDTreeViewBase

src/skeleton/panecontrol.cpp, src/skeleton/panecontrol.h
メンバー関数の仮引数`event`にconst修飾子をつけることができるとcppcheckに指摘されました。
この`event`は未使用変数なので関数の宣言や定義から取り除いてレポートを抑制します。
同様に他のメンバー関数のうち未使用の`event`を取り除きます。
cppcheck 2.14.2のレポート
```
src/skeleton/panecontrol.cpp:220:56: style: Parameter 'event' can be declared as pointer to const [constParameterPointer]
void PaneControl::motion_notify_event( GdkEventMotion* event )
^
```
=> PaneControl: Get rid of member function unused parameters

src/article/drawareabase.cpp, src/message/messageviewbase.cpp, src/skeleton/dragtreeview.cpp, src/skeleton/dragtreeview.h, src/skeleton/editview.h, src/skeleton/toolbar.h, src/skeleton/window.h
C++20からUTF-8文字列リテラルの型がchar8_tの配列に変更されるとclangに指摘されたためu8プレフィックスを外してコンパイラー警告を抑制します。
JDimのソースコードのエンコーディングはUTF-8なので影響はありません。
clang-18のレポート (file pathを一部省略)
```
src/article/drawareabase.cpp:326:51: warning: type of UTF-8 string literal will change from array of const char to array of const char8_t in C++20 [-Wc++20-compat]
src/article/drawareabase.cpp:327:51: warning: type of UTF-8 string literal will change from array of const char to array of const char8_t in C++20 [-Wc++20-compat]
src/message/messageviewbase.cpp:219:43: warning: type of UTF-8 string literal will change from array of const char to array of const char8_t in C++20 [-Wc++20-compat]
src/message/messageviewbase.cpp:228:17: warning: type of UTF-8 string literal will change from array of const char to array of const char8_t in C++20 …
```
=> Fix compiler warnings for -Wc++20-compat part1

src/control/mousekeypref.cpp, src/control/mousekeypref.h
ショートカットキー設定とマウスジェスチャ設定とマウスボタン設定のダイアログに設定項目をキーワードでフィルタリングする検索ボックスとボックスを開閉するトグルボタンを追加します。
また、検索ボックスを開くキーボードショートカットキー(Ctrl+F)も実装します。
検索ボックスに入力したキーワードで設定項目のフィルタリングを行います。
設定項目のラベルにキーワードが含まれていればその項目を表示します。
検索ボックスを閉じたりキーワードが空欄のときはフィルタリングが解除されます。
検索はキーワードの前後にある空白を取り除いて単純な比較で実行するため正規表現や大文字小文字の無視、migemoを使ってローマ字から日本語の検索
などは行いません。
また、キーワードの中に空白が含まれていても全体を1つのキーワードとして検索します。
Closes #1439
=> MouseKeyPref: Implement search box on MouseKeyPref to filter rows

src/dbtree/nodetreebase.cpp, src/jdlib/miscutil.cpp, test/gtest_jdlib_misctrip.cpp
C++20からUTF-8文字列リテラルの型が`char8_t`の配列に変更されるとclangに指摘されたためu8プレフィックスを外してコンパイラー警告を抑制します。
JDimのソースコードのエンコーディングはUTF-8なので影響はありません。
clang-18のレポート (file pathを一部省略)
```
src/dbtree/nodetreebase.cpp:2407:39: warning: type of UTF-8 string literal will change from array of const char to array of const char8_t in C++20 [-Wc++20-compat]
src/jdlib/miscutil.cpp:119:39: warning: type of UTF-8 string literal will change from array of const char to array of const char8_t in C++20 [-Wc++20-compat]
test/gtest_jdlib_misctrip.cpp:25:35: warning: type of UTF-8 string literal will change from array of const char to array of const char8_t in C++20 [-Wc++20-compat]
test/gtest_jdlib_misctrip.cpp:30:45: warning: type of UTF-8 string literal will change from array of const char to array of const char8_t in C++20 …
```
=> Fix compiler warnings for -Wc++20-compat part2

test/gtest_jdlib_miscutil.cpp
C++20からUTF-8文字列リテラルの型がchar8_tの配列に変更されるとclangに指摘されたためu8プレフィックスを外してコンパイラー警告を抑制します。
JDimのソースコードのエンコーディングはUTF-8なので影響はありません。
clang-18のレポート (file pathを一部省略)
```
test/gtest_jdlib_miscutil.cpp:17:42: warning: type of UTF-8 string literal will change from array of const char to array of const char8_t in C++20 [-Wc++20-compat]
test/gtest_jdlib_miscutil.cpp:23:42: warning: type of UTF-8 string literal will change from array of const char to array of const char8_t in C++20 [-Wc++20-compat]
test/gtest_jdlib_miscutil.cpp:25:22: warning: type of UTF-8 string literal will change from array of const char to array of const char8_t in C++20 [-Wc++20-compat]
test/gtest_jdlib_miscutil.cpp:25:31: warning: type of UTF-8 string literal will change from array of const char to array of const char8_t in C++20 …
```
=> Fix compiler warnings for -Wc++20-compat part3

test/gtest_dbimg_imgroot.cpp, test/meson.build
`ImgRoot::get_type_ext()`の動作は`Urlreplace_Manager`の設定に依存します。
そのため、テストケースで使うURLは予約済みのドメイン .test を使用することでキャッシュや設定の影響を受けないようにします。
関連のissue: #1440
=> Add test cases for DBIMG::ImgRoot::get_type_ext()

src/dbimg/imginterface.cpp, src/dbimg/imginterface.h, src/dbimg/imgroot.cpp, src/dbimg/imgroot.h
`get_type_ext()` 関数の `const char*` と `int` を引数に取るオーバーロードを削除し、`const std::string&` を引数に取る形に統一しました。
これにより、コードの重複を削減し、メンテナンス性を向上させました。
`Urlreplace_Manager::get_imgctrl()` の関数呼び出しにおいて、ヌル終端文字列が必要なため、`std::string_view` ではなく`const std::string&` を引き続き使用します。
Removed the overload of the `get_type_ext()` function that takes `const char*` and `int` as arguments, consolidating it to use `const std::string&`.  This change reduces code duplication and improves maintainability.  The `Urlreplace_Manager::get_imgctrl()` call requires a null-terminated string, so we continue using `const std::string&` instead of `std::string_view`.
関連のissue: #1440
=> ImgRoot: Simplify `get_type_ext()` function by removing overloads

src/dbimg/imgroot.cpp, test/gtest_dbimg_imgroot.cpp
画像URLの種類を判定する関数を修正し、URLの引数とアンカー(フラグメント) 部分を無視して正確に画像形式を判定できるようにしました。
修正前は引数とアンカーの部分まで含めてチェックしていたため、例えば`http://example.com/image.jpg?foo=bar`のようなURLの場合、`.jpg?foo=bar`という拡張子として判定され、画像URLを正しく判定できない状態でした。
この修正により、引数やアンカーが付与された画像URLでも正しく判定できるようになります。 テストケースも追加し、引数やアンカーが含まれるURLに対して正しい判定が行われることを確認しました。
Modified the function that detects the type of image URL to ignore the query parameters and anchor (fragment) parts, allowing for more accurate image format detection.
Previously, the entire URL including parameters and anchors was checked.  For example, a URL like `http://example.com/image.jpg?foo=bar` would be incorrectly judged as having the extension .jpg?foo=bar, preventing correct identification of image URLs.
This fix ensures that image URLs with parameters and anchors are correctly …
=> ImgRoot: Ignore URL parameters and anchors in image format detection

src/dbimg/imgroot.cpp, test/gtest_dbimg_imgroot.cpp
URLの画像拡張子を安全にチェックできない短すぎるURLに対して、画像タイプを判定せず`T_UNKNOWN`を返すようにしました。
これにより、誤ったURLが画像として認識されるのを防ぎます。
また、新しいテストケースを追加して、短すぎるURLが正しく`T_UNKNOWN`を返すことを確認します。
Updated the logic to return `T_UNKNOWN` for URLs that are too short to safely check for image extensions. This prevents incorrect URLs from being recognized as images.  Additionally, a new test case was added to ensure that short URLs correctly return `T_UNKNOWN`.
関連のissue: #1440
=> ImgRoot: Fix to avoid treating too short URLs as images

src/dbimg/imgroot.cpp, src/dbimg/imgroot.h
関数のロジックを変更せず、画像URLの拡張子判定に`std::string_view`を使用するようにリファクタリングしました。
これにより、コードの可読性が向上し、冗長なポインタ操作を削減しました。
また、各関数にDoxygenスタイルのコメントを追加し、関数の役割と引数の説明を明確化します。
Refactored the image URL extension check functions to use `std::string_view` without changing the existing logic.  This improves code readability and eliminates redundant pointer manipulation.
Additionally, Doxygen-style comments have been added to clarify the purpose and parameters of each function.
関連のissue: #1440
=> ImgRoot: Refactor image extension checks using std::string_view

src/jdlib/loader.cpp
HTTPやURLの仕様に基づいて、リクエストで送信するパスからアンカー(`#`以降の部分)を取り除きます。
修正前はアンカーを含めてパスを送信していたため、間違ったリクエストとしてサーバーからエラーを返されることがありました。
Based on the specifications of HTTP and URL, remove the anchor (the part after `#`) from the path sent in the request.
Before the fix, the path was sent including the anchor, which sometimes resulted in receiving an error from the server as an incorrect request.
Closes #1449
=> Loader: Get rid of anchor from path for HTTP request

src/skeleton/undobuffer.cpp, src/skeleton/undobuffer.h
cppcheckにより、メンバー関数の仮引数`item`にconst修飾子を付けることができると指摘されました。
この`item`は関数の中でコンテナに挿入するため、const参照ではなく値渡しに変更し、move semanticsを使って値のコピーを回避しながら挿入するように修正します。
Cppcheck points out that the member function's parameter `item` could be declared as a const reference.  Since this `item` is inserted into a container within the function, it is changed to pass by value instead of const reference, and move semantics is used to avoid copying the value during insertion.
cppcheck 2.15のレポート
```
src/skeleton/undobuffer.cpp:18:40: style: Parameter 'item' can be declared as reference to const [constParameterReference]
void UNDO_BUFFER::set_item( UNDO_ITEM& item )
^
```
=> Change UNDO_BUFFER::set_item() argument to pass by value

test/gtest_jdlib_miscutil.cpp
C++20からUTF-8文字列リテラルの型が`char8_t`の配列に変更されるとclangに指摘されたためu8プレフィックスを外してコンパイラー警告を抑制します。 JDimのソースコードのエンコーディングはUTF-8なので影響はありません。
clang-18のレポート (file pathを一部省略)
```
test/gtest_jdlib_miscutil.cpp:17:42: warning: type of UTF-8 string literal will change from array of const char to array of const char8_t in C++20 [-Wc++20-compat]
test/gtest_jdlib_miscutil.cpp:23:42: warning: type of UTF-8 string literal will change from array of const char to array of const char8_t in C++20 [-Wc++20-compat]
test/gtest_jdlib_miscutil.cpp:25:22: warning: type of UTF-8 string literal will change from array of const char to array of const char8_t in C++20 [-Wc++20-compat]
test/gtest_jdlib_miscutil.cpp:25:31: warning: type of UTF-8 string literal will change from array of const char to array of const char8_t in C++20 …
```
=> Fix compiler warnings for -Wc++20-compat part3,4,5

src/article/articleviewbase.cpp, src/article/articleviewpreview.cpp, src/bbslist/bbslistviewbase.cpp, src/board/boardviewbase.cpp, src/control/control.cpp, src/control/controlid.h, src/control/controlutil.cpp, src/control/mousekeyconf.cpp, src/control/mousekeyitem.h, src/control/mousekeypref.cpp, src/image/imageviewbase.cpp, src/jdlib/meson.build, src/meson.build, src/message/messageviewbase.cpp, src/skeleton/entry.cpp, src/winmain.cpp, test/meson.build
コントロールIDのenum識別子`None`を`NoOperation`に変更し、MesonのUnity buildが失敗する不具合を修正します。
修正前は、X11ライブラリのヘッダーファイル`/usr/include/X11/X.h`で定義された`None`マクロが、JDimの`src/control/controlid.h`で定義されたenum識別子`None`を上書きし、コンパイルエラーが発生していました。
Change the control ID enum identifier from `None` to `NoOperation` and fix the issue causing the meson Unity build to fail.
Before this change, the `None` macro defined in the X11 library header `/usr/include/X11/X.h` was overwriting the `None` enum identifier defined in `src/control/controlid.h` of JDim, causing a compilation error.
Meson の構成を更新し、JDim のコア部分(src/ にあるソースファイル)を静的ライブラリにまとめました。
この静的ライブラリを、JDim の実行ファイルとテストプログラムにリンクさせます。
この変更前は、2つのビルドターゲットに対してソースファイルを別々にコンパイルし、リンクしていました。
また、Meson の Unity build の block size を大きくすると、 X11 ライブラリのヘッダーファイルで定義されたマクロ(Bool, None)が Google Test …
=> meson: Fix unity build

src/article/drawareabase.cpp, src/jdlib/jdiconv.cpp, src/jdlib/misccharcode.cpp, src/jdlib/misccharcode.h, test/gtest_jdlib_misccharcode.cpp
UTF-32の値からUnicodeのコードポイントを表す文字列("U+XXXX")を返す関数を追加します。
- 返り値は"U+"プレフィックスを付けた4〜6桁の16進数値（A〜Fは大文字）。
- U+10000未満の値は4桁にゼロ埋めします。
テストケースも合わせて追加し、異常値の処理も含めたケースをカバーしています。
Add a function that returns a string representing the Unicode code point from a UTF-32 value ("U+XXXX").
- The return value is a 4-6 digit hexadecimal number with a "U+"
prefix (A-F are uppercase).
- Values below U+10000 are zero-padded to 4 digits.
Test cases are added, covering cases including out-of-range values.
`char32_t` (UTF-32) の値をデバッグやログ出力する際、Unicode の U+XXXX 形式にフォーマットするよう変更します。
以前は iostream で10進数や16進数の形式で出力していましたが、C++20で<<演算子のオーバーロードが削除されたため、これに対応するための修正です。
Change the output format of `char32_t` (UTF-32) values in debugging and logging to the Unicode U+XXXX format.
Previously, the values were output in decimal or …
=> Modify char32_t output to Unicode format and ensure C++20 compatibility

src/dbtree/nodetree2ch.h
クラスのプライベートメンバー変数が使われていないとclangに指摘されたため`[[maybe_unused]]`を付与して警告を抑制します。
clang-18の警告
```
In file included from ../src/dbtree/nodetree2ch.cpp:6:
../src/dbtree/nodetree2ch.h:18:16: warning: private field 'm_since_time' is not used [-Wunused-private-field]
18 |         time_t m_since_time; // スレが立った時刻
|                ^
1 warning generated.
```
修正にあたり報告をしていただきありがとうございました。
https://mao.5ch.net/test/read.cgi/linux/1722942440/267
=> NodeTree2ch: Set maybe_unused attribute for class member

src/main.cpp
関数の引数にnullポインターを渡しているとscan-buildに指摘されたため、nullチェックを追加します。
scan-build-19 のレポート
```
../../../src/main.cpp:375:9: warning: Null pointer passed to 1st parameter expecting 'nonnull' [core.NonNullParamChecker]
375 |         std::setbuf( m_redirect_stdout, nullptr );
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../../src/main.cpp:377:9: warning: Null pointer passed to 1st parameter expecting 'nonnull' [core.NonNullParamChecker]
377 |         std::setbuf( m_redirect_stderr, nullptr );
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> Fix scan-build warnings for core.NonNullParamChecker

src/skeleton/compentry.cpp, src/skeleton/compentry.h
Wayland環境で書き込みビューをウインドウ表示すると、名前欄とメール欄の入力補完ポップアップが正しい位置に表示されない問題を修正します。
以前は、入力補完のポップアップを`Gtk::Window::move()`を使って入力欄の下に配置していましたが、Wayland環境では期待通りに動作しませんでした。
その代わりに`gdk_window_move_to_rect()`を使用して配置するようにします。
Fix the issue where the completion popup for the name and email fields does not appear in the correct position when displaying the entry view window on Wayland.
Previously, the completion popup was positioned under the input field using `Gtk::Window::move()`, but it did not work as expected on Wayland. Instead, it is now positioned using `gdk_window_move_to_rect()`.
Closes #1466
=> Fix completion popup position on Wayland

.github/workflows/weekly.yml
GitHub Actions のWeekly CI で、muon-master ジョブが Muon リビジョン 6ec469bb42b28f3a1943d58c0e15a8493220c2f7（2024-11-03）以降の実行ファイル名変更の影響で失敗していたため、対応します。
この変更により、実行ファイル名を新しい `muon-bootstrap` に更新し、正常にジョブが完了するようにします。
Fixes the failure in the muon-master job of GitHub Actions Weekly CI, caused by a change in the Muon executable name to `muon-bootstrap` since revision 6ec469bb42b28f3a1943d58c0e15a8493220c2f7 (2024-11-03).  This update adjusts the job configuration to use the new executable name, ensuring successful completion of the job.
Closes #1469
=> Fix failing muon-master job in GitHub Actions Weekly CI

src/article/articleviewbase.cpp, src/image/imageviewpopup.cpp, src/image/imageviewpopup.h, src/skeleton/dragtreeview.cpp, src/skeleton/popupwin.cpp, src/skeleton/popupwin.h, src/skeleton/view.cpp, src/skeleton/view.h
Wayland環境で多段ポップアップがマウスポインターから離れて表示される問題を修正します。
`PopupWin`コンストラクタの中では`Gdk::Window`が関連付けされないため、`realize`シグナルでウィンドウ操作を行います。
また、ポップアップ表示に`gdk_window_move_to_rect()`を使用し、表示サイズを自動調整するため`SKELETON::View`に自然サイズ用メソッドを追加しました。X11では従来の方法を維持し、適切な表示動作を実現します。
This commit fixes the issue where multi-level popups appear away from the mouse pointer on Wayland.
It adjusts `PopupWin` behavior by handling window operations on the `realize` signal, as `Gdk::Window` is not linked in the constructor.  Popups now use `gdk_window_move_to_rect()` for automatic resizing, and `SKELETON::View` has added methods for natural sizing. On X11, the previous method remains in use, ensuring correct display behavior.
エラーメッセージを表示する際に固定サイズ(200x50)で表示される問題を修正します。
`Gtk::Label`ウィジェットから取得した自然なサイズ(natural …
=> Fix popup position issue on Wayland and improve natural sizing

src/fontcolorpref.cpp
環境変数 `GTK_THEME` がライトテーマを定義しているときは、「ダークテーマで表示する」設定のチェックを外してGTKテーマの状態と一致させます。
関連のpull request: https://github.com/JDimproved/JDim/pull/1474
=> FontColorPref: Override check state if GTK_THEME defines light theme

src/icons/iconmanager.cpp
インストールされているアイコンテーマを探すとき、環境変数を調べてSnap環境で実行されているかチェックします。Snapで実行されているときはアクセス権限がないファイルを調べないようにします。
この修正よって、Snap版でフォントと色の詳細設定が開けない問題を修正します。(下記エラーメッセージ)
環境変数:
https://snapcraft.io/docs/gnome-extension#p-113162-runtime-variables
- SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
- GTK_USE_PORTAL: '1'
エラーメッセージ:
```
unhandled exception (type Glib::Error) in signal handler:
domain: g-file-error-quark
code  : 2
what  : ディレクトリ“/var/lib/snapd/desktop/icons”を開くときにエラーが発生しました: Permission denied
```
関連のpull request: https://github.com/JDimproved/JDim/issues/1476
Closes #1477
=> Fix preference dialog crashing on snap app

src/fontcolorpref.cpp
フォントと色の詳細設定ダイアログのテーマの設定タブにある設定でニーモニックキーが重複している項目があるため、キーを変更して重複を解消します。
また、GTK2の用語で説明している設定項目のラベルをGTK3の用語に更新して分かりやすくします。
=> FontColorPref: Change mnemonic key to solve duplicate keys

src/skeleton/popupwin.cpp
ポップアップが親ウインドウの配置されているモニターの画面領域に収まるようにサイズを調整するよう変更します。
以前は [`Gdk::Screen`][1] を使用してポップアップのサイズを計算していましたが、 `Gdk::Screen` は複数モニターを一つの
画面領域として扱うため、マルチディスプレイ環境ではポップアップが画面を跨いで表示される問題がありました。
今回の変更では、親ウインドウが配置されているモニター(`Gdk::Monitor`)の作業領域を利用して、ポップアップのサイズと位置を計算します。
これにより、ポップアップがモニター内に収まるようになります。
Adjust the popup window's size to fit within the monitor where its parent window is located.
Previously, the popup size was calculated using [`Gdk::Screen`][1], which represents a single screen area combining multiple monitors.  This caused popups to span across screens in multi-monitor environments.
With this update, the popup's size and position are calculated based on the work area of the monitor (`Gdk::Monitor`) where the parent window resides. This ensures that the popup fits within the correct …
=> Improve popup display handling for multi-monitor setups in X11

src/article/drawareabase.cpp, src/config/configitems.cpp, src/config/configitems.h, src/config/defaultconf.h, src/config/globalconf.h, src/fontcolorpref.cpp
フォントと色の詳細設定の「スレビューの選択範囲の色設定にGTKテーマを用いる(E)」設定を「スレビューの文字色、背景色、選択範囲の色設定にGTKテーマを用いる(E)」に拡張します。
この変更により、設定を有効にした場合、選択範囲だけでなく、通常のテキストの文字色と背景色にもGTKテーマが提供する定義済みカラーが適用されます。これにより、スレビューの配色をGTKテーマに合わせる際の設定作業が簡単になります。
詳細:
スレビューの配色とGTKテーマの定義済みカラーの対応は以下の通りです。
- 文字色: `@theme_text_color`
- 背景色: `@theme_base_color`
- 選択範囲の文字色: `@theme_selected_fg_color`
- 選択範囲の背景色: `@theme_selected_bg_color`
変更内容:
- `init_color`メソッドに文字色と背景色の設定を追加
- 関連コメントと設定項目の表記を更新
- エラーメッセージを明確化
設定内容の一貫性を高め、ユーザー体験の向上を図ります。
The font and color settings option "Use GTK theme for thread view selection colors (E)" has been extended to "Use GTK theme for thread view text, background, and selection colors (E)".
With this change, when the setting is enabled, not only the selection colors but also the text and background colors will use the …
=> Add GTK theme support for thread view text and background colors

src/board/boardviewbase.cpp, src/colorid.h, src/config/aboutconfig.cpp, src/config/configitems.cpp, src/config/defaultconf.h, src/control/mousekeypref.cpp, src/fontcolorpref.cpp
フォントと色の詳細設定に、スレ一覧や設定画面(about:config など)におけるハイライト表示の文字色の設定を追加します。これにより、ユーザーは背景色と文字色を自由にカスタマイズできるようになり、特にダークテーマ使用時の視認性低下を防ぐ効果が期待できます。
詳細:
- 新たに追加された設定項目：`COLOR_CHAR_HIGHLIGHT_TREE`
- スレ一覧や設定画面でのハイライト文字色を制御
- 設定変更に伴い、以下のソースコードを修正
- `BoardViewBase`, `AboutConfig`, `FontColorPref`などのハイライト関連ロジックを更新
- 設定保存とデフォルト値の管理に関する修正を反映
この機能追加により、テーマの視覚的な一貫性とカスタマイズ性が向上します。
Add a new font and color setting to customize the highlight text color in thread lists and configuration screens (e.g., about:config).  This feature allows users to freely adjust both background and text colors, addressing visibility issues, especially when using dark themes.
Details:
- Newly added setting: `COLOR_CHAR_HIGHLIGHT_TREE`
- Controls highlight text color in thread lists and configuration screens
- Updated source code logic for …
=> FontColorPref: Add highlight text color settings to improve visibility

docs/manual/2024.md, meson.build, src/jdversion.h
=> Bump version to 0.13.0-beta

src/board/boardviewbase.cpp
スレ一覧で検索を実行するとJDimが異常終了する不具合を修正します。
Issue #1486 の修正で、スレ一覧の項目にハイライトの文字色と背景色を設定するため Gtk::CellRenderer を Gtk::CellRendererText にキャストする
処理が追加されました。しかし、スレ一覧にはアイコン(Gtk::CellRendererPixbuf を利用)の項目があるため、アイコンの文字色と背景色の設定でキャストに失敗して nullptr が返りそのまま続行した結果、Segmentation fault が発生しました。
Segmentation faultのレポート
```
Thread 1 "jdim" received signal SIGSEGV, Segmentation fault.
0x00007ffff7a56507 in Gtk::CellRendererText::property_foreground() ()
from /lib/x86_64-linux-gnu/libgtkmm-3.0.so.1
(gdb) frame 1
this=0x55555b0be7c0, cell=<optimized out>, it=...)
at ../src/board/boardviewbase.cpp:914
914             rentext->property_foreground() = CONFIG::get_color( COLOR_CHAR_HIGHLIGHT_TREE );
(gdb) p rentext
$4 = (Gtk::CellRendererText *) 0x0
```
他の修正:
- スレタイトルのハイライトを解除するとき、文字色のリセットを追加します。
- scanbuild-19 …
=> BoardViewBase::slot_cell_data: Fix segfault

src/skeleton/popupwin.cpp, src/skeleton/popupwin.h
Wayland環境のポップアップ配置ロジックをX11環境にも適用します。
このパッチは親ウィンドウの左上を原点としてポップアップの位置を決定し、2つのウィンドウの相対的な座標で配置します。これにより、モニターの画面領域を考慮した座標計算がY方向のみで済むようになります(マウスポインターの上と下どちらにポップアップを配置するかの判断など)。
Waylandでは、SKELETON::Viewの自然な幅・高さを基にGTK/GDKがポップアップサイズを計算しますが、X11環境では高さが大きい場合に期待通りに動作しないことがあります。このため、X11環境では`Gtk::Window::set_default_size()`を使ってポップアップの幅と高さを明示的に指定するよう変更しました。
配置処理の統合により使わなくなった`PopupWin::move_resize_conventional()`を削除して、`PopupWin::move_resize_wayland()`の名前を`move_resize()`に変更します。
マルチディスプレイ環境でX11を使用し、モニタの位置にオフセットがある場合、ポップアップがマウスからずれて表示される問題を直します。
パッチ作成の際に @mokeke-maru さんの[修正][1]を参考にしました。
バグ報告とパッチのご提供いただきまして、ありがとうございました。
[1]: https://github.com/mokeke-maru/JDim/commit/b6563e5dcfdfa5f13f4c6cd30e236c4f5c6e0262
=> Apply Wayland popup positioning logic to X11

src/jdlib/misccharcode.cpp
char32_t (UTF-32) の値をデバッグやログ出力する際、Unicode の U+XXXX 形式にフォーマットするよう変更します。
以前は iostream で10進数や16進数の形式で出力していましたが、C++20で<<演算子のオーバーロードが削除されたため、これに対応するための修正です。
Change the output format of char32_t (UTF-32) values in debugging and logging to the Unicode U+XXXX format.
Previously, the values were output in decimal or hexadecimal using iostream, but this is no longer compatible with the new standard as the << operator overload was removed in C++20.
C++20モードでビルドしたときのエラーログ:
```
./src/jdlib/misccharcode.cpp: In function ‘int MISC::utf32toutf8(char32_t, char*)’:
../src/jdlib/misccharcode.cpp:515:62: error: use of deleted function ‘std::basic_ostream<char, _Traits>& std::operator<<(basic_ostream<char, _Traits>&, char32_t) [with _Traits = char_traits<char>]’
515 |         std::cout << "MISC::utf32toutf8 : …
```
=> Modify char32_t output to Unicode format part2

src/dbtree/nodetree2ch.cpp
5ch.netの過去ログdatのうち、現役サーバーに収容されている番号9桁のスレッドを読み込むことができるように修正します。番号9桁のdat URLは、oyster下のサブディレクトリ名に番号上位3桁を使用していましたが、2024年2月頃から上位4桁を使うように変更されています。
- 変更前: https://kizuna.5ch.net/event/oyster/980/980934474.dat
- 変更後: https://kizuna.5ch.net/event/oyster/9809/980934474.dat
注意:
過去ログdatは現役サーバーに収容されているスレッドに限り取得できます。
過去ログサーバーに収容されているスレッドは、read.cgiにアクセスすると、`kako.5ch.net`にHTTPリダイレクトして開きます。
過去ログのdatにアクセスするときも同様にリダイレクトしますが、この修正を行った時点では404 Not Foundが返ってきてdatを取得することができません。
https://mao.5ch.net/test/read.cgi/linux/1722942440/181
Closes #1493
=> NodeTree2ch: Update kako log dat URL

src/skeleton/window.cpp, src/skeleton/window.h
Wayland版GNOMEにおいて、メインウィンドウ、書き込みビューウィンドウ、画像ビューウィンドウを開く度にウィンドウが意図せず拡大する問題を修正します。
背景:
Wayland環境では、ウィンドウがrealizeされた際に、初期設定で指定したサイズよりも大きく表示されることがあります。ウィンドウの幅と高さは、デスクトップ環境やテーマによって異なる固定値で増加します。
この修正では、初期設定サイズとウィンドウがrealizeされた際のサイズの差分を算出し、サイズ保存処理でその差分を差し引くことで補正を行います。これにより、ウィンドウが不要に拡大するのを防ぎます。
パッチ作成にあたり、@feynoobs さんの[プルリクエスト][1]を参考にしました。
バグ報告とプルリクエストのご提供いただきありがとうございました。
Fixes an issue where the main window, write view window, and image view window would unintentionally increase in size each time they were opened in GNOME on Wayland.
Background:
In Wayland environments, windows may appear larger than their initially specified size when they are realized. The width and height of the window increase by fixed values that vary depending on the desktop environment and theme.
This fix calculates the …
=> JDWindow: Fix window resizing issue on Wayland

README.md, docs/index.md, docs/manual/2024.md, docs/manual/2025.md, docs/manual/about.md, docs/manual/history.md, jdim.metainfo.xml, src/jdversion.h
- copyrightの表示を2025年に更新する
- オンラインマニュアルに更新履歴(2025年)のページを作成し未リリースの変更を移動する
=> Update year to 2025

src/bbslist/selectdialog.cpp
Wayland版GNOMEにおいて、お気に入り追加先選択ダイアログの詳細ボタンを押してリストを折り畳んだ際に、ダイアログの幅が不適切に拡大される問題を修正します。
背景:
一部のウインドウマネージャーでは、`Gtk::Widget::get_width()`が返す幅にClient-side decoration (CSD)などの装飾が含まれる場合があります。この幅をそのまま`Gtk::Window::resize()`に渡すと、ウインドウのコンテンツ領域（クライアント領域）が保存したサイズに復元されません。
修正内容:
この問題を解決するため、ウインドウのコンテンツ領域サイズを取得する`gtk_window_get_size()`を使用して正しい幅を取得し、`resize()`に指定するよう変更しました。
This commit fixes an issue in Wayland GNOME where the width of the "Add to Favorites" selection dialog expands unexpectedly when the "Details" button is pressed and the list is collapsed.
Background:
In some window managers, `Gtk::Widget::get_width()` includes decorations such as client-side decorations (CSD).  Passing this width directly to `Gtk::Window::resize()` causes the content area of the window to fail to restore to its saved …
=> Fix dialog width issue when toggling list in Wayland GNOME

src/skeleton/window.cpp, src/skeleton/window.h
ウインドウ（メイン、書き込みビュー、画像ビュー）のサイズ変更イベント処理を修正し、画像ビューの折りたたむ機能がWayland環境でも正常に動作するよう対応します。
背景:
一部のウィンドウマネージャーでは、 `event->width/height` の値にClient-side decoration (CSD)などの装飾が含まれている可能性があります。
`Gtk::Window::resize()`はウィンドウのコンテンツ領域（クライアント領域）を指定したサイズに変更するため、装飾が含まれたサイズを渡すと、保存したサイズに正しく復元しません。代わりに、コンテンツ領域のサイズ保存に適している `Gtk::Window::get_size()` を使用します。
修正内容:
サイズ変更イベント処理において、 `event->width` および `event->height` からウィンドウサイズを取得する代わりに、 `get_size()` を使用するように変更しました。
また、この変更に伴い、不要になった `slot_realize()` 関数を削除しました。
This commit modifies the window resize event handling for the main, write, and image view windows to ensure the fold functionality in the image view works correctly in Wayland environments.
Background:
In some window managers, the values of `event->width/height` may include decorations such as Client-side …
=> Fix image view window folding not working on Wayland

src/article/font.cpp, test/gtest_dbtree_nodetreebase.cpp
Fedora 42に投入されるgcc15開発版でcompileすると出る警告を解消します。
man gccによると、-Wrange-loop-construct は -Wall で有効になると書いてありますが、gcc14だとこの警告は出ません。
gcc15開発版のレポート(抜粋)
```
../src/article/font.cpp:85:25: warning: loop variable ‘<structured bindings>’ creates a copy from type ‘const int [2]’ [-Wrange-loop-construct]
../test/gtest_dbtree_nodetreebase.cpp:37:15: warning: loop variable ‘<structured bindings>’ creates a copy from type ‘const char* const [2]’ [-Wrange-loop-construct]
../test/gtest_dbtree_nodetreebase.cpp:53:15: warning: loop variable ‘<structured bindings>’ creates a copy from type ‘const char* const [2]’ [-Wrange-loop-construct]
../test/gtest_dbtree_nodetreebase.cpp:69:15: warning: loop variable ‘<structured bindings>’ creates a copy from type ‘const char* const [2]’ [-Wrange-loop-construct] …
```
=> Fix compiler warnings for -Wrange-loop-construct

meson.build, src/jdversion.h
開発中のバージョンであることを明らかにするためalpha版に更新します。
=> Bump version to 0.14.0-alpha

.github/workflows/ccpp.yml, .github/workflows/weekly.yml
コンパイラ対応とオプションのライブラリを確認するためGitHub Actionsを利用してCI設定を構成します。[20 jobs][*]を超えると実行待機が発生するため廃止予定オプションとコンパイラオプションはテストから除外しています。
ディストロとツールチェーンの組み合わせも網羅していません。
コンパイラ: gcc-10 ~ gcc-13, clang-11 ~ clang-18
ディストロ: Ubuntu22.04, Ubuntu24.04
ビルドツール: Meson
AddressSanitizerを有効にしたビルド (1 job)
Ubuntu24.04
- gcc-13
コンパイラーを変更するビルド (13 jobs)
Ubuntu22.04
- gcc-10
- gcc-11
- gcc-12
- clang-11
- clang-12
- clang-13
- clang-14
- clang-15
Ubuntu24.04
- gcc-13
- gcc-14
- clang-16
- clang-17
- clang-18
オプションのビルド (6 jobs)
Ubuntu22.04
- gnutls, oniguruma, xsmp, migemo, alsa, pangolayout
- openssl, gregex, migemo, sessionlib=no, compat_cache_dir=disabled
- openssl, oniguruma, xsmp, alsa, pangolayout
Ubuntu24.04
- gnutls, oniguruma, xsmp, migemo, alsa, pangolayout
- openssl, gregex, migemo, sessionlib=no, …
=> Update CI settings (2025-01)

src/config/configitems.cpp, src/config/configitems.h, src/config/defaultconf.h, src/config/globalconf.cpp, src/config/globalconf.h, src/core.cpp, src/fontcolorpref.cpp, src/fontcolorpref.h
`src/colorid.h` で定義されている列挙値を参考に、ダークテーマの配色を配列 `kDarkColors` として定義します。配色はGTK3デフォルトテーマのAdwaita-darkを元にカスタマイズしています。これにより、ダークテーマを使用する際の色彩設定が統一され、視認性が向上します。
Define color scheme for dark theme as array `kDarkColors` referring to enum values defined in `src/colorid.h`.  The color scheme is customized based on GTK3 default theme Adwaita-dark.  This improves consistency in color settings and enhances visibility when using the dark theme.
フォントと色の詳細設定ダイアログの「色の設定」タブにある既存の「選択行の色をデフォルトに戻す」ボタンのラベルを「ライト」に変更し、代わりにライトテーマのデフォルト色を適用するボタンとします。
そして、選択行の色をダークテーマのデフォルト色に戻す「ダーク」ボタンを追加します。
この修正により、色の設定をデフォルト色にリセットする際に、ライトテーマだけでなくダークテーマにも対応可能になります。
これにより、ダークテーマ利用時の設定操作性が向上します。
Modify the existing "Reset selected row color to default" button in the "Color Settings" tab of the font and color detail settings dialog, …
=> FontColorPref: Add dark theme color preset

src/core.cpp, src/setupwizard.cpp, src/setupwizard.h
セットアップウィザードに新しくテーマを選択するページを追加します。
このページでは、以下の2つのテーマから選択できます：
* システム設定: 従来のライトテーマとシステムのGTKテーマを使用します。
* ダークテーマ: ダークテーマの配色とGTKテーマAdwaitaを使用します。
この変更により、初回起動時にダークテーマを選択できるようになり、ユーザー体験が向上します。特にダークテーマを希望するユーザーにとって、セットアップの利便性が高まります。
また、この変更はセットアップウィザードの4番目のステップとして追加され、その他の設定手順に影響を与えないよう設計されています。
A new page for selecting themes adds to the setup wizard.
On this page, users can choose from the following two themes:
* System theme: Uses the traditional light theme and the system's GTK theme.
* Dark theme: Uses the dark theme color scheme and the Adwaita GTK theme.
This change allows users to select the dark theme during the initial setup, enhancing the overall user experience. It especially improves convenience for users who prefer a dark theme.
Additionally, the new theme selection page is added …
=> Add a theme selection page to the setup wizard

src/board/boardviewbase.cpp, src/dbtree/boardbase.cpp
スレ一覧でスレをあぼ〜んする際、スレタイトルに絵文字が含まれていると、正しく処理されない問題を修正します。
背景:
これまで、あぼ〜ん判定に使用するスレッド情報のスレタイトルは`DBTREE::ArticleBase::get_subject()` から取得していました。
このメンバー関数は、スレタイトルを表示用に変換する処理を行っていません。
一方で、NG スレタイトルに登録されるスレタイトルはスレ一覧の表示用スレタイトルを基にしており、以下の変換が適用されていました：
- `DBTREE::ArticleBase::get_modified_subject(true)` による置換処理
- `MISC::to_markup()` による Pango Markup 変換
この違いにより、あぼ〜ん判定時にスレッド情報のスレタイトルと NG スレタイトルが一致せず、絵文字を含むスレタイトルが正しく処理されない問題が発生していました。
修正内容:
この修正では、NG スレタイトルに登録されるスレタイトルを、表示用に変換されたものではなく、未変換のものに変更します。
これにより、あぼ〜ん判定時のスレタイトルの変換状態を統一し、処理の実行性能を維持します。
影響:
- NG スレタイトルに登録されるスレタイトルが未変換のものになるため、手動で編集する際の可読性が低下する可能性があります。
- ただし、スレあぼ〜んの操作は主に GUI を通じて行われるため、実際の運用では問題にならないと考えられます。
---
Fixes an issue where aboning a thread from the thread list does not work correctly if the thread title contains emojis.
Background: …
=> Fix: Incorrect thread title matching when aboning threads with emojis

src/article/articleviewbase.cpp, src/article/drawareabase.cpp, src/article/drawareabase.h
スレッドビューの検索開始位置をマウスクリックで指定可能にします。
これにより、検索開始位置を直感的に設定できます。
**背景:**
JDimの検索機能では、「次検索」や「前検索」を使用する際、検索開始位置が自動的に決まり、ユーザーが手動で変更することはできません。他の一般的なテキストエディタやWebブラウザでは、マウスクリックで検索の開始位置を指定する仕様が多く、JDimの操作性向上のためにこの機能を導入します。
**機能追加:**
スレッドビュー内でマウスクリックした位置を基準に「次検索」「前検索」の動作を調整します。
**マウスのクリック位置と検索の動作ルール:**
| マウスのクリック位置          | 次検索の動作        | 前検索の動作        |
| :---                          | :---                | :---                |
| 先頭のヒットより前をクリック  | 先頭のヒットを選択  | 末尾のヒットを選択  |
| ヒットの1文字目をクリック     | そのヒットを選択    | 1つ前のヒットを選択 |
| ヒットの2文字目以降をクリック | 1つ次のヒットを選択 | 1つ前のヒットを選択 |
| ヒットとヒットの間をクリック  | 1つ次のヒットを選択 | 1つ前のヒットを選択 |
| 末尾のヒットより後をクリック  | 先頭のヒットを選択  | 末尾のヒットを選択  |
---
Allow specifying the search start position in the thread view by mouse click.  This allows you to intuitively set the search start …
=> Allow specifying search start position in thread view by mouse click

src/config/configitems.cpp
全体スレあぼ～ん設定(対象：スレ一覧)において、「xレス以下のスレをあぼ～ん」に1以上の値を設定すると、JDim起動時に読み込みエラーが発生する不具合を修正します。この修正により、起動時の読み込みエラーが解消され、「xレス以下のスレをあぼ～ん」「xレス以上のスレをあぼ～ん」の機能が正常に動作するようになります。
**背景:**
`CONFIG::ConfigItems::load()` で `abone_low_number_thread` と`abone_high_number_thread` を読み込む際、`CONFIG::get_max_resnumber()`を使用していました。しかし、`abone_low_number_thread` の読み込み段階では `max_resnumber` がまだロードされていないため、`CONFIG::get_max_resnumber()` が初期値 0 を返していました。
これにより、設定値の判定が正常に行われず、スレッド非表示機能が正しく動作しない状態でした。
**修正内容:**
設定値を読み込む際に、他の設定値に依存するのではなく、定数`std::numeric_limits<int>::max() - 1` を使用するように修正しました。
これにより、設定値の上限を適切に設定し、初期値による誤判定を防ぎます。
----
Fix a bug where a loading error occurs when JDim starts if a value of 1 or more is set for "Hide threads with x or fewer responses" in the overall thread hiding settings (target: thread list). This fix …
=> ConfigItems: Fix a loading error in the thread hiding settings

src/skeleton/view.cpp, src/skeleton/view.h
スレッドビュー、スレッド一覧、サイドバーにおいて、メニューキーで開くコンテキストメニューが意図しない位置に表示される問題を修正します。
従来、メニューキーを押すとコンテキストメニューはビューの左上に表示される想定でしたが、実際にはビューの種類や環境によって異なる位置に表示されていました。今回の修正により、メニューキーで開いたコンテキストメニューが常にビューの左上に表示されるようになります。
これにより、コンテキストメニューの表示位置が一貫し、ユーザーは予測どおりの位置にメニューを表示させることができるため、操作性が向上します。
この修正では、`popup_at_widget()` を使用し、ビューの左上にメニューの左上が一致するよう調整します。また、今回の修正では、ポップアップメニューの表示位置を調整するために使用していた `slot_popup_menu_position()` 関数を削除しました。これにより、メニュー表示位置の一貫性を確保し、意図した動作を実現します。
**注意:**
コンテキストメニューのサイズが大きく、ビューの左上に揃えるとディスプレイからはみ出す場合、メニューは画面内に収まるように自動調整されることがあります。これにより、環境によってはメニューが完全に左上に配置されない場合があります。
**背景:**
スレッドビュー、スレッド一覧、サイドバーでは、メニューキー（メニューとその上にカーソルが描かれているキー）や `Shift + F10` を押すと、フォーカスされているUIのコンテキストメニューを開く機能があります。
ソースコードの[コメント][1]には、メニューキーを押した際のコンテキストメニューの表示位置は「viewの左上の座標をセットする」と記載されています。しかし、実際の動作では意図した位置に表示されない場合があり、ビューの種類やディスプレイ …
=> Fix context menu is displayed at an incorrect position

src/image/imageadmin.cpp, src/image/imageview.cpp, src/image/imageviewbase.cpp
画像ビューにおいて、メニューキー（または `Shift + F10` キー）によるコンテキストメニュー表示機能を追加します。これにより、スレビュー、スレ一覧、サイドバー、および画像ビューでのキーボード操作の一貫性が向上し、操作の利便性が高まります。
**背景:**
キーボードのメニューキー（メニューとその上にカーソルが描かれているキー）や `Shift + F10` は、フォーカスされているUIのコンテキストメニューを開く機能があります。JDim では、GTK が提供するデフォルトのコンテキストメニューがメニューキーに対応しているだけでなく、スレビュー、スレ一覧、サイドバーでも使用できます。しかし、画像ビューではメニューキーが機能しないため、キーボード操作の一貫性が損なわれていました。
画像ビューはタブにフォーカスが当たる仕組みのため(`ImageAdmin::focus_view()`を参照)、画像ビュー内でメニューキーを押すと、タブの画像アイコン (`ImageViewIcon`) でキー入力が処理されます。
そのため、`ImageViewMain` にメニューキーの入力処理を追加しても、キー入力を受け取れず動作しません。
**修正内容:**
この問題を解決するため、`ImageViewIcon` に `ImageViewMain` の `key_press_event` を処理するシグナルハンドラを接続し、キー入力イベントを `ImageViewMain` に伝達するようにしました。
`ImageViewMain::operate_view()` で `CONTROL::ShowPopupMenu` を処理し、`show_popupmenu("", true)` を呼び出すことで、メニューキーと `Shift + F10` の両方でコンテキストメニューを表示します。 …
=> Add context menu display via menu key in Image View

src/history/historysubmenu.cpp, src/skeleton/admin.cpp, src/skeleton/admin.h, src/skeleton/menubutton.cpp, src/skeleton/menubutton.h, src/usrcmdpref.cpp
JDimの動作環境が更新され、GTK 3.24.6 未満のサポートが不要になったため、該当するソースコードを整理します。
プロジェクトのドキュメントには、GTKのバージョン要件を明確に記述していませんが、サポート対象としている Debian bullseye に収録されているGTK3のバージョンが 3.24.24 なので、削除してもサポートに影響がないと判断しました。
---
As the operating environment of JDim has been updated, support for GTK versions below 3.24.6 is no longer necessary, so the corresponding source code has been removed.
The project documentation does not explicitly state the GTK version requirements, but the GTK3 version included in Debian bullseye, which is a supported environment, is 3.24.24. Therefore, it was determined that removing this code would not affect support.
関連のissue: #1515, #1516
=> Remove support code for GTK versions older than 3.24.6

src/skeleton/view.cpp
This reverts commit d34fc3bbcee32f9195c1ddf1f49b247bd2c5f518.
ツールバーボタンを押して表示するポップアップメニューが出ないと報告がありましたので一度変更を取り消します。
影響を受けるツールバーボタンを確認したところ、以下のボタンでポップアップメニューが表示されませんでした。
- スレ一覧
- お気に入り追加
- 削除
- スレビュー
- 削除
https://mao.5ch.net/test/read.cgi/linux/1722942440/537-538n
関連のissue: #1516
=> Revert "View: Adjust context menu position to prevent it from going off-screen"

src/article/articleviewbase.cpp, src/bbslist/bbslistviewbase.cpp, src/board/boardviewbase.cpp, src/image/imageview.cpp, src/image/imageviewbase.cpp, src/skeleton/toolbar.cpp, src/skeleton/view.cpp, src/skeleton/view.h
このPull request は https://github.com/JDimproved/JDim/issues/1516#issuecomment-2671562878 の「アイデア2: コマンドの即時実行」を実装します。
ビューを右クリックしたときのコンテキストメニュー表示処理を `Gtk::Menu::popup_at_pointer()` に変更します。
この関数は、処理中のマウスポインターの座標にメニューを表示します。
従来の実装では、メニューのサイズが大きい場合、ディスプレイの外にはみ出してメニュー項目が一部見えなくなることがありました。
`popup_at_pointer()` を使用することで、メニューが画面内に収まるよう自動的に調整されます。
しかし、`popup_at_pointer()` に変更すると、ツールバーボタンのポップアップメニューが表示されなくなる問題が発生しました。
これは、`Gtk::Menu` の新しいAPIが `GdkEvent` を必要とするためです。
ツールバーボタンのクリック時にはコマンドを送信するだけでメニュー表示を実行しないため、イベント処理を抜けた後では `GdkEvent` を取得できず、 `popup_at_pointer()` に必要な情報を渡せません。
この問題を解決するため、ツールバーボタンの「削除」や「お気に入り追加」ボタンをクリックしたときに送信するコマンドを、待ち行列に追加する `SKELETON::Admin::set_command()` から即時実行する `set_command_immediately()` に変更しました。これにより、イベント処理中に `popup_at_pointer()` を呼び出してメニューを表示できるようになります。
**注意:** …
=> Fix toolbar button menu display and apply `popup_at_pointer()`

src/dbtree/nodetree2ch.cpp, src/dbtree/nodetree2ch.h, src/dbtree/nodetreebase.cpp, src/dbtree/nodetreebase.h
cppcheck 2.17で、 `NodeTree2ch::process_raw_lines()` が基底クラスに処理を移譲しているだけだと指摘されます。 `process_raw_lines()` はキャッシュ保存前の前処理を行う派生クラスで必要でしたが、現在は利用されていません。そのため、`NodeTree2ch::process_raw_lines()` と `NodeTreeBase::process_raw_lines()` の実装および関連する呼び出しを削除します。
---
cppcheck 2.17 reports that `NodeTree2ch::process_raw_lines()` merely delegates to the base class. `process_raw_lines()` was needed for preprocessing before cache storage in derived classes, but it is no longer used. Therefore, I remove the implementations of `NodeTree2ch::process_raw_lines()` and `NodeTreeBase::process_raw_lines()` along with their related calls.
---
cppcheck 2.17のレポート:
```
src/dbtree/nodetree2ch.h:34:15: style: The function 'process_raw_lines' overrides a function in a base class but just delegates back to the base class. …
```
=> Remove unnecessary process_raw_lines() from NodeTree2ch and NodeTreeBase

src/article/articleadmin.h, src/article/articleviewbase.cpp, src/article/toolbar.cpp, src/board/boardadmin.h, src/board/boardviewbase.cpp, src/board/toolbar.cpp, src/skeleton/admin.cpp, src/skeleton/admin.h, src/skeleton/view.cpp, src/skeleton/view.h
このPull request は https://github.com/JDimproved/JDim/issues/1516#issuecomment-2671562878 の「アイデア3: `popup_at_widget()`を適切に使う」を実装します。
`SKELETON::View::show_popupmenu()` の第2引数 `position` に `PopupMenuPosition::toolbar_button` （ツールバーボタンの下）を追加します。さらに、表示位置のウィジェットを指定する第3引数 `anchor_widget` を追加します。この引数を省略可能にすることで、不要な場合は明示的に指定せずに関数を呼び出せるようにします。
さらに、引数の値が誤っていてポップアップメニューを正常に配置できない場合、メニュー表示の代わりにエラーメッセージをコンソールに出力するエラー処理を実装します。
**背景:**
変更前は、ツールバーボタンを押した際にポップアップメニューがマウスポインターの位置に表示されていたため、ツールバーとの関連が分かりにくい問題がありました。 `PopupMenuPosition::toolbar_button` を追加することで、ツールバーボタンとポップアップメニューの関係が直感的に分かる配置にできます。
---
Add `PopupMenuPosition::toolbar_button` (below the toolbar button) as an option for the `position` parameter in `SKELETON::View::show_popupmenu()`. Additionally, introduce a third parameter, `anchor_widget`, to …
=> Improve popup menu positioning for toolbar buttons

src/image/imageadmin.cpp, src/image/imageadmin.h
画像ビューを閉じるコマンドを送信する割り込みハンドラを実装します。
画像を閉じるためのURLを格納するキューが空でない場合、URLを取り出して閉じるコマンドを送信し、trueを返して処理を継続します。
キューが空の場合、タブ操作の状態をfalseに切り替え、falseを返してハンドラの接続を解除します。
**背景:**
多量の画像を閉じる際、一度にすべての閉じるコマンドを送信すると保留中のイベントが蓄積され、ウインドウがフリーズする問題が発生していました。
そこで、`Glib::signal_idle()` を利用し、保留中の優先度が高いイベントがないときに実行する割り込みハンドラで閉じるコマンドを少しずつ送信するように変更しました。これにより、画像を閉じる処理を断続的に実行できます。
**注意:**
`ImageAdmin::slot_close_command()` は、スレッドセーフではないためメインスレッドや割り込みハンドラで呼び出す必要があります。
---
If the queue storing URLs for closing images is not empty, retrieve a URL, send the close command, and return true to continue processing.  If the queue is empty, switch the tab operation state to false, return false to disconnect the handler, and end processing.
**Background:**
When closing a large number of images, sending all close commands at once …
=> Optimize closing multiple images using a queue and idle handler

src/image/imageadmin.cpp
`ImageAdmin::restore()` で、前回開いていたURLを復元する際に、タブ操作中のビューの再描画を無効化するフラグ（`SESSION::set_tab_operating()`）を設定するように修正します。
また、復元するURLが最後の一つになったときに、このフラグを解除して一度だけ後続の処理を行います。この修正により、タブ操作中のビューの更新処理がスキップされ、読み込みの負荷が低減します。
**修正の効果:**
`gprof` を有効にしてビルドした JDim を使用し、約 1000 個の画像タブを開くキャッシュディレクトリを指定して起動と終了を行い、プロファイルを計測しました。その結果、修正の適用前は `ImageAdmin::update_status_of_all_views()` が Flat profile の上位に入っていましたが、修正の適用後は順位が 2000 程度下がり、負荷が減少します。体感では、JDimの起動にかかる時間に変化は見られませんが、プロファイルの改善により今後の性能改善の基盤とします。
---
Modify `ImageAdmin::restore()` to set a flag (`SESSION::set_tab_operating()`) that disables view redraws during tab operations while restoring previously opened URLs.  Additionally, clear this flag and perform subsequent processing only once when the last URL is restored. This change skips view update processing …
=> Add flag to reduce load during tab operations in `ImageAdmin::restore()`

src/config/defaultconf.h
ユーザーエージェント文字列の初期設定を更新してブラウザの識別子にバージョン番号を追加します。
5ch.netのスレッドに書き込みを試みると、「ERROR: 不正な UserAgent を検出しました。」というエラーメッセージが表示され、書き込みに失敗する問題が報告されていました。新しいユーザーエージェント文字列を利用すると書き込みエラーを回避することができます。
新しいユーザーエージェント文字列は「Monazilla/1.00 JD/2006.1.1」にします。
**背景:**
"JDim" を利用しない理由は、JDimはJDの仕様を引き継ぎ、初期設定でも "JD" が使用され続けているためです。そのため、互換性を保つ観点から "JD" を使用するほうが適切と判断しました。
バージョン番号の部分は「2006.1.1」にします。これはJDバージョン1がリリースされた日付に基づいています。一般的にユーザーエージェント文字列のバージョン番号は新しいリリースごとに値が更新されます。
しかし、5ch.netで使用されているユーザーを識別するどんぐりシステムの仕様により、バージョン番号部分を変更するとユーザー識別用の警備員アカウントが変わってしまいます。そこで、バージョン番号を固定値とすることで、書き込みエラーの回避と警備員アカウントの維持を目指します。
----
Update the default User-Agent string setting to add a version number to the browser identifier.
There have been reports of issues when attempting to post on 5ch.net threads, where an error message "ERROR: Invalid …
=> Add version number to User-Agent string

src/dbtree/article2ch.cpp
レス投稿時刻(time)を現在時間にする
レス投稿時刻がずれすぎと5chから言われる
おそらくJDimでは一回timeを取得したら使いまわしでこのエラーが出るのではと推測
関数で取得してるtimeをtime関数で生のUNIX時間にする
スレ立てにも影響してるかもしれないけど対応したのはレスだけ
=> 5chに時間が古いと言われてかけなくなったので、timeに現在時間を入れたとても暫定的な対応

src/dbtree/article2ch.cpp, src/jdlib/cookiemanager.cpp, test/gtest_jdlib_cookiemanager.cpp
Pinkチャンネルに書き込めない不具合の対応
Pinkチャンネルでは未だにyuki=akariが使われているようだが、
JDimからyuki=akariが送信されていないようなので修正しようと思った。
SimpleCookieManager::get_cookie_by_hostでCookieのarrayがうまく文字列に
変換できていなさそうなので処理の修正。
このプルリクエストが正しいのであれば、
SimpleCookieManager::delete_cookie_by_host
も修正がいるかも知れないです
C++の知識が疎くてより良い書き方などあったら修正をお願いします。
5chのJDimのスレには、この修正を当てなくてもPinkチャンネルに書けている
というレスもあるので、本当に必要な処理かわからないです。
=> Pink post fix

src/article/articleadmin.cpp, src/board/boardadmin.cpp, src/core.cpp, src/history/historymanager.cpp, src/image/imageadmin.cpp, src/image/imageadmin.h, src/menuslots.cpp, src/session.cpp, src/session.h, src/skeleton/admin.cpp, src/skeleton/admin.h
This PR refactors session data containers for URLs and lock states from std::list to std::vector.
タブやセッション情報で利用していたURLリストのコンテナを`std::list`から`std::vector`に統一しました。これにより、イテレーションやランダムアクセスのパフォーマンスが向上し、APIの整合性も高まりました。関連する関数定義やクラスの仮想関数も全てvector型に修正しています。
---
Unified the containers for URL lists used in tabs and session information from std::list to std::vector. This improves iteration and random access performance, and enhances API consistency. All related function definitions and virtual methods have also been
updated to use vector.
スレッド一覧や画像タブなどのロック状態リストの内部実装を、`std::list<bool>`から`std::vector<char>`へ変更しました。`vector<bool>`の特殊化による取り扱いの難しさを避けるため、`vector<char>`を採用しています。これによりメモリ効率とAPIの一貫性が向上します。関連するクラスや関数の型も全て修正しました。
---
Changed the implementation of lock state lists for thread lists and image tabs …
=> Refactor session containers: replace std::list with std::vector for URLs and lock states

src/message/messageviewbase.cpp, src/message/post.cpp
投稿確認ダイアログのサイズが画面幅いっぱいに広がる問題を修正します。
5ch.netのスレッドに書き込んだとき、投稿確認ダイアログの幅がデスクトップ全体に広がってしまうとの報告がありました。
原因は、`ConfirmDiag` に初期サイズが指定されていなかったため、環境によってはウィンドウが画面全体に拡大されてしまうことでした。
本修正では、`ConfirmDiag` に `set_default_size(600, 400)` を指定し、適切なサイズで表示されるようにしています。
また、同様の問題が `MessageViewBase::post_fin()` 内の `SKELETON::DetailDiag` にもあったため、あわせて初期サイズの設定を追加しています。
---
When posting to a thread on 5ch.net, the confirmation dialog was reported to stretch across the entire desktop width.  The cause was that `ConfirmDiag` did not have an explicit default size, which could result in oversized windows depending on the environment.  This commit sets a default size of `600x400` for `ConfirmDiag` to ensure an appropriate display size.
Additionally, a similar issue was found in `MessageViewBase::post_fin()` with a …
=> Fix confirmation dialog expanding to full screen width

snap/snapcraft.yaml
2025年3月31日以降、snapパッケージで利用しているランタイムである[GNOME Extension][1]（gnome-42-2204）は、stableチャンネルにおいてriscv64アーキテクチャを[サポート][2]するようになりました。
これに対応するため、snapcraft.yamlにriscv64向けのビルド設定を追加します。
[1]: https://snapcraft.io/docs/gnome-extension
[2]: https://github.com/ubuntu/gnome-sdk/issues/285
---
Since March 31, 2025, the GNOME Extension (gnome-42-2204) runtime used by snap packages has started supporting the riscv64 architecture on the stable channel.
To align with this update, this commit adds build configuration for riscv64 in snapcraft.yaml.
=> Add build configuration for riscv64 snap package

src/article/drawareabase.cpp
スレビューで「ここまで読んだ」セパレーターを範囲選択の始点または終点に含めて「選択範囲のレスをあぼーん」を実行すると、機能が動作しない不具合を修正しました。
`get_selection_resnum_from()`および`get_selection_resnum_to()`関数において、選択範囲の始点または終点が「ここまで読んだ」セパレーターである場合に、正しくレス番号を取得できるようロジックを更新しました。これにより、セパレーターを含む範囲でも「選択範囲のレスをあぼーん」機能が正常に動作するようになります。
また、これらのメンバー関数にDoxygen形式のコメントを追加し、コードの可読性とドキュメントを向上させました。
---
Fixed a bug where the "Abonn selected range of responses" function in the Review View did not work when the selected range included the "Read up to here" separator at its start or end.
The logic in `get_selection_resnum_from()` and `get_selection_resnum_to()` functions has been updated to correctly retrieve the response number when the selection range starts or ends with the "Read up to here" separator. This ensures the "Abonn selected range of responses" function now works …
=> Fix "Aborn selected responses" not working when selection includes separator

src/article/drawareabase.cpp
スレビューの「選択範囲のレスをあぼーん」機能が、レス表示上の特定の文字位置を範囲選択の始点または終点に含んだ場合に動作しない不具合を修正しました。
`get_selection_resnum_from()`および`get_selection_resnum_to()`関数において、選択範囲の始点または終点がレス番号を持たないヘッダー（例: 投稿者名、メール欄、投稿時間など）である場合でも、関連するレス番号を正しく取得できるようロジックを更新しました。これにより、特定の文字位置を含む範囲でも「選択範囲のレスをあぼーん」機能が正常に動作するようになります。
また、これらのメンバー関数にDoxygen形式のコメントを追加し、コードの可読性とドキュメントを向上させました。
---
Fixed a bug where the "Abonn selected range of responses" function in the Review View did not work when the selected range included specific text positions within the response display at its start or end.
The logic in `get_selection_resnum_from()` and `get_selection_resnum_to()` functions has been updated. This ensures that the correct response number is retrieved even when the selection range starts or ends with headers that do not directly have a …
=> Fix abone-by-selection failure when range starts/ends at specific text nodes

src/article/articleviewsearch.cpp, src/article/toolbarsearch.cpp
検索機能のツールバーにある「検索バーを開く」および「検索バーを閉じる」ボタンが、常に検索バーが表示されている状況下で期待通りに機能しない問題に対応しました。
以下の修正を行っています。
- 検索ボックスでESCキーを押しても検索バーが閉じないように変更しました。
- 検索バーを常に表示させるため、「検索バーを閉じる」ボタンを無効化し、ツールチップで「検索バーは常に表示されます。」と補足説明を追加しました。
- 同様に、「検索バーを開く」ボタンも常に無効化し、ツールチップで「検索バーは常に表示されます。」と補足説明を追加しました。
これにより、検索機能のUIにおけるボタンの挙動の一貫性を向上させ、ユーザーの混乱を防ぎます。
---
Disable search toolbar buttons to improve UI consistency for search features. The "Open Search Bar" and "Close Search Bar" buttons in the search feature toolbars (Title Search and Cached Log Search) did not function as expected because the search bar is always visible.
This commit addresses the issue by:
- Preventing the search bar from closing when the ESC key is pressed in the search box.
- Disabling the "Close Search Bar" button and adding a tooltip "The search bar is …
=> Disable search toolbar buttons to improve UI consistency

docs/manual/2025.md, meson.build, src/jdversion.h
=> Bump version to 0.14.0-beta

meson.build, src/jdversion.h
開発中のバージョンであることを明らかにするためalpha版に更新します。
=> Bump version to 0.15.0-alpha

docs/manual/usrcmd.md, src/core.cpp, src/jdlib/miscutil.cpp, src/jdlib/miscutil.h, test/gtest_jdlib_miscutil.cpp
ユーザーコマンドでシングルクオートを使用できない不具合を修正するために、文字列の先頭と末尾のクオートを取り除く新しいヘルパー関数 `MISC::remove_quotes()` を追加しました。
この関数は、ダブルクオート `"` とシングルクオート `'` の両方に対応しており、`src/core.cpp` のロジックをより簡潔にするために使用されます。また、再利用可能なユーティリティとして、将来の機能追加にも役立ちます。
同時に、この関数の動作を保証するために、`test/gtest_jdlib_miscutil.cpp` に単体テストを追加しました。正常系とエッジケースの両方を網羅することで、関数の信頼性を確保しています。
---
This commit introduces a new helper function, `MISC::remove_quotes()`, to strip leading and trailing quotes from a string. This function is a preparatory step to fix the bug where user commands fail when arguments are wrapped in single quotes.
`MISC::remove_quotes()` handles both single (`'`) and double (`"`) quotes, providing a clean and reusable utility that will be used to simplify the logic in `src/core.cpp`.
To ensure correctness, this change also includes a …
=> Allow user commands to use single-quoted arguments with $VIEW

src/message/post.cpp, src/message/post.h, test/gtest_message_post.cpp, test/meson.build
投稿エラーダイアログでURLが二重に表示される不具合を修正するため、エラーメッセージのクリーンアップと`<a>`タグ処理を行うヘルパー関数 `MESSAGE::Post::process_error_message()` を追加します。
この関数は、`href`属性とリンクテキストが一致する場合にのみ、URLの重複を削除します。また、samba秒の抽出などの関連処理も一元化します。これにより、副作用のないロジックを独立してテストできるようになります。
本コミットには、関数の正確性を検証するための広範な単体テストも含まれています。
---
Adds a new helper function, `MESSAGE::Post::process_error_message()`, to clean up error messages and handle `<a>` tags. This is a preparatory step to fix the bug where URLs appear duplicated in the post error dialog.
The function removes redundant URLs when the `href` attribute and link text are identical, while preserving both when they are different.  It also centralizes related logic, such as extracting the samba seconds, allowing for side-effect-free unit testing.
Comprehensive unit tests are included to verify the …
=> fix: Correct duplicate URL display in the post error dialog
